import type { ScriptGroup } from '../types';

/**
 * Reading track, part 1: hiragana and katakana. These run alongside the main
 * units a few characters per session, so learners speak from day one (with
 * romaji under each word) while the aids fade as they learn each character.
 * Kanji follow, built from kanji.json.
 */
export const kanaGroups: ScriptGroup[] = [
  {
    id: 'ja-kana-1',
    title: 'Hiragana 1: あ to と',
    script: 'hiragana',
    lessons: [
      {
        id: 'g-ja-kana1-1',
        title: 'Three scripts: hiragana, katakana, kanji',
        summary:
          'Japanese mixes three scripts, often in the same sentence. Hiragana (ひらがな, hiragana) writes native words and grammar endings, katakana (カタカナ, katakana) writes words borrowed from other languages, like コーヒー (kōhī, coffee), and kanji (かんじ, kanji) are characters from Chinese that carry meaning, like 山 (やま, yama, mountain). Each kana is a whole syllable, not a letter, and the chart begins with the five vowels あ (a), い (i), う (u), え (e), お (o), said short and clear as in \'ah, ee, oo, eh, oh\'. Every other row adds a consonant to those vowels, so the k row is か (ka), き (ki), く (ku), け (ke), こ (ko). Japanese has no spaces between words, and the shifts between scripts help you see where words start. Romaji under each word is only a stepping stone: it fades out for each kana as you learn it, so read the kana first and glance down only when you need to.',
        examples: [
          { text: 'あい', en: 'love' },
          { text: 'いえ', en: 'house; home' },
          { text: 'うえ', en: 'up; above' },
          { text: 'あおい', en: 'blue' },
        ],
        drills: [
          { text: '___え', en: 'ie — house', answer: 'い', distractors: ['あ', 'う', 'お'] },
          { text: 'あ___い', en: 'aoi — blue', answer: 'お', distractors: ['あ', 'う', 'え'] },
          { text: 'いい___', en: 'iie — no', answer: 'え', distractors: ['あ', 'い', 'お'] },
          { text: 'あ___', en: 'au — to meet', answer: 'う', distractors: ['い', 'え', 'お'] },
          { text: '___か', en: 'aka — red', answer: 'あ', distractors: ['お', 'い', 'え'] },
        ],
      },
      {
        id: 'g-ja-kana1-2',
        title: 'The k, s, t rows and the special sounds し, ち, つ',
        summary:
          'The k row (か き く け こ: ka, ki, ku, ke, ko), the s row (さ し す せ そ: sa, shi, su, se, so) and the t row (た ち つ て と: ta, chi, tsu, te, to) put a consonant in front of the five vowels. Three sounds break the pattern: し is shi (not \'si\'), ち is chi (not \'ti\'), and つ is tsu, with the \'ts\' of \'cats\' (not \'tu\'). The vowels u and i often go almost silent between sounds like k, s, sh and t, so すき (suki, like) sounds like \'ski\' and あした (ashita, tomorrow) like \'ash-ta\'. Watch the look-alikes: さ (sa) and ち (chi) are mirror images, き (ki) has two crossbars where さ (sa) has one, and し (shi) is a vertical hook while つ (tsu) is a sideways one.',
        examples: [
          { text: 'くつした', en: 'socks' },
          { text: 'あした', en: 'tomorrow' },
          { text: 'おいしい', en: 'delicious' },
          { text: 'すこし', en: 'a little' },
        ],
        drills: [
          { text: '___さ', en: 'kasa — umbrella', answer: 'か', distractors: ['き', 'こ', 'け'] },
          { text: 'あ___', en: 'ashi — leg; foot', answer: 'し', distractors: ['さ', 'ち', 'す'] },
          { text: '___かてつ', en: 'chikatetsu — subway', answer: 'ち', distractors: ['さ', 'し', 'つ'] },
          { text: 'く___', en: 'kutsu — shoes', answer: 'つ', distractors: ['す', 'ち', 'し'] },
          { text: '___と', en: 'soto — outside', answer: 'そ', distractors: ['さ', 'せ', 'す'] },
        ],
      },
    ],
    items: [
      { id: 'v-ja-kana-1-01', text: 'あ', en: 'a', pos: 'character', example: { text: 'あか', en: 'red' } },
      { id: 'v-ja-kana-1-02', text: 'い', en: 'i', pos: 'character', example: { text: 'いす', en: 'chair' } },
      { id: 'v-ja-kana-1-03', text: 'う', en: 'u', pos: 'character', example: { text: 'うた', en: 'song' } },
      { id: 'v-ja-kana-1-04', text: 'え', en: 'e', pos: 'character', example: { text: 'えき', en: 'train station' } },
      { id: 'v-ja-kana-1-05', text: 'お', en: 'o', pos: 'character', example: { text: 'おかし', en: 'sweets; snacks' } },
      { id: 'v-ja-kana-1-06', text: 'か', en: 'ka', pos: 'character', example: { text: 'かさ', en: 'umbrella' } },
      { id: 'v-ja-kana-1-07', text: 'き', en: 'ki', pos: 'character', example: { text: 'あき', en: 'autumn; fall' } },
      { id: 'v-ja-kana-1-08', text: 'く', en: 'ku', pos: 'character', example: { text: 'くち', en: 'mouth' } },
      { id: 'v-ja-kana-1-09', text: 'け', en: 'ke', pos: 'character', example: { text: 'さけ', en: 'salmon; sake (rice wine)' } },
      { id: 'v-ja-kana-1-10', text: 'こ', en: 'ko', pos: 'character', example: { text: 'ここ', en: 'here' } },
      { id: 'v-ja-kana-1-11', text: 'さ', en: 'sa', pos: 'character', example: { text: 'あさ', en: 'morning' } },
      { id: 'v-ja-kana-1-12', text: 'し', en: 'shi', pos: 'character', example: { text: 'しお', en: 'salt' } },
      { id: 'v-ja-kana-1-13', text: 'す', en: 'su', pos: 'character', example: { text: 'すし', en: 'sushi' } },
      { id: 'v-ja-kana-1-14', text: 'せ', en: 'se', pos: 'character', example: { text: 'せき', en: 'seat' } },
      { id: 'v-ja-kana-1-15', text: 'そ', en: 'so', pos: 'character', example: { text: 'そこ', en: 'there (near you)' } },
      { id: 'v-ja-kana-1-16', text: 'た', en: 'ta', pos: 'character', example: { text: 'たこ', en: 'octopus' } },
      { id: 'v-ja-kana-1-17', text: 'ち', en: 'chi', pos: 'character', example: { text: 'ちいさい', en: 'small' } },
      { id: 'v-ja-kana-1-18', text: 'つ', en: 'tsu', pos: 'character', example: { text: 'つくえ', en: 'desk' } },
      { id: 'v-ja-kana-1-19', text: 'て', en: 'te', pos: 'character', example: { text: 'ちかてつ', en: 'subway' } },
      { id: 'v-ja-kana-1-20', text: 'と', en: 'to', pos: 'character', example: { text: 'とけい', en: 'clock; watch' } },
    ],
  },
  {
    id: 'ja-kana-2',
    title: 'Hiragana 2: な to ん',
    script: 'hiragana',
    lessons: [
      {
        id: 'g-ja-kana2-1',
        title: 'The n, h, m rows (ふ = fu)',
        summary:
          'The n row (な に ぬ ね の: na, ni, nu, ne, no), the h row (は ひ ふ へ ほ: ha, hi, fu, he, ho) and the m row (ま み む め も: ma, mi, mu, me, mo) follow the same consonant + vowel pattern you already know. The exception is ふ: it is written fu, but it\'s a soft puff of air between your lips, without touching your teeth to your lip as in English \'f\' — somewhere between \'hoo\' and \'foo\'. ひ (hi) is also breathier than in English, close to the start of \'huge\'. Look-alikes to watch: ぬ (nu) ends in a loop and め (me) does not; ね (ne) ends in a loop while れ (re) and わ (wa) do not; and ほ (ho) has one more crossbar than は (ha).',
        examples: [
          { text: 'なまえ', en: 'name' },
          { text: 'さかな', en: 'fish' },
          { text: 'ふね', en: 'ship; boat' },
          { text: 'みみ', en: 'ear' },
        ],
        drills: [
          { text: 'おか___', en: 'okane — money', answer: 'ね', distractors: ['れ', 'わ', 'ぬ'] },
          { text: '___く', en: 'fuku — clothes', answer: 'ふ', distractors: ['ひ', 'は', 'ほ'] },
          { text: 'さか___', en: 'sakana — fish', answer: 'な', distractors: ['ね', 'の', 'に'] },
          { text: '___と', en: 'hito — person', answer: 'ひ', distractors: ['ふ', 'へ', 'ほ'] },
          { text: 'あた___', en: 'atama — head', answer: 'ま', distractors: ['も', 'ほ', 'は'] },
        ],
      },
      {
        id: 'g-ja-kana2-2',
        title: 'や ゆ よ, the r row, わ, を and ん — plus why the particles は, へ, を are read wa, e, o',
        summary:
          'The y row has only three kana, や (ya), ゆ (yu), よ (yo), and the w row keeps just わ (wa) and を (wo, pronounced o). The r row ら り る れ ろ (ra, ri, ru, re, ro) is a quick tap of the tongue just behind the upper teeth, close to the \'tt\' in American \'butter\' — not an English r or l. ん (n) is the only kana without a vowel; it never begins a word, and it takes a full beat, so ほん (hon, book) has two beats. As particles (small grammar words), は is read wa, へ is read e, and を is read o: ねこは (neko wa), うちへ (uchi e), ほんを (hon o), and the greeting こんにちは (konnichiwa) ends in that same は. The pitfall: inside ordinary words は and へ keep their usual sounds, as in はな (hana, flower) and へや (heya, room), while を is used only as a particle.',
        examples: [
          { text: 'ねこはかわいい。', reading: 'ねこ は かわいい。', en: 'Cats are cute.' },
          { text: 'うちへかえります。', reading: 'うち へ かえります。', en: 'I\'m going home.' },
          { text: 'ほんをよみます。', reading: 'ほん を よみます。', en: 'I\'ll read a book.' },
          { text: 'あれはなに？', reading: 'あれ は なに？', en: 'What is that?' },
        ],
        drills: [
          { text: 'それ___なに？', reading: 'それ ___ なに？', en: 'sore wa nani? — What\'s that (near you)?', answer: 'は', distractors: ['わ', 'を', 'へ'] },
          { text: 'にほん___いきます。', reading: 'にほん ___ いきます。', en: 'Nihon e ikimasu. — I\'m going to Japan.', answer: 'へ', distractors: ['え', 'は', 'を'] },
          { text: 'ほん___かいます。', reading: 'ほん ___ かいます。', en: 'hon o kaimasu. — I\'ll buy a book.', answer: 'を', distractors: ['お', 'は', 'へ'] },
          { text: 'さく___', en: 'sakura — cherry blossom', answer: 'ら', distractors: ['る', 'ろ', 'れ'] },
          { text: '___き', en: 'yuki — snow', answer: 'ゆ', distractors: ['よ', 'や', 'る'] },
        ],
      },
    ],
    items: [
      { id: 'v-ja-kana-2-01', text: 'な', en: 'na', pos: 'character', example: { text: 'なつ', en: 'summer' } },
      { id: 'v-ja-kana-2-02', text: 'に', en: 'ni', pos: 'character', example: { text: 'にく', en: 'meat' } },
      { id: 'v-ja-kana-2-03', text: 'ぬ', en: 'nu', pos: 'character', example: { text: 'いぬ', en: 'dog' } },
      { id: 'v-ja-kana-2-04', text: 'ね', en: 'ne', pos: 'character', example: { text: 'ねこ', en: 'cat' } },
      { id: 'v-ja-kana-2-05', text: 'の', en: 'no', pos: 'character', example: { text: 'のみもの', en: 'drink; beverage' } },
      { id: 'v-ja-kana-2-06', text: 'は', en: 'ha', pos: 'character', example: { text: 'はな', en: 'flower' } },
      { id: 'v-ja-kana-2-07', text: 'ひ', en: 'hi', pos: 'character', example: { text: 'ひと', en: 'person' } },
      { id: 'v-ja-kana-2-08', text: 'ふ', en: 'fu', pos: 'character', example: { text: 'ふゆ', en: 'winter' } },
      { id: 'v-ja-kana-2-09', text: 'へ', en: 'he', pos: 'character', example: { text: 'へや', en: 'room' } },
      { id: 'v-ja-kana-2-10', text: 'ほ', en: 'ho', pos: 'character', example: { text: 'ほん', en: 'book' } },
      { id: 'v-ja-kana-2-11', text: 'ま', en: 'ma', pos: 'character', example: { text: 'まち', en: 'town' } },
      { id: 'v-ja-kana-2-12', text: 'み', en: 'mi', pos: 'character', example: { text: 'みせ', en: 'shop; store' } },
      { id: 'v-ja-kana-2-13', text: 'む', en: 'mu', pos: 'character', example: { text: 'さむい', en: 'cold (weather)' } },
      { id: 'v-ja-kana-2-14', text: 'め', en: 'me', pos: 'character', example: { text: 'あめ', en: 'rain' } },
      { id: 'v-ja-kana-2-15', text: 'も', en: 'mo', pos: 'character', example: { text: 'もも', en: 'peach' } },
      { id: 'v-ja-kana-2-16', text: 'や', en: 'ya', pos: 'character', example: { text: 'やさい', en: 'vegetables' } },
      { id: 'v-ja-kana-2-17', text: 'ゆ', en: 'yu', pos: 'character', example: { text: 'ゆき', en: 'snow' } },
      { id: 'v-ja-kana-2-18', text: 'よ', en: 'yo', pos: 'character', example: { text: 'よる', en: 'night' } },
      { id: 'v-ja-kana-2-19', text: 'ら', en: 'ra', pos: 'character', example: { text: 'さくら', en: 'cherry blossom' } },
      { id: 'v-ja-kana-2-20', text: 'り', en: 'ri', pos: 'character', example: { text: 'とり', en: 'bird; chicken' } },
      { id: 'v-ja-kana-2-21', text: 'る', en: 'ru', pos: 'character', example: { text: 'はる', en: 'spring (season)' } },
      { id: 'v-ja-kana-2-22', text: 'れ', en: 're', pos: 'character', example: { text: 'これ', en: 'this' } },
      { id: 'v-ja-kana-2-23', text: 'ろ', en: 'ro', pos: 'character', example: { text: 'いろ', en: 'color' } },
      { id: 'v-ja-kana-2-24', text: 'わ', en: 'wa', pos: 'character', example: { text: 'わたし', en: 'I; me' } },
      { id: 'v-ja-kana-2-25', text: 'を', en: 'wo', pos: 'character', example: { text: 'てをあらいます。', reading: 'て を あらいます。', en: 'I wash my hands.' } },
      { id: 'v-ja-kana-2-26', text: 'ん', en: 'n', pos: 'character', example: { text: 'にほん', en: 'Japan' } },
    ],
  },
  {
    id: 'ja-kana-3',
    title: 'Hiragana 3: ゛ ゜, small ゃゅょ っ, long vowels',
    script: 'hiragana',
    lessons: [
      {
        id: 'g-ja-kana3-1',
        title: 'Dakuten ゛ and handakuten ゜',
        summary:
          'Two small marks turn kana you already know into new sounds. The dakuten ゛ (two short strokes, nicknamed てんてん, tenten) voices the consonant: k → g (か ka → が ga), s → z (さ sa → ざ za), t → d (た ta → だ da), and h → b (は ha → ば ba). The handakuten ゜ (a small circle, まる, maru) goes only on the h row and gives p: ぱ (pa), ぴ (pi), ぷ (pu), ぺ (pe), ぽ (po). Like し (shi), じ is ji, not \'zi\', and in the d row ぢ (ji) and づ (zu) sound exactly like じ (ji) and ず (zu). The pitfall is spelling: write じ and ず by default, and use ぢ or づ only in the few words that need them, such as はなぢ (hanaji, nosebleed) and つづく (tsuzuku, to continue).',
        examples: [
          { text: 'ひらがな', en: 'hiragana' },
          { text: 'てんぷら', en: 'tempura' },
          { text: 'だいがく', en: 'university' },
          { text: 'ぶどう', en: 'grapes' },
        ],
        drills: [
          { text: 'か___', en: 'kagi — key', answer: 'ぎ', distractors: ['き', 'ぐ', 'じ'] },
          { text: 'えん___つ', en: 'enpitsu — pencil', answer: 'ぴ', distractors: ['び', 'ひ', 'ぷ'] },
          { text: '___た', en: 'buta — pig', answer: 'ぶ', distractors: ['ぷ', 'ふ', 'ぼ'] },
          { text: 'ま___', en: 'mado — window', answer: 'ど', distractors: ['と', 'ぞ', 'ご'] },
          { text: 'ち___', en: 'chizu — map', answer: 'ず', distractors: ['す', 'ぞ', 'じ'] },
        ],
      },
      {
        id: 'g-ja-kana3-2',
        title: 'Small ゃ ゅ ょ, small っ, and long vowels',
        summary:
          'A small ゃ, ゅ or ょ (small ya, yu, yo) after an i-sound kana (き ki, し shi, ち chi, に ni, ひ hi, み mi, り ri, ぎ gi, じ ji, び bi, ぴ pi) blends with it into a single beat: き + ゃ = きゃ (kya), し + ゅ = しゅ (shu), ち + ょ = ちょ (cho), じ + ゃ = じゃ (ja). Size matters: びょういん (byōin) is \'hospital\', but びよういん (biyōin) is \'beauty salon\'. A small っ (small tsu) doubles the next consonant with a tiny pause that takes one beat, so きって (kitte, stamp) is different from きて (kite, \'come\'). Long vowels also take two beats and are spelled with an extra vowel: おかあさん (okāsan, mother), おにいさん (oniisan, older brother), and usually う for a long o and い for a long e, as in がっこう (gakkō, school) and せんせい (sensei, teacher). Cutting a long vowel short changes the word: おばあさん (obāsan) is \'grandmother\', but おばさん (obasan) is \'aunt\'.',
        examples: [
          { text: 'きって', en: 'postage stamp' },
          { text: 'がっこう', en: 'school' },
          { text: 'おかあさん', en: 'mother' },
          { text: 'びょういん', en: 'hospital' },
          { text: 'りょこう', en: 'trip; travel' },
        ],
        drills: [
          { text: 'おち___', en: 'ocha — tea', answer: 'ゃ', distractors: ['や', 'ゅ', 'ょ'] },
          { text: 'ま___ちゃ', en: 'matcha — powdered green tea', answer: 'っ', distractors: ['つ', 'ち', 'あ'] },
          { text: 'おば___さん', en: 'obāsan — grandmother', answer: 'あ', distractors: ['お', 'う', 'い'] },
          { text: 'せんせ___', en: 'sensei — teacher', answer: 'い', distractors: ['え', 'あ', 'う'] },
          { text: 'だいじ___うぶ', en: 'daijōbu — it\'s OK; all right', answer: 'ょ', distractors: ['よ', 'ゅ', 'ゃ'] },
        ],
      },
    ],
    items: [
      { id: 'v-ja-kana-3-01', text: 'が', en: 'ga', pos: 'character', example: { text: 'えいが', en: 'movie' } },
      { id: 'v-ja-kana-3-02', text: 'ぎ', en: 'gi', pos: 'character', example: { text: 'ぎんこう', en: 'bank' } },
      { id: 'v-ja-kana-3-03', text: 'ぐ', en: 'gu', pos: 'character', example: { text: 'すぐ', en: 'right away; soon' } },
      { id: 'v-ja-kana-3-04', text: 'げ', en: 'ge', pos: 'character', example: { text: 'げんき', en: 'healthy; full of energy' } },
      { id: 'v-ja-kana-3-05', text: 'ご', en: 'go', pos: 'character', example: { text: 'ごはん', en: 'cooked rice; meal' } },
      { id: 'v-ja-kana-3-06', text: 'ざ', en: 'za', pos: 'character', example: { text: 'ざっし', en: 'magazine' } },
      { id: 'v-ja-kana-3-07', text: 'じ', en: 'ji', pos: 'character', example: { text: 'じかん', en: 'time' } },
      { id: 'v-ja-kana-3-08', text: 'ず', en: 'zu', pos: 'character', example: { text: 'みず', en: 'water' } },
      { id: 'v-ja-kana-3-09', text: 'ぜ', en: 'ze', pos: 'character', example: { text: 'かぜ', en: 'wind; a cold' } },
      { id: 'v-ja-kana-3-10', text: 'ぞ', en: 'zo', pos: 'character', example: { text: 'かぞく', en: 'family' } },
      { id: 'v-ja-kana-3-11', text: 'だ', en: 'da', pos: 'character', example: { text: 'ともだち', en: 'friend' } },
      { id: 'v-ja-kana-3-12', text: 'ぢ', en: 'ji', pos: 'character', example: { text: 'はなぢ', en: 'nosebleed' } },
      { id: 'v-ja-kana-3-13', text: 'づ', en: 'zu', pos: 'character', example: { text: 'つづく', en: 'to continue' } },
      { id: 'v-ja-kana-3-14', text: 'で', en: 'de', pos: 'character', example: { text: 'でんわ', en: 'telephone' } },
      { id: 'v-ja-kana-3-15', text: 'ど', en: 'do', pos: 'character', example: { text: 'どこ', en: 'where' } },
      { id: 'v-ja-kana-3-16', text: 'ば', en: 'ba', pos: 'character', example: { text: 'かばん', en: 'bag' } },
      { id: 'v-ja-kana-3-17', text: 'び', en: 'bi', pos: 'character', example: { text: 'えび', en: 'shrimp' } },
      { id: 'v-ja-kana-3-18', text: 'ぶ', en: 'bu', pos: 'character', example: { text: 'しんぶん', en: 'newspaper' } },
      { id: 'v-ja-kana-3-19', text: 'べ', en: 'be', pos: 'character', example: { text: 'たべもの', en: 'food' } },
      { id: 'v-ja-kana-3-20', text: 'ぼ', en: 'bo', pos: 'character', example: { text: 'ぼうし', en: 'hat; cap' } },
      { id: 'v-ja-kana-3-21', text: 'ぱ', en: 'pa', pos: 'character', example: { text: 'かんぱい', en: 'cheers! (a toast)' } },
      { id: 'v-ja-kana-3-22', text: 'ぴ', en: 'pi', pos: 'character', example: { text: 'えんぴつ', en: 'pencil' } },
      { id: 'v-ja-kana-3-23', text: 'ぷ', en: 'pu', pos: 'character', example: { text: 'きっぷ', en: 'ticket (train, bus)' } },
      { id: 'v-ja-kana-3-24', text: 'ぺ', en: 'pe', pos: 'character', example: { text: 'ぺらぺら', en: 'fluent (in a language)' } },
      { id: 'v-ja-kana-3-25', text: 'ぽ', en: 'po', pos: 'character', example: { text: 'さんぽ', en: 'walk; stroll' } },
      { id: 'v-ja-kana-3-26', text: 'きゃ', en: 'kya', pos: 'character', example: { text: 'おきゃくさん', reading: 'おきゃくさん', en: 'customer; guest' } },
      { id: 'v-ja-kana-3-27', text: 'きゅ', en: 'kyu', pos: 'character', example: { text: 'きゅうり', en: 'cucumber' } },
      { id: 'v-ja-kana-3-28', text: 'きょ', en: 'kyo', pos: 'character', example: { text: 'きょう', en: 'today' } },
      { id: 'v-ja-kana-3-29', text: 'しゃ', en: 'sha', pos: 'character', example: { text: 'しゃしん', en: 'photo' } },
      { id: 'v-ja-kana-3-30', text: 'しゅ', en: 'shu', pos: 'character', example: { text: 'しゅくだい', en: 'homework' } },
      { id: 'v-ja-kana-3-31', text: 'しょ', en: 'sho', pos: 'character', example: { text: 'としょかん', en: 'library' } },
      { id: 'v-ja-kana-3-32', text: 'ちゃ', en: 'cha', pos: 'character', example: { text: 'おちゃ', en: 'tea; green tea' } },
      { id: 'v-ja-kana-3-33', text: 'ちゅ', en: 'chu', pos: 'character', example: { text: 'ちゅうもん', en: 'order (at a restaurant or shop)' } },
      { id: 'v-ja-kana-3-34', text: 'ちょ', en: 'cho', pos: 'character', example: { text: 'ちょっと', en: 'a little; a bit' } },
      { id: 'v-ja-kana-3-35', text: 'じゃ', en: 'ja', pos: 'character', example: { text: 'じゃがいも', en: 'potato' } },
      { id: 'v-ja-kana-3-36', text: 'じゅ', en: 'ju', pos: 'character', example: { text: 'じゅぎょう', en: 'class; lesson' } },
      { id: 'v-ja-kana-3-37', text: 'じょ', en: 'jo', pos: 'character', example: { text: 'じょうず', en: 'skilled; good at' } },
    ],
  },
  {
    id: 'ja-kana-4',
    title: 'Katakana 1: ア to ノ',
    script: 'katakana',
    lessons: [
      {
        id: 'g-ja-kana4-1',
        title: 'What katakana is for: loanwords, foreign names, emphasis',
        summary:
          'Katakana (カタカナ, katakana) has the same sounds as hiragana in sharper, more angular shapes: ア (a) matches あ (a), and カ (ka) matches か (ka). It is used mainly for words borrowed from other languages, like テスト (tesuto, test), for foreign names and places, like カナダ (Kanada, Canada), and for emphasis and sound effects, a bit like italics in English. Loanwords are reshaped to fit Japanese sounds, so most consonants get a vowel after them: \'necktie\' becomes ネクタイ (nekutai). The pitfall is expecting English pronunciation — read the kana as written, then guess the English word. Also watch シ (shi) and ツ (tsu): シ\'s two dots sit on the left and its long stroke sweeps up from the bottom, while ツ\'s dots sit on top and its long stroke falls from the top right.',
        examples: [
          { text: 'テスト', en: 'test' },
          { text: 'スカート', en: 'skirt' },
          { text: 'カナダ', en: 'Canada' },
          { text: 'ケイト', en: 'Kate (a name)' },
        ],
        drills: [
          { text: 'テ___ト', en: 'tesuto — test', answer: 'ス', distractors: ['ヌ', 'ソ', 'ク'] },
          { text: 'ネク___イ', en: 'nekutai — necktie', answer: 'タ', distractors: ['ク', 'ケ', 'ナ'] },
          { text: 'スー___', en: 'sūtsu — suit', answer: 'ツ', distractors: ['シ', 'ソ', 'ノ'] },
          { text: 'タク___ー', en: 'takushī — taxi', answer: 'シ', distractors: ['ツ', 'ソ', 'ノ'] },
          { text: '___ート', en: 'nōto — notebook', answer: 'ノ', distractors: ['ソ', 'ナ', 'ク'] },
        ],
      },
      {
        id: 'g-ja-kana4-2',
        title: 'The long-vowel mark ー and small ッ in katakana words',
        summary:
          'In katakana, a long vowel is shown with the bar ー (chōonpu) instead of an extra vowel kana: コーヒー (kōhī, coffee), ケーキ (kēki, cake). The bar simply holds the vowel before it for one more beat. A small ッ (small tsu) works just like hiragana っ, doubling the next consonant with a short pause: ネット (netto, internet), クッキー (kukkī, cookie). English words often get one or both, so \'soccer\' is サッカー (sakkā) and \'sweater\' is セーター (sētā). The pitfall is cutting them short: ケーキ has three beats (ke-e-ki), and dropping the ー or ッ gives a different word or no word at all.',
        examples: [
          { text: 'クッキー', en: 'cookie' },
          { text: 'セーター', en: 'sweater' },
          { text: 'ネット', en: 'the internet' },
          { text: 'サッカー', en: 'soccer' },
        ],
        drills: [
          { text: 'ケ___キ', en: 'kēki — cake', answer: 'ー', distractors: ['エ', 'イ', 'ッ'] },
          { text: 'ソ___クス', en: 'sokkusu — socks', answer: 'ッ', distractors: ['ツ', 'ー', 'ク'] },
          { text: 'スニ___カー', en: 'sunīkā — sneakers', answer: 'ー', distractors: ['イ', 'ッ', 'ニ'] },
          { text: 'キ___チン', en: 'kitchin — kitchen', answer: 'ッ', distractors: ['ツ', 'ー', 'シ'] },
          { text: 'コ___ト', en: 'kōto — coat', answer: 'ー', distractors: ['ウ', 'オ', 'ッ'] },
        ],
      },
    ],
    items: [
      { id: 'v-ja-kana-4-01', text: 'ア', en: 'a', pos: 'character', example: { text: 'アイス', en: 'ice cream' } },
      { id: 'v-ja-kana-4-02', text: 'イ', en: 'i', pos: 'character', example: { text: 'イタリア', en: 'Italy' } },
      { id: 'v-ja-kana-4-03', text: 'ウ', en: 'u', pos: 'character', example: { text: 'ウイスキー', en: 'whisky' } },
      { id: 'v-ja-kana-4-04', text: 'エ', en: 'e', pos: 'character', example: { text: 'エアコン', en: 'air conditioner' } },
      { id: 'v-ja-kana-4-05', text: 'オ', en: 'o', pos: 'character', example: { text: 'オレンジ', en: 'orange' } },
      { id: 'v-ja-kana-4-06', text: 'カ', en: 'ka', pos: 'character', example: { text: 'カレー', en: 'curry' } },
      { id: 'v-ja-kana-4-07', text: 'キ', en: 'ki', pos: 'character', example: { text: 'スキー', en: 'skiing; skis' } },
      { id: 'v-ja-kana-4-08', text: 'ク', en: 'ku', pos: 'character', example: { text: 'クラス', en: 'class' } },
      { id: 'v-ja-kana-4-09', text: 'ケ', en: 'ke', pos: 'character', example: { text: 'ケーキ', en: 'cake' } },
      { id: 'v-ja-kana-4-10', text: 'コ', en: 'ko', pos: 'character', example: { text: 'コーヒー', en: 'coffee' } },
      { id: 'v-ja-kana-4-11', text: 'サ', en: 'sa', pos: 'character', example: { text: 'サラダ', en: 'salad' } },
      { id: 'v-ja-kana-4-12', text: 'シ', en: 'shi', pos: 'character', example: { text: 'タクシー', en: 'taxi' } },
      { id: 'v-ja-kana-4-13', text: 'ス', en: 'su', pos: 'character', example: { text: 'スープ', en: 'soup' } },
      { id: 'v-ja-kana-4-14', text: 'セ', en: 'se', pos: 'character', example: { text: 'セット', en: 'set; set meal' } },
      { id: 'v-ja-kana-4-15', text: 'ソ', en: 'so', pos: 'character', example: { text: 'ソース', en: 'sauce' } },
      { id: 'v-ja-kana-4-16', text: 'タ', en: 'ta', pos: 'character', example: { text: 'タオル', en: 'towel' } },
      { id: 'v-ja-kana-4-17', text: 'チ', en: 'chi', pos: 'character', example: { text: 'チケット', en: 'ticket' } },
      { id: 'v-ja-kana-4-18', text: 'ツ', en: 'tsu', pos: 'character', example: { text: 'ツアー', en: 'tour' } },
      { id: 'v-ja-kana-4-19', text: 'テ', en: 'te', pos: 'character', example: { text: 'テレビ', en: 'TV' } },
      { id: 'v-ja-kana-4-20', text: 'ト', en: 'to', pos: 'character', example: { text: 'トイレ', en: 'toilet; restroom' } },
      { id: 'v-ja-kana-4-21', text: 'ナ', en: 'na', pos: 'character', example: { text: 'ナイフ', en: 'knife' } },
      { id: 'v-ja-kana-4-22', text: 'ニ', en: 'ni', pos: 'character', example: { text: 'テニス', en: 'tennis' } },
      { id: 'v-ja-kana-4-23', text: 'ヌ', en: 'nu', pos: 'character', example: { text: 'カヌー', en: 'canoe' } },
      { id: 'v-ja-kana-4-24', text: 'ネ', en: 'ne', pos: 'character', example: { text: 'ネクタイ', en: 'necktie; tie' } },
      { id: 'v-ja-kana-4-25', text: 'ノ', en: 'no', pos: 'character', example: { text: 'ノート', en: 'notebook' } },
    ],
  },
  {
    id: 'ja-kana-5',
    title: 'Katakana 2: ハ to ン and loanwords',
    script: 'katakana',
    lessons: [
      {
        id: 'g-ja-kana5-1',
        title: 'The h, m, y, r, w rows, ン, and ゛ ゜ in katakana',
        summary:
          'The rest of katakana mirrors hiragana: ハ ヒ フ ヘ ホ (ha, hi, fu, he, ho), マ ミ ム メ モ (ma, mi, mu, me, mo), ヤ ユ ヨ (ya, yu, yo), ラ リ ル レ ロ (ra, ri, ru, re, ro), ワ (wa), ヲ (wo) and ン (n). The marks ゛ and ゜ work just as in hiragana, giving バ (ba), パ (pa), ガ (ga), ズ (zu), ド (do) and so on, as in バス (basu, bus) and パン (pan, bread). English l and r both become the r row, and v usually becomes b: \'lemon\' is レモン (remon) and \'video\' is ビデオ (bideo). ヘ (he) looks almost the same in both scripts, and ヲ (wo) is rarely seen, because the particle を (o) is written in hiragana. Watch the look-alikes ソ (so) and ン (n): ソ\'s long stroke falls from the top right, while ン\'s sweeps up from the bottom left, just like ツ (tsu) and シ (shi).',
        examples: [
          { text: 'バス', en: 'bus' },
          { text: 'パン', en: 'bread' },
          { text: 'レモン', en: 'lemon' },
          { text: 'ビデオ', en: 'video' },
        ],
        drills: [
          { text: '___ス', en: 'basu — bus', answer: 'バ', distractors: ['パ', 'ハ', 'ボ'] },
          { text: '___ン', en: 'pan — bread', answer: 'パ', distractors: ['バ', 'ハ', 'ポ'] },
          { text: 'レモ___', en: 'remon — lemon', answer: 'ン', distractors: ['ソ', 'シ', 'ツ'] },
          { text: 'ホテ___', en: 'hoteru — hotel', answer: 'ル', distractors: ['レ', 'ロ', 'リ'] },
          { text: 'ア___リカ', en: 'Amerika — America', answer: 'メ', distractors: ['ヌ', 'ナ', 'ム'] },
        ],
      },
      {
        id: 'g-ja-kana5-2',
        title: 'Extended katakana for foreign sounds: ティ, ファ, ウィ, ジェ, ヴ',
        summary:
          'To write sounds that Japanese lacks, katakana adds a small ァ, ィ, ゥ, ェ or ォ (small a, i, u, e, o) after a full-size kana, and the two are read as one beat. ティ (ti) and ディ (di) give \'tee\' and \'dee\', as in パーティー (pātī, party), and ファ, フィ, フェ, フォ give f plus any vowel, as in フォーク (fōku, fork). ウィ (wi) and ウェ (we) appear in words like ハロウィン (harowin, Halloween) and ウェブ (webu, web), and ジェ (je), シェ (she) and チェ (che) in words like ジェット (jetto, jet) and チェック (chekku, check). ヴ (vu) can write a v, as in ヴィーガン (vīgan, vegan), but most people still say it as b, and many words are usually spelled with the b row instead, like バイオリン (baiorin, violin). The pitfall: spellings vary (パーティー pātī or パーティ pāti), so learn each word\'s common form, and remember that ティ (ti) is one beat, not テ + イ (te + i).',
        examples: [
          { text: 'パーティー', en: 'party' },
          { text: 'フォーク', en: 'fork' },
          { text: 'ハロウィン', en: 'Halloween' },
          { text: 'ジェットコースター', reading: 'ジェットコースター', en: 'roller coaster' },
          { text: 'ヴィーガン', en: 'vegan' },
        ],
        drills: [
          { text: 'パー___ー', en: 'pātī — party', answer: 'ティ', distractors: ['チ', 'テイ', 'ディ'] },
          { text: '___ッション', en: 'fasshon — fashion', answer: 'ファ', distractors: ['ハ', 'フア', 'フォ'] },
          { text: 'ハロ___ン', en: 'harowin — Halloween', answer: 'ウィ', distractors: ['ウェ', 'ウォ', 'ワ'] },
          { text: '___ット', en: 'jetto — jet', answer: 'ジェ', distractors: ['ジャ', 'ゼ', 'シェ'] },
          { text: '___ーク', en: 'fōku — fork', answer: 'フォ', distractors: ['ホ', 'フ', 'ファ'] },
        ],
      },
    ],
    items: [
      { id: 'v-ja-kana-5-01', text: 'ハ', en: 'ha', pos: 'character', example: { text: 'ハンバーガー', reading: 'ハンバーガー', en: 'hamburger' } },
      { id: 'v-ja-kana-5-02', text: 'ヒ', en: 'hi', pos: 'character', example: { text: 'ヒーター', en: 'heater' } },
      { id: 'v-ja-kana-5-03', text: 'フ', en: 'fu', pos: 'character', example: { text: 'フランス', en: 'France' } },
      { id: 'v-ja-kana-5-04', text: 'ヘ', en: 'he', pos: 'character', example: { text: 'ヘルメット', en: 'helmet' } },
      { id: 'v-ja-kana-5-05', text: 'ホ', en: 'ho', pos: 'character', example: { text: 'ホテル', en: 'hotel' } },
      { id: 'v-ja-kana-5-06', text: 'マ', en: 'ma', pos: 'character', example: { text: 'マスク', en: 'face mask' } },
      { id: 'v-ja-kana-5-07', text: 'ミ', en: 'mi', pos: 'character', example: { text: 'ミルク', en: 'milk' } },
      { id: 'v-ja-kana-5-08', text: 'ム', en: 'mu', pos: 'character', example: { text: 'ゲーム', en: 'game; video game' } },
      { id: 'v-ja-kana-5-09', text: 'メ', en: 'me', pos: 'character', example: { text: 'メール', en: 'email' } },
      { id: 'v-ja-kana-5-10', text: 'モ', en: 'mo', pos: 'character', example: { text: 'リモコン', en: 'remote control' } },
      { id: 'v-ja-kana-5-11', text: 'ヤ', en: 'ya', pos: 'character', example: { text: 'タイヤ', en: 'tire (on a car)' } },
      { id: 'v-ja-kana-5-12', text: 'ユ', en: 'yu', pos: 'character', example: { text: 'ユニフォーム', reading: 'ユニフォーム', en: 'uniform (for sports)' } },
      { id: 'v-ja-kana-5-13', text: 'ヨ', en: 'yo', pos: 'character', example: { text: 'ヨーロッパ', en: 'Europe' } },
      { id: 'v-ja-kana-5-14', text: 'ラ', en: 'ra', pos: 'character', example: { text: 'ラーメン', en: 'ramen' } },
      { id: 'v-ja-kana-5-15', text: 'リ', en: 'ri', pos: 'character', example: { text: 'アメリカ', en: 'America; the US' } },
      { id: 'v-ja-kana-5-16', text: 'ル', en: 'ru', pos: 'character', example: { text: 'ビール', en: 'beer' } },
      { id: 'v-ja-kana-5-17', text: 'レ', en: 're', pos: 'character', example: { text: 'レストラン', en: 'restaurant' } },
      { id: 'v-ja-kana-5-18', text: 'ロ', en: 'ro', pos: 'character', example: { text: 'ロビー', en: 'lobby' } },
      { id: 'v-ja-kana-5-19', text: 'ワ', en: 'wa', pos: 'character', example: { text: 'ワイン', en: 'wine' } },
      { id: 'v-ja-kana-5-20', text: 'ヲ', en: 'wo', pos: 'character', example: { text: 'ミズヲクダサイ', reading: 'ミズ ヲ クダサイ', en: 'Water, please. (all-katakana style, as in old telegrams)' } },
      { id: 'v-ja-kana-5-21', text: 'ン', en: 'n', pos: 'character', example: { text: 'ペン', en: 'pen' } },
    ],
  },
];
