import type { Unit } from '../types';

/** Japanese units 23–28 (JLPT N3). Normal adult kanji usage; readings are full kana. */
export const unitsN3: Unit[] = [
  // ───────────────────────────── N3 ─────────────────────────────
  {
    id: 'ja-n3-01',
    cefr: 'B1',
    order: 23,
    title: '受身: The passive',
    theme: 'Saying what was done to you, and talking about bad luck and annoying events',
    canDo: [
      'I can say what someone did to me using the passive.',
      'I can describe things that are built, read, or loved by others using the passive.',
      'I can complain about annoying things that happened to me with the suffering passive.',
      'I can tell a friend the story of a bad day.',
    ],
    grammar: [
      {
        id: 'g-ja-n3-01-1',
        title: 'Passive 〜られる',
        summary:
          "The passive turns 'A did something to B' into 'B had something done (by A)', and the doer is marked with に. Group 2 verbs change る to られる (たべる → たべられる); group 1 verbs change the final u-sound to an a-sound and add れる (かく → かかれる, よむ → よまれる, いう → いわれる — note that う becomes わ); the irregular verbs become される (する) and こられる (くる). Passive verbs then conjugate like group 2 verbs: 叱られた, 褒められます, 盗まれない. Japanese uses the passive a lot for things done to you personally (先生に褒められた, 'I was praised by my teacher') and for facts where the doer doesn't matter (この本は世界中で読まれている). A common pitfall: for group 2 verbs the passive looks exactly like the potential (たべられる can mean 'be eaten' or 'can eat'), so rely on context and the に-phrase.",
        examples: [
          { text: '子どものころ、よく母に叱られました。', reading: 'こども の ころ、 よく はは に しかられました。', en: 'When I was a child, I often got scolded by my mother.' },
          { text: '会議で部長に意見を聞かれました。', reading: 'かいぎ で ぶちょう に いけん を きかれました。', en: 'At the meeting, I was asked for my opinion by the department manager.' },
          { text: 'この小説は世界中で読まれています。', reading: 'この しょうせつ は せかいじゅう で よまれて います。', en: 'This novel is read all over the world.' },
          { text: 'オリンピックは四年に一度開かれる。', reading: 'オリンピック は よねん に いちど ひらかれる。', en: 'The Olympics are held once every four years.' },
        ],
        drills: [
          { text: '犬に手を___。', reading: 'いぬ に て を ___。', en: 'I got bitten on the hand by a dog.', answer: 'かまれた', distractors: ['かんだ', 'かませた', 'かめた'] },
          { text: 'このお寺は600年前に___。', reading: 'この おてら は ろっぴゃくねん まえ に ___。', en: 'This temple was built 600 years ago.', answer: '建てられた', distractors: ['建てた', '建てさせた', '建てられる'] },
          { text: 'テストでいい点を取って、父に___。', reading: 'テスト で いい てん を とって、 ちち に ___。', en: 'I got a good score on the test and was praised by my father.', answer: '褒められた', distractors: ['褒めた', '褒めさせた', '褒められる'] },
          { text: 'この歌は五十年以上、多くの人に___います。', reading: 'この うた は ごじゅうねん いじょう、 おおく の ひと に ___ います。', en: 'This song has been loved by many people for over fifty years.', answer: '愛されて', distractors: ['愛して', '愛させて', '愛せて'] },
          { text: 'パーティーに___けど、行けなかった。', reading: 'パーティー に ___ けど、 いけなかった。', en: "I was invited to the party, but I couldn't go.", answer: '誘われた', distractors: ['誘った', '誘わせた', '誘えた'] },
        ],
      },
      {
        id: 'g-ja-n3-01-2',
        title: 'The suffering passive (雨に降られた)',
        summary:
          "Japanese can also use the passive with verbs that have no object, like 降る, 泣く or 来る, to show that the speaker was negatively affected — this is called the suffering (or adversative) passive. 雨に降られた literally means 'I was rained on' (I got caught in the rain), and 赤ちゃんに一晩中泣かれた means 'the baby cried all night, and I suffered for it'. The cause of the trouble takes に, and the person who suffered is the subject, usually left out because it's 'me'. With verbs that take an object, the affected thing keeps を: 弟にケーキを食べられた ('my little brother ate my cake on me'). English has no direct equivalent, so translate with 'on me' or by adding the feeling. A common mistake is using this for kind actions — for favors, use 〜てもらう or 〜てくれる instead (友達に手伝ってもらった, not 手伝われた).",
        examples: [
          { text: '帰り道で雨に降られて、びしょびしょになった。', reading: 'かえりみち で あめ に ふられて、 びしょびしょ に なった。', en: 'I got caught in the rain on the way home and got soaked.' },
          { text: '隣の部屋の人に夜遅くまでパーティーをされて、眠れませんでした。', reading: 'となり の へや の ひと に よる おそく まで パーティー を されて、 ねむれません でした。', en: "The people next door had a party until late at night, and I couldn't sleep." },
          { text: '試験の前の日に友達に来られて、勉強できなかった。', reading: 'しけん の まえ の ひ に ともだち に こられて、 べんきょう できなかった。', en: "A friend came over the day before my exam, so I couldn't study." },
          { text: '妹に私のケーキを食べられた。', reading: 'いもうと に わたし の ケーキ を たべられた。', en: 'My little sister ate my cake on me.' },
        ],
        drills: [
          { text: '駅から歩いていたら、急に雨に___。', reading: 'えき から あるいて いたら、 きゅう に あめ に ___。', en: 'I was walking from the station when I suddenly got caught in the rain.', answer: '降られた', distractors: ['降った', '降らせた', '降れた'] },
          { text: '一晩中、赤ちゃんに___、全然寝られなかった。', reading: 'ひとばんじゅう、 あかちゃん に ___、 ぜんぜん ねられなかった。', en: "The baby cried all night (on me), so I couldn't sleep at all.", answer: '泣かれて', distractors: ['泣いて', '泣かせて', '泣けて'] },
          { text: '母に日記を___、とても恥ずかしかった。', reading: 'はは に にっき を ___、 とても はずかしかった。', en: 'My mother read my diary, and I was really embarrassed.', answer: '読まれて', distractors: ['読んで', '読ませて', '読めて'] },
          { text: '前に背の高い人に___、ステージが見えなかった。', reading: 'まえ に せ の たかい ひと に ___、 ステージ が みえなかった。', en: "A tall person stood in front of me, so I couldn't see the stage.", answer: '立たれて', distractors: ['立って', '立たせて', '立てて'] },
          { text: '大切な花瓶を猫に___。', reading: 'たいせつ な かびん を ねこ に ___。', en: 'My cat broke my precious vase (on me).', answer: '割られた', distractors: ['割った', '割れた', '割らせた'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n3-01-01', text: '叱る', reading: 'しかる', en: 'to scold', pos: 'verb', example: { text: '宿題を忘れて、先生に叱られました。', reading: 'しゅくだい を わすれて、 せんせい に しかられました。', en: 'I forgot my homework and got scolded by the teacher.' } },
      { id: 'v-ja-n3-01-02', text: '褒める', reading: 'ほめる', en: 'to praise', pos: 'verb', example: { text: '料理が上手だと、みんなに褒められた。', reading: 'りょうり が じょうず だ と、 みんな に ほめられた。', en: 'Everyone praised me for being a good cook.' } },
      { id: 'v-ja-n3-01-03', text: '盗む', reading: 'ぬすむ', en: 'to steal', pos: 'verb', example: { text: '駅で財布を盗まれました。', reading: 'えき で さいふ を ぬすまれました。', en: 'My wallet was stolen at the station.' } },
      { id: 'v-ja-n3-01-04', text: '踏む', reading: 'ふむ', en: 'to step on', pos: 'verb', example: { text: '満員電車で足を踏まれて、痛かった。', reading: 'まんいんでんしゃ で あし を ふまれて、 いたかった。', en: 'Someone stepped on my foot on the packed train, and it hurt.' } },
      { id: 'v-ja-n3-01-05', text: 'かむ', en: 'to bite; to chew', pos: 'verb', example: { text: 'よくかんで食べてください。', reading: 'よく かんで たべて ください。', en: 'Please chew your food well.' } },
      { id: 'v-ja-n3-01-06', text: '刺す', reading: 'さす', en: 'to sting; to stab', pos: 'verb', example: { text: 'ハチに刺されて、手が赤くなった。', reading: 'ハチ に さされて、 て が あかく なった。', en: 'I got stung by a bee and my hand turned red.' } },
      { id: 'v-ja-n3-01-07', text: '汚す', reading: 'よごす', en: 'to get (something) dirty', pos: 'verb', example: { text: '借りた本をコーヒーで汚してしまった。', reading: 'かりた ほん を コーヒー で よごして しまった。', en: 'I got coffee on a book I borrowed.' } },
      { id: 'v-ja-n3-01-08', text: 'ぬれる', en: 'to get wet', pos: 'verb', example: { text: '傘がなくて、服がぬれてしまった。', reading: 'かさ が なくて、 ふく が ぬれて しまった。', en: "I didn't have an umbrella, so my clothes got wet." } },
      { id: 'v-ja-n3-01-09', text: '誘う', reading: 'さそう', en: 'to invite; to ask (someone) along', pos: 'verb', example: { text: '友達に映画に誘われた。', reading: 'ともだち に えいが に さそわれた。', en: 'A friend invited me to a movie.' } },
      { id: 'v-ja-n3-01-10', text: '邪魔', reading: 'じゃま', en: 'hindrance; being in the way', pos: 'noun', example: { text: '弟に勉強の邪魔をされた。', reading: 'おとうと に べんきょう の じゃま を された。', en: 'My little brother kept interrupting my studying.' } },
      { id: 'v-ja-n3-01-11', text: '迷惑', reading: 'めいわく', en: 'trouble; nuisance; bother', pos: 'noun', example: { text: '電車の中で大声で話すのは、周りの人に迷惑です。', reading: 'でんしゃ の なか で おおごえ で はなす の は、 まわり の ひと に めいわく です。', en: 'Talking loudly on the train bothers the people around you.' } },
      { id: 'v-ja-n3-01-12', text: '遅刻', reading: 'ちこく', en: 'being late', pos: 'noun', example: { text: '寝坊して、会社に遅刻した。', reading: 'ねぼう して、 かいしゃ に ちこく した。', en: 'I overslept and was late for work.' } },
      { id: 'v-ja-n3-01-13', text: '最悪', reading: 'さいあく', en: 'the worst; terrible (na-adj.)', pos: 'adjective', example: { text: '今日は朝から最悪だった。', reading: 'きょう は あさ から さいあく だった。', en: 'Today was terrible from the morning on.' } },
      { id: 'v-ja-n3-01-14', text: '満員', reading: 'まんいん', en: 'full; packed (with people)', pos: 'noun', example: { text: 'この時間の電車はいつも満員です。', reading: 'この じかん の でんしゃ は いつも まんいん です。', en: 'The trains at this hour are always packed.' } },
      { id: 'v-ja-n3-01-15', text: '文句', reading: 'もんく', en: 'complaint', pos: 'noun', example: { text: '隣の人に「うるさい」と文句を言われた。', reading: 'となり の ひと に 「うるさい」 と もんく を いわれた。', en: 'My neighbor complained that I was too noisy.' } },
      { id: 'v-ja-n3-01-16', text: '発明', reading: 'はつめい', en: 'invention', pos: 'noun', example: { text: 'カップラーメンは日本で発明された。', reading: 'カップラーメン は にほん で はつめい された。', en: 'Cup noodles were invented in Japan.' } },
      { id: 'v-ja-n3-01-17', text: '翻訳', reading: 'ほんやく', en: 'translation', pos: 'noun', example: { text: '彼の小説は三十以上の言語に翻訳されている。', reading: 'かれ の しょうせつ は さんじゅう いじょう の げんご に ほんやく されて いる。', en: 'His novels have been translated into more than thirty languages.' } },
      { id: 'v-ja-n3-01-18', text: '泥棒', reading: 'どろぼう', en: 'thief; burglar', pos: 'noun', example: { text: '留守の間に泥棒に入られた。', reading: 'るす の あいだ に どろぼう に はいられた。', en: 'A burglar broke into our place while we were out.' } },
    ],
    scenario: {
      title: 'The worst day ever',
      setting: "It's Friday evening in Tokyo. You meet a friend at an izakaya after what was honestly the worst day of your week.",
      aiRole: 'Haruka, a sympathetic friend from university who loves hearing stories',
      learnerGoal:
        'Tell Haruka at least three bad things that happened to you today using the passive (e.g. getting caught in the rain, being scolded, having something stolen), react to her sympathy, and end on a positive note.',
      opener: 'お疲れ！なんか元気ないね。今日、何かあったの？',
      openerReading: 'おつかれ！ なんか げんき ない ね。 きょう、 なにか あった の？',
    },
  },
  {
    id: 'ja-n3-02',
    cefr: 'B1',
    order: 24,
    title: '使役: Making and letting',
    theme: 'Making and letting people do things, asking permission politely, and being made to do things',
    canDo: [
      'I can say that someone made or let someone do something.',
      'I can politely ask permission with 〜させてください and 〜させていただけませんか.',
      'I can complain about things I was made to do with the causative-passive.',
      'I can ask my manager to let me leave work early.',
    ],
    grammar: [
      {
        id: 'g-ja-n3-02-1',
        title: 'Causative 〜させる',
        summary:
          "The causative means 'make someone do' or 'let someone do'. Group 2 verbs change る to させる (たべる → たべさせる); group 1 verbs change the final u-sound to an a-sound and add せる (いく → いかせる, かう → かわせる); the irregular verbs become させる (する) and こさせる (くる). The person who is made or allowed to act takes に when the verb already has an object with を (子どもに野菜を食べさせる), and usually を when it doesn't (子どもを公園で遊ばせる). Whether it means 'make' or 'let' comes from context — adding 〜てくれる makes it a favor, so 父は留学させてくれた means 'my father let me study abroad'. With emotion verbs it means 'cause to feel': みんなを笑わせる (make everyone laugh), 親を心配させる (make your parents worry). A common pitfall: the causative is used about people under you (children, staff, pets), so don't use it to talk about 'letting' your boss or teacher do something.",
        examples: [
          { text: '母は毎日、私に野菜を食べさせました。', reading: 'はは は まいにち、 わたし に やさい を たべさせました。', en: 'My mother made me eat vegetables every day.' },
          { text: '部長は新人に会議の資料を作らせた。', reading: 'ぶちょう は しんじん に かいぎ の しりょう を つくらせた。', en: 'The manager had the new employee prepare the materials for the meeting.' },
          { text: '子どもを公園で自由に遊ばせています。', reading: 'こども を こうえん で じゆう に あそばせて います。', en: "I'm letting the kids play freely in the park." },
          { text: '彼はいつも冗談を言って、みんなを笑わせる。', reading: 'かれ は いつも じょうだん を いって、 みんな を わらわせる。', en: 'He always tells jokes and makes everyone laugh.' },
          { text: '遅く帰って、親を心配させてしまった。', reading: 'おそく かえって、 おや を しんぱい させて しまった。', en: 'I came home late and made my parents worry.' },
        ],
        drills: [
          { text: '先生は学生に毎日日記を___。', reading: 'せんせい は がくせい に まいにち にっき を ___。', en: 'The teacher makes the students write a diary every day.', answer: '書かせます', distractors: ['書かれます', '書きます', '書かせられます'] },
          { text: '父は私を一人で海外に___くれた。', reading: 'ちち は わたし を ひとり で かいがい に ___ くれた。', en: 'My father let me go abroad on my own.', answer: '行かせて', distractors: ['行かれて', '行って', '行けて'] },
          { text: 'プレゼントをあげて、彼女を___。', reading: 'プレゼント を あげて、 かのじょ を ___。', en: 'I gave my girlfriend a present and made her happy.', answer: '喜ばせた', distractors: ['喜ばれた', '喜んだ', '喜ばせられた'] },
          { text: '息子にピアノを___いますが、本人はあまり好きじゃないようです。', reading: 'むすこ に ピアノ を ___ います が、 ほんにん は あまり すき じゃ ない よう です。', en: "I'm having my son take piano lessons, but he doesn't seem to like it much.", answer: '習わせて', distractors: ['習われて', '習って', '習えて'] },
          { text: '母親は子ども___野菜を食べさせた。', reading: 'ははおや は こども ___ やさい を たべさせた。', en: 'The mother made her child eat vegetables.', answer: 'に', distractors: ['を', 'が', 'で'] },
        ],
      },
      {
        id: 'g-ja-n3-02-2',
        title: '〜させてください and causative-passive 〜させられる',
        summary:
          "To ask permission to do something yourself, use the causative て-form + ください, literally 'please let me…': 私にやらせてください. In business or with superiors, the softer 〜させていただけませんか ('could you possibly allow me to…?') is far more polite: 今日は早く帰らせていただけませんか. The causative-passive means 'be made to do' something you didn't want to do: group 2 verbs take させられる (たべさせられる), group 1 verbs take せられる or the more common short form される (のませられる → のまされる), and する becomes させられる. The person who forced you is marked with に: 部長に残業させられた ('my manager made me work overtime'). Watch out: the short される form isn't used for group 1 verbs ending in す (はなす → はなさせられる), and don't confuse 〜させられた ('I was made to') with 〜させた ('I made someone') — English 'made' covers both.",
        examples: [
          { text: 'その仕事、ぜひ私にやらせてください。', reading: 'その しごと、 ぜひ わたし に やらせて ください。', en: 'Please let me do that job.' },
          { text: '体調が悪いので、今日は早退させていただけませんか。', reading: 'たいちょう が わるい ので、 きょう は そうたい させて いただけません か。', en: "I'm not feeling well — could I possibly leave early today?" },
          { text: '子どものころ、毎日ピアノを練習させられました。', reading: 'こども の ころ、 まいにち ピアノ を れんしゅう させられました。', en: 'As a child, I was made to practice the piano every day.' },
          { text: '昨日の飲み会で、先輩にお酒をたくさん飲まされた。', reading: 'きのう の のみかい で、 せんぱい に おさけ を たくさん のまされた。', en: 'At the drinking party yesterday, a senior colleague made me drink a lot.' },
          { text: '駅で一時間も待たされました。', reading: 'えき で いちじかん も またされました。', en: 'I was kept waiting at the station for a whole hour.' },
        ],
        drills: [
          { text: 'その件は少し___ください。', reading: 'その けん は すこし ___ ください。', en: 'Please let me think about that matter a little.', answer: '考えさせて', distractors: ['考えられて', '考えて', '考えさせられて'] },
          { text: '熱があるので、今日は___いただけませんか。', reading: 'ねつ が ある ので、 きょう は ___ いただけません か。', en: 'I have a fever — could you let me take today off?', answer: '休ませて', distractors: ['休まれて', '休んで', '休まされて'] },
          { text: '子どものころ、嫌いなにんじんを無理やり___。', reading: 'こども の ころ、 きらい な にんじん を むりやり ___。', en: 'As a kid, I was forced to eat carrots, which I hated.', answer: '食べさせられた', distractors: ['食べさせた', '食べられた', '食べた'] },
          { text: '部長に毎晩遅くまで___、本当に疲れた。', reading: 'ぶちょう に まいばん おそく まで ___、 ほんとう に つかれた。', en: 'My manager made me work late every night, and I was really exhausted.', answer: '残業させられて', distractors: ['残業させて', '残業されて', '残業して'] },
          { text: '友達に三十分も___。', reading: 'ともだち に さんじゅっぷん も ___。', en: 'My friend kept me waiting for a full thirty minutes.', answer: '待たされた', distractors: ['待たせた', '待った', '待てた'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n3-02-01', text: '驚く', reading: 'おどろく', en: 'to be surprised', pos: 'verb', example: { text: '急に後ろから声をかけて、友達を驚かせた。', reading: 'きゅう に うしろ から こえ を かけて、 ともだち を おどろかせた。', en: 'I called out from behind and startled my friend.' } },
      { id: 'v-ja-n3-02-02', text: '喜ぶ', reading: 'よろこぶ', en: 'to be glad; to be delighted', pos: 'verb', example: { text: '合格の知らせを聞いて、両親はとても喜んだ。', reading: 'ごうかく の しらせ を きいて、 りょうしん は とても よろこんだ。', en: "My parents were overjoyed to hear I'd passed." } },
      { id: 'v-ja-n3-02-03', text: '悲しむ', reading: 'かなしむ', en: 'to be sad; to grieve', pos: 'verb', example: { text: '親を悲しませるようなことはしたくない。', reading: 'おや を かなしませる よう な こと は したくない。', en: "I don't want to do anything that would make my parents sad." } },
      { id: 'v-ja-n3-02-04', text: '育てる', reading: 'そだてる', en: 'to raise; to bring up', pos: 'verb', example: { text: '祖母は一人で五人の子どもを育てた。', reading: 'そぼ は ひとり で ごにん の こども を そだてた。', en: 'My grandmother raised five children on her own.' } },
      { id: 'v-ja-n3-02-05', text: '任せる', reading: 'まかせる', en: 'to leave (a task) to someone; to entrust', pos: 'verb', example: { text: 'この仕事は君に任せるよ。', reading: 'この しごと は きみ に まかせる よ。', en: "I'm leaving this job to you." } },
      { id: 'v-ja-n3-02-06', text: '断る', reading: 'ことわる', en: 'to refuse; to turn down', pos: 'verb', example: { text: '上司の誘いを断るのは難しい。', reading: 'じょうし の さそい を ことわる の は むずかしい。', en: "It's hard to turn down an invitation from your boss." } },
      { id: 'v-ja-n3-02-07', text: '我慢', reading: 'がまん', en: 'patience; putting up with something', pos: 'noun', example: { text: '眠かったけど、会議が終わるまで我慢した。', reading: 'ねむかった けど、 かいぎ が おわる まで がまん した。', en: 'I was sleepy, but I held out until the meeting ended.' } },
      { id: 'v-ja-n3-02-08', text: '命令', reading: 'めいれい', en: 'order; command', pos: 'noun', example: { text: '社長の命令なら、仕方がない。', reading: 'しゃちょう の めいれい なら、 しかた が ない。', en: "If it's the company president's order, we have no choice." } },
      { id: 'v-ja-n3-02-09', text: '許可', reading: 'きょか', en: 'permission', pos: 'noun', example: { text: 'ここで写真を撮るには許可が必要です。', reading: 'ここ で しゃしん を とる に は きょか が ひつよう です。', en: 'You need permission to take photos here.' } },
      { id: 'v-ja-n3-02-10', text: '早退', reading: 'そうたい', en: 'leaving (work or school) early', pos: 'noun', example: { text: '熱が出たので、学校を早退した。', reading: 'ねつ が でた ので、 がっこう を そうたい した。', en: 'I had a fever, so I left school early.' } },
      { id: 'v-ja-n3-02-11', text: '残業', reading: 'ざんぎょう', en: 'overtime (work)', pos: 'noun', example: { text: '今週は毎日残業している。', reading: 'こんしゅう は まいにち ざんぎょう して いる。', en: "I've been working overtime every day this week." } },
      { id: 'v-ja-n3-02-12', text: '上司', reading: 'じょうし', en: 'boss; superior', pos: 'noun', example: { text: '上司に仕事のことを相談した。', reading: 'じょうし に しごと の こと を そうだん した。', en: 'I talked to my boss about work.' } },
      { id: 'v-ja-n3-02-13', text: '部下', reading: 'ぶか', en: 'subordinate; member of your team', pos: 'noun', example: { text: '彼は部下に仕事を任せるのが上手だ。', reading: 'かれ は ぶか に しごと を まかせる の が じょうず だ。', en: "He's good at handing work over to his team." } },
      { id: 'v-ja-n3-02-14', text: '体調', reading: 'たいちょう', en: 'physical condition; how one feels', pos: 'noun', example: { text: '最近、体調がよくない。', reading: 'さいきん、 たいちょう が よくない。', en: "I haven't been feeling well lately." } },
      { id: 'v-ja-n3-02-15', text: '書類', reading: 'しょるい', en: 'documents; paperwork', pos: 'noun', example: { text: '明日までにこの書類を出してください。', reading: 'あした まで に この しょるい を だして ください。', en: 'Please hand in these documents by tomorrow.' } },
      { id: 'v-ja-n3-02-16', text: '塾', reading: 'じゅく', en: 'cram school', pos: 'noun', example: { text: '息子を週に三回塾に通わせている。', reading: 'むすこ を しゅう に さんかい じゅく に かよわせて いる。', en: 'I send my son to cram school three times a week.' } },
      { id: 'v-ja-n3-02-17', text: '自由', reading: 'じゆう', en: 'free; freedom (na-adj.)', pos: 'adjective', example: { text: '週末は自由に過ごしたい。', reading: 'しゅうまつ は じゆう に すごしたい。', en: 'I want to spend my weekends however I like.' } },
      { id: 'v-ja-n3-02-18', text: '無理やり', reading: 'むりやり', en: 'forcibly; against one\'s will', pos: 'adverb', example: { text: '嫌がる子どもを無理やり歯医者に連れていった。', reading: 'いやがる こども を むりやり はいしゃ に つれて いった。', en: 'I dragged my reluctant child to the dentist.' } },
    ],
    scenario: {
      title: 'Asking to leave early',
      setting:
        'You work at a trading company in Tokyo. You need to leave two hours early today for a family matter, so you go to your manager\'s desk in the afternoon.',
      aiRole: 'Mr. Yamamoto, your busy but fair department manager',
      learnerGoal:
        'Politely ask to leave early using 〜させていただけませんか, explain your reason, offer to finish or hand over your remaining work, and thank him.',
      opener: 'ああ、お疲れさま。どうした？何か相談？',
      openerReading: 'ああ、 おつかれさま。 どう した？ なにか そうだん？',
    },
  },
  {
    id: 'ja-n3-03',
    cefr: 'B1',
    order: 25,
    title: '敬語: Honorific and humble language',
    theme: 'Showing respect with honorific and humble verbs in hotels, shops, and business',
    canDo: [
      'I can recognize and use common honorific verbs such as いらっしゃる and 召し上がる.',
      'I can talk about my own actions humbly with 申す, 参る, and お〜する.',
      'I can understand the polite language used by hotel and shop staff.',
      'I can check in at a hotel and make simple requests.',
    ],
    grammar: [
      {
        id: 'g-ja-n3-03-1',
        title: 'Honorific verbs and お〜になる',
        summary:
          'Honorific language (尊敬語, そんけいご) raises the other person by describing their actions respectfully — never use it about yourself. Several common verbs have special honorific forms: いる/行く/来る → いらっしゃる, 言う → おっしゃる, 食べる/飲む → 召し上がる (めしあがる), 見る → ご覧になる (ごらんになる), する → なさる, and 知っている → ご存じだ (ごぞんじだ). Most other verbs use お + ます-stem + になる (待つ → お待ちになる, 帰る → お帰りになる), and polite requests use お + stem + ください (お待ちください, お座りください). Note the irregular ます-forms: いらっしゃいます, おっしゃいます, なさいます (not いらっしゃります). A common pitfall is using a humble verb for a superior\'s action, e.g. 社長が参りました instead of 社長がいらっしゃいました.',
        examples: [
          { text: '社長は今、会議室にいらっしゃいます。', reading: 'しゃちょう は いま、 かいぎしつ に いらっしゃいます。', en: 'The company president is in the meeting room now.' },
          { text: '先生、何を召し上がりますか。', reading: 'せんせい、 なに を めしあがります か。', en: 'Professor, what would you like to eat?' },
          { text: 'お客様、何時ごろお戻りになりますか。', reading: 'おきゃくさま、 なんじ ごろ おもどり に なります か。', en: 'Around what time will you be back? (to a guest)' },
          { text: 'こちらの資料はもうご覧になりましたか。', reading: 'こちら の しりょう は もう ごらん に なりました か。', en: 'Have you already looked at these materials?' },
          { text: 'どうぞ、こちらでお待ちください。', reading: 'どうぞ、 こちら で おまち ください。', en: 'Please wait here.' },
        ],
        drills: [
          { text: '部長は明日、大阪へ___。', reading: 'ぶちょう は あした、 おおさか へ ___。', en: 'The department manager is going to Osaka tomorrow. (respectful)', answer: 'いらっしゃいます', distractors: ['参ります', 'いらっしゃります', 'おります'] },
          { text: '先生が「明日は休みです」と___。', reading: 'せんせい が 「あした は やすみ です」 と ___。', en: 'The teacher said there is no class tomorrow. (respectful)', answer: 'おっしゃいました', distractors: ['申しました', 'おっしゃりました', 'いたしました'] },
          { text: 'どうぞ、たくさん___ください。', reading: 'どうぞ、 たくさん ___ ください。', en: 'Please help yourself — eat as much as you like.', answer: '召し上がって', distractors: ['いただいて', '食べさせて', '参って'] },
          { text: '田中様、こちらにお名前を___ください。', reading: 'たなか さま、 こちら に おなまえ を ___ ください。', en: 'Mr. Tanaka, please write your name here.', answer: 'お書き', distractors: ['お書きに', 'ご書き', 'お書きして'] },
          { text: 'このニュースをもう___か。', reading: 'この ニュース を もう ___ か。', en: 'Have you already seen this news? (respectful)', answer: 'ご覧になりました', distractors: ['拝見しました', 'お見になりました', 'ご覧しました'] },
        ],
      },
      {
        id: 'g-ja-n3-03-2',
        title: 'Humble verbs and お〜する',
        summary:
          "Humble language (謙譲語, けんじょうご) lowers yourself or your group — your family or your company — to show respect to the listener; never use it for the listener's actions. Common humble verbs: 行く/来る → 参る (まいる), 言う → 申す (もうす), する → いたす, いる → おる, 見る → 拝見する (はいけんする), 食べる/飲む/もらう → いただく, and 訪ねる/聞く → 伺う (うかがう). For other verbs, use お + ます-stem + する (持つ → お持ちする, 待つ → お待ちする), or ご + noun + する for many Chinese-origin する-verbs (案内 → ご案内する, 連絡 → ご連絡する); using いたす instead of する makes it even more polite (ご案内いたします). These お〜する forms are only for actions done for or toward the other person, so you can't use them for things you do purely for yourself. When speaking to outsiders, even your own boss is on 'your side': say 田中はただ今おりません, not 田中さんはいらっしゃいません.",
        examples: [
          { text: 'はじめまして。さくら銀行の田中と申します。', reading: 'はじめまして。 さくらぎんこう の たなか と もうします。', en: "Nice to meet you. I'm Tanaka from Sakura Bank." },
          { text: 'お荷物、お持ちしましょうか。', reading: 'おにもつ、 おもち しましょう か。', en: 'Shall I carry your luggage for you?' },
          { text: '明日の午後3時に、そちらに伺います。', reading: 'あした の ごご さんじ に、 そちら に うかがいます。', en: "I'll come to your office at 3 p.m. tomorrow." },
          { text: 'お部屋までご案内いたします。', reading: 'おへや まで ごあんない いたします。', en: "I'll show you to your room." },
          { text: '父は今、出かけております。', reading: 'ちち は いま、 でかけて おります。', en: 'My father is out at the moment.' },
        ],
        drills: [
          { text: 'はじめまして。キムと___。', reading: 'はじめまして。 キム と ___。', en: "Nice to meet you. I'm Kim.", answer: '申します', distractors: ['おっしゃいます', '言われます', 'いらっしゃいます'] },
          { text: '駅までお迎えに___。', reading: 'えき まで おむかえ に ___。', en: "I'll come to the station to pick you up.", answer: '参ります', distractors: ['いらっしゃいます', 'お越しになります', 'なさいます'] },
          { text: 'お荷物を___しましょうか。', reading: 'おにもつ を ___ しましょう か。', en: 'Shall I carry your bags for you?', answer: 'お持ち', distractors: ['お持ちに', 'ご持ち', '持って'] },
          { text: '会議室まで___いたします。', reading: 'かいぎしつ まで ___ いたします。', en: "I'll show you to the meeting room.", answer: 'ご案内', distractors: ['お案内', 'ご案内に', '案内して'] },
          { text: '先生の新しいご本、もう___。', reading: 'せんせい の あたらしい ごほん、 もう ___。', en: "Professor, I've already had a look at your new book.", answer: '拝見しました', distractors: ['ご覧になりました', '拝見になりました', 'お見しました'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n3-03-01', text: 'いらっしゃる', en: 'to be; to go; to come (honorific)', pos: 'verb', example: { text: '田中先生はいらっしゃいますか。', reading: 'たなか せんせい は いらっしゃいます か。', en: 'Is Professor Tanaka in?' } },
      { id: 'v-ja-n3-03-02', text: 'おっしゃる', en: 'to say (honorific)', pos: 'verb', example: { text: 'すみません、今何とおっしゃいましたか。', reading: 'すみません、 いま なん と おっしゃいました か。', en: "I'm sorry, what did you just say?" } },
      { id: 'v-ja-n3-03-03', text: '召し上がる', reading: 'めしあがる', en: 'to eat; to drink (honorific)', pos: 'verb', example: { text: 'お飲み物は何を召し上がりますか。', reading: 'おのみもの は なに を めしあがります か。', en: 'What would you like to drink?' } },
      { id: 'v-ja-n3-03-04', text: 'ご覧になる', reading: 'ごらん に なる', en: 'to see; to look at (honorific)', pos: 'verb', example: { text: '窓から富士山がご覧になれます。', reading: 'まど から ふじさん が ごらん に なれます。', en: 'You can see Mt. Fuji from the window.' } },
      { id: 'v-ja-n3-03-05', text: '申す', reading: 'もうす', en: 'to say; to be called (humble)', pos: 'verb', example: { text: '受付の佐藤と申します。', reading: 'うけつけ の さとう と もうします。', en: "I'm Sato from the front desk." } },
      { id: 'v-ja-n3-03-06', text: '参る', reading: 'まいる', en: 'to go; to come (humble)', pos: 'verb', example: { text: 'すぐに係の者が参ります。', reading: 'すぐ に かかり の もの が まいります。', en: 'A staff member will be with you shortly.' } },
      { id: 'v-ja-n3-03-07', text: '伺う', reading: 'うかがう', en: 'to visit; to ask (humble)', pos: 'verb', example: { text: 'ちょっと伺いたいことがあるんですが。', reading: 'ちょっと うかがいたい こと が ある ん です が。', en: "There's something I'd like to ask you." } },
      { id: 'v-ja-n3-03-08', text: '拝見する', reading: 'はいけん する', en: 'to see; to look at (humble)', pos: 'verb', example: { text: 'パスポートを拝見してもよろしいですか。', reading: 'パスポート を はいけん して も よろしい です か。', en: 'May I see your passport?' } },
      { id: 'v-ja-n3-03-09', text: '予約', reading: 'よやく', en: 'reservation; booking', pos: 'noun', example: { text: '今日から二泊で予約している山田です。', reading: 'きょう から にはく で よやく して いる やまだ です。', en: "I'm Yamada — I have a reservation for two nights starting today." } },
      { id: 'v-ja-n3-03-10', text: '宿泊', reading: 'しゅくはく', en: 'stay (at a hotel); lodging', pos: 'noun', example: { text: '宿泊料金には朝食が含まれています。', reading: 'しゅくはくりょうきん に は ちょうしょく が ふくまれて います。', en: 'Breakfast is included in the room rate.' } },
      { id: 'v-ja-n3-03-11', text: '朝食', reading: 'ちょうしょく', en: 'breakfast', pos: 'noun', example: { text: '朝食は七時から一階のレストランでございます。', reading: 'ちょうしょく は しちじ から いっかい の レストラン で ございます。', en: "Breakfast is served from seven o'clock in the restaurant on the first floor." } },
      { id: 'v-ja-n3-03-12', text: '禁煙', reading: 'きんえん', en: 'no smoking; non-smoking', pos: 'noun', example: { text: '禁煙のお部屋をお願いします。', reading: 'きんえん の おへや を おねがい します。', en: 'A non-smoking room, please.' } },
      { id: 'v-ja-n3-03-13', text: '確認', reading: 'かくにん', en: 'confirmation; checking', pos: 'noun', example: { text: 'ご予約の内容を確認いたします。', reading: 'ごよやく の ないよう を かくにん いたします。', en: "I'll confirm the details of your reservation." } },
      { id: 'v-ja-n3-03-14', text: '担当', reading: 'たんとう', en: 'being in charge (of something)', pos: 'noun', example: { text: 'この件の担当は私です。', reading: 'この けん の たんとう は わたし です。', en: "I'm the person in charge of this matter." } },
      { id: 'v-ja-n3-03-15', text: '少々', reading: 'しょうしょう', en: 'a little; a moment (polite)', pos: 'adverb', example: { text: '少々お待ちください。', reading: 'しょうしょう おまち ください。', en: 'Please wait a moment.' } },
      { id: 'v-ja-n3-03-16', text: 'かしこまりました', en: 'certainly; understood (polite)', pos: 'phrase', example: { text: 'かしこまりました。すぐにお持ちします。', reading: 'かしこまりました。 すぐ に おもち します。', en: "Certainly. I'll bring it right away." } },
      { id: 'v-ja-n3-03-17', text: 'お客様', reading: 'おきゃくさま', en: 'customer; guest (polite)', pos: 'noun', example: { text: 'お客様、お荷物はこちらでお預かりします。', reading: 'おきゃくさま、 おにもつ は こちら で おあずかり します。', en: 'We can keep your luggage here for you. (to a guest)' } },
      { id: 'v-ja-n3-03-18', text: 'フロント', en: 'front desk (of a hotel)', pos: 'noun', example: { text: '鍵はフロントにお預けください。', reading: 'かぎ は フロント に おあずけ ください。', en: 'Please leave your key at the front desk.' } },
    ],
    scenario: {
      title: 'Checking in at a hotel',
      setting: 'You arrive at a hotel in Kyoto in the late afternoon. The front-desk clerk greets you in polite keigo.',
      aiRole: 'Ms. Nakamura, a polite and attentive front-desk clerk at the hotel',
      learnerGoal:
        'Give your name and confirm your reservation, answer her questions about your stay, ask what time breakfast is, and politely request help with something (luggage, a taxi, or a late checkout).',
      opener: 'いらっしゃいませ。チェックインでございますか。お名前を伺ってもよろしいでしょうか。',
      openerReading: 'いらっしゃいませ。 チェックイン で ございます か。 おなまえ を うかがって も よろしい でしょう か。',
    },
  },
  {
    id: 'ja-n3-04',
    cefr: 'B1',
    order: 26,
    title: '変化と決心: Change and decisions',
    theme: 'Talking about changes in ability and habits, efforts, and decisions made by you or for you',
    canDo: [
      'I can describe how my abilities and habits have changed with 〜ようになる.',
      'I can talk about efforts I make with 〜ようにする.',
      'I can explain decisions I made and decisions made for me with 〜ことにする and 〜ことになる.',
      'I can talk about changes to my lifestyle.',
    ],
    grammar: [
      {
        id: 'g-ja-n3-04-1',
        title: '〜ようになる and 〜ようにする',
        summary:
          "〜ようになる describes a gradual change in ability or habit: dictionary or potential form + ようになる. 日本語が話せるようになった means 'I've become able to speak Japanese', and 毎朝走るようになった means 'I've started running every morning (it became a habit)'. For something that stopped, change the ない-form to なくなる: 最近、テレビを見なくなった ('I've stopped watching TV lately'). 〜ようにする means 'make an effort to' or 'make a point of', and 〜ようにしている describes an ongoing effort: 野菜を食べるようにしている ('I try to eat vegetables'); with ない it means 'make sure not to': 遅刻しないようにしてください. A common pitfall is adding ようになる to nouns and adjectives — for those, just use になる / くなる (元気になった, 寒くなった).",
        examples: [
          { text: '日本に来て、納豆が食べられるようになりました。', reading: 'にほん に きて、 なっとう が たべられる よう に なりました。', en: "Since coming to Japan, I've become able to eat natto." },
          { text: '子どもが生まれてから、たばこを吸わなくなった。', reading: 'こども が うまれて から、 たばこ を すわなく なった。', en: 'I stopped smoking after my child was born.' },
          { text: '健康のために、毎日三十分歩くようにしています。', reading: 'けんこう の ため に、 まいにち さんじゅっぷん あるく よう に して います。', en: 'For my health, I make a point of walking thirty minutes every day.' },
          { text: '寝る前にスマホを見ないようにしている。', reading: 'ねる まえ に スマホ を みない よう に して いる。', en: 'I try not to look at my phone before bed.' },
          { text: '最近、よく眠れるようになった。', reading: 'さいきん、 よく ねむれる よう に なった。', en: "Lately I've been able to sleep well." },
        ],
        drills: [
          { text: '練習して、自転車に___ようになった。', reading: 'れんしゅう して、 じてんしゃ に ___ よう に なった。', en: 'I practiced and became able to ride a bicycle.', answer: '乗れる', distractors: ['乗る', '乗った', '乗って'] },
          { text: '最近、テレビをあまり___なった。', reading: 'さいきん、 テレビ を あまり ___ なった。', en: "Lately I hardly watch TV anymore.", answer: '見なく', distractors: ['見ない', '見なくて', '見られない'] },
          { text: '毎日、日本語のニュースを聞く___しています。', reading: 'まいにち、 にほんご の ニュース を きく ___ して います。', en: 'I make a point of listening to the news in Japanese every day.', answer: 'ように', distractors: ['ために', 'のに', 'ばかり'] },
          { text: '約束の時間に遅れない___してください。', reading: 'やくそく の じかん に おくれない ___ して ください。', en: "Please make sure you're not late for the appointment.", answer: 'ように', distractors: ['ために', 'そうに', 'のに'] },
          { text: '一人暮らしを始めてから、自分で料理を___ようになった。', reading: 'ひとりぐらし を はじめて から、 じぶん で りょうり を ___ よう に なった。', en: "Since I started living alone, I've started cooking for myself.", answer: 'する', distractors: ['した', 'して', 'しない'] },
        ],
      },
      {
        id: 'g-ja-n3-04-2',
        title: '〜ことにする and 〜ことになる',
        summary:
          "〜ことにする means 'decide to' — a decision you make yourself: dictionary or ない-form + ことにする, e.g. 来年、留学することにした ('I've decided to study abroad next year'). 〜ことになる means 'it has been decided' or 'it's turned out that' — the decision comes from someone else or from circumstances: 来月、大阪に引っ越すことになりました. Their ている-forms describe standing rules: 〜ことにしている ('I make it a rule to') is a personal policy, while 〜ことになっている ('the rule is that') is an official or outside rule. A common pitfall is using ことにする for decisions you didn't make, like a transfer ordered by your company — that's ことになる. On the other hand, people often say ことになりました even about their own decisions (結婚することになりました) because it sounds more modest.",
        examples: [
          { text: '来年から一人暮らしをすることにしました。', reading: 'らいねん から ひとりぐらし を する こと に しました。', en: "I've decided to start living on my own next year." },
          { text: '今日から甘いものは食べないことにする。', reading: 'きょう から あまい もの は たべない こと に する。', en: "From today, I'm not going to eat sweets." },
          { text: '四月から大阪の支店で働くことになりました。', reading: 'しがつ から おおさか の してん で はたらく こと に なりました。', en: "It's been decided that I'll work at the Osaka branch from April." },
          { text: '私は毎朝コーヒーを一杯だけ飲むことにしている。', reading: 'わたし は まいあさ コーヒー を いっぱい だけ のむ こと に して いる。', en: 'I make it a rule to drink only one cup of coffee each morning.' },
          { text: 'この寮では、夜十一時までに帰ることになっている。', reading: 'この りょう で は、 よる じゅういちじ まで に かえる こと に なって いる。', en: 'In this dorm, the rule is that you have to be back by 11 p.m.' },
        ],
        drills: [
          { text: 'よく考えて、仕事を___ことにしました。', reading: 'よく かんがえて、 しごと を ___ こと に しました。', en: 'After thinking it over carefully, I decided to quit my job.', answer: 'やめる', distractors: ['やめた', 'やめて', 'やめれば'] },
          { text: '来年の春、結婚する___なりました。', reading: 'らいねん の はる、 けっこん する ___ なりました。', en: "It's been decided that we'll get married next spring.", answer: 'ことに', distractors: ['ように', 'ことが', 'ために'] },
          { text: '健康のために、エレベーターを使わないことに___。', reading: 'けんこう の ため に、 エレベーター を つかわない こと に ___。', en: "For my health, I've decided not to use elevators.", answer: 'しました', distractors: ['なりました', 'なっています', 'なります'] },
          { text: '日本では、車は道の左側を走ることに___。', reading: 'にほん で は、 くるま は みち の ひだりがわ を はしる こと に ___。', en: 'In Japan, the rule is that cars drive on the left side of the road.', answer: 'なっています', distractors: ['しています', 'しました', 'なりました'] },
          { text: '話し合った結果、旅行は来月に延期する___しました。', reading: 'はなしあった けっか、 りょこう は らいげつ に えんき する ___ しました。', en: 'After talking it over, we decided to postpone the trip until next month.', answer: 'ことに', distractors: ['ように', 'ことが', 'ために'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n3-04-01', text: '習慣', reading: 'しゅうかん', en: 'habit; custom', pos: 'noun', example: { text: '寝る前に本を読むのが習慣です。', reading: 'ねる まえ に ほん を よむ の が しゅうかん です。', en: 'Reading before bed is a habit of mine.' } },
      { id: 'v-ja-n3-04-02', text: '健康', reading: 'けんこう', en: 'health; healthy (na-adj.)', pos: 'noun', example: { text: 'お酒の飲みすぎは健康によくない。', reading: 'おさけ の のみすぎ は けんこう に よくない。', en: 'Drinking too much is bad for your health.' } },
      { id: 'v-ja-n3-04-03', text: '睡眠', reading: 'すいみん', en: 'sleep', pos: 'noun', example: { text: '毎日七時間以上の睡眠を取るようにしている。', reading: 'まいにち しちじかん いじょう の すいみん を とる よう に して いる。', en: 'I try to get at least seven hours of sleep every day.' } },
      { id: 'v-ja-n3-04-04', text: '栄養', reading: 'えいよう', en: 'nutrition', pos: 'noun', example: { text: 'コンビニの弁当だけでは栄養が足りない。', reading: 'コンビニ の べんとう だけ で は えいよう が たりない。', en: "You don't get enough nutrition from convenience-store bento alone." } },
      { id: 'v-ja-n3-04-05', text: '体重', reading: 'たいじゅう', en: '(body) weight', pos: 'noun', example: { text: '半年で体重が五キロ減った。', reading: 'はんとし で たいじゅう が ごキロ へった。', en: 'I lost five kilos in six months.' } },
      { id: 'v-ja-n3-04-06', text: '減らす', reading: 'へらす', en: 'to reduce; to cut down on', pos: 'verb', example: { text: 'お酒の量を減らすことにした。', reading: 'おさけ の りょう を へらす こと に した。', en: "I've decided to cut down on how much I drink." } },
      { id: 'v-ja-n3-04-07', text: '増やす', reading: 'ふやす', en: 'to increase', pos: 'verb', example: { text: '野菜を食べる量を増やしたい。', reading: 'やさい を たべる りょう を ふやしたい。', en: 'I want to eat more vegetables.' } },
      { id: 'v-ja-n3-04-08', text: '慣れる', reading: 'なれる', en: 'to get used to', pos: 'verb', example: { text: '日本の生活にもう慣れましたか。', reading: 'にほん の せいかつ に もう なれました か。', en: 'Have you gotten used to life in Japan yet?' } },
      { id: 'v-ja-n3-04-09', text: '早起き', reading: 'はやおき', en: 'getting up early', pos: 'noun', example: { text: '早起きするようになってから、朝の時間が楽しい。', reading: 'はやおき する よう に なって から、 あさ の じかん が たのしい。', en: "Since I started getting up early, I've been enjoying my mornings." } },
      { id: 'v-ja-n3-04-10', text: '決心', reading: 'けっしん', en: 'determination; resolution', pos: 'noun', example: { text: '今年こそ日本語能力試験に合格すると決心した。', reading: 'ことし こそ にほんごのうりょくしけん に ごうかく する と けっしん した。', en: "I made up my mind that this is the year I'll pass the JLPT." } },
      { id: 'v-ja-n3-04-11', text: '目標', reading: 'もくひょう', en: 'goal; target', pos: 'noun', example: { text: '今年の目標は毎日一万歩歩くことです。', reading: 'ことし の もくひょう は まいにち いちまんぽ あるく こと です。', en: 'My goal this year is to walk ten thousand steps a day.' } },
      { id: 'v-ja-n3-04-12', text: '節約', reading: 'せつやく', en: 'saving; cutting costs', pos: 'noun', example: { text: '節約のために、お弁当を作ることにした。', reading: 'せつやく の ため に、 おべんとう を つくる こと に した。', en: "To save money, I've decided to make my own lunches." } },
      { id: 'v-ja-n3-04-13', text: '自炊', reading: 'じすい', en: 'cooking for oneself', pos: 'noun', example: { text: '一人暮らしを始めてから、毎日自炊している。', reading: 'ひとりぐらし を はじめて から、 まいにち じすい して いる。', en: "Since I started living alone, I've been cooking for myself every day." } },
      { id: 'v-ja-n3-04-14', text: '夜更かし', reading: 'よふかし', en: 'staying up late', pos: 'noun', example: { text: '夜更かしをしないように、十一時には寝ている。', reading: 'よふかし を しない よう に、 じゅういちじ に は ねて いる。', en: "So I don't stay up too late, I go to bed by eleven." } },
      { id: 'v-ja-n3-04-15', text: '次第に', reading: 'しだいに', en: 'gradually', pos: 'adverb', example: { text: '次第に日本の生活が楽しくなってきた。', reading: 'しだいに にほん の せいかつ が たのしく なって きた。', en: "I've gradually started to enjoy life in Japan." } },
      { id: 'v-ja-n3-04-16', text: '以前', reading: 'いぜん', en: 'before; formerly', pos: 'noun', example: { text: '以前はよく外食していたが、今はほとんどしない。', reading: 'いぜん は よく がいしょく して いた が、 いま は ほとんど しない。', en: 'I used to eat out a lot, but now I hardly ever do.' } },
      { id: 'v-ja-n3-04-17', text: '運動不足', reading: 'うんどうぶそく', en: 'lack of exercise', pos: 'noun', example: { text: '運動不足なので、駅まで歩くようにしている。', reading: 'うんどうぶそく な ので、 えき まで あるく よう に して いる。', en: "I don't get enough exercise, so I make a point of walking to the station." } },
      { id: 'v-ja-n3-04-18', text: '一人暮らし', reading: 'ひとりぐらし', en: 'living alone', pos: 'noun', example: { text: '大学に入って、一人暮らしを始めた。', reading: 'だいがく に はいって、 ひとりぐらし を はじめた。', en: 'When I started university, I began living on my own.' } },
    ],
    scenario: {
      title: 'A new lifestyle',
      setting:
        'You run into Mr. Sato, an older neighbor in your Tokyo apartment building, in the elevator. He notices you look a lot healthier than you did last year.',
      aiRole: 'Mr. Sato, a friendly retired neighbor in his sixties who likes to chat',
      learnerGoal:
        'Tell Mr. Sato about two or three changes in your habits (〜ようになった / 〜ようにしている), explain one decision you have made (〜ことにした), and ask him about his own daily routine.',
      opener: 'おはようございます。最近、なんだか元気そうですね。何か始めたんですか。',
      openerReading: 'おはようございます。 さいきん、 なんだか げんきそう です ね。 なにか はじめた ん です か。',
    },
  },
  {
    id: 'ja-n3-05',
    cefr: 'B1',
    order: 27,
    title: 'のに・ても: Contrast and concession',
    theme: 'Expressing frustration and concession, and describing simultaneous or just-finished actions',
    canDo: [
      'I can express frustration or surprise with 〜のに.',
      'I can say "even if" or "even though" with 〜ても.',
      'I can describe doing two things at once with 〜ながら, and timing with 〜ところ and 〜たばかり.',
      'I can politely bring up a problem with a roommate.',
    ],
    grammar: [
      {
        id: 'g-ja-n3-05-1',
        title: '〜のに and 〜ても',
        summary:
          "〜のに means 'even though' or 'despite', and it carries the speaker's frustration, surprise or disappointment that things didn't go as expected. It follows plain forms, but な-adjectives and nouns take な: 高いのに, 行ったのに, 静かなのに, 日曜日なのに. 〜ても means 'even if' or 'even though' as a neutral or hypothetical statement: verb て-form + も (雨が降っても行きます), い-adjectives くても (高くても), and nouns or な-adjectives でも (雨でも, 静かでも). With question words, ても means 'no matter': 何度言っても ('no matter how many times I say it'), いくら探しても ('however hard I look'). The key difference: のに describes something that actually happened, so its second half can't be a request, invitation or intention (×高いのに買ってください), while ても works fine there (高くても買ってください).",
        examples: [
          { text: '一生懸命勉強したのに、試験に落ちてしまった。', reading: 'いっしょうけんめい べんきょう した のに、 しけん に おちて しまった。', en: 'I studied really hard, but I still failed the exam.' },
          { text: '約束したのに、彼は来なかった。', reading: 'やくそく した のに、 かれ は こなかった。', en: "He promised, and yet he didn't come." },
          { text: '雨が降っても、試合は行われます。', reading: 'あめ が ふって も、 しあい は おこなわれます。', en: 'The game will go ahead even if it rains.' },
          { text: 'いくら説明しても、わかってもらえなかった。', reading: 'いくら せつめい して も、 わかって もらえなかった。', en: "No matter how much I explained, they didn't understand." },
          { text: '日曜日なのに、会社に行かなければならない。', reading: 'にちようび な のに、 かいしゃ に いかなければ ならない。', en: "Even though it's Sunday, I have to go to work." },
        ],
        drills: [
          { text: '何回も電話した___、出てくれなかった。', reading: 'なんかい も でんわ した ___、 でて くれなかった。', en: "I called many times, but they never picked up.", answer: 'のに', distractors: ['ので', 'から', 'ても'] },
          { text: '雨が___、明日のハイキングは中止しません。', reading: 'あめ が ___、 あした の ハイキング は ちゅうし しません。', en: "Even if it rains, we won't cancel tomorrow's hike.", answer: '降っても', distractors: ['降るのに', '降ったのに', '降るので'] },
          { text: 'この部屋は駅から近い___、家賃が安い。', reading: 'この へや は えき から ちかい ___、 やちん が やすい。', en: 'This apartment is close to the station, and yet the rent is cheap.', answer: 'のに', distractors: ['ので', 'のは', 'ても'] },
          { text: 'どんなに___、毎朝六時に起きます。', reading: 'どんなに ___、 まいあさ ろくじ に おきます。', en: "No matter how tired I am, I get up at six every morning.", answer: '疲れていても', distractors: ['疲れているのに', '疲れていて', '疲れているので'] },
          { text: '値段が___、いいものを買いたい。', reading: 'ねだん が ___、 いい もの を かいたい。', en: "Even if it's expensive, I want to buy something good.", answer: '高くても', distractors: ['高ければ', '高いでも', '高くて'] },
        ],
      },
      {
        id: 'g-ja-n3-05-2',
        title: '〜ながら, 〜ところ, 〜ばかり',
        summary:
          "〜ながら attaches to the ます-stem and means one person doing two things at the same time: 音楽を聞きながら勉強する ('study while listening to music') — the main action comes last. 〜ところだ shows the stage of an action: dictionary form + ところ ('about to': 出かけるところ), 〜ている + ところ ('in the middle of': 食べているところ) and た-form + ところ ('just did': 着いたところ). た-form + ばかり also means 'just did', but it's based on how the speaker feels, so it can cover a longer time (先月来たばかり is fine, but not 先月来たところ). After a noun, ばかり means 'nothing but' or 'only': ゲームばかりしている ('does nothing but play games'). A common pitfall is using ながら for actions by two different people, or for two separate steps in order — use 〜て or 〜てから for those.",
        examples: [
          { text: '彼女はいつもスマホを見ながらご飯を食べる。', reading: 'かのじょ は いつも スマホ を みながら ごはん を たべる。', en: 'She always looks at her phone while eating.' },
          { text: '今、ちょうど出かけるところです。', reading: 'いま、 ちょうど でかける ところ です。', en: "I'm just about to head out." },
          { text: '今、晩ご飯を作っているところだから、あとで電話するね。', reading: 'いま、 ばんごはん を つくって いる ところ だ から、 あと で でんわ する ね。', en: "I'm in the middle of making dinner, so I'll call you later." },
          { text: 'さっき家に着いたところです。', reading: 'さっき いえ に ついた ところ です。', en: 'I just got home a moment ago.' },
          { text: 'この靴は先週買ったばかりなのに、もう壊れた。', reading: 'この くつ は せんしゅう かった ばかり な のに、 もう こわれた。', en: "I only bought these shoes last week, and they're already broken." },
        ],
        drills: [
          { text: 'テレビを___ご飯を食べないで。', reading: 'テレビ を ___ ごはん を たべないで。', en: "Don't eat while watching TV.", answer: '見ながら', distractors: ['見ても', '見るのに', '見たばかり'] },
          { text: 'もしもし、今ちょうど駅に着いた___だよ。', reading: 'もしもし、 いま ちょうど えき に ついた ___ だ よ。', en: 'Hello? I just got to the station this very moment.', answer: 'ところ', distractors: ['ながら', 'のに', 'ても'] },
          { text: 'ごめん、今お風呂に入っている___だから、あとでかけ直すね。', reading: 'ごめん、 いま おふろ に はいって いる ___ だ から、 あと で かけなおす ね。', en: "Sorry, I'm in the bath right now, so I'll call you back later.", answer: 'ところ', distractors: ['ばかり', 'ながら', 'はず'] },
          { text: '日本に来た___なので、まだ日本語がよくわかりません。', reading: 'にほん に きた ___ な ので、 まだ にほんご が よく わかりません。', en: "I've only just come to Japan, so I don't understand Japanese well yet.", answer: 'ばかり', distractors: ['ながら', 'ても', 'のに'] },
          { text: 'ルームメイトは毎日ゲーム___していて、全然掃除をしない。', reading: 'ルームメイト は まいにち ゲーム ___ して いて、 ぜんぜん そうじ を しない。', en: 'My roommate does nothing but play games every day and never cleans.', answer: 'ばかり', distractors: ['ながら', 'ところ', 'のに'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n3-05-01', text: 'ルームメイト', en: 'roommate', pos: 'noun', example: { text: 'ルームメイトと家事を分担している。', reading: 'ルームメイト と かじ を ぶんたん して いる。', en: 'I split the housework with my roommate.' } },
      { id: 'v-ja-n3-05-02', text: '散らかる', reading: 'ちらかる', en: 'to be messy; to be cluttered', pos: 'verb', example: { text: 'リビングがいつも散らかっていて、落ち着かない。', reading: 'リビング が いつも ちらかって いて、 おちつかない。', en: "The living room is always a mess, so I can't relax." } },
      { id: 'v-ja-n3-05-03', text: '騒ぐ', reading: 'さわぐ', en: 'to make noise; to be loud', pos: 'verb', example: { text: 'パーティーで騒いで、隣の人に注意された。', reading: 'パーティー で さわいで、 となり の ひと に ちゅうい された。', en: 'We were loud at the party and got told off by the neighbors.' } },
      { id: 'v-ja-n3-05-04', text: '守る', reading: 'まもる', en: 'to keep (a promise or rule); to protect', pos: 'verb', example: { text: '決めたルールはちゃんと守ろうよ。', reading: 'きめた ルール は ちゃんと まもろう よ。', en: "Let's actually stick to the rules we agreed on." } },
      { id: 'v-ja-n3-05-05', text: '破る', reading: 'やぶる', en: 'to break (a promise); to tear', pos: 'verb', example: { text: '彼はまた約束を破った。', reading: 'かれ は また やくそく を やぶった。', en: 'He broke his promise again.' } },
      { id: 'v-ja-n3-05-06', text: '干す', reading: 'ほす', en: 'to hang out to dry; to air', pos: 'verb', example: { text: '晴れているので、布団を干しましょう。', reading: 'はれて いる ので、 ふとん を ほしましょう。', en: "It's sunny, so let's put the futons out to air." } },
      { id: 'v-ja-n3-05-07', text: '洗濯物', reading: 'せんたくもの', en: 'laundry', pos: 'noun', example: { text: '雨が降りそうだから、洗濯物を取り込んでくれる？', reading: 'あめ が ふりそう だ から、 せんたくもの を とりこんで くれる？', en: 'It looks like rain — could you bring the laundry in?' } },
      { id: 'v-ja-n3-05-08', text: '洗い物', reading: 'あらいもの', en: 'the dishes (to be washed)', pos: 'noun', example: { text: '洗い物がたまっているのに、誰も洗わない。', reading: 'あらいもの が たまって いる のに、 だれ も あらわない。', en: 'The dishes are piling up, and yet nobody washes them.' } },
      { id: 'v-ja-n3-05-09', text: '当番', reading: 'とうばん', en: "(one's) turn for a chore; duty", pos: 'noun', example: { text: '今週のゴミ出しの当番は誰？', reading: 'こんしゅう の ゴミだし の とうばん は だれ？', en: "Whose turn is it to take out the trash this week?" } },
      { id: 'v-ja-n3-05-10', text: '夜中', reading: 'よなか', en: 'the middle of the night', pos: 'noun', example: { text: '夜中に洗濯機を回すのはやめてください。', reading: 'よなか に せんたくき を まわす の は やめて ください。', en: "Please don't run the washing machine in the middle of the night." } },
      { id: 'v-ja-n3-05-11', text: '勝手', reading: 'かって', en: 'selfish; as one pleases (na-adj.)', pos: 'adjective', example: { text: '人の物を勝手に使わないでください。', reading: 'ひと の もの を かって に つかわないで ください。', en: "Please don't use other people's things without asking." } },
      { id: 'v-ja-n3-05-12', text: '遠慮', reading: 'えんりょ', en: 'holding back; reserve', pos: 'noun', example: { text: '困ったことがあったら、遠慮しないで言ってね。', reading: 'こまった こと が あったら、 えんりょ しないで いって ね。', en: "If anything's bothering you, don't hold back — just tell me." } },
      { id: 'v-ja-n3-05-13', text: '正直', reading: 'しょうじき', en: 'honest; frank (na-adj.)', pos: 'adjective', example: { text: '正直に言うと、ちょっと困っているんだ。', reading: 'しょうじき に いう と、 ちょっと こまって いる ん だ。', en: "To be honest, it's been a bit of a problem for me." } },
      { id: 'v-ja-n3-05-14', text: 'せっかく', en: 'with much effort; since you went to the trouble', pos: 'adverb', example: { text: 'せっかく作ったのに、誰も食べてくれなかった。', reading: 'せっかく つくった のに、 だれ も たべて くれなかった。', en: "I went to the trouble of cooking, and nobody ate it." } },
      { id: 'v-ja-n3-05-15', text: 'わざわざ', en: "going out of one's way; specially", pos: 'adverb', example: { text: 'わざわざ駅まで迎えに来てくれて、ありがとう。', reading: 'わざわざ えき まで むかえ に きて くれて、 ありがとう。', en: 'Thanks for going out of your way to pick me up at the station.' } },
      { id: 'v-ja-n3-05-16', text: '相変わらず', reading: 'あいかわらず', en: 'as usual; as always', pos: 'adverb', example: { text: '彼は相変わらず朝が弱い。', reading: 'かれ は あいかわらず あさ が よわい。', en: "He's as bad at getting up in the morning as ever." } },
      { id: 'v-ja-n3-05-17', text: '割り勘', reading: 'わりかん', en: 'splitting the cost (equally)', pos: 'noun', example: { text: '電気代は三人で割り勘にしよう。', reading: 'でんきだい は さんにん で わりかん に しよう。', en: "Let's split the electricity bill three ways." } },
      { id: 'v-ja-n3-05-18', text: '共同', reading: 'きょうどう', en: 'shared; joint', pos: 'noun', example: { text: 'このシェアハウスは台所とお風呂が共同です。', reading: 'この シェアハウス は だいどころ と おふろ が きょうどう です。', en: 'In this share house, the kitchen and bathroom are shared.' } },
    ],
    scenario: {
      title: 'A word with your roommate',
      setting:
        'You share an apartment in Tokyo with a Japanese roommate. The dishes have piled up again and his music was loud late last night, so you decide to bring it up politely.',
      aiRole: 'Daiki, your easygoing but messy roommate, a university student who gets a little defensive at first',
      learnerGoal:
        "Politely raise two problems using 〜のに or 〜ても, listen to Daiki's side of the story, and agree on a fair solution such as a chore rota or quiet hours.",
      opener: 'あ、おかえり。ごめん、今ゲームしてるところなんだけど、何か用？',
      openerReading: 'あ、 おかえり。 ごめん、 いま ゲーム してる ところ な ん だ けど、 なにか よう？',
    },
  },
  {
    id: 'ja-n3-06',
    cefr: 'B1',
    order: 28,
    title: '意見を言う: Explaining and opinions',
    theme: 'Drawing conclusions, giving reasons, and stating opinions in a discussion',
    canDo: [
      'I can say what I expect to be true with 〜はず and explain conclusions with 〜わけ.',
      'I can say what people ought to do with 〜べき.',
      'I can talk about a topic with 〜について and say how things vary with 〜によって.',
      'I can share and support my opinion in a group discussion about remote work.',
    ],
    grammar: [
      {
        id: 'g-ja-n3-06-1',
        title: '〜はず and 〜わけ',
        summary:
          "〜はずだ expresses a confident expectation based on facts or logic: 'should be', 'is supposed to'. It follows plain forms, with の after nouns and な after な-adjectives: 会議は三時からのはずだ, 彼はもう着いたはずです. はずがない means 'there's no way that…': 彼が嘘をつくはずがない. 〜わけだ states a conclusion you've just understood — 'that's why', 'no wonder' — and わけではない softens a statement to 'it's not (necessarily) that…': 嫌いなわけではない ('it's not that I dislike it'). わけがない, like はずがない, means 'no way'. A common pitfall is using はず for your own plans or intentions; for those, use つもり or 予定 instead.",
        examples: [
          { text: '荷物は昨日送ったので、今日届くはずです。', reading: 'にもつ は きのう おくった ので、 きょう とどく はず です。', en: 'I sent the package yesterday, so it should arrive today.' },
          { text: '鍵をかけたはずなのに、ドアが開いていた。', reading: 'かぎ を かけた はず な のに、 ドア が あいて いた。', en: "I was sure I'd locked it, but the door was open." },
          { text: 'まじめな彼が会議を忘れるはずがない。', reading: 'まじめ な かれ が かいぎ を わすれる はず が ない。', en: "There's no way someone as conscientious as him would forget the meeting." },
          { text: '三年も中国に住んでいたんですか。中国語が上手なわけですね。', reading: 'さんねん も ちゅうごく に すんで いた ん です か。 ちゅうごくご が じょうず な わけ です ね。', en: 'You lived in China for three years? No wonder your Chinese is so good.' },
          { text: '在宅勤務に反対しているわけではありません。', reading: 'ざいたくきんむ に はんたい して いる わけ で は ありません。', en: "It's not that I'm against working from home." },
        ],
        drills: [
          { text: '田中さんは朝の新幹線に乗ったから、もう大阪に着いている___だ。', reading: 'たなか さん は あさ の しんかんせん に のった から、 もう おおさか に ついて いる ___ だ。', en: "Mr. Tanaka took the morning bullet train, so I expect he's already in Osaka.", answer: 'はず', distractors: ['ところ', 'ばかり', 'ながら'] },
          { text: '小学生にこんな難しい問題がわかる___がない。', reading: 'しょうがくせい に こんな むずかしい もんだい が わかる ___ が ない。', en: "There's no way an elementary school kid could understand such a difficult problem.", answer: 'はず', distractors: ['べき', 'ところ', 'ばかり'] },
          { text: '料理が嫌いな___ではないけど、忙しくて作る時間がない。', reading: 'りょうり が きらい な ___ で は ない けど、 いそがしくて つくる じかん が ない。', en: "It's not that I dislike cooking — I'm just too busy to find the time.", answer: 'わけ', distractors: ['はず', 'べき', 'ところ'] },
          { text: '窓が開いていたのか。どうりで寒い___だ。', reading: 'まど が あいて いた の か。 どうりで さむい ___ だ。', en: "The window was open? No wonder it's cold.", answer: 'わけ', distractors: ['べき', 'つもり'] },
          { text: '会議は十時からの___ですが、まだ誰も来ていません。', reading: 'かいぎ は じゅうじ から の ___ です が、 まだ だれ も きて いません。', en: "The meeting is supposed to start at ten, but nobody's here yet.", answer: 'はず', distractors: ['わけ', 'べき', 'ところ'] },
        ],
      },
      {
        id: 'g-ja-n3-06-2',
        title: '〜べき, 〜について, 〜によって',
        summary:
          "〜べきだ means 'should' or 'ought to' as a strong opinion or moral duty: dictionary form + べきだ (for する, both するべき and すべき are used); the negative is べきではない ('should not'). Because it sounds forceful, it's better for general opinions than for advice to the person in front of you — use 〜たほうがいい for that. 〜について means 'about' or 'concerning': 在宅勤務について話し合う; before a noun it becomes についての (環境についての本). 〜によって means 'depending on' (人によって考え方が違う), 'because of' or 'by means of' (地震によって), and 'by' for the creator in passive sentences (電話はベルによって発明された). A common pitfall is mixing up について ('about a topic') and によって ('depending on / by').",
        examples: [
          { text: '会社はもっと社員の意見を聞くべきだ。', reading: 'かいしゃ は もっと しゃいん の いけん を きく べき だ。', en: "Companies should listen more to their employees' opinions." },
          { text: '大事なことは、メールではなく直接話すべきだと思います。', reading: 'だいじ な こと は、 メール で は なく ちょくせつ はなす べき だ と おもいます。', en: 'I think important things should be said in person, not by email.' },
          { text: '今日は在宅勤務のメリットとデメリットについて話しましょう。', reading: 'きょう は ざいたくきんむ の メリット と デメリット に ついて はなしましょう。', en: "Today, let's talk about the pros and cons of working from home." },
          { text: '考え方は人によって違います。', reading: 'かんがえかた は ひと に よって ちがいます。', en: 'Ways of thinking differ from person to person.' },
          { text: '電話はベルによって発明されました。', reading: 'でんわ は ベル に よって はつめい されました。', en: 'The telephone was invented by Bell.' },
        ],
        drills: [
          { text: '人のプライバシーは守る___だ。', reading: 'ひと の プライバシー は まもる ___ だ。', en: "We ought to protect people's privacy.", answer: 'べき', distractors: ['はず', 'わけ', 'ところ'] },
          { text: '学生は授業中にスマホを使う___ではない。', reading: 'がくせい は じゅぎょうちゅう に スマホ を つかう ___ で は ない。', en: 'Students ought not to use their phones during class.', answer: 'べき', distractors: ['はず', 'つもり', 'ながら'] },
          { text: '来週の会議では、新しい制度___話し合います。', reading: 'らいしゅう の かいぎ で は、 あたらしい せいど ___ はなしあいます。', en: "At next week's meeting, we'll discuss the new system.", answer: 'について', distractors: ['によって', 'にとって', 'に対して'] },
          { text: 'ホテルの値段は季節___大きく変わります。', reading: 'ホテル の ねだん は きせつ ___ おおきく かわります。', en: 'Hotel prices vary a lot depending on the season.', answer: 'によって', distractors: ['について', 'にとって', 'として'] },
          { text: 'この建物は有名な建築家___設計された。', reading: 'この たてもの は ゆうめい な けんちくか ___ せっけい された。', en: 'This building was designed by a famous architect.', answer: 'によって', distractors: ['について', 'にとって', 'として'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n3-06-01', text: '在宅勤務', reading: 'ざいたくきんむ', en: 'working from home; remote work', pos: 'noun', example: { text: '週に二日、在宅勤務をしています。', reading: 'しゅう に ふつか、 ざいたくきんむ を して います。', en: 'I work from home two days a week.' } },
      { id: 'v-ja-n3-06-02', text: '通勤', reading: 'つうきん', en: 'commuting (to work)', pos: 'noun', example: { text: '在宅勤務なら、通勤の時間がかからない。', reading: 'ざいたくきんむ なら、 つうきん の じかん が かからない。', en: "If you work from home, you don't lose time commuting." } },
      { id: 'v-ja-n3-06-03', text: '賛成', reading: 'さんせい', en: 'agreement; being in favor', pos: 'noun', example: { text: '私はその意見に賛成です。', reading: 'わたし は その いけん に さんせい です。', en: 'I agree with that opinion.' } },
      { id: 'v-ja-n3-06-04', text: '反対', reading: 'はんたい', en: 'opposition; being against', pos: 'noun', example: { text: '部長は新しい制度に反対している。', reading: 'ぶちょう は あたらしい せいど に はんたい して いる。', en: 'The manager is against the new system.' } },
      { id: 'v-ja-n3-06-05', text: '集中', reading: 'しゅうちゅう', en: 'concentration; focus', pos: 'noun', example: { text: '家だと、仕事に集中できない。', reading: 'いえ だ と、 しごと に しゅうちゅう できない。', en: "At home, I can't concentrate on work." } },
      { id: 'v-ja-n3-06-06', text: '効率', reading: 'こうりつ', en: 'efficiency', pos: 'noun', example: { text: '在宅勤務のほうが効率がいいという人も多い。', reading: 'ざいたくきんむ の ほう が こうりつ が いい と いう ひと も おおい。', en: 'Many people say working from home is more efficient.' } },
      { id: 'v-ja-n3-06-07', text: '職場', reading: 'しょくば', en: 'workplace', pos: 'noun', example: { text: '職場の雰囲気がいいと、仕事も楽しい。', reading: 'しょくば の ふんいき が いい と、 しごと も たのしい。', en: 'When the atmosphere at work is good, the job is fun too.' } },
      { id: 'v-ja-n3-06-08', text: '同僚', reading: 'どうりょう', en: 'coworker; colleague', pos: 'noun', example: { text: '同僚と直接話す機会が減った。', reading: 'どうりょう と ちょくせつ はなす きかい が へった。', en: 'I have fewer chances to talk with coworkers face to face.' } },
      { id: 'v-ja-n3-06-09', text: '影響', reading: 'えいきょう', en: 'influence; effect', pos: 'noun', example: { text: '在宅勤務は私たちの生活に大きな影響を与えた。', reading: 'ざいたくきんむ は わたしたち の せいかつ に おおきな えいきょう を あたえた。', en: 'Working from home has had a big effect on our lives.' } },
      { id: 'v-ja-n3-06-10', text: '調査', reading: 'ちょうさ', en: 'survey; investigation', pos: 'noun', example: { text: 'ある調査によると、多くの人が在宅勤務を希望している。', reading: 'ある ちょうさ に よる と、 おおく の ひと が ざいたくきんむ を きぼう して いる。', en: 'According to one survey, many people want to work from home.' } },
      { id: 'v-ja-n3-06-11', text: '結果', reading: 'けっか', en: 'result', pos: 'noun', example: { text: 'アンケートの結果は来週発表されます。', reading: 'アンケート の けっか は らいしゅう はっぴょう されます。', en: 'The results of the questionnaire will be announced next week.' } },
      { id: 'v-ja-n3-06-12', text: '結論', reading: 'けつろん', en: 'conclusion', pos: 'noun', example: { text: '話し合ったが、結論は出なかった。', reading: 'はなしあった が、 けつろん は でなかった。', en: "We talked it over, but didn't reach a conclusion." } },
      { id: 'v-ja-n3-06-13', text: '議論', reading: 'ぎろん', en: 'discussion; debate', pos: 'noun', example: { text: 'この問題について、もっと議論するべきだ。', reading: 'この もんだい に ついて、 もっと ぎろん する べき だ。', en: 'We should discuss this issue more.' } },
      { id: 'v-ja-n3-06-14', text: '欠点', reading: 'けってん', en: 'drawback; weak point', pos: 'noun', example: { text: 'この方法の欠点は、時間がかかることだ。', reading: 'この ほうほう の けってん は、 じかん が かかる こと だ。', en: 'The drawback of this method is that it takes time.' } },
      { id: 'v-ja-n3-06-15', text: '確かに', reading: 'たしかに', en: "certainly; it's true that", pos: 'adverb', example: { text: '確かに便利ですが、問題もあると思います。', reading: 'たしかに べんり です が、 もんだい も ある と おもいます。', en: "It's certainly convenient, but I think there are problems too." } },
      { id: 'v-ja-n3-06-16', text: '一方', reading: 'いっぽう', en: 'on the other hand; meanwhile', pos: 'conjunction', example: { text: '通勤がないのはいい。一方で、運動不足になりやすい。', reading: 'つうきん が ない の は いい。 いっぽう で、 うんどうぶそく に なりやすい。', en: "Not having to commute is nice. On the other hand, it's easy to get too little exercise." } },
      { id: 'v-ja-n3-06-17', text: '考え方', reading: 'かんがえかた', en: 'way of thinking; point of view', pos: 'noun', example: { text: '世代によって、仕事に対する考え方が違う。', reading: 'せだい に よって、 しごと に たいする かんがえかた が ちがう。', en: 'Attitudes toward work differ from generation to generation.' } },
      { id: 'v-ja-n3-06-18', text: '制度', reading: 'せいど', en: 'system (of rules); institution', pos: 'noun', example: { text: '来年から、新しい休暇制度が始まる。', reading: 'らいねん から、 あたらしい きゅうかせいど が はじまる。', en: 'A new leave system starts next year.' } },
    ],
    scenario: {
      title: 'Discussion group: remote work',
      setting:
        "You're at a weekly Japanese discussion group at a community center in Tokyo. Today's topic is whether companies should allow more remote work.",
      aiRole: "Ms. Kobayashi, the group's facilitator, an office worker who asks follow-up questions and likes to play devil's advocate",
      learnerGoal:
        'Say whether you are for or against remote work, give at least two reasons (using はず, わけ, or によって), respond to a counterargument, and say what you think companies should do (〜べきだ).',
      opener: 'じゃあ、始めましょう。今日のテーマは在宅勤務です。皆さんは在宅勤務に賛成ですか、反対ですか。',
      openerReading: 'じゃあ、 はじめましょう。 きょう の テーマ は ざいたくきんむ です。 みなさん は ざいたくきんむ に さんせい です か、 はんたい です か。',
    },
  },
];
