import type { Unit } from '../types';

/** Japanese units 1–5: the kana (hiragana and katakana). */
export const unitsKana: Unit[] = [
  // ───────────────────────────── Hiragana ─────────────────────────────
  {
    id: 'ja-k1',
    cefr: 'A1',
    order: 1,
    title: 'Hiragana 1: あ to と',
    theme: 'The three Japanese scripts, your first 20 hiragana, and everyday greetings',
    canDo: [
      'I can explain what hiragana, katakana, and kanji are each used for.',
      'I can read and write the hiragana あ to と.',
      'I can say good morning, hello, thank you, and excuse me.',
    ],
    grammar: [
      {
        id: 'g-ja-k1-1',
        title: 'Three scripts: hiragana, katakana, kanji',
        summary:
          "Japanese mixes three scripts, often in the same sentence. Hiragana (ひらがな, hiragana) writes native words and grammar endings, katakana (カタカナ, katakana) writes words borrowed from other languages, like コーヒー (kōhī, coffee), and kanji (かんじ, kanji) are characters from Chinese that carry meaning, like 山 (やま, yama, mountain). Each kana is a whole syllable, not a letter, and the chart begins with the five vowels あ (a), い (i), う (u), え (e), お (o), said short and clear as in 'ah, ee, oo, eh, oh'. Every other row adds a consonant to those vowels, so the k row is か (ka), き (ki), く (ku), け (ke), こ (ko). Japanese has no spaces between words, and the shifts between scripts help you see where words start. A common pitfall is leaning on romaji: every word can be written in hiragana, so learn to read the kana directly from day one.",
        examples: [
          { text: 'あい', en: 'love' },
          { text: 'いえ', en: 'house; home' },
          { text: 'うえ', en: 'up; above' },
          { text: 'あおい', en: 'blue' },
        ],
        drills: [
          { text: '___え', en: 'ie — house', answer: 'い', distractors: ['あ', 'う', 'お'] },
          { text: 'あ___い', en: 'aoi — blue', answer: 'お', distractors: ['あ', 'う', 'え'] },
          { text: 'いい___', en: 'iie — no', answer: 'え', distractors: ['あ', 'い', 'お'] },
          { text: 'あ___', en: 'au — to meet', answer: 'う', distractors: ['い', 'え', 'お'] },
          { text: '___か', en: 'aka — red', answer: 'あ', distractors: ['お', 'い', 'え'] },
        ],
      },
      {
        id: 'g-ja-k1-2',
        title: 'The k, s, t rows and the special sounds し, ち, つ',
        summary:
          "The k row (か き く け こ: ka, ki, ku, ke, ko), the s row (さ し す せ そ: sa, shi, su, se, so) and the t row (た ち つ て と: ta, chi, tsu, te, to) put a consonant in front of the five vowels. Three sounds break the pattern: し is shi (not 'si'), ち is chi (not 'ti'), and つ is tsu, with the 'ts' of 'cats' (not 'tu'). The vowels u and i often go almost silent between sounds like k, s, sh and t, so すき (suki, like) sounds like 'ski' and あした (ashita, tomorrow) like 'ash-ta'. Watch the look-alikes: さ (sa) and ち (chi) are mirror images, き (ki) has two crossbars where さ (sa) has one, and し (shi) is a vertical hook while つ (tsu) is a sideways one.",
        examples: [
          { text: 'くつした', en: 'socks' },
          { text: 'あした', en: 'tomorrow' },
          { text: 'おいしい', en: 'delicious' },
          { text: 'すこし', en: 'a little' },
        ],
        drills: [
          { text: '___さ', en: 'kasa — umbrella', answer: 'か', distractors: ['き', 'こ', 'け'] },
          { text: 'あ___', en: 'ashi — leg; foot', answer: 'し', distractors: ['さ', 'ち', 'す'] },
          { text: '___かてつ', en: 'chikatetsu — subway', answer: 'ち', distractors: ['さ', 'し', 'つ'] },
          { text: 'く___', en: 'kutsu — shoes', answer: 'つ', distractors: ['す', 'ち', 'し'] },
          { text: '___と', en: 'soto — outside', answer: 'そ', distractors: ['さ', 'せ', 'す'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-k1-01', text: 'あ', en: 'a', pos: 'character', example: { text: 'あか', en: 'red' } },
      { id: 'v-ja-k1-02', text: 'い', en: 'i', pos: 'character', example: { text: 'いす', en: 'chair' } },
      { id: 'v-ja-k1-03', text: 'う', en: 'u', pos: 'character', example: { text: 'うた', en: 'song' } },
      { id: 'v-ja-k1-04', text: 'え', en: 'e', pos: 'character', example: { text: 'えき', en: 'train station' } },
      { id: 'v-ja-k1-05', text: 'お', en: 'o', pos: 'character', example: { text: 'おかし', en: 'sweets; snacks' } },
      { id: 'v-ja-k1-06', text: 'か', en: 'ka', pos: 'character', example: { text: 'かさ', en: 'umbrella' } },
      { id: 'v-ja-k1-07', text: 'き', en: 'ki', pos: 'character', example: { text: 'あき', en: 'autumn; fall' } },
      { id: 'v-ja-k1-08', text: 'く', en: 'ku', pos: 'character', example: { text: 'くち', en: 'mouth' } },
      { id: 'v-ja-k1-09', text: 'け', en: 'ke', pos: 'character', example: { text: 'さけ', en: 'salmon; sake (rice wine)' } },
      { id: 'v-ja-k1-10', text: 'こ', en: 'ko', pos: 'character', example: { text: 'ここ', en: 'here' } },
      { id: 'v-ja-k1-11', text: 'さ', en: 'sa', pos: 'character', example: { text: 'あさ', en: 'morning' } },
      { id: 'v-ja-k1-12', text: 'し', en: 'shi', pos: 'character', example: { text: 'しお', en: 'salt' } },
      { id: 'v-ja-k1-13', text: 'す', en: 'su', pos: 'character', example: { text: 'すし', en: 'sushi' } },
      { id: 'v-ja-k1-14', text: 'せ', en: 'se', pos: 'character', example: { text: 'せき', en: 'seat' } },
      { id: 'v-ja-k1-15', text: 'そ', en: 'so', pos: 'character', example: { text: 'そこ', en: 'there (near you)' } },
      { id: 'v-ja-k1-16', text: 'た', en: 'ta', pos: 'character', example: { text: 'たこ', en: 'octopus' } },
      { id: 'v-ja-k1-17', text: 'ち', en: 'chi', pos: 'character', example: { text: 'ちいさい', en: 'small' } },
      { id: 'v-ja-k1-18', text: 'つ', en: 'tsu', pos: 'character', example: { text: 'つくえ', en: 'desk' } },
      { id: 'v-ja-k1-19', text: 'て', en: 'te', pos: 'character', example: { text: 'ちかてつ', en: 'subway' } },
      { id: 'v-ja-k1-20', text: 'と', en: 'to', pos: 'character', example: { text: 'とけい', en: 'clock; watch' } },
      { id: 'v-ja-k1-21', text: 'おはよう', en: 'good morning (casual)', pos: 'phrase', example: { text: 'おはようございます。', reading: 'おはよう ございます。', en: 'Good morning. (polite)' } },
      { id: 'v-ja-k1-22', text: 'こんにちは', en: 'hello; good afternoon', pos: 'phrase', example: { text: 'こんにちは、たなかさん。', reading: 'こんにちは、 たなか さん。', en: 'Hello, Mr. Tanaka.' } },
      { id: 'v-ja-k1-23', text: 'ありがとう', en: 'thanks (casual)', pos: 'phrase', example: { text: 'ありがとうございます。', reading: 'ありがとう ございます。', en: 'Thank you very much. (polite)' } },
      { id: 'v-ja-k1-24', text: 'すみません', en: 'excuse me; sorry', pos: 'phrase', example: { text: 'すみません、ここ、いいですか。', reading: 'すみません、 ここ、 いい です か。', en: 'Excuse me, is this seat free?' } },
    ],
    scenario: {
      title: 'Good morning, neighbor!',
      setting: "It's 8 a.m. in a quiet residential street in Tokyo. You step out of your apartment and meet the older woman who lives next door.",
      aiRole: 'Mrs. Sato (さとうさん), a cheerful retired neighbor who loves her little garden',
      learnerGoal:
        'Return her おはようございます, agree about the weather with そうですね, thank her with ありがとうございます when she offers you a persimmon from her garden, and excuse yourself politely to leave.',
      opener: 'おはようございます。いいてんきですね。',
      openerReading: 'おはよう ございます。 いい てんき です ね。',
    },
  },
  {
    id: 'ja-k2',
    cefr: 'A1',
    order: 2,
    title: 'Hiragana 2: な to ん',
    theme: 'The rest of the basic hiragana, how particles are read, and first-meeting phrases',
    canDo: [
      'I can read and write the hiragana な to ん.',
      'I can read the particles は, へ, and を correctly as wa, e, and o.',
      'I can introduce myself with はじめまして and say goodbye and good night.',
    ],
    grammar: [
      {
        id: 'g-ja-k2-1',
        title: 'The n, h, m rows (ふ = fu)',
        summary:
          "The n row (な に ぬ ね の: na, ni, nu, ne, no), the h row (は ひ ふ へ ほ: ha, hi, fu, he, ho) and the m row (ま み む め も: ma, mi, mu, me, mo) follow the same consonant + vowel pattern you already know. The exception is ふ: it is written fu, but it's a soft puff of air between your lips, without touching your teeth to your lip as in English 'f' — somewhere between 'hoo' and 'foo'. ひ (hi) is also breathier than in English, close to the start of 'huge'. Look-alikes to watch: ぬ (nu) ends in a loop and め (me) does not; ね (ne) ends in a loop while れ (re) and わ (wa) do not; and ほ (ho) has one more crossbar than は (ha).",
        examples: [
          { text: 'なまえ', en: 'name' },
          { text: 'さかな', en: 'fish' },
          { text: 'ふね', en: 'ship; boat' },
          { text: 'みみ', en: 'ear' },
        ],
        drills: [
          { text: 'おか___', en: 'okane — money', answer: 'ね', distractors: ['れ', 'わ', 'ぬ'] },
          { text: '___く', en: 'fuku — clothes', answer: 'ふ', distractors: ['ひ', 'は', 'ほ'] },
          { text: 'さか___', en: 'sakana — fish', answer: 'な', distractors: ['ね', 'の', 'に'] },
          { text: '___と', en: 'hito — person', answer: 'ひ', distractors: ['ふ', 'へ', 'ほ'] },
          { text: 'あた___', en: 'atama — head', answer: 'ま', distractors: ['も', 'ほ', 'は'] },
        ],
      },
      {
        id: 'g-ja-k2-2',
        title: 'や ゆ よ, the r row, わ, を and ん — plus why the particles は, へ, を are read wa, e, o',
        summary:
          "The y row has only three kana, や (ya), ゆ (yu), よ (yo), and the w row keeps just わ (wa) and を (wo, pronounced o). The r row ら り る れ ろ (ra, ri, ru, re, ro) is a quick tap of the tongue just behind the upper teeth, close to the 'tt' in American 'butter' — not an English r or l. ん (n) is the only kana without a vowel; it never begins a word, and it takes a full beat, so ほん (hon, book) has two beats. As particles (small grammar words), は is read wa, へ is read e, and を is read o: ねこは (neko wa), うちへ (uchi e), ほんを (hon o), and the greeting こんにちは (konnichiwa) ends in that same は. The pitfall: inside ordinary words は and へ keep their usual sounds, as in はな (hana, flower) and へや (heya, room), while を is used only as a particle.",
        examples: [
          { text: 'ねこはかわいい。', reading: 'ねこ は かわいい。', en: 'Cats are cute.' },
          { text: 'うちへかえります。', reading: 'うち へ かえります。', en: "I'm going home." },
          { text: 'ほんをよみます。', reading: 'ほん を よみます。', en: "I'll read a book." },
          { text: 'あれはなに？', reading: 'あれ は なに？', en: 'What is that?' },
        ],
        drills: [
          { text: 'それ___なに？', reading: 'それ ___ なに？', en: "sore wa nani? — What's that (near you)?", answer: 'は', distractors: ['わ', 'を', 'へ'] },
          { text: 'にほん___いきます。', reading: 'にほん ___ いきます。', en: "Nihon e ikimasu. — I'm going to Japan.", answer: 'へ', distractors: ['え', 'は', 'を'] },
          { text: 'ほん___かいます。', reading: 'ほん ___ かいます。', en: "hon o kaimasu. — I'll buy a book.", answer: 'を', distractors: ['お', 'は', 'へ'] },
          { text: 'さく___', en: 'sakura — cherry blossom', answer: 'ら', distractors: ['る', 'ろ', 'れ'] },
          { text: '___き', en: 'yuki — snow', answer: 'ゆ', distractors: ['よ', 'や', 'る'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-k2-01', text: 'な', en: 'na', pos: 'character', example: { text: 'なつ', en: 'summer' } },
      { id: 'v-ja-k2-02', text: 'に', en: 'ni', pos: 'character', example: { text: 'にく', en: 'meat' } },
      { id: 'v-ja-k2-03', text: 'ぬ', en: 'nu', pos: 'character', example: { text: 'いぬ', en: 'dog' } },
      { id: 'v-ja-k2-04', text: 'ね', en: 'ne', pos: 'character', example: { text: 'ねこ', en: 'cat' } },
      { id: 'v-ja-k2-05', text: 'の', en: 'no', pos: 'character', example: { text: 'のみもの', en: 'drink; beverage' } },
      { id: 'v-ja-k2-06', text: 'は', en: 'ha', pos: 'character', example: { text: 'はな', en: 'flower' } },
      { id: 'v-ja-k2-07', text: 'ひ', en: 'hi', pos: 'character', example: { text: 'ひと', en: 'person' } },
      { id: 'v-ja-k2-08', text: 'ふ', en: 'fu', pos: 'character', example: { text: 'ふゆ', en: 'winter' } },
      { id: 'v-ja-k2-09', text: 'へ', en: 'he', pos: 'character', example: { text: 'へや', en: 'room' } },
      { id: 'v-ja-k2-10', text: 'ほ', en: 'ho', pos: 'character', example: { text: 'ほん', en: 'book' } },
      { id: 'v-ja-k2-11', text: 'ま', en: 'ma', pos: 'character', example: { text: 'まち', en: 'town' } },
      { id: 'v-ja-k2-12', text: 'み', en: 'mi', pos: 'character', example: { text: 'みせ', en: 'shop; store' } },
      { id: 'v-ja-k2-13', text: 'む', en: 'mu', pos: 'character', example: { text: 'さむい', en: 'cold (weather)' } },
      { id: 'v-ja-k2-14', text: 'め', en: 'me', pos: 'character', example: { text: 'あめ', en: 'rain' } },
      { id: 'v-ja-k2-15', text: 'も', en: 'mo', pos: 'character', example: { text: 'もも', en: 'peach' } },
      { id: 'v-ja-k2-16', text: 'や', en: 'ya', pos: 'character', example: { text: 'やさい', en: 'vegetables' } },
      { id: 'v-ja-k2-17', text: 'ゆ', en: 'yu', pos: 'character', example: { text: 'ゆき', en: 'snow' } },
      { id: 'v-ja-k2-18', text: 'よ', en: 'yo', pos: 'character', example: { text: 'よる', en: 'night' } },
      { id: 'v-ja-k2-19', text: 'ら', en: 'ra', pos: 'character', example: { text: 'さくら', en: 'cherry blossom' } },
      { id: 'v-ja-k2-20', text: 'り', en: 'ri', pos: 'character', example: { text: 'とり', en: 'bird; chicken' } },
      { id: 'v-ja-k2-21', text: 'る', en: 'ru', pos: 'character', example: { text: 'はる', en: 'spring (season)' } },
      { id: 'v-ja-k2-22', text: 'れ', en: 're', pos: 'character', example: { text: 'これ', en: 'this' } },
      { id: 'v-ja-k2-23', text: 'ろ', en: 'ro', pos: 'character', example: { text: 'いろ', en: 'color' } },
      { id: 'v-ja-k2-24', text: 'わ', en: 'wa', pos: 'character', example: { text: 'わたし', en: 'I; me' } },
      { id: 'v-ja-k2-25', text: 'を', en: 'wo', pos: 'character', example: { text: 'てをあらいます。', reading: 'て を あらいます。', en: 'I wash my hands.' } },
      { id: 'v-ja-k2-26', text: 'ん', en: 'n', pos: 'character', example: { text: 'にほん', en: 'Japan' } },
      { id: 'v-ja-k2-27', text: 'はじめまして', en: 'nice to meet you (first meeting)', pos: 'phrase', example: { text: 'はじめまして、すずきです。', reading: 'はじめまして、 すずき です。', en: "Nice to meet you. I'm Suzuki." } },
      { id: 'v-ja-k2-28', text: 'さようなら', en: 'goodbye', pos: 'phrase', example: { text: 'せんせい、さようなら。', reading: 'せんせい、 さようなら。', en: 'Goodbye, teacher.' } },
      { id: 'v-ja-k2-29', text: 'おやすみなさい', en: 'good night', pos: 'phrase', example: { text: 'おやすみなさい。またあした。', reading: 'おやすみなさい。 また あした。', en: 'Good night. See you tomorrow.' } },
    ],
    scenario: {
      title: 'Nice to meet you',
      setting: 'A community center in Yokohama is holding a welcome evening for new residents. A friendly man comes over to introduce himself.',
      aiRole: 'Mr. Yamamoto (やまもとさん), a friendly volunteer at the community center',
      learnerGoal:
        'Answer with はじめまして and your name, add よろしくおねがいします, and say さようなら politely when the evening ends.',
      opener: 'こんばんは。はじめまして、やまもとです。',
      openerReading: 'こんばんは。 はじめまして、 やまもと です。',
    },
  },
  {
    id: 'ja-k3',
    cefr: 'A1',
    order: 3,
    title: 'Hiragana 3: ゛ ゜, small ゃゅょ っ, long vowels',
    theme: 'Voiced sounds, combined sounds, double consonants, and long vowels',
    canDo: [
      'I can read voiced kana like が, ざ, だ, ば and the p sounds ぱ to ぽ.',
      'I can read combined sounds like きゃ, しゅ, and ちょ, double consonants with small っ, and long vowels.',
      'I can get through a simple payment at a convenience store.',
    ],
    grammar: [
      {
        id: 'g-ja-k3-1',
        title: 'Dakuten ゛ and handakuten ゜',
        summary:
          "Two small marks turn kana you already know into new sounds. The dakuten ゛ (two short strokes, nicknamed てんてん, tenten) voices the consonant: k → g (か ka → が ga), s → z (さ sa → ざ za), t → d (た ta → だ da), and h → b (は ha → ば ba). The handakuten ゜ (a small circle, まる, maru) goes only on the h row and gives p: ぱ (pa), ぴ (pi), ぷ (pu), ぺ (pe), ぽ (po). Like し (shi), じ is ji, not 'zi', and in the d row ぢ (ji) and づ (zu) sound exactly like じ (ji) and ず (zu). The pitfall is spelling: write じ and ず by default, and use ぢ or づ only in the few words that need them, such as はなぢ (hanaji, nosebleed) and つづく (tsuzuku, to continue).",
        examples: [
          { text: 'ひらがな', en: 'hiragana' },
          { text: 'てんぷら', en: 'tempura' },
          { text: 'だいがく', en: 'university' },
          { text: 'ぶどう', en: 'grapes' },
        ],
        drills: [
          { text: 'か___', en: 'kagi — key', answer: 'ぎ', distractors: ['き', 'ぐ', 'じ'] },
          { text: 'えん___つ', en: 'enpitsu — pencil', answer: 'ぴ', distractors: ['び', 'ひ', 'ぷ'] },
          { text: '___た', en: 'buta — pig', answer: 'ぶ', distractors: ['ぷ', 'ふ', 'ぼ'] },
          { text: 'ま___', en: 'mado — window', answer: 'ど', distractors: ['と', 'ぞ', 'ご'] },
          { text: 'ち___', en: 'chizu — map', answer: 'ず', distractors: ['す', 'ぞ', 'じ'] },
        ],
      },
      {
        id: 'g-ja-k3-2',
        title: 'Small ゃ ゅ ょ, small っ, and long vowels',
        summary:
          "A small ゃ, ゅ or ょ (small ya, yu, yo) after an i-sound kana (き ki, し shi, ち chi, に ni, ひ hi, み mi, り ri, ぎ gi, じ ji, び bi, ぴ pi) blends with it into a single beat: き + ゃ = きゃ (kya), し + ゅ = しゅ (shu), ち + ょ = ちょ (cho), じ + ゃ = じゃ (ja). Size matters: びょういん (byōin) is 'hospital', but びよういん (biyōin) is 'beauty salon'. A small っ (small tsu) doubles the next consonant with a tiny pause that takes one beat, so きって (kitte, stamp) is different from きて (kite, 'come'). Long vowels also take two beats and are spelled with an extra vowel: おかあさん (okāsan, mother), おにいさん (oniisan, older brother), and usually う for a long o and い for a long e, as in がっこう (gakkō, school) and せんせい (sensei, teacher). Cutting a long vowel short changes the word: おばあさん (obāsan) is 'grandmother', but おばさん (obasan) is 'aunt'.",
        examples: [
          { text: 'きって', en: 'postage stamp' },
          { text: 'がっこう', en: 'school' },
          { text: 'おかあさん', en: 'mother' },
          { text: 'びょういん', en: 'hospital' },
          { text: 'りょこう', en: 'trip; travel' },
        ],
        drills: [
          { text: 'おち___', en: 'ocha — tea', answer: 'ゃ', distractors: ['や', 'ゅ', 'ょ'] },
          { text: 'ま___ちゃ', en: 'matcha — powdered green tea', answer: 'っ', distractors: ['つ', 'ち', 'あ'] },
          { text: 'おば___さん', en: 'obāsan — grandmother', answer: 'あ', distractors: ['お', 'う', 'い'] },
          { text: 'せんせ___', en: 'sensei — teacher', answer: 'い', distractors: ['え', 'あ', 'う'] },
          { text: 'だいじ___うぶ', en: "daijōbu — it's OK; all right", answer: 'ょ', distractors: ['よ', 'ゅ', 'ゃ'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-k3-01', text: 'が', en: 'ga', pos: 'character', example: { text: 'えいが', en: 'movie' } },
      { id: 'v-ja-k3-02', text: 'ぎ', en: 'gi', pos: 'character', example: { text: 'ぎんこう', en: 'bank' } },
      { id: 'v-ja-k3-03', text: 'ぐ', en: 'gu', pos: 'character', example: { text: 'すぐ', en: 'right away; soon' } },
      { id: 'v-ja-k3-04', text: 'げ', en: 'ge', pos: 'character', example: { text: 'げんき', en: 'healthy; full of energy' } },
      { id: 'v-ja-k3-05', text: 'ご', en: 'go', pos: 'character', example: { text: 'ごはん', en: 'cooked rice; meal' } },
      { id: 'v-ja-k3-06', text: 'ざ', en: 'za', pos: 'character', example: { text: 'ざっし', en: 'magazine' } },
      { id: 'v-ja-k3-07', text: 'じ', en: 'ji', pos: 'character', example: { text: 'じかん', en: 'time' } },
      { id: 'v-ja-k3-08', text: 'ず', en: 'zu', pos: 'character', example: { text: 'みず', en: 'water' } },
      { id: 'v-ja-k3-09', text: 'ぜ', en: 'ze', pos: 'character', example: { text: 'かぜ', en: 'wind; a cold' } },
      { id: 'v-ja-k3-10', text: 'ぞ', en: 'zo', pos: 'character', example: { text: 'かぞく', en: 'family' } },
      { id: 'v-ja-k3-11', text: 'だ', en: 'da', pos: 'character', example: { text: 'ともだち', en: 'friend' } },
      { id: 'v-ja-k3-12', text: 'ぢ', en: 'ji', pos: 'character', example: { text: 'はなぢ', en: 'nosebleed' } },
      { id: 'v-ja-k3-13', text: 'づ', en: 'zu', pos: 'character', example: { text: 'つづく', en: 'to continue' } },
      { id: 'v-ja-k3-14', text: 'で', en: 'de', pos: 'character', example: { text: 'でんわ', en: 'telephone' } },
      { id: 'v-ja-k3-15', text: 'ど', en: 'do', pos: 'character', example: { text: 'どこ', en: 'where' } },
      { id: 'v-ja-k3-16', text: 'ば', en: 'ba', pos: 'character', example: { text: 'かばん', en: 'bag' } },
      { id: 'v-ja-k3-17', text: 'び', en: 'bi', pos: 'character', example: { text: 'えび', en: 'shrimp' } },
      { id: 'v-ja-k3-18', text: 'ぶ', en: 'bu', pos: 'character', example: { text: 'しんぶん', en: 'newspaper' } },
      { id: 'v-ja-k3-19', text: 'べ', en: 'be', pos: 'character', example: { text: 'たべもの', en: 'food' } },
      { id: 'v-ja-k3-20', text: 'ぼ', en: 'bo', pos: 'character', example: { text: 'ぼうし', en: 'hat; cap' } },
      { id: 'v-ja-k3-21', text: 'ぱ', en: 'pa', pos: 'character', example: { text: 'かんぱい', en: 'cheers! (a toast)' } },
      { id: 'v-ja-k3-22', text: 'ぴ', en: 'pi', pos: 'character', example: { text: 'えんぴつ', en: 'pencil' } },
      { id: 'v-ja-k3-23', text: 'ぷ', en: 'pu', pos: 'character', example: { text: 'きっぷ', en: 'ticket (train, bus)' } },
      { id: 'v-ja-k3-24', text: 'ぺ', en: 'pe', pos: 'character', example: { text: 'ぺらぺら', en: 'fluent (in a language)' } },
      { id: 'v-ja-k3-25', text: 'ぽ', en: 'po', pos: 'character', example: { text: 'さんぽ', en: 'walk; stroll' } },
      { id: 'v-ja-k3-26', text: 'きゃ', en: 'kya', pos: 'character', example: { text: 'おきゃくさん', reading: 'おきゃくさん', en: 'customer; guest' } },
      { id: 'v-ja-k3-27', text: 'きゅ', en: 'kyu', pos: 'character', example: { text: 'きゅうり', en: 'cucumber' } },
      { id: 'v-ja-k3-28', text: 'きょ', en: 'kyo', pos: 'character', example: { text: 'きょう', en: 'today' } },
      { id: 'v-ja-k3-29', text: 'しゃ', en: 'sha', pos: 'character', example: { text: 'しゃしん', en: 'photo' } },
      { id: 'v-ja-k3-30', text: 'しゅ', en: 'shu', pos: 'character', example: { text: 'しゅくだい', en: 'homework' } },
      { id: 'v-ja-k3-31', text: 'しょ', en: 'sho', pos: 'character', example: { text: 'としょかん', en: 'library' } },
      { id: 'v-ja-k3-32', text: 'ちゃ', en: 'cha', pos: 'character', example: { text: 'おちゃ', en: 'tea; green tea' } },
      { id: 'v-ja-k3-33', text: 'ちゅ', en: 'chu', pos: 'character', example: { text: 'ちゅうもん', en: 'order (at a restaurant or shop)' } },
      { id: 'v-ja-k3-34', text: 'ちょ', en: 'cho', pos: 'character', example: { text: 'ちょっと', en: 'a little; a bit' } },
      { id: 'v-ja-k3-35', text: 'じゃ', en: 'ja', pos: 'character', example: { text: 'じゃがいも', en: 'potato' } },
      { id: 'v-ja-k3-36', text: 'じゅ', en: 'ju', pos: 'character', example: { text: 'じゅぎょう', en: 'class; lesson' } },
      { id: 'v-ja-k3-37', text: 'じょ', en: 'jo', pos: 'character', example: { text: 'じょうず', en: 'skilled; good at' } },
    ],
    scenario: {
      title: 'Paying at the konbini',
      setting: "You're buying a rice ball and a bottle of tea at a convenience store near your station in Tokyo. The clerk scans your items.",
      aiRole: 'Kenta (けんた), a polite university student working part-time at the convenience store',
      learnerGoal:
        "Tell the clerk whether you need a bag (だいじょうぶです is a polite 'no, thanks'), say whether you'll pay by card (カード) or cash (げんきん), and thank him with ありがとうございます.",
      opener: 'いらっしゃいませ。ふくろはいりますか？',
      openerReading: 'いらっしゃいませ。 ふくろ は いります か？',
    },
  },
  // ───────────────────────────── Katakana ─────────────────────────────
  {
    id: 'ja-k4',
    cefr: 'A1',
    order: 4,
    title: 'Katakana 1: ア to ノ',
    theme: 'The first half of katakana and everyday loanwords',
    canDo: [
      'I can read and write the katakana ア to ノ.',
      'I can recognize common loanwords written in katakana, like コーヒー and ケーキ.',
      'I can order a drink and a cake at a café.',
    ],
    grammar: [
      {
        id: 'g-ja-k4-1',
        title: 'What katakana is for: loanwords, foreign names, emphasis',
        summary:
          "Katakana (カタカナ, katakana) has the same sounds as hiragana in sharper, more angular shapes: ア (a) matches あ (a), and カ (ka) matches か (ka). It is used mainly for words borrowed from other languages, like テスト (tesuto, test), for foreign names and places, like カナダ (Kanada, Canada), and for emphasis and sound effects, a bit like italics in English. Loanwords are reshaped to fit Japanese sounds, so most consonants get a vowel after them: 'necktie' becomes ネクタイ (nekutai). The pitfall is expecting English pronunciation — read the kana as written, then guess the English word. Also watch シ (shi) and ツ (tsu): シ's two dots sit on the left and its long stroke sweeps up from the bottom, while ツ's dots sit on top and its long stroke falls from the top right.",
        examples: [
          { text: 'テスト', en: 'test' },
          { text: 'スカート', en: 'skirt' },
          { text: 'カナダ', en: 'Canada' },
          { text: 'ケイト', en: 'Kate (a name)' },
        ],
        drills: [
          { text: 'テ___ト', en: 'tesuto — test', answer: 'ス', distractors: ['ヌ', 'ソ', 'ク'] },
          { text: 'ネク___イ', en: 'nekutai — necktie', answer: 'タ', distractors: ['ク', 'ケ', 'ナ'] },
          { text: 'スー___', en: 'sūtsu — suit', answer: 'ツ', distractors: ['シ', 'ソ', 'ノ'] },
          { text: 'タク___ー', en: 'takushī — taxi', answer: 'シ', distractors: ['ツ', 'ソ', 'ノ'] },
          { text: '___ート', en: 'nōto — notebook', answer: 'ノ', distractors: ['ソ', 'ナ', 'ク'] },
        ],
      },
      {
        id: 'g-ja-k4-2',
        title: 'The long-vowel mark ー and small ッ in katakana words',
        summary:
          "In katakana, a long vowel is shown with the bar ー (chōonpu) instead of an extra vowel kana: コーヒー (kōhī, coffee), ケーキ (kēki, cake). The bar simply holds the vowel before it for one more beat. A small ッ (small tsu) works just like hiragana っ, doubling the next consonant with a short pause: ネット (netto, internet), クッキー (kukkī, cookie). English words often get one or both, so 'soccer' is サッカー (sakkā) and 'sweater' is セーター (sētā). The pitfall is cutting them short: ケーキ has three beats (ke-e-ki), and dropping the ー or ッ gives a different word or no word at all.",
        examples: [
          { text: 'クッキー', en: 'cookie' },
          { text: 'セーター', en: 'sweater' },
          { text: 'ネット', en: 'the internet' },
          { text: 'サッカー', en: 'soccer' },
        ],
        drills: [
          { text: 'ケ___キ', en: 'kēki — cake', answer: 'ー', distractors: ['エ', 'イ', 'ッ'] },
          { text: 'ソ___クス', en: 'sokkusu — socks', answer: 'ッ', distractors: ['ツ', 'ー', 'ク'] },
          { text: 'スニ___カー', en: 'sunīkā — sneakers', answer: 'ー', distractors: ['イ', 'ッ', 'ニ'] },
          { text: 'キ___チン', en: 'kitchin — kitchen', answer: 'ッ', distractors: ['ツ', 'ー', 'シ'] },
          { text: 'コ___ト', en: 'kōto — coat', answer: 'ー', distractors: ['ウ', 'オ', 'ッ'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-k4-01', text: 'ア', en: 'a', pos: 'character', example: { text: 'アイス', en: 'ice cream' } },
      { id: 'v-ja-k4-02', text: 'イ', en: 'i', pos: 'character', example: { text: 'イタリア', en: 'Italy' } },
      { id: 'v-ja-k4-03', text: 'ウ', en: 'u', pos: 'character', example: { text: 'ウイスキー', en: 'whisky' } },
      { id: 'v-ja-k4-04', text: 'エ', en: 'e', pos: 'character', example: { text: 'エアコン', en: 'air conditioner' } },
      { id: 'v-ja-k4-05', text: 'オ', en: 'o', pos: 'character', example: { text: 'オレンジ', en: 'orange' } },
      { id: 'v-ja-k4-06', text: 'カ', en: 'ka', pos: 'character', example: { text: 'カレー', en: 'curry' } },
      { id: 'v-ja-k4-07', text: 'キ', en: 'ki', pos: 'character', example: { text: 'スキー', en: 'skiing; skis' } },
      { id: 'v-ja-k4-08', text: 'ク', en: 'ku', pos: 'character', example: { text: 'クラス', en: 'class' } },
      { id: 'v-ja-k4-09', text: 'ケ', en: 'ke', pos: 'character', example: { text: 'ケーキ', en: 'cake' } },
      { id: 'v-ja-k4-10', text: 'コ', en: 'ko', pos: 'character', example: { text: 'コーヒー', en: 'coffee' } },
      { id: 'v-ja-k4-11', text: 'サ', en: 'sa', pos: 'character', example: { text: 'サラダ', en: 'salad' } },
      { id: 'v-ja-k4-12', text: 'シ', en: 'shi', pos: 'character', example: { text: 'タクシー', en: 'taxi' } },
      { id: 'v-ja-k4-13', text: 'ス', en: 'su', pos: 'character', example: { text: 'スープ', en: 'soup' } },
      { id: 'v-ja-k4-14', text: 'セ', en: 'se', pos: 'character', example: { text: 'セット', en: 'set; set meal' } },
      { id: 'v-ja-k4-15', text: 'ソ', en: 'so', pos: 'character', example: { text: 'ソース', en: 'sauce' } },
      { id: 'v-ja-k4-16', text: 'タ', en: 'ta', pos: 'character', example: { text: 'タオル', en: 'towel' } },
      { id: 'v-ja-k4-17', text: 'チ', en: 'chi', pos: 'character', example: { text: 'チケット', en: 'ticket' } },
      { id: 'v-ja-k4-18', text: 'ツ', en: 'tsu', pos: 'character', example: { text: 'ツアー', en: 'tour' } },
      { id: 'v-ja-k4-19', text: 'テ', en: 'te', pos: 'character', example: { text: 'テレビ', en: 'TV' } },
      { id: 'v-ja-k4-20', text: 'ト', en: 'to', pos: 'character', example: { text: 'トイレ', en: 'toilet; restroom' } },
      { id: 'v-ja-k4-21', text: 'ナ', en: 'na', pos: 'character', example: { text: 'ナイフ', en: 'knife' } },
      { id: 'v-ja-k4-22', text: 'ニ', en: 'ni', pos: 'character', example: { text: 'テニス', en: 'tennis' } },
      { id: 'v-ja-k4-23', text: 'ヌ', en: 'nu', pos: 'character', example: { text: 'カヌー', en: 'canoe' } },
      { id: 'v-ja-k4-24', text: 'ネ', en: 'ne', pos: 'character', example: { text: 'ネクタイ', en: 'necktie; tie' } },
      { id: 'v-ja-k4-25', text: 'ノ', en: 'no', pos: 'character', example: { text: 'ノート', en: 'notebook' } },
    ],
    scenario: {
      title: 'Coffee and cake at a café',
      setting: "It's Saturday afternoon at a cozy café in Kichijoji, Tokyo. The menu is full of katakana.",
      aiRole: 'Aoi (あおい), a friendly server at the café',
      learnerGoal:
        'Order a drink and a cake from the menu with 〜をください, say whether you want your coffee hot (ホット) or iced (アイス), and thank Aoi when your order arrives.',
      opener: 'いらっしゃいませ。こちら、メニューです。',
      openerReading: 'いらっしゃいませ。 こちら、 メニュー です。',
    },
  },
  {
    id: 'ja-k5',
    cefr: 'A1',
    order: 5,
    title: 'Katakana 2: ハ to ン and loanwords',
    theme: 'The rest of katakana, sounds borrowed from other languages, and writing names',
    canDo: [
      'I can read and write the katakana ハ to ン, including forms with ゛ and ゜.',
      'I can read extended katakana like ティ, ファ, and ジェ in loanwords and names.',
      'I can say my name and my country when someone asks for them.',
    ],
    grammar: [
      {
        id: 'g-ja-k5-1',
        title: 'The h, m, y, r, w rows, ン, and ゛ ゜ in katakana',
        summary:
          "The rest of katakana mirrors hiragana: ハ ヒ フ ヘ ホ (ha, hi, fu, he, ho), マ ミ ム メ モ (ma, mi, mu, me, mo), ヤ ユ ヨ (ya, yu, yo), ラ リ ル レ ロ (ra, ri, ru, re, ro), ワ (wa), ヲ (wo) and ン (n). The marks ゛ and ゜ work just as in hiragana, giving バ (ba), パ (pa), ガ (ga), ズ (zu), ド (do) and so on, as in バス (basu, bus) and パン (pan, bread). English l and r both become the r row, and v usually becomes b: 'lemon' is レモン (remon) and 'video' is ビデオ (bideo). ヘ (he) looks almost the same in both scripts, and ヲ (wo) is rarely seen, because the particle を (o) is written in hiragana. Watch the look-alikes ソ (so) and ン (n): ソ's long stroke falls from the top right, while ン's sweeps up from the bottom left, just like ツ (tsu) and シ (shi).",
        examples: [
          { text: 'バス', en: 'bus' },
          { text: 'パン', en: 'bread' },
          { text: 'レモン', en: 'lemon' },
          { text: 'ビデオ', en: 'video' },
        ],
        drills: [
          { text: '___ス', en: 'basu — bus', answer: 'バ', distractors: ['パ', 'ハ', 'ボ'] },
          { text: '___ン', en: 'pan — bread', answer: 'パ', distractors: ['バ', 'ハ', 'ポ'] },
          { text: 'レモ___', en: 'remon — lemon', answer: 'ン', distractors: ['ソ', 'シ', 'ツ'] },
          { text: 'ホテ___', en: 'hoteru — hotel', answer: 'ル', distractors: ['レ', 'ロ', 'リ'] },
          { text: 'ア___リカ', en: 'Amerika — America', answer: 'メ', distractors: ['ヌ', 'ナ', 'ム'] },
        ],
      },
      {
        id: 'g-ja-k5-2',
        title: 'Extended katakana for foreign sounds: ティ, ファ, ウィ, ジェ, ヴ',
        summary:
          "To write sounds that Japanese lacks, katakana adds a small ァ, ィ, ゥ, ェ or ォ (small a, i, u, e, o) after a full-size kana, and the two are read as one beat. ティ (ti) and ディ (di) give 'tee' and 'dee', as in パーティー (pātī, party), and ファ, フィ, フェ, フォ give f plus any vowel, as in フォーク (fōku, fork). ウィ (wi) and ウェ (we) appear in words like ハロウィン (harowin, Halloween) and ウェブ (webu, web), and ジェ (je), シェ (she) and チェ (che) in words like ジェット (jetto, jet) and チェック (chekku, check). ヴ (vu) can write a v, as in ヴィーガン (vīgan, vegan), but most people still say it as b, and many words are usually spelled with the b row instead, like バイオリン (baiorin, violin). The pitfall: spellings vary (パーティー pātī or パーティ pāti), so learn each word's common form, and remember that ティ (ti) is one beat, not テ + イ (te + i).",
        examples: [
          { text: 'パーティー', en: 'party' },
          { text: 'フォーク', en: 'fork' },
          { text: 'ハロウィン', en: 'Halloween' },
          { text: 'ジェットコースター', reading: 'ジェットコースター', en: 'roller coaster' },
          { text: 'ヴィーガン', en: 'vegan' },
        ],
        drills: [
          { text: 'パー___ー', en: 'pātī — party', answer: 'ティ', distractors: ['チ', 'テイ', 'ディ'] },
          { text: '___ッション', en: 'fasshon — fashion', answer: 'ファ', distractors: ['ハ', 'フア', 'フォ'] },
          { text: 'ハロ___ン', en: 'harowin — Halloween', answer: 'ウィ', distractors: ['ウェ', 'ウォ', 'ワ'] },
          { text: '___ット', en: 'jetto — jet', answer: 'ジェ', distractors: ['ジャ', 'ゼ', 'シェ'] },
          { text: '___ーク', en: 'fōku — fork', answer: 'フォ', distractors: ['ホ', 'フ', 'ファ'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-k5-01', text: 'ハ', en: 'ha', pos: 'character', example: { text: 'ハンバーガー', reading: 'ハンバーガー', en: 'hamburger' } },
      { id: 'v-ja-k5-02', text: 'ヒ', en: 'hi', pos: 'character', example: { text: 'ヒーター', en: 'heater' } },
      { id: 'v-ja-k5-03', text: 'フ', en: 'fu', pos: 'character', example: { text: 'フランス', en: 'France' } },
      { id: 'v-ja-k5-04', text: 'ヘ', en: 'he', pos: 'character', example: { text: 'ヘルメット', en: 'helmet' } },
      { id: 'v-ja-k5-05', text: 'ホ', en: 'ho', pos: 'character', example: { text: 'ホテル', en: 'hotel' } },
      { id: 'v-ja-k5-06', text: 'マ', en: 'ma', pos: 'character', example: { text: 'マスク', en: 'face mask' } },
      { id: 'v-ja-k5-07', text: 'ミ', en: 'mi', pos: 'character', example: { text: 'ミルク', en: 'milk' } },
      { id: 'v-ja-k5-08', text: 'ム', en: 'mu', pos: 'character', example: { text: 'ゲーム', en: 'game; video game' } },
      { id: 'v-ja-k5-09', text: 'メ', en: 'me', pos: 'character', example: { text: 'メール', en: 'email' } },
      { id: 'v-ja-k5-10', text: 'モ', en: 'mo', pos: 'character', example: { text: 'リモコン', en: 'remote control' } },
      { id: 'v-ja-k5-11', text: 'ヤ', en: 'ya', pos: 'character', example: { text: 'タイヤ', en: 'tire (on a car)' } },
      { id: 'v-ja-k5-12', text: 'ユ', en: 'yu', pos: 'character', example: { text: 'ユニフォーム', reading: 'ユニフォーム', en: 'uniform (for sports)' } },
      { id: 'v-ja-k5-13', text: 'ヨ', en: 'yo', pos: 'character', example: { text: 'ヨーロッパ', en: 'Europe' } },
      { id: 'v-ja-k5-14', text: 'ラ', en: 'ra', pos: 'character', example: { text: 'ラーメン', en: 'ramen' } },
      { id: 'v-ja-k5-15', text: 'リ', en: 'ri', pos: 'character', example: { text: 'アメリカ', en: 'America; the US' } },
      { id: 'v-ja-k5-16', text: 'ル', en: 'ru', pos: 'character', example: { text: 'ビール', en: 'beer' } },
      { id: 'v-ja-k5-17', text: 'レ', en: 're', pos: 'character', example: { text: 'レストラン', en: 'restaurant' } },
      { id: 'v-ja-k5-18', text: 'ロ', en: 'ro', pos: 'character', example: { text: 'ロビー', en: 'lobby' } },
      { id: 'v-ja-k5-19', text: 'ワ', en: 'wa', pos: 'character', example: { text: 'ワイン', en: 'wine' } },
      { id: 'v-ja-k5-20', text: 'ヲ', en: 'wo', pos: 'character', example: { text: 'ミズヲクダサイ', reading: 'ミズ ヲ クダサイ', en: 'Water, please. (all-katakana style, as in old telegrams)' } },
      { id: 'v-ja-k5-21', text: 'ン', en: 'n', pos: 'character', example: { text: 'ペン', en: 'pen' } },
    ],
    scenario: {
      title: 'Checking in at a hotel',
      setting: "You've just arrived at a business hotel in Shinjuku, Tokyo. The receptionist needs your name and country for the check-in form.",
      aiRole: 'Ms. Kimura (きむらさん), a polite front-desk clerk at the hotel',
      learnerGoal:
        'Give your name, say which country you come from (for example, アメリカからきました), and confirm your name when Ms. Kimura reads it back in katakana.',
      opener: 'いらっしゃいませ。チェックインですね。おなまえをおねがいします。',
      openerReading: 'いらっしゃいませ。 チェックイン です ね。 おなまえ を おねがいします。',
    },
  },
];
