import type { Unit } from '../types';

/** Japanese units 11–14 (JLPT N5, part 2). */
export const unitsN5b: Unit[] = [
  // ───────────────────────────── ja-n5-06 ─────────────────────────────
  {
    id: 'ja-n5-06',
    cefr: 'A1',
    order: 11,
    title: 'どんな町ですか: Describing things',
    theme: 'Describing places, things, and people with adjectives',
    canDo: [
      'I can describe my town and everyday things with い- and な-adjectives.',
      'I can say what something is not like, using negative adjective forms.',
      'I can put an adjective before a noun and soften or strengthen it with とても and あまり.',
      'I can ask what kind of place something is with どんな.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-06-1',
        title: 'い-adjectives and な-adjectives: present and negative',
        summary:
          "Japanese has two kinds of adjectives. い-adjectives end in い (i) and go straight before です (desu): 大きいです (おおきいです, ōkii desu) 'it's big.' To make them negative, change the final い to くない (kunai): 大きくないです (おおきくないです, ōkiku nai desu). な-adjectives work like nouns: しずかです (shizuka desu) 'it's quiet,' negative しずかじゃありません (shizuka ja arimasen). The one irregular い-adjective is いい (ii, good): its negative is よくないです (yoku nai desu), never いくない (ikunai). Watch out for きれい (kirei) and ゆうめい (yūmei): they end in い but are な-adjectives, so their negatives are きれいじゃありません (kirei ja arimasen) and ゆうめいじゃありません (yūmei ja arimasen).",
        examples: [
          { text: '日本語はおもしろいです。', reading: 'にほんご は おもしろい です。', en: 'Japanese is interesting.' },
          { text: 'このへやは大きくないです。', reading: 'この へや は おおきくない です。', en: "This room isn't big." },
          { text: '私の町はしずかじゃありません。', reading: 'わたし の まち は しずか じゃ ありません。', en: "My town isn't quiet." },
          { text: 'あの山はきれいです。', reading: 'あの やま は きれい です。', en: 'That mountain is beautiful.' },
          { text: '今日の天気はよくないです。', reading: 'きょう の てんき は よくない です。', en: "The weather isn't good today." },
        ],
        drills: [
          { text: 'この町は___。', reading: 'この まち は ___。', en: "This town isn't big.", answer: '大きくないです', distractors: ['大きいじゃありません', '大きいです', '大きいないです'] },
          { text: 'このへやは___。', reading: 'この へや は ___。', en: "This room isn't quiet.", answer: 'しずかじゃありません', distractors: ['しずかくないです', 'しずかです', 'しずかないです'] },
          { text: 'あの店は___。', reading: 'あの みせ は ___。', en: "That restaurant isn't good.", answer: 'よくないです', distractors: ['いくないです', 'いいじゃありません', 'いいです'] },
          { text: 'あの人はゆうめい___。', reading: 'あの ひと は ゆうめい ___。', en: "That person isn't famous.", answer: 'じゃありません', distractors: ['くないです', 'です', 'ないです'] },
          { text: '私の町は___です。', reading: 'わたし の まち は ___ です。', en: 'My town is lively.', answer: 'にぎやか', distractors: ['にぎやかな', 'にぎやかい', 'にぎやかく'] },
        ],
      },
      {
        id: 'g-ja-n5-06-2',
        title: 'とても・あまり and adjective + noun',
        summary:
          "Before a noun, an い-adjective comes directly in front: 大きい町 (おおきいまち, ōkii machi) 'a big town.' A な-adjective needs な (na) between it and the noun: しずかな町 (しずかなまち, shizuka na machi) 'a quiet town' — but the な disappears before です (desu). とても (totemo) means 'very' and goes with positive sentences: とても大きいです (とてもおおきいです, totemo ōkii desu). あまり (amari) means 'not very' and must be followed by a negative: あまり大きくないです (あまりおおきくないです, amari ōkiku nai desu); using it with a positive form is a common mistake. To ask what something is like, use どんな (donna) + noun: どんな町ですか (どんなまちですか, donna machi desu ka).",
        examples: [
          { text: '京都はきれいな町です。', reading: 'きょうと は きれい な まち です。', en: 'Kyoto is a beautiful city.' },
          { text: '大きい駅ですね。', reading: 'おおきい えき です ね。', en: "It's a big station, isn't it?" },
          { text: 'この本はあまりおもしろくないです。', reading: 'この ほん は あまり おもしろくない です。', en: "This book isn't very interesting." },
          { text: '富士山はとてもゆうめいな山です。', reading: 'ふじさん は とても ゆうめい な やま です。', en: 'Mt. Fuji is a very famous mountain.' },
          { text: '大阪はどんな町ですか。', reading: 'おおさか は どんな まち です か。', en: 'What kind of city is Osaka?' },
        ],
        drills: [
          { text: 'とてもしずか___町です。', reading: 'とても しずか ___ まち です。', en: "It's a very quiet town.", answer: 'な', distractors: ['の', 'い', 'に'] },
          { text: '___本ですね。', reading: '___ ほん です ね。', en: "That's an old book, isn't it?", answer: '古い', distractors: ['古いな', '古な', '古く'] },
          { text: '田中さんは___しんせつな人です。', reading: 'たなか さん は ___ しんせつ な ひと です。', en: 'Mr. Tanaka is a very kind person.', answer: 'とても', distractors: ['あまり', 'どんな', 'どう'] },
          { text: 'この町はあまり___。', reading: 'この まち は あまり ___。', en: "This town isn't very lively.", answer: 'にぎやかじゃありません', distractors: ['にぎやかです', 'にぎやかくないです', 'にぎやかなです'] },
          { text: '___町ですか。', reading: '___ まち です か。', en: 'What kind of town is it?', answer: 'どんな', distractors: ['どれ', 'どこ', 'だれ'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-06-01', text: '町', reading: 'まち', en: 'town; city', pos: 'noun', example: { text: '私の町は小さいです。', reading: 'わたし の まち は ちいさい です。', en: 'My town is small.' } },
      { id: 'v-ja-n5-06-02', text: '大きい', reading: 'おおきい', en: 'big', pos: 'adjective', example: { text: 'このこうえんは大きいです。', reading: 'この こうえん は おおきい です。', en: 'This park is big.' } },
      { id: 'v-ja-n5-06-03', text: '小さい', reading: 'ちいさい', en: 'small', pos: 'adjective', example: { text: 'あの駅は小さいですね。', reading: 'あの えき は ちいさい です ね。', en: "That station is small, isn't it?" } },
      { id: 'v-ja-n5-06-04', text: '新しい', reading: 'あたらしい', en: 'new', pos: 'adjective', example: { text: 'この駅は新しいです。', reading: 'この えき は あたらしい です。', en: 'This station is new.' } },
      { id: 'v-ja-n5-06-05', text: '古い', reading: 'ふるい', en: 'old (for things, not people)', pos: 'adjective', example: { text: 'この車は古いですね。', reading: 'この くるま は ふるい です ね。', en: "This car is old, isn't it?" } },
      { id: 'v-ja-n5-06-06', text: 'いい', en: 'good', pos: 'adjective', example: { text: '田中さんはいい人です。', reading: 'たなか さん は いい ひと です。', en: 'Mr. Tanaka is a good person.' } },
      { id: 'v-ja-n5-06-07', text: 'おもしろい', en: 'interesting; funny', pos: 'adjective', example: { text: '山田先生はおもしろい人です。', reading: 'やまだ せんせい は おもしろい ひと です。', en: 'Professor Yamada is a fun person.' } },
      { id: 'v-ja-n5-06-08', text: 'つまらない', en: 'boring', pos: 'adjective', example: { text: 'この本はつまらないです。', reading: 'この ほん は つまらない です。', en: 'This book is boring.' } },
      { id: 'v-ja-n5-06-09', text: 'ひろい', en: 'spacious; wide', pos: 'adjective', example: { text: '私の学校はひろいです。', reading: 'わたし の がっこう は ひろい です。', en: 'My school is spacious.' } },
      { id: 'v-ja-n5-06-10', text: 'せまい', en: 'small (in space); cramped; narrow', pos: 'adjective', example: { text: '私のへやはせまいです。', reading: 'わたし の へや は せまい です。', en: 'My room is small.' } },
      { id: 'v-ja-n5-06-11', text: 'しずか', en: 'quiet (na-adj.)', pos: 'adjective', example: { text: 'この町はしずかです。', reading: 'この まち は しずか です。', en: 'This town is quiet.' } },
      { id: 'v-ja-n5-06-12', text: 'にぎやか', en: 'lively; bustling (na-adj.)', pos: 'adjective', example: { text: '東京はにぎやかな町です。', reading: 'とうきょう は にぎやか な まち です。', en: 'Tokyo is a lively city.' } },
      { id: 'v-ja-n5-06-13', text: 'きれい', en: 'pretty; clean (na-adj.)', pos: 'adjective', example: { text: '山がきれいですね。', reading: 'やま が きれい です ね。', en: "The mountains are beautiful, aren't they?" } },
      { id: 'v-ja-n5-06-14', text: 'ゆうめい', en: 'famous (na-adj.)', pos: 'adjective', example: { text: 'あの店はゆうめいですか。', reading: 'あの みせ は ゆうめい です か。', en: 'Is that shop famous?' } },
      { id: 'v-ja-n5-06-15', text: 'べんり', en: 'convenient (na-adj.)', pos: 'adjective', example: { text: 'この町はとてもべんりです。', reading: 'この まち は とても べんり です。', en: 'This town is very convenient.' } },
      { id: 'v-ja-n5-06-16', text: 'しんせつ', en: 'kind (na-adj.)', pos: 'adjective', example: { text: '町の人はしんせつです。', reading: 'まち の ひと は しんせつ です。', en: 'The people in town are kind.' } },
      { id: 'v-ja-n5-06-17', text: 'とても', en: 'very', pos: 'adverb', example: { text: 'この山はとても大きいです。', reading: 'この やま は とても おおきい です。', en: 'This mountain is very big.' } },
      { id: 'v-ja-n5-06-18', text: 'あまり', en: 'not very; not much (with a negative)', pos: 'adverb', example: { text: '私の町はあまり大きくないです。', reading: 'わたし の まち は あまり おおきくない です。', en: "My town isn't very big." } },
      { id: 'v-ja-n5-06-19', text: 'どんな', en: 'what kind of', pos: 'determiner', example: { text: 'マイクさんの町はどんな町ですか。', reading: 'マイク さん の まち は どんな まち です か。', en: "Mike, what's your town like?" } },
      { id: 'v-ja-n5-06-20', text: '山', reading: 'やま', en: 'mountain', pos: 'noun', example: { text: '私の町には山があります。', reading: 'わたし の まち に は やま が あります。', en: 'There are mountains in my town.' } },
      { id: 'v-ja-n5-06-21', text: 'こうえん', en: 'park', pos: 'noun', example: { text: '駅の前に大きいこうえんがあります。', reading: 'えき の まえ に おおきい こうえん が あります。', en: "There's a big park in front of the station." } },
    ],
    scenario: {
      title: 'Describing your hometown',
      setting: 'You are at a welcome party for new international students at a university in Kyoto. A Japanese student comes over to chat.',
      aiRole: 'Haruka, a friendly second-year student who grew up in Kyoto',
      learnerGoal:
        'Say where you are from, describe your hometown with at least three adjectives (including one negative with あまり), and ask Haruka what kind of city Kyoto is.',
      opener: 'はじめまして、はるかです。どこから来ましたか。どんな町ですか。',
      openerReading: 'はじめまして、 はるか です。 どこ から きました か。 どんな まち です か。',
    },
  },

  // ───────────────────────────── ja-n5-07 ─────────────────────────────
  {
    id: 'ja-n5-07',
    cefr: 'A1',
    order: 12,
    title: '好きなこと: Likes, wants, invitations',
    theme: 'Hobbies, likes and dislikes, wants, and making plans together',
    canDo: [
      "I can say what I like and dislike, and what I'm good or bad at.",
      'I can say what I want and what I want to do.',
      'I can invite someone with 〜ませんか and accept or decline politely.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-07-1',
        title: 'が with 好き・きらい・上手・下手, and ほしい',
        summary:
          "好き (すき, suki, 'like'), きらい (kirai, 'dislike'), 上手 (じょうず, jōzu, 'good at') and 下手 (へた, heta, 'bad at') are な-adjectives, and the thing you like or are good at is marked with が (ga), not を (o): 私はねこが好きです (わたしはねこがすきです, watashi wa neko ga suki desu) 'I like cats.' ほしい (hoshii, 'want') is an い-adjective for wanting things, and it also takes が: 車がほしいです (くるまがほしいです, kuruma ga hoshii desu) 'I want a car.' Their negatives follow the normal adjective rules: 好きじゃありません (すきじゃありません, suki ja arimasen) and ほしくないです (hoshiku nai desu). Japanese speakers rarely call themselves 上手 (jōzu) — it sounds like bragging — so use it to compliment others, and about yourself say あまり上手じゃありません (あまりじょうずじゃありません, amari jōzu ja arimasen).",
        examples: [
          { text: '私はねこが好きです。', reading: 'わたし は ねこ が すき です。', en: 'I like cats.' },
          { text: '田中さんはカラオケがきらいです。', reading: 'たなか さん は カラオケ が きらい です。', en: "Mr. Tanaka doesn't like karaoke." },
          { text: 'マリアさんは日本語が上手ですね。', reading: 'マリア さん は にほんご が じょうず です ね。', en: 'Maria, your Japanese is really good!' },
          { text: '私はうたが下手です。', reading: 'わたし は うた が へた です。', en: "I'm bad at singing." },
          { text: '新しい車がほしいです。', reading: 'あたらしい くるま が ほしい です。', en: 'I want a new car.' },
        ],
        drills: [
          { text: '私は日本の映画___好きです。', reading: 'わたし は にほん の えいが ___ すき です。', en: 'I like Japanese movies.', answer: 'が', distractors: ['を', 'に', 'で'] },
          { text: '私はりょうりが___。', reading: 'わたし は りょうり が ___。', en: "I'm bad at cooking.", answer: '下手です', distractors: ['上手です', '好きです', 'ほしいです'] },
          { text: '新しいパソコンが___。', reading: 'あたらしい パソコン が ___。', en: 'I want a new computer.', answer: 'ほしいです', distractors: ['好きです', 'ほしいじゃありません', '上手です'] },
          { text: '私はスポーツが好き___。', reading: 'わたし は スポーツ が すき ___。', en: "I don't like sports.", answer: 'じゃありません', distractors: ['くないです', 'です', 'ないです'] },
          { text: '車は___。', reading: 'くるま は ___。', en: "I don't want a car.", answer: 'ほしくないです', distractors: ['ほしいじゃありません', 'ほしいです', 'ほしくです'] },
        ],
      },
      {
        id: 'g-ja-n5-07-2',
        title: '〜たい, and inviting with 〜ませんか / 〜ましょう',
        summary:
          "To say what you want to do, take the ます-form, drop ます (masu) and add たいです (tai desu): 食べます (たべます, tabemasu) → 食べたいです (たべたいです, tabetai desu) 'I want to eat.' 〜たい works like an い-adjective, so its negative is 〜たくないです: 食べたくないです (たべたくないです, tabetaku nai desu). To invite someone, ask with the negative question 〜ませんか (masen ka): いっしょに映画を見ませんか (いっしょにえいがをみませんか, issho ni eiga o mimasen ka) 'Would you like to see a movie together?' To accept, or to say 'let's…', use 〜ましょう (mashō): 見ましょう (みましょう, mimashō). Don't invite people with 〜たいですか (tai desu ka, 'do you want to…?'), which sounds pushy, and decline softly with ちょっと… (chotto…), letting the sentence trail off, instead of a flat いいえ (iie).",
        examples: [
          { text: 'すしが食べたいです。', reading: 'すし が たべたい です。', en: 'I want to eat sushi.' },
          { text: '今日はなにもしたくないです。', reading: 'きょう は なにも したくない です。', en: "I don't want to do anything today." },
          { text: 'いっしょにおちゃを飲みませんか。', reading: 'いっしょ に おちゃ を のみません か。', en: 'Would you like to have some tea together?' },
          { text: 'いいですね。飲みましょう。', reading: 'いい です ね。 のみましょう。', en: "Sounds good. Let's have some." },
          { text: '土曜日に映画を見ませんか。', reading: 'どようび に えいが を みません か。', en: 'Would you like to see a movie on Saturday?' },
        ],
        drills: [
          { text: '日本へ___です。', reading: 'にほん へ ___ です。', en: 'I want to go to Japan.', answer: '行きたい', distractors: ['行きます', '行く', '行きましょう'] },
          { text: 'コーヒーは___。', reading: 'コーヒー は ___。', en: "I don't want to drink coffee.", answer: '飲みたくないです', distractors: ['飲みたいじゃありません', '飲みたいです', '飲みませんか'] },
          { text: '日曜日にいっしょにテニスを___。', reading: 'にちようび に いっしょ に テニス を ___。', en: 'Would you like to play tennis together on Sunday?', answer: 'しませんか', distractors: ['しましょう', 'したいです', 'しません'] },
          { text: 'いいですね。___。', reading: 'いい です ね。 ___。', en: "Sounds good. Let's go!", answer: '行きましょう', distractors: ['行きませんか', '行きたくないです', '行きません'] },
          { text: '何が___ですか。', reading: 'なに が ___ です か。', en: 'What do you want to eat?', answer: '食べたい', distractors: ['食べ', '食べます', '食べましょう'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-07-01', text: '好き', reading: 'すき', en: 'liked; to like (na-adj.)', pos: 'adjective', example: { text: '何のスポーツが好きですか。', reading: 'なん の スポーツ が すき です か。', en: 'What sports do you like?' } },
      { id: 'v-ja-n5-07-02', text: '大好き', reading: 'だいすき', en: 'to love; to really like (na-adj.)', pos: 'adjective', example: { text: '私はすしが大好きです。', reading: 'わたし は すし が だいすき です。', en: 'I love sushi.' } },
      { id: 'v-ja-n5-07-03', text: 'きらい', en: 'disliked; to dislike (na-adj.)', pos: 'adjective', example: { text: '私はなっとうがきらいです。', reading: 'わたし は なっとう が きらい です。', en: "I don't like natto." } },
      { id: 'v-ja-n5-07-04', text: '上手', reading: 'じょうず', en: 'good at; skillful (na-adj.)', pos: 'adjective', example: { text: 'リーさんはりょうりが上手です。', reading: 'リー さん は りょうり が じょうず です。', en: 'Lee is good at cooking.' } },
      { id: 'v-ja-n5-07-05', text: '下手', reading: 'へた', en: 'bad at; unskillful (na-adj.)', pos: 'adjective', example: { text: '私はテニスが下手です。', reading: 'わたし は テニス が へた です。', en: "I'm bad at tennis." } },
      { id: 'v-ja-n5-07-06', text: 'ほしい', en: 'to want (a thing) (i-adj.)', pos: 'adjective', example: { text: '新しいスマホがほしいです。', reading: 'あたらしい スマホ が ほしい です。', en: 'I want a new smartphone.' } },
      { id: 'v-ja-n5-07-07', text: '映画', reading: 'えいが', en: 'movie', pos: 'noun', example: { text: 'どんな映画が好きですか。', reading: 'どんな えいが が すき です か。', en: 'What kind of movies do you like?' } },
      { id: 'v-ja-n5-07-08', text: 'おんがく', en: 'music', pos: 'noun', example: { text: '私は日本のおんがくが好きです。', reading: 'わたし は にほん の おんがく が すき です。', en: 'I like Japanese music.' } },
      { id: 'v-ja-n5-07-09', text: 'うた', en: 'song; singing', pos: 'noun', example: { text: 'このうたは日本でゆうめいです。', reading: 'この うた は にほん で ゆうめい です。', en: 'This song is famous in Japan.' } },
      { id: 'v-ja-n5-07-10', text: 'スポーツ', en: 'sports', pos: 'noun', example: { text: 'スポーツはあまり好きじゃありません。', reading: 'スポーツ は あまり すき じゃ ありません。', en: "I don't like sports very much." } },
      { id: 'v-ja-n5-07-11', text: 'りょうり', en: 'cooking; cuisine; dish', pos: 'noun', example: { text: '日本りょうりが大好きです。', reading: 'にほんりょうり が だいすき です。', en: 'I love Japanese food.' } },
      { id: 'v-ja-n5-07-12', text: 'しゅみ', en: 'hobby', pos: 'noun', example: { text: 'しゅみは何ですか。', reading: 'しゅみ は なん です か。', en: 'What are your hobbies?' } },
      { id: 'v-ja-n5-07-13', text: 'ゲーム', en: 'game; video game', pos: 'noun', example: { text: 'おとうとはゲームが上手です。', reading: 'おとうと は ゲーム が じょうず です。', en: 'My little brother is good at video games.' } },
      { id: 'v-ja-n5-07-14', text: 'コンサート', en: 'concert', pos: 'noun', example: { text: 'いっしょにコンサートに行きませんか。', reading: 'いっしょ に コンサート に いきません か。', en: 'Would you like to go to a concert together?' } },
      { id: 'v-ja-n5-07-15', text: '会う', reading: 'あう', en: 'to meet; to see (a person)', pos: 'verb', example: { text: '駅で友達に会います。', reading: 'えき で ともだち に あいます。', en: "I'm meeting a friend at the station." } },
      { id: 'v-ja-n5-07-16', text: 'あそぶ', en: 'to hang out; to play', pos: 'verb', example: { text: '日曜日に友達とあそびます。', reading: 'にちようび に ともだち と あそびます。', en: "I'm hanging out with friends on Sunday." } },
      { id: 'v-ja-n5-07-17', text: 'いっしょに', en: 'together', pos: 'adverb', example: { text: 'いっしょにひるごはんを食べませんか。', reading: 'いっしょ に ひるごはん を たべません か。', en: 'Would you like to have lunch together?' } },
      { id: 'v-ja-n5-07-18', text: 'ちょっと', en: "a little; (when declining) it's a bit…", pos: 'adverb', example: { text: '土曜日はちょっと…。', reading: 'どようび は ちょっと…。', en: "Saturday is a bit… (difficult for me)." } },
      { id: 'v-ja-n5-07-19', text: 'ひま', en: 'free (time); not busy (na-adj.)', pos: 'adjective', example: { text: '今日の午後はひまですか。', reading: 'きょう の ごご は ひま です か。', en: 'Are you free this afternoon?' } },
      { id: 'v-ja-n5-07-20', text: 'ざんねん', en: 'too bad; a pity (na-adj.)', pos: 'adjective', example: { text: 'そうですか。ざんねんです。', reading: 'そう です か。 ざんねん です。', en: "I see. That's too bad." } },
      { id: 'v-ja-n5-07-21', text: 'りょこう', en: 'trip; travel', pos: 'noun', example: { text: '私のしゅみはりょこうです。', reading: 'わたし の しゅみ は りょこう です。', en: 'My hobby is traveling.' } },
    ],
    scenario: {
      title: 'Inviting a friend to a movie',
      setting: "It's Friday afternoon at your university in Tokyo. There's a new movie you want to see this weekend, and you bump into a friend in the hallway.",
      aiRole: 'Kenta, a university friend who loves anime; he is busy on Saturday but free on Sunday',
      learnerGoal:
        'Ask Kenta what kind of movies he likes, invite him with 〜ませんか, agree on a day (he can\'t do Saturday), and suggest a time and meeting place with 〜ましょう.',
      opener: 'あ、こんにちは！しゅうまつは何をしますか。',
      openerReading: 'あ、 こんにちは！ しゅうまつ は なに を します か。',
    },
  },

  // ───────────────────────────── ja-n5-08 ─────────────────────────────
  {
    id: 'ja-n5-08',
    cefr: 'A1',
    order: 13,
    title: 'て形: Requests and ongoing actions',
    theme: 'Polite requests, classroom language, and actions in progress',
    canDo: [
      'I can make the て-form of common verbs.',
      'I can politely ask someone to do something with 〜てください.',
      'I can say what is happening right now, and where I live, with 〜ています.',
      'I can ask a teacher to slow down or say something again.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-08-1',
        title: 'Making the て-form (verb groups 1, 2, 3)',
        summary:
          "The て-form (te-form) links a verb to other words, and you make it from the dictionary form. Group 2 verbs (ru-verbs) drop る (ru) and add て (te): 食べる (たべる, taberu) → 食べて (たべて, tabete). Group 1 verbs (u-verbs) change by their last sound: う・つ・る (u, tsu, ru) → って (tte), as in まつ (matsu) → まって (matte); む・ぶ・ぬ (mu, bu, nu) → んで (nde), as in 読む (よむ, yomu) → 読んで (よんで, yonde); く (ku) → いて (ite), as in 書く (かく, kaku) → 書いて (かいて, kaite); ぐ (gu) → いで (ide), as in およぐ (oyogu) → およいで (oyoide); and す (su) → して (shite), as in 話す (はなす, hanasu) → 話して (はなして, hanashite). Group 3 is irregular: する (suru) → して (shite) and 来る (くる, kuru) → 来て (きて, kite), and 行く (いく, iku) is the one exception in group 1: 行って (いって, itte), not 行いて (iite). Be careful with group 1 verbs that end in る, like 帰る (かえる, kaeru) and 入る (はいる, hairu): they become 帰って (かえって, kaette) and 入って (はいって, haitte), never 帰て (kaete).",
        examples: [
          { text: 'ちょっとまってください。', reading: 'ちょっと まって ください。', en: 'Please wait a moment.' },
          { text: 'ここに名前を書いてください。', reading: 'ここ に なまえ を かいて ください。', en: 'Please write your name here.' },
          { text: 'もう少しゆっくり話してください。', reading: 'もう すこし ゆっくり はなして ください。', en: 'Please speak a little more slowly.' },
          { text: 'おとうとは今、本を読んでいます。', reading: 'おとうと は いま、 ほん を よんで います。', en: 'My little brother is reading a book right now.' },
          { text: 'すみません、東京駅まで行ってください。', reading: 'すみません、 とうきょうえき まで いって ください。', en: 'Excuse me, please take me to Tokyo Station.' },
        ],
        drills: [
          { text: '毎日しゅくだいを___ください。', reading: 'まいにち しゅくだい を ___ ください。', en: 'Please do your homework every day.', answer: 'して', distractors: ['すて', 'すって', 'しって'] },
          { text: '水を___ください。', reading: 'みず を ___ ください。', en: 'Please drink some water.', answer: '飲んで', distractors: ['飲って', '飲みて', '飲いて'] },
          { text: 'これも___ください。', reading: 'これ も ___ ください。', en: 'Please eat this too.', answer: '食べて', distractors: ['食べって', '食べんで', '食べいて'] },
          { text: 'あの店に___ください。', reading: 'あの みせ に ___ ください。', en: 'Please go to that shop.', answer: '行って', distractors: ['行いて', '行きて', '行んで'] },
          { text: '今日ははやく___ください。', reading: 'きょう は はやく ___ ください。', en: 'Please go home early today.', answer: '帰って', distractors: ['帰て', '帰りて', '帰んで'] },
        ],
      },
      {
        id: 'g-ja-n5-08-2',
        title: '〜てください and 〜ています',
        summary:
          "Add ください (kudasai) to the て-form to ask someone politely to do something: 見てください (みてください, mite kudasai) 'please look.' The て-form + います (imasu) says what someone is doing right now: 今、テレビを見ています (いま、テレビをみています, ima terebi o mite imasu) 'I'm watching TV now'; the negative is 〜ていません (mite imasen). 〜ています also describes ongoing states, so 'I live in Tokyo' is 東京にすんでいます (とうきょうにすんでいます, Tōkyō ni sunde imasu), not すみます (sumimasu). The classic trap is しる (shiru, 'to know'): 'I know' is しっています (shitte imasu), but 'I don't know' is しりません (shirimasen), not しっていません (shitte imasen).",
        examples: [
          { text: 'すみません、もういちど言ってください。', reading: 'すみません、 もう いちど いって ください。', en: 'Excuse me, please say that again.' },
          { text: 'このかんじを読んでください。', reading: 'この かんじ を よんで ください。', en: 'Please read this kanji.' },
          { text: '今、雨がふっています。', reading: 'いま、 あめ が ふって います。', en: "It's raining now." },
          { text: '田中さんは今、電話で話しています。', reading: 'たなか さん は いま、 でんわ で はなして います。', en: 'Mr. Tanaka is talking on the phone right now.' },
          { text: '私は東京にすんでいます。', reading: 'わたし は とうきょう に すんで います。', en: 'I live in Tokyo.' },
        ],
        drills: [
          { text: 'すみません、ゆっくり話して___。', reading: 'すみません、 ゆっくり はなして ___。', en: 'Excuse me, please speak slowly.', answer: 'ください', distractors: ['います', 'あります', 'いません'] },
          { text: '今、テレビを___います。', reading: 'いま、 テレビ を ___ います。', en: "I'm watching TV now.", answer: '見て', distractors: ['見る', '見ます', '見た'] },
          { text: 'あの人の名前を___か。', reading: 'あの ひと の なまえ を ___ か。', en: "Do you know that person's name?", answer: 'しっています', distractors: ['しります', 'しってください', 'しりましょう'] },
          { text: '私は大阪に___います。', reading: 'わたし は おおさか に ___ います。', en: 'I live in Osaka.', answer: 'すんで', distractors: ['すみて', 'すむ', 'すって'] },
          { text: '田中さんは今、本を読んで___。', reading: 'たなか さん は いま、 ほん を よんで ___。', en: "Mr. Tanaka isn't reading a book right now.", answer: 'いません', distractors: ['ください', 'います', 'しません'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-08-01', text: 'まつ', en: 'to wait (for)', pos: 'verb', example: { text: '駅で友達をまちます。', reading: 'えき で ともだち を まちます。', en: "I'll wait for my friend at the station." } },
      { id: 'v-ja-n5-08-02', text: '話す', reading: 'はなす', en: 'to speak; to talk', pos: 'verb', example: { text: '先生と日本語で話します。', reading: 'せんせい と にほんご で はなします。', en: 'I talk with my teacher in Japanese.' } },
      { id: 'v-ja-n5-08-03', text: '言う', reading: 'いう', en: 'to say', pos: 'verb', example: { text: '「ありがとう」はえいごで何と言いますか。', reading: '「ありがとう」 は えいご で なん と いいます か。', en: "How do you say 'arigatō' in English?" } },
      { id: 'v-ja-n5-08-04', text: '書く', reading: 'かく', en: 'to write', pos: 'verb', example: { text: '友達にメールを書きます。', reading: 'ともだち に メール を かきます。', en: 'I write emails to my friends.' } },
      { id: 'v-ja-n5-08-05', text: 'つかう', en: 'to use', pos: 'verb', example: { text: '毎日パソコンをつかいます。', reading: 'まいにち パソコン を つかいます。', en: 'I use a computer every day.' } },
      { id: 'v-ja-n5-08-06', text: 'あける', en: 'to open (something)', pos: 'verb', example: { text: 'まどをあけてください。', reading: 'まど を あけて ください。', en: 'Please open the window.' } },
      { id: 'v-ja-n5-08-07', text: 'しめる', en: 'to close; to shut (something)', pos: 'verb', example: { text: 'ドアをしめてください。', reading: 'ドア を しめて ください。', en: 'Please close the door.' } },
      { id: 'v-ja-n5-08-08', text: 'おしえる', en: 'to teach; to tell', pos: 'verb', example: { text: '田中先生は日本語をおしえています。', reading: 'たなか せんせい は にほんご を おしえて います。', en: 'Ms. Tanaka teaches Japanese.' } },
      { id: 'v-ja-n5-08-09', text: '入る', reading: 'はいる', en: 'to enter; to go in', pos: 'verb', example: { text: 'どうぞ、入ってください。', reading: 'どうぞ、 はいって ください。', en: 'Please come in.' } },
      { id: 'v-ja-n5-08-10', text: '立つ', reading: 'たつ', en: 'to stand up', pos: 'verb', example: { text: 'みなさん、立ってください。', reading: 'みなさん、 たって ください。', en: 'Everyone, please stand up.' } },
      { id: 'v-ja-n5-08-11', text: 'すわる', en: 'to sit down', pos: 'verb', example: { text: 'どうぞ、すわってください。', reading: 'どうぞ、 すわって ください。', en: 'Please have a seat.' } },
      { id: 'v-ja-n5-08-12', text: 'すむ', en: 'to live (in a place)', pos: 'verb', example: { text: 'かぞくはアメリカにすんでいます。', reading: 'かぞく は アメリカ に すんで います。', en: 'My family lives in America.' } },
      { id: 'v-ja-n5-08-13', text: 'しる', en: 'to know (usually しっています)', pos: 'verb', example: { text: 'この店をしっていますか。', reading: 'この みせ を しって います か。', en: 'Do you know this shop?' } },
      { id: 'v-ja-n5-08-14', text: 'わかる', en: 'to understand', pos: 'verb', example: { text: 'すみません、よくわかりません。', reading: 'すみません、 よく わかりません。', en: "Sorry, I don't really understand." } },
      { id: 'v-ja-n5-08-15', text: 'ふる', en: 'to fall (of rain or snow)', pos: 'verb', example: { text: 'あしたは雨がふりますか。', reading: 'あした は あめ が ふります か。', en: 'Will it rain tomorrow?' } },
      { id: 'v-ja-n5-08-16', text: '雨', reading: 'あめ', en: 'rain', pos: 'noun', example: { text: '今日は雨ですね。', reading: 'きょう は あめ です ね。', en: "It's rainy today, isn't it?" } },
      { id: 'v-ja-n5-08-17', text: 'まど', en: 'window', pos: 'noun', example: { text: 'このへやはまどが大きいです。', reading: 'この へや は まど が おおきい です。', en: 'This room has big windows.' } },
      { id: 'v-ja-n5-08-18', text: 'しゅくだい', en: 'homework', pos: 'noun', example: { text: '今日はしゅくだいが多いです。', reading: 'きょう は しゅくだい が おおい です。', en: 'I have a lot of homework today.' } },
      { id: 'v-ja-n5-08-19', text: 'もういちど', en: 'once more; one more time', pos: 'adverb', example: { text: 'もういちどおねがいします。', reading: 'もう いちど おねがい します。', en: 'One more time, please.' } },
      { id: 'v-ja-n5-08-20', text: 'ゆっくり', en: 'slowly; taking your time', pos: 'adverb', example: { text: 'ゆっくり食べてください。', reading: 'ゆっくり たべて ください。', en: 'Please take your time eating.' } },
      { id: 'v-ja-n5-08-21', text: 'もう少し', reading: 'もう すこし', en: 'a little more', pos: 'adverb', example: { text: 'もう少しゆっくりおねがいします。', reading: 'もう すこし ゆっくり おねがい します。', en: 'A little more slowly, please.' } },
    ],
    scenario: {
      title: 'Asking the teacher to slow down',
      setting: "It's the end of a Japanese class at a language school in Osaka. The teacher explains the homework very quickly, and you miss most of it.",
      aiRole: 'Yamada-sensei, a kind Japanese teacher who tends to speak fast',
      learnerGoal:
        'Politely ask the teacher to speak more slowly and to say it again, ask her to write the page numbers down, and repeat the homework back to check that you understood.',
      opener: 'はい、では、しゅくだいです。この本の10ページから12ページまで読んでください。',
      openerReading: 'はい、 では、 しゅくだい です。 この ほん の じゅっページ から じゅうにページ まで よんで ください。',
    },
  },

  // ───────────────────────────── ja-n5-09 ─────────────────────────────
  {
    id: 'ja-n5-09',
    cefr: 'A1',
    order: 14,
    title: 'レストランで: Eating out',
    theme: 'Ordering food, counting things, and saying how something was',
    canDo: [
      'I can say how a meal, a trip, or a day was with past-tense adjectives and でした.',
      'I can count things from one to ten with ひとつ, ふたつ….',
      'I can order food and drinks with 〜をください and 〜にします, and ask for the check.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-09-1',
        title: 'Past tense of adjectives and です (かったです・でした)',
        summary:
          "An い-adjective carries the past tense itself: change the final い (i) to かったです (katta desu), so おいしい (oishii) becomes おいしかったです (oishikatta desu) 'it was delicious,' and the past negative is おいしくなかったです (oishiku nakatta desu). な-adjectives and nouns put the past on です instead: しずかでした (shizuka deshita) 'it was quiet,' 雨じゃありませんでした (あめじゃありませんでした, ame ja arimasen deshita) 'it wasn't rainy.' いい (ii) is irregular again: よかったです (yokatta desu) 'it was good,' never いかったです (ikatta desu). The most common mistake is おいしいでした (oishii deshita): with い-adjectives, です (desu) never turns into でした (deshita).",
        examples: [
          { text: '昨日のすしはおいしかったです。', reading: 'きのう の すし は おいしかった です。', en: 'The sushi yesterday was delicious.' },
          { text: 'あの店はしずかでした。', reading: 'あの みせ は しずか でした。', en: 'That restaurant was quiet.' },
          { text: 'ラーメンはあまり高くなかったです。', reading: 'ラーメン は あまり たかくなかった です。', en: "The ramen wasn't very expensive." },
          { text: '先週のりょこうはとてもよかったです。', reading: 'せんしゅう の りょこう は とても よかった です。', en: "Last week's trip was really good." },
          { text: '昨日は雨じゃありませんでした。', reading: 'きのう は あめ じゃ ありません でした。', en: "It wasn't rainy yesterday." },
        ],
        drills: [
          { text: '昨日のケーキは___。', reading: 'きのう の ケーキ は ___。', en: "Yesterday's cake was delicious.", answer: 'おいしかったです', distractors: ['おいしいでした', 'おいしかったでした', 'おいしくなかったです'] },
          { text: 'りょこうは___。', reading: 'りょこう は ___。', en: 'The trip was fun.', answer: 'たのしかったです', distractors: ['たのしいでした', 'たのしくなかったです', 'たのしいです'] },
          { text: '昨日のパーティーは___。', reading: 'きのう の パーティー は ___。', en: "Yesterday's party was lively.", answer: 'にぎやかでした', distractors: ['にぎやかかったです', 'にぎやかだったでした', 'にぎやかです'] },
          { text: 'この映画は___。', reading: 'この えいが は ___。', en: "This movie wasn't interesting.", answer: 'おもしろくなかったです', distractors: ['おもしろいじゃありませんでした', 'おもしろくないでした', 'おもしろかったです'] },
          { text: '天気は___。', reading: 'てんき は ___。', en: 'The weather was nice.', answer: 'よかったです', distractors: ['いかったです', 'いいでした', 'よくなかったです'] },
        ],
      },
      {
        id: 'g-ja-n5-09-2',
        title: 'Counting things with ひとつ・ふたつ…, 〜をください and 〜にします',
        summary:
          "For counting most everyday things — food, cups, apples, orders — Japanese uses the native counting words: ひとつ (hitotsu, 1), ふたつ (futatsu, 2), みっつ (mittsu, 3), よっつ (yottsu, 4), いつつ (itsutsu, 5), むっつ (muttsu, 6), ななつ (nanatsu, 7), やっつ (yattsu, 8), ここのつ (kokonotsu, 9) and とお (tō, 10); いくつ (ikutsu) asks 'how many?' The number comes after the noun and its particle, right before the verb: コーヒーをふたつください (kōhī o futatsu kudasai) 'Two coffees, please.' 〜をください (o kudasai) means 'please give me…', while 〜にします (ni shimasu) means 'I'll have…' when you choose from a menu: 私はカレーにします (わたしはカレーにします, watashi wa karē ni shimasu). Don't confuse よっつ (yottsu, 4) with やっつ (yattsu, 8), and don't use いち, に, さん (ichi, ni, san) here: 'three apples' is りんごをみっつ (ringo o mittsu), not りんごをさん.",
        examples: [
          { text: 'コーヒーをふたつください。', reading: 'コーヒー を ふたつ ください。', en: 'Two coffees, please.' },
          { text: '私はカレーにします。', reading: 'わたし は カレー に します。', en: "I'll have the curry." },
          { text: 'ケーキはいくつ買いましたか。', reading: 'ケーキ は いくつ かいました か。', en: 'How many cakes did you buy?' },
          { text: 'のみものは何にしますか。', reading: 'のみもの は なに に します か。', en: 'What will you have to drink?' },
          { text: '私もそれにします。', reading: 'わたし も それ に します。', en: "I'll have that too." },
        ],
        drills: [
          { text: 'ジュースを___ください。', reading: 'ジュース を ___ ください。', en: 'Two juices, please.', answer: 'ふたつ', distractors: ['ひとつ', 'みっつ', 'よっつ'] },
          { text: 'りんごを___ください。', reading: 'りんご を ___ ください。', en: 'Four apples, please.', answer: 'よっつ', distractors: ['やっつ', 'むっつ', 'いつつ'] },
          { text: '私はラーメン___します。', reading: 'わたし は ラーメン ___ します。', en: "I'll have the ramen.", answer: 'に', distractors: ['を', 'が', 'で'] },
          { text: 'すみません、お水___ください。', reading: 'すみません、 おみず ___ ください。', en: 'Excuse me, some water, please.', answer: 'を', distractors: ['に', 'が', 'で'] },
          { text: 'おにぎりは___ありますか。', reading: 'おにぎり は ___ あります か。', en: 'How many rice balls are there?', answer: 'いくつ', distractors: ['いくら', 'いつ', 'どれ'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-09-01', text: 'レストラン', en: 'restaurant', pos: 'noun', example: { text: 'この町にはいいレストランがあります。', reading: 'この まち に は いい レストラン が あります。', en: "There's a good restaurant in this town." } },
      { id: 'v-ja-n5-09-02', text: 'メニュー', en: 'menu', pos: 'noun', example: { text: 'すみません、メニューをください。', reading: 'すみません、 メニュー を ください。', en: 'Excuse me, could I have a menu?' } },
      { id: 'v-ja-n5-09-03', text: 'おいしい', en: 'delicious; tasty', pos: 'adjective', example: { text: '日本のパンはおいしいです。', reading: 'にほん の パン は おいしい です。', en: 'Bread in Japan is delicious.' } },
      { id: 'v-ja-n5-09-04', text: 'からい', en: 'spicy; hot', pos: 'adjective', example: { text: 'このカレーはからいですか。', reading: 'この カレー は からい です か。', en: 'Is this curry spicy?' } },
      { id: 'v-ja-n5-09-05', text: 'あまい', en: 'sweet', pos: 'adjective', example: { text: '私はあまいものが好きです。', reading: 'わたし は あまい もの が すき です。', en: 'I like sweet things.' } },
      { id: 'v-ja-n5-09-06', text: 'たのしい', en: 'fun; enjoyable', pos: 'adjective', example: { text: 'カラオケはたのしいですね。', reading: 'カラオケ は たのしい です ね。', en: "Karaoke is fun, isn't it?" } },
      { id: 'v-ja-n5-09-07', text: 'ひとつ', en: 'one (thing)', pos: 'number', example: { text: 'ケーキをひとつください。', reading: 'ケーキ を ひとつ ください。', en: 'One piece of cake, please.' } },
      { id: 'v-ja-n5-09-08', text: 'ふたつ', en: 'two (things)', pos: 'number', example: { text: 'おにぎりをふたつ食べました。', reading: 'おにぎり を ふたつ たべました。', en: 'I ate two rice balls.' } },
      { id: 'v-ja-n5-09-09', text: 'みっつ', en: 'three (things)', pos: 'number', example: { text: 'りんごをみっつ買いました。', reading: 'りんご を みっつ かいました。', en: 'I bought three apples.' } },
      { id: 'v-ja-n5-09-10', text: 'よっつ', en: 'four (things)', pos: 'number', example: { text: 'いすがよっつあります。', reading: 'いす が よっつ あります。', en: 'There are four chairs.' } },
      { id: 'v-ja-n5-09-11', text: 'いつつ', en: 'five (things)', pos: 'number', example: { text: 'ドーナツをいつつください。', reading: 'ドーナツ を いつつ ください。', en: 'Five doughnuts, please.' } },
      { id: 'v-ja-n5-09-12', text: 'いくつ', en: 'how many', pos: 'adverb', example: { text: 'りんごはいくつありますか。', reading: 'りんご は いくつ あります か。', en: 'How many apples are there?' } },
      { id: 'v-ja-n5-09-13', text: '魚', reading: 'さかな', en: 'fish', pos: 'noun', example: { text: '今日は魚を食べました。', reading: 'きょう は さかな を たべました。', en: 'I had fish today.' } },
      { id: 'v-ja-n5-09-14', text: 'にく', en: 'meat', pos: 'noun', example: { text: '田中さんはにくが大好きです。', reading: 'たなか さん は にく が だいすき です。', en: 'Mr. Tanaka loves meat.' } },
      { id: 'v-ja-n5-09-15', text: 'やさい', en: 'vegetables', pos: 'noun', example: { text: '毎日やさいを食べます。', reading: 'まいにち やさい を たべます。', en: 'I eat vegetables every day.' } },
      { id: 'v-ja-n5-09-16', text: 'のみもの', en: 'drink; beverage', pos: 'noun', example: { text: 'のみものは何がいいですか。', reading: 'のみもの は なに が いい です か。', en: 'What would you like to drink?' } },
      { id: 'v-ja-n5-09-17', text: 'たべもの', en: 'food', pos: 'noun', example: { text: 'どんなたべものが好きですか。', reading: 'どんな たべもの が すき です か。', en: 'What kind of food do you like?' } },
      { id: 'v-ja-n5-09-18', text: 'てんいん', en: 'store clerk; server', pos: 'noun', example: { text: 'あのてんいんさんはしんせつです。', reading: 'あの てんいん さん は しんせつ です。', en: 'That server is kind.' } },
      { id: 'v-ja-n5-09-19', text: 'おかいけい', en: 'the check; the bill', pos: 'noun', example: { text: 'すみません、おかいけいをおねがいします。', reading: 'すみません、 おかいけい を おねがい します。', en: 'Excuse me, the check, please.' } },
      { id: 'v-ja-n5-09-20', text: 'いただきます', en: 'said before eating (lit. "I humbly receive")', pos: 'phrase', example: { text: 'では、いただきます。', reading: 'では、 いただきます。', en: "Well then, let's eat! (said before a meal)" } },
      { id: 'v-ja-n5-09-21', text: 'ごちそうさまでした', en: 'thank you for the meal (said after eating)', pos: 'phrase', example: { text: 'ごちそうさまでした。とてもおいしかったです。', reading: 'ごちそうさま でした。 とても おいしかった です。', en: 'Thank you for the meal. It was delicious.' } },
    ],
    scenario: {
      title: 'Ordering at a restaurant',
      setting: 'You and a friend sit down for dinner at a small family restaurant in Tokyo. A server brings water and menus.',
      aiRole: 'Sato-san, a cheerful server at the restaurant',
      learnerGoal:
        'Ask whether a dish is spicy, order food and drinks for two using ひとつ・ふたつ with 〜をください or 〜にします, and when you ask for the check, tell the server how the meal was.',
      opener: 'いらっしゃいませ！こちらがメニューです。おのみものは何にしますか。',
      openerReading: 'いらっしゃいませ！ こちら が メニュー です。 おのみもの は なに に します か。',
    },
  },
];
