import type { Unit } from '../types';

/** Japanese units 29–35 (JLPT N2 = CEFR B2, JLPT N1 = CEFR C1). */
export const unitsN2N1: Unit[] = [
  // ───────────────────────────── N2 (B2) ─────────────────────────────
  {
    id: 'ja-n2-01',
    cefr: 'B2',
    order: 29,
    title: '書き言葉: Formal and written Japanese',
    theme: 'Reading and discussing news articles, reports, and essays',
    canDo: [
      'I can recognize and use the である style of essays, reports, and newspapers.',
      'I can understand written connective forms such as the ます-stem link, 〜ており, and 〜ず(に).',
      'I can talk about topics, targets, and contexts formally with 〜に関して, 〜に対して, and 〜における.',
    ],
    grammar: [
      {
        id: 'g-ja-n2-01-1',
        title: 'である style and written forms',
        summary:
          "Essays, reports, academic papers, and many newspaper articles use the plain である style instead of です/ます. である replaces だ after nouns and な-adjectives (重要である, 学生であった, 問題ではない), and its conjecture form is であろう. Written Japanese also prefers compact connective forms: the ます-stem instead of the て-form (発表し、…), 〜ており / 〜ておらず instead of 〜ていて / 〜ていなくて, 〜ず(に) instead of 〜ないで, and 〜ではなく instead of 〜じゃなくて. Plain だ is also used in writing, but である sounds more objective and academic; in conversation it only appears in speeches or as a joke about sounding pompous. The classic pitfall is mixing styles: once a text is in である style, it must not slip into です/ます or chatty endings like 〜よね.",
        examples: [
          { text: '環境問題は世界全体の課題である。', reading: 'かんきょうもんだい は せかい ぜんたい の かだい で ある。', en: 'Environmental problems are a challenge for the whole world.' },
          { text: '政府は新しい制度を発表し、来年から実施する予定である。', reading: 'せいふ は あたらしい せいど を はっぴょう し、 らいねん から じっし する よてい で ある。', en: 'The government announced a new system and plans to implement it from next year.' },
          { text: '原因はまだ明らかになっておらず、調査が続いている。', reading: 'げんいん は まだ あきらか に なって おらず、 ちょうさ が つづいて いる。', en: 'The cause has not yet been determined, and the investigation is ongoing.' },
          { text: '十分な議論をせずに結論を出すべきではない。', reading: 'じゅうぶん な ぎろん を せず に けつろん を だす べき で は ない。', en: 'We should not reach a conclusion without sufficient discussion.' },
          { text: '江戸は当時、世界有数の大都市であった。', reading: 'えど は とうじ、 せかい ゆうすう の だいとし で あった。', en: 'At the time, Edo was one of the largest cities in the world.' },
        ],
        drills: [
          { text: '健康は何よりも大切___。', reading: 'けんこう は なに より も たいせつ ___。', en: 'Health is more important than anything else. (essay style)', answer: 'である', distractors: ['です', 'であった', 'ではない'] },
          { text: '当時、この町は工業の中心地___。', reading: 'とうじ、 この まち は こうぎょう の ちゅうしんち ___。', en: 'At that time, this town was the center of industry. (written style)', answer: 'であった', distractors: ['である', 'でした', 'ではなかった'] },
          { text: '現在、多くの企業が在宅勤務を導入して___、その数は年々増えている。', reading: 'げんざい、 おおく の きぎょう が ざいたくきんむ を どうにゅう して ___、 その かず は ねんねん ふえて いる。', en: 'Many companies have now introduced remote work, and their number is growing every year.', answer: 'おり', distractors: ['おらず', 'いる', 'いない'] },
          { text: '市は住民に説明___、工事を始めた。', reading: 'し は じゅうみん に せつめい ___、 こうじ を はじめた。', en: 'The city began construction without explaining it to residents.', answer: 'せずに', distractors: ['しながら', 'してから', 'したうえで'] },
          { text: 'これは個人の問題___、社会全体の問題である。', reading: 'これ は こじん の もんだい ___、 しゃかい ぜんたい の もんだい で ある。', en: 'This is not an individual problem but a problem for society as a whole.', answer: 'ではなく', distractors: ['であり', 'として', 'ならば'] },
        ],
      },
      {
        id: 'g-ja-n2-01-2',
        title: '〜に関して, 〜に対して, 〜における',
        summary:
          "〜に関して (かんして; before a noun 〜に関する) means 'regarding, concerning' and is a more formal version of 〜について: この件に関してご質問はありますか. 〜に対して (たいして; before a noun 〜に対する) marks the target an action, attitude, or feeling is directed at, 'toward, against': 客に対して失礼だ, 政府に対する批判. After a clause + の, 〜のに対して contrasts two facts, 'whereas': 姉が外向的なのに対して、妹は内気だ. 〜において (before a noun 〜における) means 'in, at' a place, field, or period and is a formal replacement for で or の: 現代社会における問題. Pitfall: before a noun you need the attributive forms に関する, に対する, における (×環境問題に関して本), and に対して never means 'about' — say 環境について話す, not ×環境に対して話す.",
        examples: [
          { text: 'この件に関して、何かご質問はありますか。', reading: 'この けん に かんして、 なにか ごしつもん は あります か。', en: 'Do you have any questions regarding this matter?' },
          { text: '政府の対応に対して批判の声が上がっている。', reading: 'せいふ の たいおう に たいして ひはん の こえ が あがって いる。', en: "Criticism is mounting against the government's response." },
          { text: '都市部の人口が増えているのに対して、地方の人口は減っている。', reading: 'としぶ の じんこう が ふえて いる の に たいして、 ちほう の じんこう は へって いる。', en: 'Whereas the urban population is growing, the rural population is shrinking.' },
          { text: '現代社会における家族の役割について考える。', reading: 'げんだいしゃかい に おける かぞく の やくわり に ついて かんがえる。', en: 'We will consider the role of the family in modern society.' },
          { text: '環境問題に関する報告書を読んだ。', reading: 'かんきょうもんだい に かんする ほうこくしょ を よんだ。', en: 'I read a report on environmental issues.' },
        ],
        drills: [
          { text: 'これは環境問題___本です。', reading: 'これ は かんきょうもんだい ___ ほん です。', en: 'This is a book about environmental issues.', answer: 'に関する', distractors: ['に関して', 'に対して', 'における'] },
          { text: '親___感謝の気持ちを忘れてはいけない。', reading: 'おや ___ かんしゃ の きもち を わすれて は いけない。', en: 'You must never forget your gratitude toward your parents.', answer: 'に対する', distractors: ['に関する', 'における', 'にとって'] },
          { text: '職場___女性の役割について調べている。', reading: 'しょくば ___ じょせい の やくわり に ついて しらべて いる。', en: "I'm researching the role of women in the workplace.", answer: 'における', distractors: ['に対して', 'に関して', 'に対する'] },
          { text: '姉が外向的なの___、妹はおとなしい。', reading: 'あね が がいこうてき な の ___、 いもうと は おとなしい。', en: 'Whereas my older sister is outgoing, my younger sister is quiet.', answer: 'に対して', distractors: ['に関して', 'における', 'によって'] },
          { text: '来週の会議の日程___、改めてご連絡します。', reading: 'らいしゅう の かいぎ の にってい ___、 あらためて ごれんらく します。', en: "Regarding the schedule for next week's meeting, I'll contact you again.", answer: 'に関して', distractors: ['に対して', 'における', 'にとって'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n2-01-01', text: '記事', reading: 'きじ', en: 'article (news, magazine)', pos: 'noun', example: { text: '今朝、興味深い記事を読んだ。', reading: 'けさ、 きょうみぶかい きじ を よんだ。', en: 'This morning I read an interesting article.' } },
      { id: 'v-ja-n2-01-02', text: '報道', reading: 'ほうどう', en: 'news coverage; reporting', pos: 'noun', example: { text: '報道によると、被害は広い範囲に及んでいる。', reading: 'ほうどう に よると、 ひがい は ひろい はんい に およんで いる。', en: 'According to reports, the damage extends over a wide area.' } },
      { id: 'v-ja-n2-01-03', text: '世論', reading: 'よろん', en: 'public opinion', pos: 'noun', example: { text: '世論は増税に反対している。', reading: 'よろん は ぞうぜい に はんたい して いる。', en: 'Public opinion is against the tax increase.' } },
      { id: 'v-ja-n2-01-04', text: '論文', reading: 'ろんぶん', en: 'academic paper; thesis', pos: 'noun', example: { text: '彼は経済に関する論文を書いている。', reading: 'かれ は けいざい に かんする ろんぶん を かいて いる。', en: "He's writing a paper on economics." } },
      { id: 'v-ja-n2-01-05', text: '要約', reading: 'ようやく', en: 'summary (要約する = to summarize)', pos: 'noun', example: { text: 'この記事を三百字で要約してください。', reading: 'この きじ を さんびゃくじ で ようやく して ください。', en: 'Please summarize this article in 300 characters.' } },
      { id: 'v-ja-n2-01-06', text: '主張', reading: 'しゅちょう', en: 'claim; argument; assertion', pos: 'noun', example: { text: '筆者の主張には説得力がある。', reading: 'ひっしゃ の しゅちょう に は せっとくりょく が ある。', en: "The author's argument is persuasive." } },
      { id: 'v-ja-n2-01-07', text: '筆者', reading: 'ひっしゃ', en: 'the author (of a text)', pos: 'noun', example: { text: '筆者が最も伝えたいことは何か。', reading: 'ひっしゃ が もっとも つたえたい こと は なに か。', en: 'What does the author most want to convey?' } },
      { id: 'v-ja-n2-01-08', text: '課題', reading: 'かだい', en: 'issue; challenge; task', pos: 'noun', example: { text: '少子化は日本が直面している大きな課題である。', reading: 'しょうしか は にほん が ちょくめん して いる おおきな かだい で ある。', en: 'The falling birth rate is a major challenge facing Japan.' } },
      { id: 'v-ja-n2-01-09', text: '現状', reading: 'げんじょう', en: 'the current situation; status quo', pos: 'noun', example: { text: '現状を正しく把握する必要がある。', reading: 'げんじょう を ただしく はあく する ひつよう が ある。', en: 'We need to understand the current situation accurately.' } },
      { id: 'v-ja-n2-01-10', text: '傾向', reading: 'けいこう', en: 'tendency; trend', pos: 'noun', example: { text: '若者の新聞離れの傾向が続いている。', reading: 'わかもの の しんぶんばなれ の けいこう が つづいて いる。', en: 'The trend of young people turning away from newspapers continues.' } },
      { id: 'v-ja-n2-01-11', text: '指摘する', reading: 'してき する', en: 'to point out', pos: 'verb', example: { text: '専門家は制度の問題点を指摘した。', reading: 'せんもんか は せいど の もんだいてん を してき した。', en: 'Experts pointed out the problems with the system.' } },
      { id: 'v-ja-n2-01-12', text: '述べる', reading: 'のべる', en: 'to state; to express (formally)', pos: 'verb', example: { text: '首相は記者会見で自分の考えを述べた。', reading: 'しゅしょう は きしゃかいけん で じぶん の かんがえ を のべた。', en: 'The prime minister stated his views at a press conference.' } },
      { id: 'v-ja-n2-01-13', text: '及ぼす', reading: 'およぼす', en: 'to exert (influence); to cause (harm)', pos: 'verb', example: { text: '気候変動は農業に深刻な影響を及ぼしている。', reading: 'きこうへんどう は のうぎょう に しんこく な えいきょう を およぼして いる。', en: 'Climate change is having a serious impact on agriculture.' } },
      { id: 'v-ja-n2-01-14', text: '明らか', reading: 'あきらか', en: 'clear; evident (na-adj.)', pos: 'adjective', example: { text: '調査の結果、事故の原因が明らかになった。', reading: 'ちょうさ の けっか、 じこ の げんいん が あきらか に なった。', en: 'The investigation made the cause of the accident clear.' } },
      { id: 'v-ja-n2-01-15', text: '見出し', reading: 'みだし', en: 'headline', pos: 'noun', example: { text: '新聞の見出しだけ読んで、内容を判断してはいけない。', reading: 'しんぶん の みだし だけ よんで、 ないよう を はんだん して は いけない。', en: "Don't judge an article by reading only the headline." } },
      { id: 'v-ja-n2-01-16', text: '検討する', reading: 'けんとう する', en: 'to consider; to look into', pos: 'verb', example: { text: '政府は制度の見直しを検討している。', reading: 'せいふ は せいど の みなおし を けんとう して いる。', en: 'The government is considering a review of the system.' } },
    ],
    scenario: {
      title: 'Discussing a news article',
      setting: "At a study café in Kyoto, you and a Japanese graduate student have both read a newspaper article about Japan's falling birth rate and its effect on rural towns.",
      aiRole: 'Kenji Morita (森田健二), a sociology graduate student who loves debating current events',
      learnerGoal: "Summarize the article's main points, give your own opinion using formal expressions such as 〜に関して or 〜に対して, and respond to one of Kenji's counterarguments.",
      opener: '例の少子化に関する記事、もう読みましたか。地方への影響について、筆者の主張をどう思いました？',
      openerReading: 'れい の しょうしか に かんする きじ、 もう よみました か。 ちほう へ の えいきょう に ついて、 ひっしゃ の しゅちょう を どう おもいました？',
    },
  },
  {
    id: 'ja-n2-02',
    cefr: 'B2',
    order: 30,
    title: '時と条件: Nuanced time and conditions',
    theme: 'Precise timing, interruptions, and conditions when coordinating plans',
    canDo: [
      'I can say something should happen while a situation lasts, using 〜うちに.',
      'I can describe an interruption in the middle of an action, and something that happened the instant something else did.',
      'I can promise action as soon as something happens and set conditions with 〜次第, 〜限り, and 〜さえ〜ば.',
    ],
    grammar: [
      {
        id: 'g-ja-n2-02-1',
        title: '〜うちに, 〜最中に, 〜たとたん',
        summary:
          "〜うちに means 'while (a state still lasts)' and urges acting before the situation changes: 若いうちに, 温かいうちに; with a negative it means 'before': 忘れないうちに (before I forget). With an ongoing action (〜ているうちに) it describes a gradual, often unnoticed change: 話しているうちに仲良くなった. 〜最中に (さいちゅうに; noun + の最中に, or 〜ている最中に) means 'right in the middle of' and usually introduces an unwelcome interruption: 会議の最中に電話が鳴った. 〜たとたん(に) means 'the instant (that)' and reports a sudden, often surprising event outside the speaker's control: 立ち上がったとたん、めまいがした. Pitfall: たとたん can't be followed by your own intention, a request, or a command (×家に着いたとたん、電話してください); use 〜たらすぐ or 〜次第 for that.",
        examples: [
          { text: '温かいうちに召し上がってください。', reading: 'あたたかい うち に めしあがって ください。', en: "Please eat it while it's warm." },
          { text: '忘れないうちにメモしておこう。', reading: 'わすれない うち に メモ して おこう。', en: "I'll make a note before I forget." },
          { text: '何度も話しているうちに、彼の考えが分かってきた。', reading: 'なんど も はなして いる うち に、 かれ の かんがえ が わかって きた。', en: 'As we talked again and again, I came to understand his ideas.' },
          { text: '発表の最中に、パソコンが動かなくなった。', reading: 'はっぴょう の さいちゅう に、 パソコン が うごかなく なった。', en: 'Right in the middle of my presentation, the computer stopped working.' },
          { text: 'ドアを開けたとたん、猫が飛び出してきた。', reading: 'ドア を あけた とたん、 ねこ が とびだして きた。', en: 'The moment I opened the door, the cat dashed out.' },
        ],
        drills: [
          { text: '日本にいる___、富士山に登りたい。', reading: 'にほん に いる ___、 ふじさん に のぼりたい。', en: "I want to climb Mt. Fuji while I'm still in Japan.", answer: 'うちに', distractors: ['最中に', 'とたん', '次第'] },
          { text: '食事の___、地震が起きた。', reading: 'しょくじ の ___、 じしん が おきた。', en: 'An earthquake struck right in the middle of the meal.', answer: '最中に', distractors: ['うちに', 'とたん', '次第'] },
          { text: '電車を降りた___、雨が降り出した。', reading: 'でんしゃ を おりた ___、 あめ が ふりだした。', en: 'The moment I got off the train, it started to rain.', answer: 'とたん', distractors: ['うちに', '最中に', '次第'] },
          { text: '暗くならない___、帰りましょう。', reading: 'くらく ならない ___、 かえりましょう。', en: "Let's go home before it gets dark.", answer: 'うちに', distractors: ['最中に', 'とたん', 'あとで'] },
          { text: '急に立ち上がった___に、めまいがした。', reading: 'きゅう に たちあがった ___ に、 めまい が した。', en: 'The instant I stood up suddenly, I felt dizzy.', answer: 'とたん', distractors: ['うち', '最中', '次第'] },
        ],
      },
      {
        id: 'g-ja-n2-02-2',
        title: '〜次第, 〜限り, 〜さえ〜ば',
        summary:
          "The ます-stem + 次第 (しだい) means 'as soon as (X happens), I will…' and, unlike たとたん, is used for planned actions, promises, and requests, typically in business or formal announcements: 結果が分かり次第、ご連絡します (on its own, noun + 次第 means 'depends on': 天気次第だ). 〜限り (かぎり) means 'as long as' a condition holds; with a negative it means 'unless' (雨が降らない限り), and with verbs of knowing it means 'as far as' (私の知る限り). 〜さえ〜ば means 'if only / as long as (just this one thing)': noun + さえ + ば-form (お金さえあれば), stem + さえすれば (飲みさえすれば), or て-form + さえいれば. It is stronger than a plain 〜ば because さえ singles out the one essential condition. Pitfall: 次第 attaches to the ます-stem (着き次第, not ×着く次第) and is never used for past events (×着き次第、電話した).",
        examples: [
          { text: '詳しいことが分かり次第、お知らせします。', reading: 'くわしい こと が わかり しだい、 おしらせ します。', en: 'We will let you know as soon as we have the details.' },
          { text: '天候が回復し次第、出発します。', reading: 'てんこう が かいふく し しだい、 しゅっぱつ します。', en: 'We will depart as soon as the weather improves.' },
          { text: '雨が降らない限り、イベントは予定どおり行います。', reading: 'あめ が ふらない かぎり、 イベント は よていどおり おこないます。', en: 'Unless it rains, the event will go ahead as planned.' },
          { text: '私の知る限り、彼はまだ来ていません。', reading: 'わたし の しる かぎり、 かれ は まだ きて いません。', en: "As far as I know, he hasn't arrived yet." },
          { text: '住所さえ分かれば、地図で探せます。', reading: 'じゅうしょ さえ わかれば、 ちず で さがせます。', en: 'As long as I know the address, I can find it on a map.' },
        ],
        drills: [
          { text: '準備ができ___、始めましょう。', reading: 'じゅんび が でき ___、 はじめましょう。', en: "Let's start as soon as we're ready.", answer: '次第', distractors: ['とたん', '限り', 'うちに'] },
          { text: '会員でない___、この施設は利用できません。', reading: 'かいいん で ない ___、 この しせつ は りよう できません。', en: "Unless you're a member, you can't use this facility.", answer: '限り', distractors: ['次第', 'さえ', 'とたん'] },
          { text: 'この薬を飲み___すれば、すぐ治りますよ。', reading: 'この くすり を のみ ___ すれば、 すぐ なおります よ。', en: "If you just take this medicine, you'll get better right away.", answer: 'さえ', distractors: ['次第', '限り', 'しか'] },
          { text: '時間___あれば、もっと練習できるのに。', reading: 'じかん ___ あれば、 もっと れんしゅう できる のに。', en: 'If only I had time, I could practice more.', answer: 'さえ', distractors: ['しか', 'まで', 'こそ'] },
          { text: '結果が分かり___、ご報告いたします。', reading: 'けっか が わかり ___、 ごほうこく いたします。', en: 'I will report to you as soon as the results are known.', answer: '次第', distractors: ['とたん', '限り', 'うちに'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n2-02-01', text: '日程', reading: 'にってい', en: 'schedule; itinerary', pos: 'noun', example: { text: '会議の日程を調整しなければならない。', reading: 'かいぎ の にってい を ちょうせい しなければ ならない。', en: 'We need to adjust the meeting schedule.' } },
      { id: 'v-ja-n2-02-02', text: '調整する', reading: 'ちょうせい する', en: 'to adjust; to coordinate', pos: 'verb', example: { text: '参加者の都合を聞いて、時間を調整します。', reading: 'さんかしゃ の つごう を きいて、 じかん を ちょうせい します。', en: "I'll check what suits the participants and adjust the time." } },
      { id: 'v-ja-n2-02-03', text: '延期する', reading: 'えんき する', en: 'to postpone', pos: 'verb', example: { text: '台風のため、イベントは来週に延期された。', reading: 'たいふう の ため、 イベント は らいしゅう に えんき された。', en: 'Because of the typhoon, the event was postponed to next week.' } },
      { id: 'v-ja-n2-02-04', text: '順延', reading: 'じゅんえん', en: 'postponement (to the next available day)', pos: 'noun', example: { text: '運動会は雨天の場合、翌日に順延となります。', reading: 'うんどうかい は うてん の ばあい、 よくじつ に じゅんえん と なります。', en: 'If it rains, the sports day will be moved to the following day.' } },
      { id: 'v-ja-n2-02-05', text: '手配する', reading: 'てはい する', en: 'to arrange (tickets, transport, etc.)', pos: 'verb', example: { text: '会場までのバスを手配しておきました。', reading: 'かいじょう まで の バス を てはい して おきました。', en: "I've arranged a bus to the venue." } },
      { id: 'v-ja-n2-02-06', text: '段取り', reading: 'だんどり', en: 'arrangements; the steps of a plan', pos: 'noun', example: { text: '当日の段取りをもう一度確認しよう。', reading: 'とうじつ の だんどり を もう いちど かくにん しよう。', en: "Let's go over the plan for the day once more." } },
      { id: 'v-ja-n2-02-07', text: '当日', reading: 'とうじつ', en: 'the day (in question); on the day', pos: 'noun', example: { text: '当日は朝八時に集合してください。', reading: 'とうじつ は あさ はちじ に しゅうごう して ください。', en: 'On the day, please gather at 8 a.m.' } },
      { id: 'v-ja-n2-02-08', text: '打ち上げ', reading: 'うちあげ', en: 'wrap-up party (after an event or project)', pos: 'noun', example: { text: 'イベントが無事に終わったら、みんなで打ち上げをしよう。', reading: 'イベント が ぶじ に おわったら、 みんな で うちあげ を しよう。', en: "Once the event is over safely, let's all have a wrap-up party." } },
      { id: 'v-ja-n2-02-09', text: '見通し', reading: 'みとおし', en: 'outlook; prospect', pos: 'noun', example: { text: '工事が年内に終わる見通しは立っていない。', reading: 'こうじ が ねんない に おわる みとおし は たって いない。', en: "There's no prospect yet of the construction finishing within the year." } },
      { id: 'v-ja-n2-02-10', text: '万一', reading: 'まんいち', en: 'in the unlikely event; just in case', pos: 'adverb', example: { text: '万一雨が降った場合は、体育館で行います。', reading: 'まんいち あめ が ふった ばあい は、 たいいくかん で おこないます。', en: 'In the unlikely event of rain, it will be held in the gym.' } },
      { id: 'v-ja-n2-02-11', text: 'あらかじめ', en: 'in advance; beforehand', pos: 'adverb', example: { text: '欠席する場合は、あらかじめ連絡してください。', reading: 'けっせき する ばあい は、 あらかじめ れんらく して ください。', en: 'If you will be absent, please let us know in advance.' } },
      { id: 'v-ja-n2-02-12', text: '直前', reading: 'ちょくぜん', en: 'just before; the last minute', pos: 'noun', example: { text: '出発の直前に、忘れ物に気づいた。', reading: 'しゅっぱつ の ちょくぜん に、 わすれもの に きづいた。', en: 'Just before leaving, I noticed I had forgotten something.' } },
      { id: 'v-ja-n2-02-13', text: '臨機応変', reading: 'りんきおうへん', en: 'flexible; adapting to the situation (na-adj.)', pos: 'adjective', example: { text: '予定どおりにいかないときは、臨機応変に対応しよう。', reading: 'よていどおり に いかない とき は、 りんきおうへん に たいおう しよう。', en: "When things don't go as planned, let's adapt flexibly." } },
      { id: 'v-ja-n2-02-14', text: '手分けする', reading: 'てわけ する', en: 'to divide up (the work)', pos: 'verb', example: { text: '準備は三人で手分けしてやりましょう。', reading: 'じゅんび は さんにん で てわけ して やりましょう。', en: "Let's split up the preparations among the three of us." } },
      { id: 'v-ja-n2-02-15', text: '至急', reading: 'しきゅう', en: 'urgently; as soon as possible', pos: 'adverb', example: { text: '至急、会場の担当者に連絡してください。', reading: 'しきゅう、 かいじょう の たんとうしゃ に れんらく して ください。', en: 'Please contact the person in charge at the venue right away.' } },
      { id: 'v-ja-n2-02-16', text: '確定する', reading: 'かくてい する', en: 'to be finalized; to become definite', pos: 'verb', example: { text: '参加人数が確定したら、教えてください。', reading: 'さんかにんずう が かくてい したら、 おしえて ください。', en: 'Please tell me once the number of participants is finalized.' } },
    ],
    scenario: {
      title: 'Coordinating a community event',
      setting: 'You are helping organize a neighborhood summer festival in Yokohama. Two weeks before the event, you meet the volunteer coordinator to finalize the plan for the day and a backup plan for bad weather.',
      aiRole: 'Yuko Hayashi (林裕子), the volunteer coordinator of the neighborhood association',
      learnerGoal: 'Confirm the schedule for the day, propose a plan in case of rain using 〜限り or 〜次第, promise to contact everyone as soon as details are fixed, and agree on who arranges what.',
      opener: 'お疲れさまです。当日の段取りなんですが、天気予報次第で変わるかもしれないので、今のうちに雨の場合の計画も決めておきませんか。',
      openerReading: 'おつかれさま です。 とうじつ の だんどり なん です が、 てんきよほう しだい で かわる かも しれない ので、 いま の うち に あめ の ばあい の けいかく も きめて おきません か。',
    },
  },
  {
    id: 'ja-n2-03',
    cefr: 'B2',
    order: 31,
    title: '話し手の気持ち: Speaker attitude',
    theme: 'Obligation, reluctant necessity, conviction, and risk in big decisions',
    canDo: [
      "I can say I can't do something for social or moral reasons, or that I have no choice but to do something.",
      'I can express strong conviction with 〜に違いない.',
      'I can warn that something could lead to a bad result, and dismiss something as impossible in casual speech.',
    ],
    grammar: [
      {
        id: 'g-ja-n2-03-1',
        title: '〜わけにはいかない, 〜ざるを得ない',
        summary:
          "Dictionary form + わけにはいかない means 'I can't (very well) do X': not because it's physically impossible, but because social, moral, or practical considerations rule it out: 明日は試験だから、休むわけにはいかない. The negative 〜ないわけにはいかない means 'I can't not do X', i.e. it would be wrong not to: 誘われたら行かないわけにはいかない. 〜ざるを得ない (ざるをえない; ない-stem + ざるを得ない, with する → せざるを得ない) means 'to have no choice but to' and stresses a reluctant necessity forced by circumstances: 計画を中止せざるを得ない. It is more formal and written than its everyday equivalent 〜しかない. Pitfall: わけにはいかない is not for plain inability (if you can't swim, say 泳げない, not ×泳ぐわけにはいかない), and remember the irregular せざる (not ×しざる).",
        examples: [
          { text: '大事な会議があるので、休むわけにはいかない。', reading: 'だいじ な かいぎ が ある ので、 やすむ わけ に は いかない。', en: "I have an important meeting, so I can't very well take the day off." },
          { text: '先輩に誘われたら、行かないわけにはいかない。', reading: 'せんぱい に さそわれたら、 いかない わけ に は いかない。', en: "If a senior colleague invites me, I can't not go." },
          { text: 'まだ仕事が残っているので、先に帰るわけにはいきません。', reading: 'まだ しごと が のこって いる ので、 さき に かえる わけ に は いきません。', en: "I still have work left, so I can't leave before everyone else." },
          { text: '予算が足りないため、計画を見直さざるを得ない。', reading: 'よさん が たりない ため、 けいかく を みなおさざる を えない。', en: 'Because the budget is insufficient, we have no choice but to revise the plan.' },
          { text: '台風が近づいていたため、試合は中止せざるを得なかった。', reading: 'たいふう が ちかづいて いた ため、 しあい は ちゅうし せざる を えなかった。', en: 'Because a typhoon was approaching, the match had to be canceled.' },
        ],
        drills: [
          { text: '約束したのだから、今さら断る___。', reading: 'やくそく した の だ から、 いまさら ことわる ___。', en: "I promised, so I can't very well refuse now.", answer: 'わけにはいかない', distractors: ['ざるを得ない', 'に違いない', 'かねない'] },
          { text: '上司の命令である以上、従わ___。', reading: 'じょうし の めいれい で ある いじょう、 したがわ ___。', en: "Since it's an order from my boss, I have no choice but to obey.", answer: 'ざるを得ない', distractors: ['わけにはいかない', 'かねない', 'っこない'] },
          { text: 'この状況では、計画を変更___。', reading: 'この じょうきょう で は、 けいかく を へんこう ___。', en: 'In this situation, we have no choice but to change the plan.', answer: 'せざるを得ない', distractors: ['しざるを得ない', 'するざるを得ない', 'さざるを得ない'] },
          { text: '明日は大事な試験があるから、勉強___わけにはいかない。', reading: 'あした は だいじ な しけん が ある から、 べんきょう ___ わけ に は いかない。', en: "I have an important exam tomorrow, so I can't get away with not studying.", answer: 'しない', distractors: ['する', 'した', 'せず'] },
          { text: 'この後運転するので、お酒を飲む___。', reading: 'この あと うんてん する ので、 おさけ を のむ ___。', en: "I'm driving after this, so I can't drink.", answer: 'わけにはいきません', distractors: ['ざるを得ません', 'に違いありません', 'しかありません'] },
        ],
      },
      {
        id: 'g-ja-n2-03-2',
        title: '〜に違いない, 〜かねない, 〜っこない',
        summary:
          "〜に違いない (にちがいない; plain form, with nouns and な-adjectives attaching directly, no だ) expresses strong conviction, 'must be, surely', based on intuition as much as evidence: 留守に違いない. Compared with はずだ, a logical deduction ('should be, by reasoning'), に違いない is more emphatic and subjective, and slightly written in tone. The ます-stem + かねない means 'could well (lead to something bad)': 無理をすると、体を壊しかねない; it is only used for undesirable outcomes, and despite its negative ending it states a real possibility. Don't confuse it with 〜かねます ('I'm unable to'), a polite refusal in customer service. The ます-stem + っこない is casual speech for 'there's no way' (勝てっこない); in formal contexts use 〜はずがない or 〜わけがない instead.",
        examples: [
          { text: '部屋の電気がついているから、彼はもう帰ってきたに違いない。', reading: 'へや の でんき が ついて いる から、 かれ は もう かえって きた に ちがいない。', en: 'The light in his room is on, so he must have come home already.' },
          { text: '犯人はあの男に違いない。', reading: 'はんにん は あの おとこ に ちがいない。', en: 'The culprit must be that man.' },
          { text: 'スピードを出しすぎると、事故を起こしかねない。', reading: 'スピード を だしすぎる と、 じこ を おこし かねない。', en: 'If you drive too fast, you could well cause an accident.' },
          { text: 'そんな言い方をしたら、誤解されかねないよ。', reading: 'そんな いいかた を したら、 ごかい され かねない よ。', en: 'If you put it like that, you could easily be misunderstood.' },
          { text: '一週間でこの本を全部覚えるなんて、できっこないよ。', reading: 'いっしゅうかん で この ほん を ぜんぶ おぼえる なんて、 できっこない よ。', en: "Memorize this whole book in a week? There's no way." },
        ],
        drills: [
          { text: '彼女はあれだけ練習したのだから、合格する___。', reading: 'かのじょ は あれ だけ れんしゅう した の だ から、 ごうかく する ___。', en: "She practiced that much, so she's sure to pass.", answer: 'に違いない', distractors: ['かねない', 'っこない', 'わけにはいかない'] },
          { text: '睡眠不足が続くと、体を壊し___。', reading: 'すいみんぶそく が つづく と、 からだ を こわし ___。', en: 'If you keep going without enough sleep, you could well ruin your health.', answer: 'かねない', distractors: ['っこない', 'に違いない', 'わけにはいかない'] },
          { text: '彼に頼んでも、引き受けてくれ___よ。', reading: 'かれ に たのんで も、 ひきうけて くれ ___ よ。', en: "Even if you ask him, there's no way he'll take it on.", answer: 'っこない', distractors: ['かねない', 'に違いない', 'ざるを得ない'] },
          { text: '財布がない。電車の中で落とした___。', reading: 'さいふ が ない。 でんしゃ の なか で おとした ___。', en: 'My wallet is gone. I must have dropped it on the train.', answer: 'に違いない', distractors: ['かねない', 'っこない', 'わけにはいかない'] },
          { text: '今の発言は、誤解を招き___。', reading: 'いま の はつげん は、 ごかい を まねき ___。', en: 'What you just said could well cause a misunderstanding.', answer: 'かねない', distractors: ['かねる', 'っこない', 'に違いない'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n2-03-01', text: '転勤', reading: 'てんきん', en: 'job transfer (to another office)', pos: 'noun', example: { text: '来年の春、大阪に転勤することになった。', reading: 'らいねん の はる、 おおさか に てんきん する こと に なった。', en: "I'm being transferred to Osaka next spring." } },
      { id: 'v-ja-n2-03-02', text: '海外赴任', reading: 'かいがいふにん', en: 'overseas assignment', pos: 'noun', example: { text: '海外赴任の話を聞いて、正直迷っている。', reading: 'かいがいふにん の はなし を きいて、 しょうじき まよって いる。', en: "Since hearing about the overseas assignment, I've honestly been torn." } },
      { id: 'v-ja-n2-03-03', text: 'ためらう', en: 'to hesitate', pos: 'verb', example: { text: '彼女は本当のことを言うのをためらった。', reading: 'かのじょ は ほんとう の こと を いう の を ためらった。', en: 'She hesitated to tell the truth.' } },
      { id: 'v-ja-n2-03-04', text: '覚悟', reading: 'かくご', en: 'resolve; being prepared (for something hard)', pos: 'noun', example: { text: '苦労する覚悟はできている。', reading: 'くろう する かくご は できて いる。', en: "I'm prepared to go through hardship." } },
      { id: 'v-ja-n2-03-05', text: '決断', reading: 'けつだん', en: 'decision; resolution (決断する = to decide firmly)', pos: 'noun', example: { text: '家族と相談して、最終的な決断を下した。', reading: 'かぞく と そうだん して、 さいしゅうてき な けつだん を くだした。', en: 'After talking with my family, I made the final decision.' } },
      { id: 'v-ja-n2-03-06', text: '戸惑う', reading: 'とまどう', en: 'to be bewildered; to be at a loss', pos: 'verb', example: { text: '突然の知らせに戸惑った。', reading: 'とつぜん の しらせ に とまどった。', en: 'I was bewildered by the sudden news.' } },
      { id: 'v-ja-n2-03-07', text: '昇進', reading: 'しょうしん', en: 'promotion (at work)', pos: 'noun', example: { text: '海外での経験は昇進に有利だと言われている。', reading: 'かいがい で の けいけん は しょうしん に ゆうり だ と いわれて いる。', en: 'Experience abroad is said to help with promotion.' } },
      { id: 'v-ja-n2-03-08', text: '単身赴任', reading: 'たんしんふにん', en: 'working away from home (without one’s family)', pos: 'noun', example: { text: '父は三年間、単身赴任をしていた。', reading: 'ちち は さんねんかん、 たんしんふにん を して いた。', en: 'My father worked away from the family for three years.' } },
      { id: 'v-ja-n2-03-09', text: '犠牲', reading: 'ぎせい', en: 'sacrifice', pos: 'noun', example: { text: '家族との時間を犠牲にしてまで、出世したいとは思わない。', reading: 'かぞく と の じかん を ぎせい に して まで、 しゅっせ したい と は おもわない。', en: "I don't want to get ahead if it means sacrificing time with my family." } },
      { id: 'v-ja-n2-03-10', text: '将来性', reading: 'しょうらいせい', en: 'future prospects; potential', pos: 'noun', example: { text: 'この分野は将来性があると思う。', reading: 'この ぶんや は しょうらいせい が ある と おもう。', en: 'I think this field has a promising future.' } },
      { id: 'v-ja-n2-03-11', text: '慎重', reading: 'しんちょう', en: 'careful; cautious (na-adj.)', pos: 'adjective', example: { text: '大切な問題だから、慎重に判断したい。', reading: 'たいせつ な もんだい だ から、 しんちょう に はんだん したい。', en: "It's an important matter, so I want to decide carefully." } },
      { id: 'v-ja-n2-03-12', text: '踏み切る', reading: 'ふみきる', en: 'to take the plunge; to go ahead with', pos: 'verb', example: { text: '悩んだ末に、転職に踏み切った。', reading: 'なやんだ すえ に、 てんしょく に ふみきった。', en: 'After much agonizing, I took the plunge and changed jobs.' } },
      { id: 'v-ja-n2-03-13', text: '引き受ける', reading: 'ひきうける', en: 'to take on; to accept (a task or role)', pos: 'verb', example: { text: 'その仕事を引き受けるかどうか、まだ決めていない。', reading: 'その しごと を ひきうける か どう か、 まだ きめて いない。', en: "I haven't decided yet whether to take on that job." } },
      { id: 'v-ja-n2-03-14', text: '待遇', reading: 'たいぐう', en: 'treatment; pay and working conditions', pos: 'noun', example: { text: '新しい会社は前の会社より待遇がいい。', reading: 'あたらしい かいしゃ は まえ の かいしゃ より たいぐう が いい。', en: 'The new company offers better pay and conditions than my old one.' } },
      { id: 'v-ja-n2-03-15', text: '現地', reading: 'げんち', en: 'the place itself; local (on site)', pos: 'noun', example: { text: '現地の言葉を少しでも話せると便利だ。', reading: 'げんち の ことば を すこし でも はなせる と べんり だ。', en: "It's useful if you can speak even a little of the local language." } },
      { id: 'v-ja-n2-03-16', text: '本音', reading: 'ほんね', en: "one's true feelings", pos: 'noun', example: { text: '本音を言うと、日本を離れたくない。', reading: 'ほんね を いう と、 にほん を はなれたくない。', en: "To be honest, I don't want to leave Japan." } },
    ],
    scenario: {
      title: 'A transfer to Singapore?',
      setting: 'Your Tokyo company has offered you a three-year assignment at its Singapore office. Over coffee after work, you talk it through with a trusted senior colleague.',
      aiRole: 'Takashi Ono (小野隆), a senior colleague in his forties who once worked in London for five years',
      learnerGoal: "Explain the offer and your true feelings, give one reason you can't easily refuse and one risk you're worried about (using 〜わけにはいかない or 〜かねない), then ask for Ono's advice and say what you've decided.",
      opener: 'シンガポール赴任の話、聞いたよ。すごいチャンスに違いないけど、家族のこともあるし、迷っているんじゃない？',
      openerReading: 'シンガポール ふにん の はなし、 きいた よ。 すごい チャンス に ちがいない けど、 かぞく の こと も ある し、 まよって いる ん じゃない？',
    },
  },
  {
    id: 'ja-n2-04',
    cefr: 'B2',
    order: 32,
    title: 'ビジネス日本語: Business Japanese',
    theme: 'Business keigo, emails, and phone calls with clients',
    canDo: [
      'I can use 〜させていただく appropriately and know when it sounds excessive.',
      'I can use standard business keigo such as いたす, 申す, and おる, and refer to my own colleagues correctly when speaking to outsiders.',
      'I can open, close, and make requests in business emails and phone calls with set phrases.',
    ],
    grammar: [
      {
        id: 'g-ja-n2-04-1',
        title: '〜させていただく and business keigo',
        summary:
          "〜させていただく (causative て-form + いただく) literally means 'to humbly receive permission to do' and is used when you act with the listener's permission or in a way that affects them: 説明させていただきます, 本日は休ませていただきます. Group 1 verbs use the あ-row + せていただく (休ませて, 読ませて), group 2 verbs use させていただく (始めさせて), and する becomes させていただく. Business Japanese also relies on humble verbs (いたす for する, 申す for naming yourself, 申し上げる for saying something to a superior, おる for いる, 参る for 行く/来る) and the courteous ございます. When talking to outsiders, refer to your own colleagues, even your boss, by surname alone with humble verbs: 鈴木はただいま外出しております. Pitfalls: overusing させていただく where no permission is involved (×大学を卒業させていただきました) sounds stiff, and 'さ-inserted' forms such as ×読まさせていただく are considered errors.",
        examples: [
          { text: '本日の会議の資料を説明させていただきます。', reading: 'ほんじつ の かいぎ の しりょう を せつめい させて いただきます。', en: "Allow me to explain the materials for today's meeting." },
          { text: '申し訳ございませんが、明日は休ませていただけないでしょうか。', reading: 'もうしわけ ございません が、 あす は やすませて いただけない でしょう か。', en: "I'm very sorry, but might I take tomorrow off?" },
          { text: '担当の者が戻りましたら、折り返しお電話いたします。', reading: 'たんとう の もの が もどりましたら、 おりかえし おでんわ いたします。', en: 'When the person in charge returns, we will call you back.' },
          { text: '改めてご連絡申し上げます。', reading: 'あらためて ごれんらく もうしあげます。', en: 'I will contact you again.' },
          { text: '鈴木はただいま外出しております。', reading: 'すずき は ただいま がいしゅつ して おります。', en: 'Suzuki is out of the office at the moment.' },
        ],
        drills: [
          { text: 'それでは、会議を始め___いただきます。', reading: 'それ で は、 かいぎ を はじめ ___ いただきます。', en: 'Well then, allow me to begin the meeting.', answer: 'させて', distractors: ['て', 'られて', 'さして'] },
          { text: '体調が悪いので、今日は休___いただけませんか。', reading: 'たいちょう が わるい ので、 きょう は やす___ いただけません か。', en: "I'm not feeling well. Might I take today off?", answer: 'ませて', distractors: ['まさせて', 'んで', 'まれて'] },
          { text: '鈴木はただいま席を外して___。', reading: 'すずき は ただいま せき を はずして ___。', en: 'Suzuki is away from his desk at the moment. (to an outside caller)', answer: 'おります', distractors: ['いらっしゃいます', 'ございます', 'あります'] },
          { text: '私、営業部の田中と___。', reading: 'わたくし、 えいぎょうぶ の たなか と ___。', en: 'This is Tanaka from the sales department. (on the phone)', answer: '申します', distractors: ['申し上げます', 'おっしゃいます', 'いたします'] },
          { text: '詳細は後ほどメールでお送り___。', reading: 'しょうさい は のちほど メール で おおくり ___。', en: 'I will send you the details by email later.', answer: 'いたします', distractors: ['なさいます', 'になります', 'くださいます'] },
        ],
      },
      {
        id: 'g-ja-n2-04-2',
        title: 'Email and phone set phrases',
        summary:
          "Business emails follow a fixed frame: open with いつもお世話になっております (never こんにちは), give your company and name, state your purpose, and close with よろしくお願いいたします or the more formal 何卒よろしくお願い申し上げます. Requests are softened with cushion phrases such as お手数をおかけしますが ('sorry for the trouble') and 恐れ入りますが ('excuse me, but'), followed by humble request forms like ご確認いただけますでしょうか. On the phone, answer with お電話ありがとうございます plus your company name, say 少々お待ちください to put someone on hold, and offer 折り返しお電話いたします ('we'll call you back'). Things belonging to the other party take お/ご: ご都合, お名前, ご連絡先. Pitfall: もしもし sounds unprofessional when answering a business line, and すみません is too light for a business apology; use 申し訳ございません.",
        examples: [
          { text: 'いつもお世話になっております。山田商事の佐藤です。', reading: 'いつも おせわ に なって おります。 やまだしょうじ の さとう です。', en: 'Thank you for your continued support. This is Sato from Yamada Trading.' },
          { text: 'お手数をおかけしますが、ご確認のほどよろしくお願いいたします。', reading: 'おてすう を おかけ します が、 ごかくにん の ほど よろしく おねがい いたします。', en: "Sorry for the trouble, but I'd appreciate it if you could check this." },
          { text: '少々お待ちください。担当者に代わります。', reading: 'しょうしょう おまち ください。 たんとうしゃ に かわります。', en: "One moment, please. I'll put you through to the person in charge." },
          { text: '恐れ入りますが、もう一度お名前をお願いできますか。', reading: 'おそれいります が、 もう いちど おなまえ を おねがい できます か。', en: 'Excuse me, but could I have your name once more?' },
          { text: 'ご都合のよい日時をお知らせいただけますでしょうか。', reading: 'ごつごう の よい にちじ を おしらせ いただけます でしょう か。', en: 'Could you please let me know a date and time that suits you?' },
        ],
        drills: [
          { text: 'いつもお世話に___おります。', reading: 'いつも おせわ に ___ おります。', en: 'Thank you for your continued support. (lit. I am always in your care.)', answer: 'なって', distractors: ['して', 'いたして', 'されて'] },
          { text: 'お手数を___しますが、よろしくお願いいたします。', reading: 'おてすう を ___ します が、 よろしく おねがい いたします。', en: 'Sorry for the trouble, and thank you in advance.', answer: 'おかけ', distractors: ['おかり', 'おつけ', 'おかし'] },
          { text: '少々お___ください。', reading: 'しょうしょう お___ ください。', en: 'Please wait a moment.', answer: '待ち', distractors: ['待って', '待た', '待つ'] },
          { text: '大変申し訳___。こちらの手違いでした。', reading: 'たいへん もうしわけ ___。 こちら の てちがい でした。', en: 'We sincerely apologize. It was our mistake.', answer: 'ございません', distractors: ['ございます', 'いたしません', 'なさいません'] },
          { text: '添付の資料をご確認___でしょうか。', reading: 'てんぷ の しりょう を ごかくにん ___ でしょう か。', en: 'Could you please check the attached document?', answer: 'いただけます', distractors: ['いたします', '申します', 'まいります'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n2-04-01', text: '取引先', reading: 'とりひきさき', en: 'client; business partner', pos: 'noun', example: { text: '午後、取引先と打ち合わせがある。', reading: 'ごご、 とりひきさき と うちあわせ が ある。', en: 'I have a meeting with a client this afternoon.' } },
      { id: 'v-ja-n2-04-02', text: '打ち合わせ', reading: 'うちあわせ', en: '(business) meeting; planning session', pos: 'noun', example: { text: '打ち合わせの時間を変更していただけますか。', reading: 'うちあわせ の じかん を へんこう して いただけます か。', en: 'Could we change the time of the meeting?' } },
      { id: 'v-ja-n2-04-03', text: '担当者', reading: 'たんとうしゃ', en: 'person in charge', pos: 'noun', example: { text: '詳しいことは担当者からご説明いたします。', reading: 'くわしい こと は たんとうしゃ から ごせつめい いたします。', en: 'The person in charge will explain the details.' } },
      { id: 'v-ja-n2-04-04', text: '折り返し', reading: 'おりかえし', en: '(call) back; by return', pos: 'adverb', example: { text: '担当者が戻り次第、折り返しお電話いたします。', reading: 'たんとうしゃ が もどり しだい、 おりかえし おでんわ いたします。', en: 'We will call you back as soon as the person in charge returns.' } },
      { id: 'v-ja-n2-04-05', text: '後ほど', reading: 'のちほど', en: 'later (polite)', pos: 'adverb', example: { text: 'では、後ほど改めてご連絡いたします。', reading: 'で は、 のちほど あらためて ごれんらく いたします。', en: "Then I'll get in touch with you again later." } },
      { id: 'v-ja-n2-04-06', text: '恐縮', reading: 'きょうしゅく', en: 'feeling obliged; sorry for the trouble (恐縮です)', pos: 'noun', example: { text: 'お忙しいところ恐縮ですが、ご確認をお願いいたします。', reading: 'おいそがしい ところ きょうしゅく です が、 ごかくにん を おねがい いたします。', en: "I'm sorry to trouble you when you're busy, but please check this." } },
      { id: 'v-ja-n2-04-07', text: '了承', reading: 'りょうしょう', en: 'understanding; acknowledgment (ご了承ください = please note)', pos: 'noun', example: { text: '予告なく変更する場合がありますので、ご了承ください。', reading: 'よこく なく へんこう する ばあい が あります ので、 ごりょうしょう ください。', en: 'Please note that changes may be made without notice.' } },
      { id: 'v-ja-n2-04-08', text: '先方', reading: 'せんぽう', en: 'the other party (in a deal)', pos: 'noun', example: { text: '先方の希望を確認してから返事をします。', reading: 'せんぽう の きぼう を かくにん して から へんじ を します。', en: "I'll reply after confirming what the other party wants." } },
      { id: 'v-ja-n2-04-09', text: '見積もり', reading: 'みつもり', en: 'estimate; quote', pos: 'noun', example: { text: '来週までに見積もりをお送りします。', reading: 'らいしゅう まで に みつもり を おおくり します。', en: "We'll send you a quote by next week." } },
      { id: 'v-ja-n2-04-10', text: '納期', reading: 'のうき', en: 'delivery date; deadline', pos: 'noun', example: { text: '納期に間に合うよう、全力を尽くします。', reading: 'のうき に まにあう よう、 ぜんりょく を つくします。', en: "We'll do our utmost to meet the delivery date." } },
      { id: 'v-ja-n2-04-11', text: '承知する', reading: 'しょうち する', en: 'to understand; to acknowledge (承知しました = certainly)', pos: 'verb', example: { text: '承知いたしました。すぐに手配いたします。', reading: 'しょうち いたしました。 すぐ に てはい いたします。', en: "Certainly. I'll arrange it right away." } },
      { id: 'v-ja-n2-04-12', text: '何卒', reading: 'なにとぞ', en: 'kindly; please (very formal)', pos: 'adverb', example: { text: '何卒よろしくお願い申し上げます。', reading: 'なにとぞ よろしく おねがい もうしあげます。', en: 'Thank you very much for your kind consideration.' } },
      { id: 'v-ja-n2-04-13', text: '差し支える', reading: 'さしつかえる', en: 'to be a problem (差し支えなければ = if you don’t mind)', pos: 'verb', example: { text: '差し支えなければ、ご連絡先を教えていただけますか。', reading: 'さしつかえなければ、 ごれんらくさき を おしえて いただけます か。', en: 'If you don’t mind, could you give me your contact details?' } },
      { id: 'v-ja-n2-04-14', text: '御社', reading: 'おんしゃ', en: 'your company (spoken, respectful)', pos: 'noun', example: { text: '来週、御社に伺ってもよろしいでしょうか。', reading: 'らいしゅう、 おんしゃ に うかがって も よろしい でしょう か。', en: 'Would it be all right if I visited your company next week?' } },
      { id: 'v-ja-n2-04-15', text: '弊社', reading: 'へいしゃ', en: 'our company (humble)', pos: 'noun', example: { text: '弊社の新製品をご紹介いたします。', reading: 'へいしゃ の しんせいひん を ごしょうかい いたします。', en: "Allow me to introduce our company's new product." } },
      { id: 'v-ja-n2-04-16', text: '添付する', reading: 'てんぷ する', en: 'to attach (a file)', pos: 'verb', example: { text: '資料を添付いたしましたので、ご確認ください。', reading: 'しりょう を てんぷ いたしました ので、 ごかくにん ください。', en: "I've attached the documents, so please take a look." } },
    ],
    scenario: {
      title: 'Rescheduling a client meeting',
      setting: "You work at a Tokyo trading company. A shipping problem means you can't make Thursday's meeting with a client, so you phone their office to reschedule.",
      aiRole: 'Hiroshi Kimura (木村浩), purchasing manager at the client company, Hoshino Industries (星野工業)',
      learnerGoal: 'Introduce yourself and your company properly, apologize and explain why you need to reschedule, propose two alternative dates, and close the call with the right set phrases.',
      opener: 'お電話ありがとうございます。星野工業、購買部の木村でございます。',
      openerReading: 'おでんわ ありがとう ございます。 ほしのこうぎょう、 こうばいぶ の きむら で ございます。',
    },
  },

  // ───────────────────────────── N1 (C1) ─────────────────────────────
  {
    id: 'ja-n1-01',
    cefr: 'C1',
    order: 33,
    title: '硬い表現: Formal and literary expressions',
    theme: 'Ceremonial and literary expressions for speeches and formal writing',
    canDo: [
      'I can mark an official end point or a means with 〜をもって, and describe reaching an outcome or extreme with 〜に至る.',
      'I can single out the only fitting person or thing with 〜をおいて〜ない.',
      'I can praise what is unique to someone, say what is worthy of something, and express deep emotion with 〜ならでは, 〜に足る, and 〜に堪えない.',
    ],
    grammar: [
      {
        id: 'g-ja-n1-01-1',
        title: '〜をもって, 〜に至る, 〜をおいて',
        summary:
          "〜をもって (polite: 〜をもちまして) is used in ceremonies and official notices in two ways: to mark the point when something ends or begins (本日をもって閉店いたします, 'as of today') and to mark a means or basis (書面をもってお知らせします, 'by written notice'). 〜に至る (にいたる) means 'to reach, to lead to (an outcome)', and 〜に至るまで marks the far end of a range to stress how wide it is: 家具から食器に至るまで. 〜をおいて(ほかに)〜ない means 'no one/nothing but X' and singles X out as the only fitting choice, usually as praise: 彼をおいてほかにいない. All three belong to a stiff, written register; in everyday speech you would say 今日で, 〜まで, and 〜しかいない. Pitfall: をおいて must be followed by a negative (いない/ない), and time をもって is for official endings and starts, not casual deadlines.",
        examples: [
          { text: '本日をもちまして、当店は閉店いたします。', reading: 'ほんじつ を もちまして、 とうてん は へいてん いたします。', en: 'As of today, this store will close its doors.' },
          { text: '合否の結果は、書面をもってお知らせします。', reading: 'ごうひ の けっか は、 しょめん を もって おしらせ します。', en: 'You will be notified of the results in writing.' },
          { text: 'この店では、家具から食器に至るまで、すべて手作りだ。', reading: 'この みせ で は、 かぐ から しょっき に いたる まで、 すべて てづくり だ。', en: 'At this shop, everything from the furniture to the tableware is handmade.' },
          { text: '小さなミスが、大きな事故に至ることもある。', reading: 'ちいさな ミス が、 おおきな じこ に いたる こと も ある。', en: 'A small mistake can sometimes lead to a major accident.' },
          { text: '次の社長にふさわしいのは、山本さんをおいてほかにいない。', reading: 'つぎ の しゃちょう に ふさわしい の は、 やまもと さん を おいて ほか に いない。', en: 'There is no one but Ms. Yamamoto fit to be the next president.' },
        ],
        drills: [
          { text: '本日___、受付を終了いたします。', reading: 'ほんじつ ___、 うけつけ を しゅうりょう いたします。', en: 'Registration closes as of today.', answer: 'をもって', distractors: ['をおいて', 'にわたって', 'として'] },
          { text: 'この問題を解決できるのは、彼___ほかにいない。', reading: 'この もんだい を かいけつ できる の は、 かれ ___ ほか に いない。', en: 'There is no one but him who can solve this problem.', answer: 'をおいて', distractors: ['をもって', 'に至って', 'ならでは'] },
          { text: '話し合いを重ねた結果、ようやく合意___。', reading: 'はなしあい を かさねた けっか、 ようやく ごうい ___。', en: 'After repeated talks, they finally reached an agreement.', answer: 'に至った', distractors: ['をもった', 'をおいた', 'に足りた'] },
          { text: '赤ちゃんからお年寄りに___まで、誰でも楽しめるイベントです。', reading: 'あかちゃん から おとしより に ___ まで、 だれ でも たのしめる イベント です。', en: "It's an event everyone can enjoy, from babies to the elderly.", answer: '至る', distractors: ['もって', 'おいて', '足る'] },
          { text: '以上___、私の挨拶とさせていただきます。', reading: 'いじょう ___、 わたくし の あいさつ と させて いただきます。', en: 'With that, I conclude my remarks.', answer: 'をもちまして', distractors: ['をおきまして', 'に至りまして', 'にとりまして'] },
        ],
      },
      {
        id: 'g-ja-n1-01-2',
        title: '〜ならでは, 〜に足る, 〜に堪えない',
        summary:
          "Noun + ならではの + noun means 'unique to X, that only X can offer' and is always complimentary: 京都ならではの景色, プロならではの技術. Dictionary form (or a する-noun) + に足る (にたる) means 'worthy of, sufficient for': 信頼するに足る人物; its common negative 取るに足らない means 'trivial, not worth bothering about'. 〜に堪えない (にたえない) has two uses: after verbs like 見る or 聞く it means 'too awful to (watch/listen to)', as in 見るに堪えない, while after emotion nouns like 感謝の念 or 感激 it means 'I am overwhelmed with (gratitude)' in ceremonial speech: 感謝の念に堪えません. Pitfall: ならでは is never used for negative traits, and に足る and に堪えない belong to formal speech and writing; in conversation, 信頼できる and ひどくて見ていられない sound natural.",
        examples: [
          { text: 'これは地元の人ならではの楽しみ方だ。', reading: 'これ は じもと の ひと なら で は の たのしみかた だ。', en: 'This is a way of enjoying it that only locals know.' },
          { text: '彼は信頼するに足る人物だ。', reading: 'かれ は しんらい する に たる じんぶつ だ。', en: 'He is a person worthy of trust.' },
          { text: 'そんな取るに足らないことで悩む必要はない。', reading: 'そんな とる に たらない こと で なやむ ひつよう は ない。', en: "There's no need to worry over such a trivial thing." },
          { text: '最近の番組の中には、見るに堪えないものもある。', reading: 'さいきん の ばんぐみ の なか に は、 みる に たえない もの も ある。', en: 'Some recent TV programs are painful to watch.' },
          { text: '皆様の温かいご支援に対し、感謝の念に堪えません。', reading: 'みなさま の あたたかい ごしえん に たいし、 かんしゃ の ねん に たえません。', en: 'I cannot thank you all enough for your warm support.' },
        ],
        drills: [
          { text: '雪国___冬の祭りを楽しんだ。', reading: 'ゆきぐに ___ ふゆ の まつり を たのしんだ。', en: 'We enjoyed a winter festival unique to snow country.', answer: 'ならではの', distractors: ['に足る', 'に堪えない', 'をおいて'] },
          { text: '彼の説明は、信用する___ものではなかった。', reading: 'かれ の せつめい は、 しんよう する ___ もの で は なかった。', en: 'His explanation was not worth believing.', answer: 'に足る', distractors: ['ならではの', 'に堪えない', 'をもって'] },
          { text: '二人の言い争いは、聞く___ほどひどかった。', reading: 'ふたり の いいあらそい は、 きく ___ ほど ひどかった。', en: 'The quarrel between the two was so nasty it was unbearable to listen to.', answer: 'に堪えない', distractors: ['に足る', 'ならではの', 'をおいて'] },
          { text: '長年のご指導に対し、感謝の念に___。', reading: 'ながねん の ごしどう に たいし、 かんしゃ の ねん に ___。', en: 'I am deeply grateful for your many years of guidance.', answer: '堪えません', distractors: ['足りません', '至りません', 'もちません'] },
          { text: 'そんな___ことは気にしないでください。', reading: 'そんな ___ こと は き に しないで ください。', en: "Please don't worry about such a trivial thing.", answer: '取るに足らない', distractors: ['取るに堪えない', '取るならではの', '取るに至らない'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n1-01-01', text: '送別会', reading: 'そうべつかい', en: 'farewell party', pos: 'noun', example: { text: '部長の送別会で挨拶をすることになった。', reading: 'ぶちょう の そうべつかい で あいさつ を する こと に なった。', en: "I've been asked to give a speech at the department head's farewell party." } },
      { id: 'v-ja-n1-01-02', text: '退職', reading: 'たいしょく', en: 'retirement; leaving a job (退職する = to retire)', pos: 'noun', example: { text: '父は今年の三月で退職した。', reading: 'ちち は ことし の さんがつ で たいしょく した。', en: 'My father retired this March.' } },
      { id: 'v-ja-n1-01-03', text: '在職', reading: 'ざいしょく', en: 'being in office; time at a job', pos: 'noun', example: { text: '在職中は大変お世話になりました。', reading: 'ざいしょくちゅう は たいへん おせわ に なりました。', en: 'Thank you so much for all your help during my time here.' } },
      { id: 'v-ja-n1-01-04', text: '惜しむ', reading: 'おしむ', en: 'to regret (losing); to be sorry to part with', pos: 'verb', example: { text: '多くの人が彼の退職を惜しんだ。', reading: 'おおく の ひと が かれ の たいしょく を おしんだ。', en: 'Many people were sorry to see him retire.' } },
      { id: 'v-ja-n1-01-05', text: '恩', reading: 'おん', en: 'debt of gratitude; kindness received', pos: 'noun', example: { text: '先生から受けた恩は一生忘れません。', reading: 'せんせい から うけた おん は いっしょう わすれません。', en: 'I will never forget the kindness my teacher showed me.' } },
      { id: 'v-ja-n1-01-06', text: '携わる', reading: 'たずさわる', en: 'to be involved in; to work in (a field)', pos: 'verb', example: { text: '三十年間、教育に携わってきた。', reading: 'さんじゅうねんかん、 きょういく に たずさわって きた。', en: "I've worked in education for thirty years." } },
      { id: 'v-ja-n1-01-07', text: '歩み', reading: 'あゆみ', en: 'course; history; progress', pos: 'noun', example: { text: '創業から百年の歩みを一冊の本にまとめた。', reading: 'そうぎょう から ひゃくねん の あゆみ を いっさつ の ほん に まとめた。', en: "They put the company's hundred-year history into a single book." } },
      { id: 'v-ja-n1-01-08', text: '振り返る', reading: 'ふりかえる', en: 'to look back on', pos: 'verb', example: { text: 'この十年を振り返ると、多くの出会いがあった。', reading: 'この じゅうねん を ふりかえる と、 おおく の であい が あった。', en: 'Looking back on these ten years, I have met so many people.' } },
      { id: 'v-ja-n1-01-09', text: '門出', reading: 'かどで', en: 'a new start; setting out in life', pos: 'noun', example: { text: '新しい門出を心からお祝い申し上げます。', reading: 'あたらしい かどで を こころ から おいわい もうしあげます。', en: 'I sincerely congratulate you on your new start.' } },
      { id: 'v-ja-n1-01-10', text: '尽力', reading: 'じんりょく', en: 'great effort; dedicated service', pos: 'noun', example: { text: '長年にわたるご尽力に、心より感謝いたします。', reading: 'ながねん に わたる ごじんりょく に、 こころ より かんしゃ いたします。', en: 'I am truly grateful for your many years of dedicated work.' } },
      { id: 'v-ja-n1-01-11', text: '功績', reading: 'こうせき', en: 'achievement; contribution', pos: 'noun', example: { text: '彼の功績は社内で高く評価されている。', reading: 'かれ の こうせき は しゃない で たかく ひょうか されて いる。', en: 'His achievements are highly regarded within the company.' } },
      { id: 'v-ja-n1-01-12', text: '名残惜しい', reading: 'なごりおしい', en: 'sad to part; reluctant to say goodbye', pos: 'adjective', example: { text: '皆さんとお別れするのは名残惜しいです。', reading: 'みなさん と おわかれ する の は なごりおしい です。', en: "I'm sad to be saying goodbye to you all." } },
      { id: 'v-ja-n1-01-13', text: '感無量', reading: 'かんむりょう', en: 'being deeply moved (感無量です = I’m overwhelmed)', pos: 'noun', example: { text: '皆さんからの温かい言葉に、感無量です。', reading: 'みなさん から の あたたかい ことば に、 かんむりょう です。', en: "I'm overwhelmed by everyone's kind words." } },
      { id: 'v-ja-n1-01-14', text: '糧', reading: 'かて', en: 'nourishment; something that sustains you', pos: 'noun', example: { text: 'ここでの経験を糧に、これからも頑張ります。', reading: 'ここ で の けいけん を かて に、 これから も がんばります。', en: "Drawing strength from my experience here, I'll keep doing my best." } },
      { id: 'v-ja-n1-01-15', text: '健勝', reading: 'けんしょう', en: 'good health (formal, as ご健勝)', pos: 'noun', example: { text: '皆様のご健勝をお祈り申し上げます。', reading: 'みなさま の ごけんしょう を おいのり もうしあげます。', en: 'I wish you all good health.' } },
      { id: 'v-ja-n1-01-16', text: '志', reading: 'こころざし', en: 'aspiration; resolve', pos: 'noun', example: { text: '入社したときの志を忘れずに頑張ってください。', reading: 'にゅうしゃ した とき の こころざし を わすれず に がんばって ください。', en: 'Keep at it and never forget the aspirations you had when you joined the company.' } },
    ],
    scenario: {
      title: 'A farewell speech',
      setting: 'In a hotel banquet room in Osaka, your department is holding a farewell party for Mr. Ishikawa, the department head (部長), who is retiring after 35 years. You worked under him for three years and have been asked to give a speech.',
      aiRole: 'Naoko Fujita (藤田直子), a manager in your department acting as emcee, who introduces you and reacts to your speech',
      learnerGoal: 'Give a short formal farewell speech: thank Mr. Ishikawa using at least one ceremonial expression (〜をもって, 〜ならでは, or 〜に堪えない), mention a specific memory or achievement, and close by wishing him good health.',
      opener: '続きまして、三年間石川部長のもとで働いてきた方から、送別のご挨拶をいただきます。どうぞよろしくお願いいたします。',
      openerReading: 'つづきまして、 さんねんかん いしかわ ぶちょう の もと で はたらいて きた かた から、 そうべつ の ごあいさつ を いただきます。 どうぞ よろしく おねがい いたします。',
    },
  },
  {
    id: 'ja-n1-02',
    cefr: 'C1',
    order: 34,
    title: '微妙なニュアンス: Subtle concession',
    theme: 'Conceding, contrasting, and explaining circumstances in a local controversy',
    canDo: [
      'I can concede a point while adding a reservation with 〜ものの, 〜とはいえ, and 〜ながらも, choosing the right nuance.',
      'I can say something happened despite, or in disregard of, something else with 〜にもかかわらず and 〜をよそに.',
      'I can explain that an unusual situation arose because of special circumstances with 〜とあって.',
    ],
    grammar: [
      {
        id: 'g-ja-n1-02-1',
        title: '〜ものの, 〜とはいえ, 〜ながらも',
        summary:
          "〜ものの, 〜とはいえ, and 〜ながらも all translate as 'although', but differ in nuance. 〜ものの (plain form; nouns and な-adjectives + である) admits a fact and then says the expected next step didn't follow, often with a hint of regret: 免許は取ったものの、ほとんど運転していない. 〜とはいえ (plain form; nouns and な-adjectives can attach directly) grants a generally accepted point and then qualifies it, 'granted that…, still', and can also open a sentence as a conjunction: 春とはいえ、まだ寒い / とはいえ、課題は多い. 〜ながらも (ます-stem, い-adjective, or noun/な-adjective stem) contrasts two simultaneous states of the same subject and appears in set phrases such as 狭いながらも楽しい我が家 and 残念ながら. Pitfall: all three sound bookish in casual talk (use けど there), and because they introduce statements of fact, they don't sit well before commands or requests.",
        examples: [
          { text: '説明書を読んだものの、使い方がよく分からなかった。', reading: 'せつめいしょ を よんだ ものの、 つかいかた が よく わからなかった。', en: "Although I read the manual, I didn't really understand how to use it." },
          { text: '引き受けたものの、本当にできるかどうか不安だ。', reading: 'ひきうけた ものの、 ほんとう に できる か どう か ふあん だ。', en: "I said yes, but I'm worried whether I can really do it." },
          { text: '四月とはいえ、夜はまだ寒い。', reading: 'しがつ と は いえ、 よる は まだ さむい。', en: "It may be April, but it's still cold at night." },
          { text: '子どもとはいえ、自分の行動には責任を持つべきだ。', reading: 'こども と は いえ、 じぶん の こうどう に は せきにん を もつ べき だ。', en: 'Children though they are, they should take responsibility for their actions.' },
          { text: '彼は体が小さいながらも、力強いプレーを見せた。', reading: 'かれ は からだ が ちいさい ながら も、 ちからづよい プレー を みせた。', en: 'Small as he is, he played with real power.' },
        ],
        drills: [
          { text: '新しいパソコンを買った___、まだ一度も使っていない。', reading: 'あたらしい パソコン を かった ___、 まだ いちど も つかって いない。', en: "Although I bought a new computer, I still haven't used it once.", answer: 'ものの', distractors: ['ながらも', 'からこそ', 'とあって'] },
          { text: '春___、朝晩はまだ冷える。', reading: 'はる ___、 あさばん は まだ ひえる。', en: 'It may be spring, but mornings and evenings are still chilly.', answer: 'とはいえ', distractors: ['ものの', 'とあって', 'だけに'] },
          { text: '狭い___、日当たりのいい部屋だ。', reading: 'せまい ___、 ひあたり の いい へや だ。', en: "Though small, it's a sunny room.", answer: 'ながらも', distractors: ['とあって', 'からこそ', 'だけあって'] },
          { text: '残念___、今回は参加できません。', reading: 'ざんねん ___、 こんかい は さんか できません。', en: "Unfortunately, I can't take part this time.", answer: 'ながら', distractors: ['ものの', 'とあって', 'にもかかわらず'] },
          { text: '大きな進歩があった。___、課題はまだ多い。', reading: 'おおきな しんぽ が あった。 ___、 かだい は まだ おおい。', en: 'There has been great progress. That said, many issues remain.', answer: 'とはいえ', distractors: ['ものの', 'ながらも', 'とあって'] },
        ],
      },
      {
        id: 'g-ja-n1-02-2',
        title: '〜にもかかわらず, 〜をよそに, 〜とあって',
        summary:
          "〜にもかかわらず (plain form or noun; nouns and な-adjectives may take である) means 'despite' and neutrally states that a result runs against expectation: 雨にもかかわらず、大勢の人が集まった. Noun + をよそに means 'ignoring, paying no heed to' other people's worries, opposition, or expectations, and carries a critical or dramatic tone: 親の心配をよそに、彼は一人で旅立った. 〜とあって (plain form or noun) means 'since it is (a special occasion)' and presents an unusual scene as natural under the circumstances, which makes it a favorite of news reports: 連休とあって、観光地はどこも混雑している. Pitfall: をよそに needs a noun for people's feelings or reactions (心配, 反対, 批判, 期待), not a simple obstacle like 雨, and とあって describes observed situations, so it isn't followed by the speaker's own requests or intentions.",
        examples: [
          { text: '大雨にもかかわらず、試合は予定どおり行われた。', reading: 'おおあめ に も かかわらず、 しあい は よていどおり おこなわれた。', en: 'Despite the heavy rain, the match went ahead as scheduled.' },
          { text: '何度も注意したにもかかわらず、同じミスが繰り返された。', reading: 'なんど も ちゅうい した に も かかわらず、 おなじ ミス が くりかえされた。', en: 'Despite repeated warnings, the same mistake was made again.' },
          { text: '住民の反対をよそに、工事が始まった。', reading: 'じゅうみん の はんたい を よそ に、 こうじ が はじまった。', en: "Construction began, ignoring the residents' opposition." },
          { text: '親の心配をよそに、娘は一人で海外へ旅立った。', reading: 'おや の しんぱい を よそ に、 むすめ は ひとり で かいがい へ たびだった。', en: "Paying no heed to her parents' worries, the daughter set off abroad alone." },
          { text: '人気歌手が来るとあって、会場は若者でいっぱいだった。', reading: 'にんきかしゅ が くる と あって、 かいじょう は わかもの で いっぱい だった。', en: 'With a popular singer coming, the venue was packed with young people.' },
        ],
        drills: [
          { text: '平日___、店は大勢の客でにぎわっていた。', reading: 'へいじつ ___、 みせ は おおぜい の きゃく で にぎわって いた。', en: 'Despite it being a weekday, the shop was bustling with customers.', answer: 'にもかかわらず', distractors: ['とあって', 'をよそに', 'だけあって'] },
          { text: '周囲の期待___、彼は音楽の道に進んだ。', reading: 'しゅうい の きたい ___、 かれ は おんがく の みち に すすんだ。', en: 'Paying no heed to what everyone around him expected, he chose a career in music.', answer: 'をよそに', distractors: ['とあって', 'ならではの', 'に応えて'] },
          { text: '年末___、駅は帰省する人で混雑している。', reading: 'ねんまつ ___、 えき は きせい する ひと で こんざつ して いる。', en: "With it being the end of the year, the station is crowded with people heading to their hometowns.", answer: 'とあって', distractors: ['にもかかわらず', 'をよそに', 'とはいえ'] },
          { text: '十分に準備した___、結果は思わしくなかった。', reading: 'じゅうぶん に じゅんび した ___、 けっか は おもわしく なかった。', en: 'Despite thorough preparation, the results were disappointing.', answer: 'にもかかわらず', distractors: ['とあって', 'をよそに', 'からこそ'] },
          { text: '初めての日本公演___、ファンの興奮は最高潮に達した。', reading: 'はじめて の にほん こうえん ___、 ファン の こうふん は さいこうちょう に たっした。', en: "Since it was the band's first concert in Japan, the fans' excitement reached a peak.", answer: 'とあって', distractors: ['にもかかわらず', 'をよそに', 'ながらも'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n1-02-01', text: '賛否', reading: 'さんぴ', en: 'approval or disapproval; for and against', pos: 'noun', example: { text: '新しい条例をめぐって、賛否が分かれている。', reading: 'あたらしい じょうれい を めぐって、 さんぴ が わかれて いる。', en: 'Opinion is divided over the new ordinance.' } },
      { id: 'v-ja-n1-02-02', text: '条例', reading: 'じょうれい', en: 'local ordinance; bylaw', pos: 'noun', example: { text: '市は路上喫煙を禁止する条例を定めた。', reading: 'し は ろじょうきつえん を きんし する じょうれい を さだめた。', en: 'The city passed an ordinance banning smoking on the street.' } },
      { id: 'v-ja-n1-02-03', text: '自治体', reading: 'じちたい', en: 'local government; municipality', pos: 'noun', example: { text: '多くの自治体が観光税の導入を検討している。', reading: 'おおく の じちたい が かんこうぜい の どうにゅう を けんとう して いる。', en: 'Many municipalities are considering introducing a tourist tax.' } },
      { id: 'v-ja-n1-02-04', text: '撤回', reading: 'てっかい', en: 'withdrawal; retraction (撤回する = to withdraw)', pos: 'noun', example: { text: '市長は批判を受けて、発言を撤回した。', reading: 'しちょう は ひはん を うけて、 はつげん を てっかい した。', en: 'Facing criticism, the mayor retracted his remarks.' } },
      { id: 'v-ja-n1-02-05', text: '妥協', reading: 'だきょう', en: 'compromise (妥協する = to compromise)', pos: 'noun', example: { text: 'お互いに少しずつ妥協する必要がある。', reading: 'おたがい に すこし ずつ だきょう する ひつよう が ある。', en: 'Both sides need to compromise a little.' } },
      { id: 'v-ja-n1-02-06', text: '懸念', reading: 'けねん', en: 'concern; apprehension (懸念する = to be concerned)', pos: 'noun', example: { text: '観光客の増加による騒音を懸念する声もある。', reading: 'かんこうきゃく の ぞうか に よる そうおん を けねん する こえ も ある。', en: 'Some people are concerned about noise from the rise in tourists.' } },
      { id: 'v-ja-n1-02-07', text: '是非', reading: 'ぜひ', en: 'right or wrong; the merits (of an issue)', pos: 'noun', example: { text: 'カジノ誘致の是非を問う住民投票が行われた。', reading: 'カジノ ゆうち の ぜひ を とう じゅうみんとうひょう が おこなわれた。', en: 'A local referendum was held on whether to bring in a casino.' } },
      { id: 'v-ja-n1-02-08', text: '異議', reading: 'いぎ', en: 'objection', pos: 'noun', example: { text: 'その決定に異議を唱える人は少なくなかった。', reading: 'その けってい に いぎ を となえる ひと は すくなく なかった。', en: 'Quite a few people objected to the decision.' } },
      { id: 'v-ja-n1-02-09', text: '強行する', reading: 'きょうこう する', en: 'to force through; to push ahead with', pos: 'verb', example: { text: '市は反対を押し切って、計画を強行した。', reading: 'し は はんたい を おしきって、 けいかく を きょうこう した。', en: 'The city overrode the opposition and forced the plan through.' } },
      { id: 'v-ja-n1-02-10', text: '譲歩', reading: 'じょうほ', en: 'concession (譲歩する = to make concessions)', pos: 'noun', example: { text: '交渉の末、会社側が大幅に譲歩した。', reading: 'こうしょう の すえ、 かいしゃがわ が おおはば に じょうほ した。', en: 'After negotiations, the company made major concessions.' } },
      { id: 'v-ja-n1-02-11', text: '根拠', reading: 'こんきょ', en: 'grounds; basis; evidence', pos: 'noun', example: { text: 'その主張には科学的な根拠がない。', reading: 'その しゅちょう に は かがくてき な こんきょ が ない。', en: 'That claim has no scientific basis.' } },
      { id: 'v-ja-n1-02-12', text: '一理ある', reading: 'いちり ある', en: 'to have a point', pos: 'phrase', example: { text: '確かに、彼の意見にも一理ある。', reading: 'たしか に、 かれ の いけん に も いちり ある。', en: 'Admittedly, his opinion has a point too.' } },
      { id: 'v-ja-n1-02-13', text: '両立', reading: 'りょうりつ', en: 'achieving both; balancing (両立する = to be compatible)', pos: 'noun', example: { text: '経済発展と環境保護を両立させるのは難しい。', reading: 'けいざいはってん と かんきょうほご を りょうりつ させる の は むずかしい。', en: 'It is hard to achieve both economic development and environmental protection.' } },
      { id: 'v-ja-n1-02-14', text: '憤り', reading: 'いきどおり', en: 'indignation; resentment', pos: 'noun', example: { text: '説明のないまま決定されたことに、住民は強い憤りを感じている。', reading: 'せつめい の ない まま けってい された こと に、 じゅうみん は つよい いきどおり を かんじて いる。', en: 'Residents are deeply indignant that it was decided without any explanation.' } },
      { id: 'v-ja-n1-02-15', text: '踏まえる', reading: 'ふまえる', en: 'to take into account; to build on', pos: 'verb', example: { text: '住民の意見を踏まえて、計画を見直すべきだ。', reading: 'じゅうみん の いけん を ふまえて、 けいかく を みなおす べき だ。', en: "The plan should be revised in light of residents' opinions." } },
      { id: 'v-ja-n1-02-16', text: '白紙', reading: 'はくし', en: 'blank slate (白紙に戻す = to scrap and start over)', pos: 'noun', example: { text: '反対が多かったため、計画は白紙に戻された。', reading: 'はんたい が おおかった ため、 けいかく は はくし に もどされた。', en: 'Because of strong opposition, the plan was scrapped and sent back to square one.' } },
    ],
    scenario: {
      title: 'The lakeside resort debate',
      setting: "Your town in Nagano has approved a large resort hotel by the lake despite many residents' objections. After a meeting at the community center, you discuss the decision with a neighbor who supports it.",
      aiRole: 'Shigeru Matsuda (松田茂), a local shop owner in his sixties who believes the resort will revive the town',
      learnerGoal: "State your position on the decision, concede one of Mr. Matsuda's points using 〜とはいえ or 〜ものの, criticize how the decision was made using 〜にもかかわらず or 〜をよそに, and propose a compromise.",
      opener: '反対の声も多かったものの、リゾート計画はついに決まりましたね。私は町のためにはいいことだと思っていますが、あなたはどうですか。',
      openerReading: 'はんたい の こえ も おおかった ものの、 リゾート けいかく は ついに きまりました ね。 わたし は まち の ため に は いい こと だ と おもって います が、 あなた は どう です か。',
    },
  },
  {
    id: 'ja-n1-03',
    cefr: 'C1',
    order: 35,
    title: '議論する: Debate and persuasion',
    theme: 'Arguing a case formally: resolve, purpose, and rebuttal',
    canDo: [
      'I can state firm negative resolve or negative conjecture with 〜まい.',
      'I can express a strong purpose in formal language with 〜べく and 〜んがため.',
      'I can rebut overgeneralizations and argue for a minimum or an extreme with 〜からといって, 〜ないまでも, and 〜はおろか.',
    ],
    grammar: [
      {
        id: 'g-ja-n1-03-1',
        title: '〜まい, 〜んがため, 〜べく',
        summary:
          "〜まい is a literary negative with two meanings: firm negative resolve, 'I will never…' (二度と失敗はするまい), and negative conjecture, 'probably won't' (彼はもう来るまい). It follows the dictionary form of group 1 verbs (行くまい); group 2 verbs take either the dictionary form or the stem (食べるまい / 食べまい), and する and 来る usually become するまい and 来るまい. 〜べく (dictionary form; する → すべく or するべく) means 'in order to' and suggests a purposeful, effortful action: 夢を実現すべく努力する. 〜んがため(に) (ない-stem + んがため, with する → せんがため) is even more archaic and emphatic, 'for the sole purpose of', and often implies going to extremes: 勝たんがために手段を選ばない. Pitfall: neither べく nor んがため can be followed by a request or command (×合格すべく、勉強しなさい), and both sound stilted in conversation, where ために is the norm.",
        examples: [
          { text: 'あんな失敗は二度とするまいと心に決めた。', reading: 'あんな しっぱい は にど と する まい と こころ に きめた。', en: 'I made up my mind never to make a mistake like that again.' },
          { text: 'この雨では、彼はもう来るまい。', reading: 'この あめ で は、 かれ は もう くる まい。', en: "In this rain, he probably won't come now." },
          { text: '最新の情報を得るべく、専門家に話を聞いた。', reading: 'さいしん の じょうほう を える べく、 せんもんか に はなし を きいた。', en: 'To get the latest information, I interviewed experts.' },
          { text: '彼は夢を実現すべく、会社を辞めて留学した。', reading: 'かれ は ゆめ を じつげん すべく、 かいしゃ を やめて りゅうがく した。', en: 'To realize his dream, he quit his job and went to study abroad.' },
          { text: '生きんがために、彼はどんな仕事でも引き受けた。', reading: 'いきん が ため に、 かれ は どんな しごと でも ひきうけた。', en: 'Simply to survive, he took on any work at all.' },
        ],
        drills: [
          { text: '二度と同じ過ちは繰り返す___と誓った。', reading: 'にど と おなじ あやまち は くりかえす ___ と ちかった。', en: 'I vowed never to repeat the same mistake.', answer: 'まい', distractors: ['べく', 'んがため', 'べき'] },
          { text: '顧客の信頼を取り戻す___、全社員が努力している。', reading: 'こきゃく の しんらい を とりもどす ___、 ぜんしゃいん が どりょく して いる。', en: "Every employee is working hard to win back customers' trust.", answer: 'べく', distractors: ['まい', 'べき', 'んがため'] },
          { text: '試験に合格せ___ために、彼は寝る時間も惜しんで勉強した。', reading: 'しけん に ごうかく せ ___ ため に、 かれ は ねる じかん も おしんで べんきょう した。', en: 'With the sole aim of passing the exam, he studied so hard he even begrudged himself sleep.', answer: 'んが', distractors: ['ず', 'まい', 'べく'] },
          { text: 'あの頑固な父のことだから、そう簡単には許す___。', reading: 'あの がんこ な ちち の こと だ から、 そう かんたん に は ゆるす ___。', en: "Knowing how stubborn my father is, he probably won't forgive me that easily.", answer: 'まい', distractors: ['べく', 'べき', 'まま'] },
          { text: '社会の変化に対応す___、制度の見直しが進められている。', reading: 'しゃかい の へんか に たいおう す ___、 せいど の みなおし が すすめられて いる。', en: 'The system is being reviewed in order to respond to changes in society.', answer: 'べく', distractors: ['べき', 'んがため', 'ずに'] },
        ],
      },
      {
        id: 'g-ja-n1-03-2',
        title: '〜からといって, 〜ないまでも, 〜はおろか',
        summary:
          "〜からといって (plain form) is followed by a negative conclusion and means 'just because X doesn't mean Y'; it is the standard way to rebut a hasty generalization, often ending in 〜とは限らない or 〜わけではない: 安いからといって、品質が悪いとは限らない. 〜ないまでも means 'even if not (as far as) X, at least Y' and lowers the bar from an ideal to a minimum, typically followed by せめて, 〜べきだ, or 〜たい: 毎日とは言わないまでも、週に一度は運動したい. X はおろか Y も/さえ/まで means 'let alone X, (not even) Y': X is the obvious, bigger case and Y the more basic one, usually in a negative sentence expressing surprise or dismay: 漢字はおろか、ひらがなも読めない. Pitfall: はおろか is emotional and negative, so for a neutral or positive 'not only… but also' use 〜はもちろん (英語はもちろん、中国語も話せる). In a debate, からといって attacks the opponent's logic, while ないまでも offers a realistic compromise.",
        examples: [
          { text: '留学したからといって、必ず外国語が上手になるわけではない。', reading: 'りゅうがく した から と いって、 かならず がいこくご が じょうず に なる わけ で は ない。', en: "Just because you study abroad doesn't mean you'll definitely become good at a foreign language." },
          { text: '便利だからといって、何でも人工知能に任せるのは危険だ。', reading: 'べんり だ から と いって、 なんでも じんこうちのう に まかせる の は きけん だ。', en: "Convenient as it may be, it's dangerous to leave everything to AI." },
          { text: '満点とは言わないまでも、合格点は取りたい。', reading: 'まんてん と は いわない まで も、 ごうかくてん は とりたい。', en: "I won't say a perfect score, but I'd at least like a passing grade." },
          { text: '謝罪はしないまでも、説明くらいはするべきだ。', reading: 'しゃざい は しない まで も、 せつめい くらい は する べき だ。', en: "Even if they won't apologize, they should at least give an explanation." },
          { text: '忙しくて、旅行はおろか、週末に休むこともできない。', reading: 'いそがしくて、 りょこう は おろか、 しゅうまつ に やすむ こと も できない。', en: "I'm so busy I can't even rest on weekends, let alone travel." },
        ],
        drills: [
          { text: '一度成功した___、油断してはいけない。', reading: 'いちど せいこう した ___、 ゆだん して は いけない。', en: "Just because you succeeded once doesn't mean you can let your guard down.", answer: 'からといって', distractors: ['ないまでも', 'はおろか', 'とあって'] },
          { text: '毎日とは言わ___、週に数回は運動しよう。', reading: 'まいにち と は いわ ___、 しゅう に すうかい は うんどう しよう。', en: "I won't say every day, but let's exercise at least a few times a week.", answer: 'ないまでも', distractors: ['ないからといって', 'ないばかりか', 'ないとあって'] },
          { text: '彼は小説___、新聞さえ読まない。', reading: 'かれ は しょうせつ ___、 しんぶん さえ よまない。', en: "He doesn't even read newspapers, let alone novels.", answer: 'はおろか', distractors: ['からといって', 'ないまでも', 'とはいえ'] },
          { text: '優勝は___までも、せめて決勝には進みたい。', reading: 'ゆうしょう は ___ まで も、 せめて けっしょう に は すすみたい。', en: "Even if we can't win the championship, I at least want to reach the final.", answer: 'できない', distractors: ['できる', 'できた', 'できず'] },
          { text: '日本人だ___、誰もが敬語を正しく使えるわけではない。', reading: 'にほんじん だ ___、 だれ も が けいご を ただしく つかえる わけ で は ない。', en: "Just because someone is Japanese doesn't mean they can use keigo correctly.", answer: 'からといって', distractors: ['ないまでも', 'はおろか', 'とあって'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n1-03-01', text: '人工知能', reading: 'じんこうちのう', en: 'artificial intelligence; AI', pos: 'noun', example: { text: '人工知能は教育の在り方を大きく変えつつある。', reading: 'じんこうちのう は きょういく の ありかた を おおきく かえつつ ある。', en: 'AI is dramatically changing the shape of education.' } },
      { id: 'v-ja-n1-03-02', text: '導入', reading: 'どうにゅう', en: 'introduction (of a system); adoption (導入する = to introduce)', pos: 'noun', example: { text: '来年度から、すべての学校でタブレットが導入されることになった。', reading: 'らいねんど から、 すべて の がっこう で タブレット が どうにゅう される こと に なった。', en: 'It has been decided that tablets will be introduced in every school from next school year.' } },
      { id: 'v-ja-n1-03-03', text: '弊害', reading: 'へいがい', en: 'harmful effect; drawback', pos: 'noun', example: { text: 'スマホに頼りすぎることの弊害も指摘されている。', reading: 'スマホ に たよりすぎる こと の へいがい も してき されて いる。', en: 'The harmful effects of relying too much on smartphones have also been pointed out.' } },
      { id: 'v-ja-n1-03-04', text: '恩恵', reading: 'おんけい', en: 'benefit; blessing', pos: 'noun', example: { text: '技術の進歩の恩恵を受けているのは、主に都市部の学生だ。', reading: 'ぎじゅつ の しんぽ の おんけい を うけて いる の は、 おもに としぶ の がくせい だ。', en: 'It is mainly students in cities who benefit from technological progress.' } },
      { id: 'v-ja-n1-03-05', text: '依存', reading: 'いぞん', en: 'dependence (依存する = to depend on)', pos: 'noun', example: { text: '学生が人工知能に依存しすぎることを心配する教師も多い。', reading: 'がくせい が じんこうちのう に いぞん しすぎる こと を しんぱい する きょうし も おおい。', en: 'Many teachers worry that students depend too much on AI.' } },
      { id: 'v-ja-n1-03-06', text: '思考力', reading: 'しこうりょく', en: 'ability to think; thinking skills', pos: 'noun', example: { text: '思考力を育てる教育が求められている。', reading: 'しこうりょく を そだてる きょういく が もとめられて いる。', en: 'There is demand for education that develops thinking skills.' } },
      { id: 'v-ja-n1-03-07', text: '反論', reading: 'はんろん', en: 'counterargument; rebuttal (反論する = to argue back)', pos: 'noun', example: { text: '彼の意見に対して、すぐに反論した。', reading: 'かれ の いけん に たいして、 すぐ に はんろん した。', en: 'I immediately argued against his opinion.' } },
      { id: 'v-ja-n1-03-08', text: '論点', reading: 'ろんてん', en: 'point at issue; the point of an argument', pos: 'noun', example: { text: '議論の論点がずれているように思います。', reading: 'ぎろん の ろんてん が ずれて いる よう に おもいます。', en: 'I think the discussion is drifting off the point.' } },
      { id: 'v-ja-n1-03-09', text: '説得力', reading: 'せっとくりょく', en: 'persuasiveness', pos: 'noun', example: { text: 'データを示すと、主張に説得力が増す。', reading: 'データ を しめす と、 しゅちょう に せっとくりょく が ます。', en: 'Showing data makes an argument more persuasive.' } },
      { id: 'v-ja-n1-03-10', text: '一概に', reading: 'いちがいに', en: 'across the board; as a sweeping generalization (with a negative)', pos: 'adverb', example: { text: '新しい技術が悪いとは一概には言えない。', reading: 'あたらしい ぎじゅつ が わるい と は いちがいに は いえない。', en: "You can't say across the board that new technology is bad." } },
      { id: 'v-ja-n1-03-11', text: '格差', reading: 'かくさ', en: 'gap; disparity', pos: 'noun', example: { text: '家庭の経済力による教育格差が広がっている。', reading: 'かてい の けいざいりょく に よる きょういくかくさ が ひろがって いる。', en: 'The education gap caused by differences in family income is widening.' } },
      { id: 'v-ja-n1-03-12', text: '不正', reading: 'ふせい', en: 'cheating; dishonesty; fraud', pos: 'noun', example: { text: 'レポートの不正を見抜くのは簡単ではない。', reading: 'レポート の ふせい を みぬく の は かんたん で は ない。', en: "It isn't easy to spot cheating on reports." } },
      { id: 'v-ja-n1-03-13', text: '見解', reading: 'けんかい', en: 'view; opinion (formal)', pos: 'noun', example: { text: 'この問題について、専門家の見解は分かれている。', reading: 'この もんだい に ついて、 せんもんか の けんかい は わかれて いる。', en: 'Experts are divided in their views on this issue.' } },
      { id: 'v-ja-n1-03-14', text: '補う', reading: 'おぎなう', en: 'to make up for; to supplement', pos: 'verb', example: { text: '教師不足を補うために、人工知能を活用する学校もある。', reading: 'きょうしぶそく を おぎなう ため に、 じんこうちのう を かつよう する がっこう も ある。', en: 'Some schools use AI to make up for a shortage of teachers.' } },
      { id: 'v-ja-n1-03-15', text: '活用する', reading: 'かつよう する', en: 'to make (good) use of', pos: 'verb', example: { text: '新しい技術をうまく活用すれば、学習の効率が上がる。', reading: 'あたらしい ぎじゅつ を うまく かつよう すれば、 がくしゅう の こうりつ が あがる。', en: 'If we make good use of new technology, learning becomes more efficient.' } },
      { id: 'v-ja-n1-03-16', text: '本末転倒', reading: 'ほんまつてんとう', en: 'putting the cart before the horse', pos: 'noun', example: { text: '道具に頼りすぎて考えなくなるのは本末転倒だ。', reading: 'どうぐ に たよりすぎて かんがえなく なる の は ほんまつてんとう だ。', en: 'Relying on tools so much that you stop thinking defeats the purpose.' } },
    ],
    scenario: {
      title: 'Debate: AI in the classroom',
      setting: "At a university seminar in Tokyo, students hold a formal debate on the motion 'Schools should actively use AI in teaching.' You argue against the motion.",
      aiRole: 'Rina Kobayashi (小林里奈), a sharp third-year student on the affirmative side who argues that AI tutors will close the education gap',
      learnerGoal: "Give two reasons against the motion, rebut Rina's main argument using 〜からといって, offer a realistic counterproposal with 〜ないまでも, and close with a persuasive summary.",
      opener: 'では、肯定側から始めます。人工知能を活用すれば、一人一人に合った学習が可能になり、教育格差を縮めることができます。この点について、否定側のご意見を伺いたいと思います。',
      openerReading: 'で は、 こうていがわ から はじめます。 じんこうちのう を かつよう すれば、 ひとりひとり に あった がくしゅう が かのう に なり、 きょういくかくさ を ちぢめる こと が できます。 この てん に ついて、 ひていがわ の ごいけん を うかがいたい と おもいます。',
    },
  },
];
