import type { Unit } from '../types';

/** Japanese units 2–6 (JLPT N5, part 1). */
export const unitsN5a: Unit[] = [
  // ───────────────────────────── N5 (A1) ─────────────────────────────
  {
    id: 'ja-n5-01',
    cefr: 'A1',
    order: 2,
    title: 'はじめまして: Introductions',
    theme: 'Introducing yourself, nationalities, and jobs',
    canDo: [
      'I can say my name, nationality, and job or school.',
      'I can say what I am not with じゃありません.',
      'I can ask yes/no questions with か and answer with はい or いいえ.',
      'I can use の to say things like "my name" and "a Japanese teacher".',
    ],
    grammar: [
      {
        id: 'g-ja-n5-01-1',
        title: 'X は Y です and じゃありません',
        summary:
          "The basic Japanese sentence is X は Y です (X wa Y desu), 'X is Y': 私は学生です (わたし は がくせい です, watashi wa gakusei desu) 'I'm a student.' は marks the topic, what you're talking about; as a particle it is pronounced wa, but it is always written は. です (desu) goes at the very end and makes the sentence polite; Japanese has no words for 'a' or 'the', and the topic is dropped when it's obvious: 学生です (がくせい です, gakusei desu) 'I'm a student.' For 'X is not Y', replace です with じゃありません (ja arimasen); ではありません (dewa arimasen) is a more formal version you'll see in writing. Add さん (san) after other people's names, as in 田中さん (たなか さん, Tanaka-san), but never after your own. Pitfall: じゃありません already does the job of です, so never add です after it.",
        examples: [
          { text: '私は学生です。', reading: 'わたし は がくせい です。', en: "I'm a student." },
          { text: '山田さんは先生です。', reading: 'やまだ さん は せんせい です。', en: 'Ms. Yamada is a teacher.' },
          { text: '私はアメリカ人です。', reading: 'わたし は アメリカじん です。', en: "I'm American." },
          { text: 'マリアさんは日本人じゃありません。', reading: 'マリア さん は にほんじん じゃ ありません。', en: "Maria isn't Japanese." },
          { text: '私は先生じゃありません。学生です。', reading: 'わたし は せんせい じゃ ありません。 がくせい です。', en: "I'm not a teacher. I'm a student." },
        ],
        drills: [
          { text: '山本さん___先生です。', reading: 'やまもと さん ___ せんせい です。', en: 'Mr. Yamamoto is a teacher.', answer: 'は', distractors: ['を', 'に', 'で'] },
          { text: '田中さんは学生___。', reading: 'たなか さん は がくせい ___。', en: "Mr. Tanaka isn't a student.", answer: 'じゃありません', distractors: ['です', 'ですか'] },
          { text: '私は日本人じゃ___。', reading: 'わたし は にほんじん じゃ ___。', en: "I'm not Japanese.", answer: 'ありません', distractors: ['です', 'あります'] },
          { text: 'エマさんは先生じゃありません。いしゃ___。', reading: 'エマ さん は せんせい じゃ ありません。 いしゃ ___。', en: "Emma isn't a teacher. She's a doctor.", answer: 'です', distractors: ['じゃありません', 'ですか'] },
          { text: 'はじめまして。リサ___。', reading: 'はじめまして。 リサ ___。', en: "Nice to meet you. I'm Lisa.", answer: 'です', distractors: ['は', 'か', 'の'] },
        ],
      },
      {
        id: 'g-ja-n5-01-2',
        title: 'Questions with か, and the particle の',
        summary:
          "To make a yes/no question, put か (ka) at the end of the sentence; the word order doesn't change: 学生ですか (がくせい です か, gakusei desu ka) 'Are you a student?' Questions in Japanese are often written with 。 instead of ？. Answer with はい (hai, yes) or いいえ (iie, no), often followed by そうです (sou desu, 'that's right') or ちがいます (chigaimasu, 'that's not right'). The particle の (no) joins two nouns: A の B means 'A's B' or 'B of A', so 私の名前 (わたし の なまえ, watashi no namae) is 'my name' and 日本語の先生 (にほんご の せんせい, nihongo no sensei) is 'a Japanese teacher'. Pitfall: the order is the reverse of English 'of', so the owner or describer always comes first.",
        examples: [
          { text: 'ケンさんは学生ですか。', reading: 'ケン さん は がくせい です か。', en: 'Is Ken a student?' },
          { text: 'はい、そうです。大学生です。', reading: 'はい、 そう です。 だいがくせい です。', en: "Yes, that's right. He's a university student." },
          { text: '私の名前はリサです。', reading: 'わたし の なまえ は リサ です。', en: 'My name is Lisa.' },
          { text: '田中さんは東京大学の学生です。', reading: 'たなか さん は とうきょうだいがく の がくせい です。', en: 'Mr. Tanaka is a student at the University of Tokyo.' },
          { text: '「アメリカ人ですか。」「いいえ、ちがいます。カナダ人です。」', reading: '「アメリカじん です か。」 「いいえ、 ちがいます。 カナダじん です。」', en: '"Are you American?" "No, I\'m not. I\'m Canadian."' },
        ],
        drills: [
          { text: 'マリアさんは学生です___。', reading: 'マリア さん は がくせい です ___。', en: 'Is Maria a student?', answer: 'か', distractors: ['の', 'は', 'を'] },
          { text: '私___名前はケンです。', reading: 'わたし ___ なまえ は ケン です。', en: 'My name is Ken.', answer: 'の', distractors: ['は', 'か', 'を'] },
          { text: '山田さんは日本語___先生です。', reading: 'やまだ さん は にほんご ___ せんせい です。', en: 'Ms. Yamada is a Japanese-language teacher.', answer: 'の', distractors: ['は', 'か', 'を'] },
          { text: '「学生ですか。」「___、学生です。」', reading: '「がくせい です か。」 「___、 がくせい です。」', en: '"Are you a student?" "Yes, I am."', answer: 'はい', distractors: ['いいえ', 'だれ'] },
          { text: '「日本人ですか。」「いいえ、___。」', reading: '「にほんじん です か。」 「いいえ、 ___。」', en: '"Are you Japanese?" "No, I\'m not."', answer: 'ちがいます', distractors: ['そうです', 'はい'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-01-01', text: '私', reading: 'わたし', en: 'I; me', pos: 'pronoun', example: { text: '私はジョンです。', reading: 'わたし は ジョン です。', en: "I'm John." } },
      { id: 'v-ja-n5-01-02', text: '学生', reading: 'がくせい', en: 'student', pos: 'noun', example: { text: 'マリアさんは学生です。', reading: 'マリア さん は がくせい です。', en: 'Maria is a student.' } },
      { id: 'v-ja-n5-01-03', text: '先生', reading: 'せんせい', en: 'teacher', pos: 'noun', example: { text: '先生は日本人です。', reading: 'せんせい は にほんじん です。', en: 'The teacher is Japanese.' } },
      { id: 'v-ja-n5-01-04', text: '大学', reading: 'だいがく', en: 'university', pos: 'noun', example: { text: 'リーさんは大学の先生です。', reading: 'リー さん は だいがく の せんせい です。', en: 'Mr. Lee is a university teacher.' } },
      { id: 'v-ja-n5-01-05', text: '大学生', reading: 'だいがくせい', en: 'university student', pos: 'noun', example: { text: '私は大学生です。', reading: 'わたし は だいがくせい です。', en: "I'm a university student." } },
      { id: 'v-ja-n5-01-06', text: '高校生', reading: 'こうこうせい', en: 'high school student', pos: 'noun', example: { text: 'トムさんは高校生ですか。', reading: 'トム さん は こうこうせい です か。', en: 'Is Tom a high school student?' } },
      { id: 'v-ja-n5-01-07', text: 'りゅうがくせい', en: 'international student', pos: 'noun', example: { text: 'アンナさんはりゅうがくせいです。', reading: 'アンナ さん は りゅうがくせい です。', en: 'Anna is an international student.' } },
      { id: 'v-ja-n5-01-08', text: 'かいしゃいん', en: 'office worker; company employee', pos: 'noun', example: { text: '私はかいしゃいんじゃありません。', reading: 'わたし は かいしゃいん じゃ ありません。', en: "I'm not an office worker." } },
      { id: 'v-ja-n5-01-09', text: 'いしゃ', en: 'doctor', pos: 'noun', example: { text: '川口さんはいしゃです。', reading: 'かわぐち さん は いしゃ です。', en: 'Ms. Kawaguchi is a doctor.' } },
      { id: 'v-ja-n5-01-10', text: '日本', reading: 'にほん', en: 'Japan', pos: 'noun', example: { text: '日本の大学の学生です。', reading: 'にほん の だいがく の がくせい です。', en: "I'm a student at a Japanese university." } },
      { id: 'v-ja-n5-01-11', text: '日本人', reading: 'にほんじん', en: 'Japanese (person)', pos: 'noun', example: { text: '山田さんは日本人です。', reading: 'やまだ さん は にほんじん です。', en: 'Ms. Yamada is Japanese.' } },
      { id: 'v-ja-n5-01-12', text: 'アメリカ人', reading: 'アメリカじん', en: 'American (person)', pos: 'noun', example: { text: 'エマさんはアメリカ人ですか。', reading: 'エマ さん は アメリカじん です か。', en: 'Is Emma American?' } },
      { id: 'v-ja-n5-01-13', text: '日本語', reading: 'にほんご', en: 'Japanese (language)', pos: 'noun', example: { text: '私は日本語の学生です。', reading: 'わたし は にほんご の がくせい です。', en: "I'm a student of Japanese." } },
      { id: 'v-ja-n5-01-14', text: '英語', reading: 'えいご', en: 'English (language)', pos: 'noun', example: { text: 'ジョンさんは英語の先生です。', reading: 'ジョン さん は えいご の せんせい です。', en: 'John is an English teacher.' } },
      { id: 'v-ja-n5-01-15', text: '名前', reading: 'なまえ', en: 'name', pos: 'noun', example: { text: 'お名前は何ですか。', reading: 'おなまえ は なん です か。', en: "What's your name?" } },
      { id: 'v-ja-n5-01-16', text: '友だち', reading: 'ともだち', en: 'friend', pos: 'noun', example: { text: 'ケンさんは私の友だちです。', reading: 'ケン さん は わたし の ともだち です。', en: 'Ken is my friend.' } },
      { id: 'v-ja-n5-01-17', text: 'だれ', en: 'who', pos: 'pronoun', example: { text: '日本語の先生はだれですか。', reading: 'にほんご の せんせい は だれ です か。', en: 'Who is the Japanese teacher?' } },
      { id: 'v-ja-n5-01-20', text: 'そうです', en: "that's right", pos: 'phrase', example: { text: '「先生ですか。」「はい、そうです。」', reading: '「せんせい です か。」 「はい、 そう です。」', en: '"Are you a teacher?" "Yes, I am."' } },
      { id: 'v-ja-n5-01-21', text: 'ちがう', en: 'to be different; to be wrong', pos: 'verb', example: { text: '「中国人ですか。」「いいえ、ちがいます。」', reading: '「ちゅうごくじん です か。」 「いいえ、 ちがいます。」', en: '"Are you Chinese?" "No, I\'m not."' } },
      { id: 'v-ja-n5-01-22', text: 'よろしくおねがいします', en: 'nice to meet you (lit. please treat me kindly)', pos: 'phrase', example: { text: 'リサです。よろしくおねがいします。', reading: 'リサ です。 よろしく おねがいします。', en: "I'm Lisa. Nice to meet you." } },
    ],
    scenario: {
      title: 'Meeting a classmate',
      setting: "It's your first day at a Japanese language school in Tokyo. During the break, the student sitting next to you turns to say hello.",
      aiRole: 'Kim Minji (キム・ミンジ), a cheerful classmate from Korea who is also learning Japanese',
      learnerGoal: "Introduce yourself (name, nationality, and job or school), ask Minji whether she's a student and what she does, and finish with よろしくおねがいします.",
      opener: 'はじめまして。キムです。私はかんこくじんです。お名前は？',
      openerReading: 'はじめまして。 キム です。 わたし は かんこくじん です。 おなまえ は？',
    },
  },
  {
    id: 'ja-n5-02',
    cefr: 'A1',
    order: 3,
    title: 'これはいくらですか: Things and prices',
    theme: 'Pointing at things, asking what they are, and shopping with yen',
    canDo: [
      'I can point to things near me, near you, and far away with これ, それ and あれ.',
      'I can ask what something is and whose it is.',
      'I can ask how much something costs and understand prices in yen.',
      'I can say "this one too" with も.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-02-1',
        title: 'これ・それ・あれ・どれ and この・その・あの',
        summary:
          "Japanese points at things at three distances. これ (kore) is something near me, それ (sore) is near you, and あれ (are) is over there, away from both of us; どれ (dore) asks 'which one?'. These work like nouns on their own: これは本です (これ は ほん です, kore wa hon desu) 'This is a book.' To put 'this' or 'that' in front of a noun, use この (kono), その (sono), あの (ano) and どの (dono) instead: この本 (この ほん, kono hon) 'this book'. Pitfall: この・その・あの・どの can never stand alone, so この です is wrong, and これ・それ・あれ can't go before a noun, so これ本 (これ ほん, kore hon) is wrong too.",
        examples: [
          { text: 'これは何ですか。', reading: 'これ は なん です か。', en: 'What is this?' },
          { text: 'それは私のかさです。', reading: 'それ は わたし の かさ です。', en: "That's my umbrella." },
          { text: 'あの人は山田先生です。', reading: 'あの ひと は やまだ せんせい です。', en: 'That person over there is Ms. Yamada, our teacher.' },
          { text: '田中さんのかばんはどれですか。', reading: 'たなか さん の かばん は どれ です か。', en: "Which bag is Mr. Tanaka's?" },
          { text: 'そのとけいは日本のですか。', reading: 'その とけい は にほん の です か。', en: 'Is that watch a Japanese one?' },
        ],
        drills: [
          { text: '___は何ですか。', reading: '___ は なん です か。', en: "What is this? (the thing I'm holding)", answer: 'これ', distractors: ['この', 'それ', 'どれ'] },
          { text: '___かばんはいくらですか。', reading: '___ かばん は いくら です か。', en: 'How much is that bag (near you)?', answer: 'その', distractors: ['それ', 'あの', 'どの'] },
          { text: '___は山田さんのかさです。', reading: '___ は やまだ さん の かさ です。', en: "That one over there is Ms. Yamada's umbrella.", answer: 'あれ', distractors: ['あの', 'これ', 'どれ'] },
          { text: 'ジョンさんのかばんは___ですか。', reading: 'ジョン さん の かばん は ___ です か。', en: "Which one is John's bag?", answer: 'どれ', distractors: ['どの', 'だれ', 'あの'] },
          { text: '___人は先生です。', reading: '___ ひと は せんせい です。', en: 'That person over there is a teacher.', answer: 'あの', distractors: ['あれ', 'この', 'どの'] },
        ],
      },
      {
        id: 'g-ja-n5-02-2',
        title: 'Numbers, 円, いくら, and も (also)',
        summary:
          "Numbers 1–10 are いち, に, さん, よん, ご, ろく, なな, はち, きゅう, じゅう (ichi, ni, san, yon, go, roku, nana, hachi, kyuu, juu), and bigger numbers are built like 'two-ten-five': にじゅうご (nijuugo) is 25. 100 is ひゃく (hyaku), 1,000 is せん (sen) and 10,000 is いちまん (ichiman), with sound changes to memorize: さんびゃく (sanbyaku, 300), ろっぴゃく (roppyaku, 600), はっぴゃく (happyaku, 800), さんぜん (sanzen, 3,000), はっせん (hassen, 8,000). Prices end in 円 (えん, en), and you ask the price with いくらですか (ikura desu ka) 'How much is it?'. The particle も (mo) means 'also, too' and takes the place of は: これも500円です (これ も ごひゃくえん です, kore mo gohyaku-en desu) 'This is 500 yen too.' Pitfall: も replaces は, so はも is always wrong, and 10,000 is never just まん.",
        examples: [
          { text: 'これはいくらですか。', reading: 'これ は いくら です か。', en: 'How much is this?' },
          { text: 'この本は1500円です。', reading: 'この ほん は せんごひゃくえん です。', en: 'This book is 1,500 yen.' },
          { text: '「それはいくらですか。」「300円です。」', reading: '「それ は いくら です か。」 「さんびゃくえん です。」', en: '"How much is that?" "It\'s 300 yen."' },
          { text: 'これも800円です。', reading: 'これ も はっぴゃくえん です。', en: 'This one is 800 yen too.' },
          { text: '私も学生です。', reading: 'わたし も がくせい です。', en: "I'm a student too." },
        ],
        drills: [
          { text: 'これ___500円です。', reading: 'これ ___ ごひゃくえん です。', en: 'This one is also 500 yen.', answer: 'も', distractors: ['は', 'の', 'を'] },
          { text: 'この本は___ですか。', reading: 'この ほん は ___ です か。', en: 'How much is this book?', answer: 'いくら', distractors: ['どれ', 'だれ', 'なん'] },
          { text: 'そのかさは___円です。', reading: 'その かさ は ___えん です。', en: 'That umbrella is 300 yen.', answer: 'さんびゃく', distractors: ['さんひゃく', 'さんぴゃく'] },
          { text: 'このかばんは___円です。', reading: 'この かばん は ___えん です。', en: 'This bag is 8,000 yen.', answer: 'はっせん', distractors: ['はちせん', 'はっぜん'] },
          { text: '「私はアメリカ人です。」「私___アメリカ人です。」', reading: '「わたし は アメリカじん です。」 「わたし ___ アメリカじん です。」', en: '"I\'m American." "I\'m American too."', answer: 'も', distractors: ['は', 'の', 'か'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-02-01', text: 'これ', en: 'this (one, near me)', pos: 'pronoun', example: { text: 'これは日本の本です。', reading: 'これ は にほん の ほん です。', en: 'This is a Japanese book.' } },
      { id: 'v-ja-n5-02-02', text: 'それ', en: 'that (one, near you)', pos: 'pronoun', example: { text: 'それは英語の本ですか。', reading: 'それ は えいご の ほん です か。', en: 'Is that an English book?' } },
      { id: 'v-ja-n5-02-03', text: 'あれ', en: 'that (one, over there)', pos: 'pronoun', example: { text: 'あれは何ですか。', reading: 'あれ は なん です か。', en: "What's that over there?" } },
      { id: 'v-ja-n5-02-04', text: 'どれ', en: 'which (one)', pos: 'pronoun', example: { text: 'ケンさんのかさはどれですか。', reading: 'ケン さん の かさ は どれ です か。', en: "Which umbrella is Ken's?" } },
      { id: 'v-ja-n5-02-05', text: 'この', en: 'this … (near me)', pos: 'determiner', example: { text: 'このかばんはいくらですか。', reading: 'この かばん は いくら です か。', en: 'How much is this bag?' } },
      { id: 'v-ja-n5-02-06', text: 'その', en: 'that … (near you)', pos: 'determiner', example: { text: 'その本は先生のです。', reading: 'その ほん は せんせい の です。', en: "That book is the teacher's." } },
      { id: 'v-ja-n5-02-07', text: 'あの', en: 'that … (over there)', pos: 'determiner', example: { text: 'あの人はだれですか。', reading: 'あの ひと は だれ です か。', en: 'Who is that person over there?' } },
      { id: 'v-ja-n5-02-08', text: 'どの', en: 'which …', pos: 'determiner', example: { text: '「どの本ですか。」「その本です。」', reading: '「どの ほん です か。」 「その ほん です。」', en: '"Which book?" "That one, by you."' } },
      { id: 'v-ja-n5-02-09', text: '何', reading: 'なに', en: 'what (also read なん)', pos: 'pronoun', example: { text: 'それは何ですか。', reading: 'それ は なん です か。', en: 'What is that?' } },
      { id: 'v-ja-n5-02-10', text: 'いくら', en: 'how much', pos: 'adverb', example: { text: '「これはいくらですか。」「500円です。」', reading: '「これ は いくら です か。」 「ごひゃくえん です。」', en: '"How much is this?" "It\'s 500 yen."' } },
      { id: 'v-ja-n5-02-11', text: '円', reading: 'えん', en: 'yen', pos: 'counter', example: { text: 'このかさは700円です。', reading: 'この かさ は ななひゃくえん です。', en: 'This umbrella is 700 yen.' } },
      { id: 'v-ja-n5-02-12', text: '百', reading: 'ひゃく', en: 'hundred', pos: 'number', example: { text: 'これは百円です。', reading: 'これ は ひゃくえん です。', en: 'This is 100 yen.' } },
      { id: 'v-ja-n5-02-13', text: '千', reading: 'せん', en: 'thousand', pos: 'number', example: { text: 'このかばんは五千円です。', reading: 'この かばん は ごせんえん です。', en: 'This bag is 5,000 yen.' } },
      { id: 'v-ja-n5-02-14', text: '万', reading: 'まん', en: 'ten thousand', pos: 'number', example: { text: 'このとけいは一万円です。', reading: 'この とけい は いちまんえん です。', en: 'This watch is 10,000 yen.' } },
      { id: 'v-ja-n5-02-15', text: 'も', en: 'also; too', pos: 'particle', example: { text: 'このかさも山田さんのです。', reading: 'この かさ も やまだ さん の です。', en: "This umbrella is Ms. Yamada's too." } },
      { id: 'v-ja-n5-02-16', text: '本', reading: 'ほん', en: 'book', pos: 'noun', example: { text: '山田さんの本です。', reading: 'やまだ さん の ほん です。', en: "It's Ms. Yamada's book." } },
      { id: 'v-ja-n5-02-17', text: 'かさ', en: 'umbrella', pos: 'noun', example: { text: 'このかさはだれのですか。', reading: 'この かさ は だれ の です か。', en: 'Whose umbrella is this?' } },
      { id: 'v-ja-n5-02-18', text: 'かばん', en: 'bag', pos: 'noun', example: { text: 'あのかばんはいくらですか。', reading: 'あの かばん は いくら です か。', en: 'How much is that bag over there?' } },
      { id: 'v-ja-n5-02-19', text: 'とけい', en: 'watch; clock', pos: 'noun', example: { text: 'これは日本のとけいです。', reading: 'これ は にほん の とけい です。', en: 'This is a Japanese watch.' } },
      { id: 'v-ja-n5-02-20', text: 'おみやげ', en: 'souvenir; gift from a trip', pos: 'noun', example: { text: 'これはきょうとのおみやげです。', reading: 'これ は きょうと の おみやげ です。', en: 'This is a souvenir from Kyoto.' } },
      { id: 'v-ja-n5-02-21', text: 'みせ', en: 'shop; store', pos: 'noun', example: { text: 'あのみせは何のみせですか。', reading: 'あの みせ は なん の みせ です か。', en: 'What kind of shop is that?' } },
      { id: 'v-ja-n5-02-22', text: 'ゆかた', en: 'yukata (light cotton kimono)', pos: 'noun', example: { text: 'このゆかたは6000円です。', reading: 'この ゆかた は ろくせんえん です。', en: 'This yukata is 6,000 yen.' } },
    ],
    scenario: {
      title: 'Buying souvenirs',
      setting: "You're in a small souvenir shop near Sensoji Temple in Asakusa, Tokyo, looking for gifts to take home.",
      aiRole: 'Mrs. Sato (さとうさん), the friendly owner of the shop',
      learnerGoal: 'Point to items with これ, それ and あれ, ask what they are and how much they cost, understand the prices in yen, and choose something to buy (これをください, kore o kudasai).',
      opener: 'いらっしゃいませ！このゆかたは3000円です。',
      openerReading: 'いらっしゃいませ！ この ゆかた は さんぜんえん です。',
    },
  },
  {
    id: 'ja-n5-03',
    cefr: 'A1',
    order: 4,
    title: 'どこにありますか: Places and locations',
    theme: 'Asking where things are and describing locations',
    canDo: [
      'I can ask where a place or thing is.',
      'I can say that something or someone is in a place with あります and います.',
      'I can describe a location with words like 上, 中, 前 and となり.',
      'I can find the restroom, shops, and exits in a train station.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-03-1',
        title: 'あります / います with に',
        summary:
          "Japanese has two verbs for 'there is' or 'is (somewhere)': あります (arimasu) for things and plants, and います (imasu) for people and animals. To say what is in a place, use 'Place に Thing が あります': つくえの上に本があります (つくえ の うえ に ほん が あります, tsukue no ue ni hon ga arimasu) 'There's a book on the desk.' To say where a known thing is, use 'Thing は Place に あります': トイレはあそこにあります (toire wa asoko ni arimasu) 'The restroom is over there.' に (ni) marks where something is, and the negatives are ありません (arimasen) and いません (imasen). Pitfall: anything alive that moves on its own takes います, so it's ねこがいます (neko ga imasu), never ねこがあります.",
        examples: [
          { text: 'つくえの上に本があります。', reading: 'つくえ の うえ に ほん が あります。', en: "There's a book on the desk." },
          { text: 'きょうしつに先生がいます。', reading: 'きょうしつ に せんせい が います。', en: "There's a teacher in the classroom." },
          { text: 'トイレはどこにありますか。', reading: 'トイレ は どこ に あります か。', en: 'Where is the restroom?' },
          { text: 'あそこに田中さんがいます。', reading: 'あそこ に たなか さん が います。', en: 'Mr. Tanaka is over there.' },
          { text: 'ここにトイレはありません。', reading: 'ここ に トイレ は ありません。', en: "There's no restroom here." },
        ],
        drills: [
          { text: 'つくえの上にねこが___。', reading: 'つくえ の うえ に ねこ が ___。', en: "There's a cat on the desk.", answer: 'います', distractors: ['あります', 'ありません'] },
          { text: 'かばんの中に本が___。', reading: 'かばん の なか に ほん が ___。', en: "There's a book in the bag.", answer: 'あります', distractors: ['います', 'いません'] },
          { text: 'えき___コンビニがあります。', reading: 'えき ___ コンビニ が あります。', en: "There's a convenience store at the station.", answer: 'に', distractors: ['を', 'で', 'へ'] },
          { text: 'トイレは___にありますか。', reading: 'トイレ は ___ に あります か。', en: 'Where is the restroom?', answer: 'どこ', distractors: ['だれ', 'どれ', 'なに'] },
          { text: 'きょうしつに学生は___。', reading: 'きょうしつ に がくせい は ___。', en: 'There are no students in the classroom.', answer: 'いません', distractors: ['ありません', 'います'] },
        ],
      },
      {
        id: 'g-ja-n5-03-2',
        title: 'ここ・そこ・あそこ and position words (上・下・中・前・後ろ・となり)',
        summary:
          "ここ (koko) 'here', そこ (soko) 'there, near you', あそこ (asoko) 'over there' and どこ (doko) 'where?' follow the same こ・そ・あ・ど pattern as これ・それ・あれ・どれ. For an exact position, use 'Noun の position word': 上 (うえ, ue) on or above, 下 (した, shita) under, 中 (なか, naka) inside, 前 (まえ, mae) in front of, 後ろ (うしろ, ushiro) behind, and となり (tonari) next to. Then add に and the verb: えきの前にあります (えき の まえ に あります, eki no mae ni arimasu) 'It's in front of the station.' Pitfall: the order is the reverse of English: 'under the chair' is いすの下 (いす の した, isu no shita), literally 'the chair's underside', so the reference point always comes first.",
        examples: [
          { text: 'ここはどこですか。', reading: 'ここ は どこ です か。', en: 'Where am I? (lit. Where is here?)' },
          { text: 'いすの下にかばんがあります。', reading: 'いす の した に かばん が あります。', en: "There's a bag under the chair." },
          { text: '山田さんは田中さんの後ろにいます。', reading: 'やまだ さん は たなか さん の うしろ に います。', en: 'Ms. Yamada is behind Mr. Tanaka.' },
          { text: 'かばんの中に何がありますか。', reading: 'かばん の なか に なに が あります か。', en: "What's in the bag?" },
          { text: 'ぎんこうはえきの前にあります。', reading: 'ぎんこう は えき の まえ に あります。', en: 'The bank is in front of the station.' },
        ],
        drills: [
          { text: 'ねこはつくえの___にいます。', reading: 'ねこ は つくえ の ___ に います。', en: 'The cat is under the desk.', answer: '下', distractors: ['上', '中', '前'] },
          { text: '「トイレはどこですか。」「___です。」', reading: '「トイレ は どこ です か。」 「___ です。」', en: '"Where\'s the restroom?" "It\'s right here."', answer: 'ここ', distractors: ['あそこ', 'この', 'どこ'] },
          { text: 'えきはぎんこうの___にあります。', reading: 'えき は ぎんこう の ___ に あります。', en: 'The station is next to the bank.', answer: 'となり', distractors: ['前', '上', '後ろ'] },
          { text: 'かばんの___にかさがあります。', reading: 'かばん の ___ に かさ が あります。', en: "There's an umbrella in the bag.", answer: '中', distractors: ['上', '下', '後ろ'] },
          { text: 'こうばんはえきの___にあります。', reading: 'こうばん は えき の ___ に あります。', en: 'The police box is in front of the station.', answer: '前', distractors: ['中', '上', 'となり'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-03-01', text: 'ここ', en: 'here', pos: 'pronoun', example: { text: 'ここは東京えきです。', reading: 'ここ は とうきょうえき です。', en: 'This is Tokyo Station.' } },
      { id: 'v-ja-n5-03-02', text: 'そこ', en: 'there (near you)', pos: 'pronoun', example: { text: 'そこに何がありますか。', reading: 'そこ に なに が あります か。', en: "What's there by you?" } },
      { id: 'v-ja-n5-03-03', text: 'あそこ', en: 'over there', pos: 'pronoun', example: { text: '出口はあそこです。', reading: 'でぐち は あそこ です。', en: 'The exit is over there.' } },
      { id: 'v-ja-n5-03-04', text: 'どこ', en: 'where', pos: 'pronoun', example: { text: 'えきはどこですか。', reading: 'えき は どこ です か。', en: 'Where is the station?' } },
      { id: 'v-ja-n5-03-05', text: '上', reading: 'うえ', en: 'on; above; top', pos: 'noun', example: { text: 'つくえの上にかばんがあります。', reading: 'つくえ の うえ に かばん が あります。', en: "There's a bag on the desk." } },
      { id: 'v-ja-n5-03-06', text: '下', reading: 'した', en: 'under; below', pos: 'noun', example: { text: 'いすの下にねこがいます。', reading: 'いす の した に ねこ が います。', en: "There's a cat under the chair." } },
      { id: 'v-ja-n5-03-07', text: '中', reading: 'なか', en: 'inside; in', pos: 'noun', example: { text: 'えきの中にコンビニがあります。', reading: 'えき の なか に コンビニ が あります。', en: "There's a convenience store inside the station." } },
      { id: 'v-ja-n5-03-08', text: '前', reading: 'まえ', en: 'in front of; before', pos: 'noun', example: { text: 'ぎんこうの前にいます。', reading: 'ぎんこう の まえ に います。', en: "I'm in front of the bank." } },
      { id: 'v-ja-n5-03-09', text: '後ろ', reading: 'うしろ', en: 'behind; back', pos: 'noun', example: { text: 'えきの後ろにホテルがあります。', reading: 'えき の うしろ に ホテル が あります。', en: "There's a hotel behind the station." } },
      { id: 'v-ja-n5-03-10', text: 'となり', en: 'next to; next door', pos: 'noun', example: { text: 'コンビニのとなりにぎんこうがあります。', reading: 'コンビニ の となり に ぎんこう が あります。', en: "There's a bank next to the convenience store." } },
      { id: 'v-ja-n5-03-11', text: 'ある', en: 'to be; to exist (things)', pos: 'verb', example: { text: 'このえきにエレベーターはありますか。', reading: 'この えき に エレベーター は あります か。', en: 'Does this station have an elevator?' } },
      { id: 'v-ja-n5-03-12', text: 'いる', en: 'to be; to exist (people, animals)', pos: 'verb', example: { text: '田中さんは今、どこにいますか。', reading: 'たなか さん は いま、 どこ に います か。', en: 'Where is Mr. Tanaka now?' } },
      { id: 'v-ja-n5-03-13', text: 'えき', en: 'station', pos: 'noun', example: { text: 'えきはあそこです。', reading: 'えき は あそこ です。', en: 'The station is over there.' } },
      { id: 'v-ja-n5-03-14', text: 'トイレ', en: 'restroom; toilet', pos: 'noun', example: { text: 'トイレはどこですか。', reading: 'トイレ は どこ です か。', en: "Where's the restroom?" } },
      { id: 'v-ja-n5-03-15', text: 'コンビニ', en: 'convenience store', pos: 'noun', example: { text: 'えきの前にコンビニがあります。', reading: 'えき の まえ に コンビニ が あります。', en: "There's a convenience store in front of the station." } },
      { id: 'v-ja-n5-03-16', text: 'ぎんこう', en: 'bank', pos: 'noun', example: { text: 'ぎんこうはえきのとなりです。', reading: 'ぎんこう は えき の となり です。', en: 'The bank is next to the station.' } },
      { id: 'v-ja-n5-03-17', text: '出口', reading: 'でぐち', en: 'exit', pos: 'noun', example: { text: '出口はどこですか。', reading: 'でぐち は どこ です か。', en: 'Where is the exit?' } },
      { id: 'v-ja-n5-03-18', text: '入口', reading: 'いりぐち', en: 'entrance', pos: 'noun', example: { text: '入口はここです。', reading: 'いりぐち は ここ です。', en: 'The entrance is here.' } },
      { id: 'v-ja-n5-03-19', text: 'きっぷ', en: 'ticket', pos: 'noun', example: { text: 'きっぷはかばんの中です。', reading: 'きっぷ は かばん の なか です。', en: 'The ticket is in my bag.' } },
      { id: 'v-ja-n5-03-20', text: 'こうばん', en: 'police box', pos: 'noun', example: { text: 'あそこにこうばんがあります。', reading: 'あそこ に こうばん が あります。', en: "There's a police box over there." } },
      { id: 'v-ja-n5-03-21', text: 'いぬ', en: 'dog', pos: 'noun', example: { text: 'えきの前にいぬがいます。', reading: 'えき の まえ に いぬ が います。', en: "There's a dog in front of the station." } },
      { id: 'v-ja-n5-03-22', text: 'つくえ', en: 'desk', pos: 'noun', example: { text: 'つくえの下にかばんがあります。', reading: 'つくえ の した に かばん が あります。', en: "There's a bag under the desk." } },
    ],
    scenario: {
      title: 'Asking at the station',
      setting: "You've just arrived at a big, busy station in Tokyo. You need a restroom, a convenience store, and the right exit, so you stop at the station attendant's window.",
      aiRole: 'Mr. Kato (かとうさん), a patient station attendant',
      learnerGoal: 'Ask where the restroom, a convenience store, and the exit are, understand answers with words like 前, 中 and となり, and thank the attendant.',
      opener: 'こんにちは。ここは東口です。どうしましたか。',
      openerReading: 'こんにちは。 ここ は ひがしぐち です。 どう しました か。',
    },
  },
  {
    id: 'ja-n5-04',
    cefr: 'A1',
    order: 5,
    title: '毎日の生活: Daily routine',
    theme: 'Talking about what you do every day and when',
    canDo: [
      'I can talk about what I do every day using polite ます verbs.',
      "I can say what I did and didn't do yesterday.",
      'I can ask and tell the time.',
      'I can say where and when I do things with で and に.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-04-1',
        title: 'ます verbs: present, negative, past (ます・ません・ました・ませんでした)',
        summary:
          "Polite verbs end in ます (masu), and only the ending changes: 食べます (たべます, tabemasu) 'eat, will eat', 食べません (たべません, tabemasen) 'don't eat, won't eat', 食べました (たべました, tabemashita) 'ate', 食べませんでした (たべません でした, tabemasen deshita) 'didn't eat'. There's no separate future tense: the ます form covers both habits and the future, as in あした見ます (あした みます, ashita mimasu) 'I'll watch it tomorrow.' The verb always comes at the end of the sentence. Dictionaries list verbs in their plain form, like 食べる (たべる, taberu) and 飲む (のむ, nomu); for now, just learn each verb's ます form. Pitfall: don't forget でした in the past negative, because 食べません (たべません, tabemasen) alone means 'I don't eat', not 'I didn't eat'.",
        examples: [
          { text: '毎日コーヒーを飲みます。', reading: 'まいにち コーヒー を のみます。', en: 'I drink coffee every day.' },
          { text: '私はあさごはんを食べません。', reading: 'わたし は あさごはん を たべません。', en: "I don't eat breakfast." },
          { text: 'きのう、テレビを見ました。', reading: 'きのう、 テレビ を みました。', en: 'I watched TV yesterday.' },
          { text: 'きのうは本を読みませんでした。', reading: 'きのう は ほん を よみません でした。', en: "I didn't read yesterday." },
          { text: 'あした、としょかんでべんきょうします。', reading: 'あした、 としょかん で べんきょう します。', en: "I'll study at the library tomorrow." },
        ],
        drills: [
          { text: '毎日、水を___。', reading: 'まいにち、 みず を ___。', en: 'I drink water every day.', answer: '飲みます', distractors: ['飲みません', '飲みました'] },
          { text: 'きのう、本を___。', reading: 'きのう、 ほん を ___。', en: 'I read a book yesterday.', answer: '読みました', distractors: ['読みます', '読みません'] },
          { text: '私はテレビを___。', reading: 'わたし は テレビ を ___。', en: "I don't watch TV.", answer: '見ません', distractors: ['見ます', '見ました', '見ませんでした'] },
          { text: 'きのう、あさごはんを___。', reading: 'きのう、 あさごはん を ___。', en: "I didn't eat breakfast yesterday.", answer: '食べませんでした', distractors: ['食べません', '食べました'] },
          { text: 'あした、6時に___。', reading: 'あした、 ろくじ に ___。', en: "Tomorrow I'll get up at six.", answer: 'おきます', distractors: ['おきました', 'おきませんでした'] },
        ],
      },
      {
        id: 'g-ja-n5-04-2',
        title: 'Particles を, で (place of action), に (time) and telling time',
        summary:
          "を (o) marks the object, the thing you eat, drink, watch or read: コーヒーを飲みます (コーヒー を のみます, koohii o nomimasu) 'I drink coffee'; it's written を but pronounced o. で (de) marks the place where an action happens: うちで食べます (うち で たべます, uchi de tabemasu) 'I eat at home.' に (ni) marks a clock time: 7時におきます (しちじ に おきます, shichiji ni okimasu) 'I get up at 7', but words like 毎日 (まいにち, mainichi), 今日 (きょう, kyou), きのう (kinou) and あした (ashita) take no particle. Tell the time with 時 (じ, ji) for o'clock, 分 (ふん or ぷん, fun or pun) for minutes, and 半 (はん, han) for half past; watch out for 4時 (よじ, yoji), 7時 (しちじ, shichiji) and 9時 (くじ, kuji). Pitfall: don't use に for the place of an action: it's としょかんでべんきょうします (toshokan de benkyou shimasu), not としょかんに.",
        examples: [
          { text: '7時におきます。', reading: 'しちじ に おきます。', en: 'I get up at seven.' },
          { text: 'うちであさごはんを食べます。', reading: 'うち で あさごはん を たべます。', en: 'I eat breakfast at home.' },
          { text: 'カフェでコーヒーを飲みます。', reading: 'カフェ で コーヒー を のみます。', en: 'I drink coffee at a café.' },
          { text: '今、3時半です。', reading: 'いま、 さんじはん です。', en: "It's 3:30 now." },
          { text: 'まいばん11時にねます。', reading: 'まいばん じゅういちじ に ねます。', en: 'I go to bed at eleven every night.' },
        ],
        drills: [
          { text: 'パン___食べます。', reading: 'パン ___ たべます。', en: 'I eat bread.', answer: 'を', distractors: ['に', 'で', 'へ'] },
          { text: 'まいばん、___にねます。', reading: 'まいばん、 ___ に ねます。', en: 'I go to bed at nine every night.', answer: 'くじ', distractors: ['きゅうじ', 'きゅじ'] },
          { text: '6時___おきます。', reading: 'ろくじ ___ おきます。', en: 'I get up at six.', answer: 'に', distractors: ['で', 'を', 'の'] },
          { text: '今、___です。', reading: 'いま、 ___ です。', en: "It's four o'clock now.", answer: 'よじ', distractors: ['よんじ', 'しじ'] },
          { text: 'きのう、レストラン___ばんごはんを食べました。', reading: 'きのう、 レストラン ___ ばんごはん を たべました。', en: 'Yesterday I ate dinner at a restaurant.', answer: 'で', distractors: ['に', 'を', 'へ'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-04-01', text: '毎日', reading: 'まいにち', en: 'every day', pos: 'noun', example: { text: '毎日、日本語をべんきょうします。', reading: 'まいにち、 にほんご を べんきょう します。', en: 'I study Japanese every day.' } },
      { id: 'v-ja-n5-04-02', text: '今日', reading: 'きょう', en: 'today', pos: 'noun', example: { text: '今日はとしょかんで本を読みます。', reading: 'きょう は としょかん で ほん を よみます。', en: "Today I'll read at the library." } },
      { id: 'v-ja-n5-04-03', text: 'きのう', en: 'yesterday', pos: 'noun', example: { text: 'きのう、コーヒーを飲みませんでした。', reading: 'きのう、 コーヒー を のみません でした。', en: "I didn't drink coffee yesterday." } },
      { id: 'v-ja-n5-04-04', text: 'あした', en: 'tomorrow', pos: 'noun', example: { text: 'あした、何をしますか。', reading: 'あした、 なに を します か。', en: 'What are you doing tomorrow?' } },
      { id: 'v-ja-n5-04-05', text: '今', reading: 'いま', en: 'now', pos: 'noun', example: { text: '今、何時ですか。', reading: 'いま、 なんじ です か。', en: 'What time is it now?' } },
      { id: 'v-ja-n5-04-06', text: '〜時', reading: '〜じ', en: "o'clock", pos: 'counter', example: { text: '10時にねます。', reading: 'じゅうじ に ねます。', en: 'I go to bed at ten.' } },
      { id: 'v-ja-n5-04-07', text: '〜分', reading: '〜ふん', en: 'minute(s) (also read ぷん)', pos: 'counter', example: { text: '7時15分におきます。', reading: 'しちじ じゅうごふん に おきます。', en: 'I get up at 7:15.' } },
      { id: 'v-ja-n5-04-08', text: '半', reading: 'はん', en: 'half; half past', pos: 'noun', example: { text: '今、8時半です。', reading: 'いま、 はちじはん です。', en: "It's 8:30 now." } },
      { id: 'v-ja-n5-04-09', text: 'おきる', en: 'to get up; to wake up', pos: 'verb', example: { text: 'あさ、何時におきますか。', reading: 'あさ、 なんじ に おきます か。', en: 'What time do you get up in the morning?' } },
      { id: 'v-ja-n5-04-10', text: 'ねる', en: 'to go to bed; to sleep', pos: 'verb', example: { text: 'きのう、12時にねました。', reading: 'きのう、 じゅうにじ に ねました。', en: 'I went to bed at twelve last night.' } },
      { id: 'v-ja-n5-04-11', text: '食べる', reading: 'たべる', en: 'to eat', pos: 'verb', example: { text: 'うちでばんごはんを食べます。', reading: 'うち で ばんごはん を たべます。', en: 'I eat dinner at home.' } },
      { id: 'v-ja-n5-04-12', text: '飲む', reading: 'のむ', en: 'to drink', pos: 'verb', example: { text: 'あさ、コーヒーを飲みます。', reading: 'あさ、 コーヒー を のみます。', en: 'I drink coffee in the morning.' } },
      { id: 'v-ja-n5-04-13', text: '見る', reading: 'みる', en: 'to see; to watch', pos: 'verb', example: { text: 'うちでテレビを見ました。', reading: 'うち で テレビ を みました。', en: 'I watched TV at home.' } },
      { id: 'v-ja-n5-04-14', text: '読む', reading: 'よむ', en: 'to read', pos: 'verb', example: { text: '毎日、本を読みますか。', reading: 'まいにち、 ほん を よみます か。', en: 'Do you read every day?' } },
      { id: 'v-ja-n5-04-15', text: 'べんきょうする', en: 'to study', pos: 'verb', example: { text: 'きのう、日本語をべんきょうしませんでした。', reading: 'きのう、 にほんご を べんきょう しません でした。', en: "I didn't study Japanese yesterday." } },
      { id: 'v-ja-n5-04-16', text: 'あさごはん', en: 'breakfast', pos: 'noun', example: { text: 'あさごはんを食べましたか。', reading: 'あさごはん を たべました か。', en: 'Did you eat breakfast?' } },
      { id: 'v-ja-n5-04-17', text: 'ばんごはん', en: 'dinner', pos: 'noun', example: { text: '7時にばんごはんを食べます。', reading: 'しちじ に ばんごはん を たべます。', en: 'I eat dinner at seven.' } },
      { id: 'v-ja-n5-04-18', text: 'コーヒー', en: 'coffee', pos: 'noun', example: { text: 'コーヒーを飲みません。', reading: 'コーヒー を のみません。', en: "I don't drink coffee." } },
      { id: 'v-ja-n5-04-19', text: 'テレビ', en: 'TV', pos: 'noun', example: { text: 'まいばん、テレビを見ます。', reading: 'まいばん、 テレビ を みます。', en: 'I watch TV every night.' } },
      { id: 'v-ja-n5-04-20', text: 'うち', en: 'home; house', pos: 'noun', example: { text: 'うちで日本語をべんきょうします。', reading: 'うち で にほんご を べんきょう します。', en: 'I study Japanese at home.' } },
      { id: 'v-ja-n5-04-21', text: 'としょかん', en: 'library', pos: 'noun', example: { text: 'としょかんで本を読みました。', reading: 'としょかん で ほん を よみました。', en: 'I read a book at the library.' } },
      { id: 'v-ja-n5-04-22', text: '午後', reading: 'ごご', en: 'afternoon; p.m.', pos: 'noun', example: { text: '午後3時にコーヒーを飲みます。', reading: 'ごご さんじ に コーヒー を のみます。', en: 'I have coffee at 3 p.m.' } },
    ],
    scenario: {
      title: 'Talking with your host family',
      setting: "You're on a homestay in Osaka. At dinner, your host mother asks about your day and your usual routine.",
      aiRole: 'Mrs. Suzuki (すずきさん), your kind and curious host mother',
      learnerGoal: 'Tell her what time you got up and what you did today (and where), describe what you usually do in the evening, and say what time you go to bed.',
      opener: 'おかえりなさい。今日は何をしましたか。',
      openerReading: 'おかえりなさい。 きょう は なに を しました か。',
    },
  },
  {
    id: 'ja-n5-05',
    cefr: 'A1',
    order: 6,
    title: 'どこへ行きますか: Going places',
    theme: 'Saying where, when, how, and with whom you go',
    canDo: [
      "I can say where I'm going, coming, or going back to.",
      'I can say how I travel: by train, bus, bike, or on foot.',
      'I can say who I go with and on which day.',
      'I can ask when someone is going somewhere with いつ.',
    ],
    grammar: [
      {
        id: 'g-ja-n5-05-1',
        title: '行く・来る・帰る with へ/に and で (transport)',
        summary:
          "The three basic motion verbs are 行きます (いきます, ikimasu) 'go', 来ます (きます, kimasu) 'come' and 帰ります (かえります, kaerimasu) 'go back, go home'. Mark the destination with へ (written へ, pronounced e) or に (ni); both mean 'to': 学校へ行きます (がっこう へ いきます, gakkou e ikimasu) 'I go to school.' Mark the means of transport with で (de): 電車で (でんしゃ で, densha de) 'by train', バスで (basu de) 'by bus'; 'on foot' is あるいて (aruite), with no で. Use 帰ります (かえります), not 行きます (いきます), for returning to where you belong: your home, your country, or the hotel you're staying at. Pitfall: 来ます is read きます (kimasu), even though its dictionary form 来る is read くる (kuru).",
        examples: [
          { text: '毎日、電車で学校へ行きます。', reading: 'まいにち、 でんしゃ で がっこう へ いきます。', en: 'I go to school by train every day.' },
          { text: '田中さんはあした、うちに来ます。', reading: 'たなか さん は あした、 うち に きます。', en: 'Mr. Tanaka is coming to my house tomorrow.' },
          { text: '6時にうちへ帰ります。', reading: 'ろくじ に うち へ かえります。', en: 'I go home at six.' },
          { text: 'バスでかいしゃに行きますか。', reading: 'バス で かいしゃ に いきます か。', en: 'Do you go to work by bus?' },
          { text: 'タクシーでホテルへ帰りました。', reading: 'タクシー で ホテル へ かえりました。', en: 'I went back to the hotel by taxi.' },
        ],
        drills: [
          { text: '学校___行きます。', reading: 'がっこう ___ いきます。', en: 'I go to school.', answer: 'へ', distractors: ['を', 'で', 'が'] },
          { text: 'バス___えきへ行きます。', reading: 'バス ___ えき へ いきます。', en: 'I go to the station by bus.', answer: 'で', distractors: ['に', 'を', 'へ'] },
          { text: 'あした、友だちがうちに___。', reading: 'あした、 ともだち が うち に ___。', en: 'Tomorrow a friend is coming to my house.', answer: '来ます', distractors: ['行きます', '帰ります'] },
          { text: 'あした、アメリカに___。', reading: 'あした、 アメリカ に ___。', en: "Tomorrow I'm going back home to America.", answer: '帰ります', distractors: ['来ます', '行きます'] },
          { text: 'きのう、どこ___行きましたか。', reading: 'きのう、 どこ ___ いきました か。', en: 'Where did you go yesterday?', answer: 'に', distractors: ['で', 'を', 'が'] },
        ],
      },
      {
        id: 'g-ja-n5-05-2',
        title: 'と (with someone), days of the week, いつ',
        summary:
          "と (to) after a person means 'together with': 友だちと行きます (ともだち と いきます, tomodachi to ikimasu) 'I'll go with a friend'; to say 'alone', use ひとりで (hitori de). The days of the week all end in 曜日 (ようび, youbi): 月曜日 (げつようび, getsuyoubi) Monday, 火曜日 (かようび, kayoubi) Tuesday, 水曜日 (すいようび, suiyoubi) Wednesday, 木曜日 (もくようび, mokuyoubi) Thursday, 金曜日 (きんようび, kin'youbi) Friday, 土曜日 (どようび, doyoubi) Saturday, 日曜日 (にちようび, nichiyoubi) Sunday. A day of the week takes に, as in 土曜日に行きます (どようび に いきます, doyoubi ni ikimasu) 'I'll go on Saturday', but relative time words like あした (ashita) and らいしゅう (raishuu, next week) take no particle. Ask 'when?' with いつ (itsu), which also takes no particle: いつ来ますか (いつ きます か, itsu kimasu ka) 'When are you coming?' Pitfall: と is for people and で is for transport: 友だちとバスで行きます (ともだち と バス で いきます, tomodachi to basu de ikimasu) 'I'll go by bus with a friend.'",
        examples: [
          { text: '日曜日に友だちと東京へ行きます。', reading: 'にちようび に ともだち と とうきょう へ いきます。', en: "On Sunday I'm going to Tokyo with a friend." },
          { text: 'いつ日本に来ましたか。', reading: 'いつ にほん に きました か。', en: 'When did you come to Japan?' },
          { text: '土曜日にひとりできょうとへ行きました。', reading: 'どようび に ひとり で きょうと へ いきました。', en: 'On Saturday I went to Kyoto by myself.' },
          { text: 'だれと行きますか。', reading: 'だれ と いきます か。', en: 'Who are you going with?' },
          { text: 'らいしゅうの木曜日におおさかへ行きます。', reading: 'らいしゅう の もくようび に おおさか へ いきます。', en: "I'm going to Osaka next Thursday." },
        ],
        drills: [
          { text: '友だち___としょかんへ行きます。', reading: 'ともだち ___ としょかん へ いきます。', en: "I'm going to the library with a friend.", answer: 'と', distractors: ['で', 'に', 'を'] },
          { text: '___国へ帰りますか。', reading: '___ くに へ かえります か。', en: 'When are you going back to your country?', answer: 'いつ', distractors: ['どこ', 'だれ', 'なに'] },
          { text: '土曜日___デパートへ行きます。', reading: 'どようび ___ デパート へ いきます。', en: "I'm going to the department store on Saturday.", answer: 'に', distractors: ['で', 'を', 'と'] },
          { text: '「いつ行きますか。」「___に行きます。」', reading: '「いつ いきます か。」 「___ に いきます。」', en: '"When are you going?" "I\'m going on Friday."', answer: '金曜日', distractors: ['月曜日', '火曜日', '土曜日'] },
          { text: 'ひとり___えきへ行きました。', reading: 'ひとり ___ えき へ いきました。', en: 'I went to the station alone.', answer: 'で', distractors: ['と', 'に', 'を'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n5-05-01', text: '行く', reading: 'いく', en: 'to go', pos: 'verb', example: { text: 'あした、えきへ行きます。', reading: 'あした、 えき へ いきます。', en: "I'll go to the station tomorrow." } },
      { id: 'v-ja-n5-05-02', text: '来る', reading: 'くる', en: 'to come', pos: 'verb', example: { text: '先生は9時に来ます。', reading: 'せんせい は くじ に きます。', en: 'The teacher comes at nine.' } },
      { id: 'v-ja-n5-05-03', text: '帰る', reading: 'かえる', en: 'to go home; to return', pos: 'verb', example: { text: '何時にうちに帰りますか。', reading: 'なんじ に うち に かえります か。', en: 'What time are you going home?' } },
      { id: 'v-ja-n5-05-04', text: '電車', reading: 'でんしゃ', en: 'train', pos: 'noun', example: { text: '電車でかいしゃへ行きます。', reading: 'でんしゃ で かいしゃ へ いきます。', en: 'I go to work by train.' } },
      { id: 'v-ja-n5-05-05', text: 'バス', en: 'bus', pos: 'noun', example: { text: 'バスで学校に来ました。', reading: 'バス で がっこう に きました。', en: 'I came to school by bus.' } },
      { id: 'v-ja-n5-05-06', text: 'じてんしゃ', en: 'bicycle', pos: 'noun', example: { text: 'じてんしゃでとしょかんへ行きます。', reading: 'じてんしゃ で としょかん へ いきます。', en: 'I go to the library by bicycle.' } },
      { id: 'v-ja-n5-05-07', text: 'ひこうき', en: 'airplane', pos: 'noun', example: { text: 'ひこうきで日本に来ました。', reading: 'ひこうき で にほん に きました。', en: 'I came to Japan by plane.' } },
      { id: 'v-ja-n5-05-08', text: 'あるいて', en: 'on foot; walking', pos: 'adverb', example: { text: 'あるいてえきへ行きます。', reading: 'あるいて えき へ いきます。', en: 'I walk to the station.' } },
      { id: 'v-ja-n5-05-09', text: '学校', reading: 'がっこう', en: 'school', pos: 'noun', example: { text: '日曜日は学校へ行きません。', reading: 'にちようび は がっこう へ いきません。', en: "I don't go to school on Sundays." } },
      { id: 'v-ja-n5-05-10', text: 'かいしゃ', en: 'company; office', pos: 'noun', example: { text: 'かいしゃは東京にあります。', reading: 'かいしゃ は とうきょう に あります。', en: 'My company is in Tokyo.' } },
      { id: 'v-ja-n5-05-11', text: '月曜日', reading: 'げつようび', en: 'Monday', pos: 'noun', example: { text: '月曜日の9時に学校へ行きます。', reading: 'げつようび の くじ に がっこう へ いきます。', en: "I'm going to school at nine on Monday." } },
      { id: 'v-ja-n5-05-12', text: '火曜日', reading: 'かようび', en: 'Tuesday', pos: 'noun', example: { text: '火曜日にとしょかんへ行きます。', reading: 'かようび に としょかん へ いきます。', en: "I'm going to the library on Tuesday." } },
      { id: 'v-ja-n5-05-13', text: '水曜日', reading: 'すいようび', en: 'Wednesday', pos: 'noun', example: { text: '水曜日は何をしますか。', reading: 'すいようび は なに を します か。', en: 'What are you doing on Wednesday?' } },
      { id: 'v-ja-n5-05-14', text: '木曜日', reading: 'もくようび', en: 'Thursday', pos: 'noun', example: { text: '木曜日にひとりでぎんこうへ行きました。', reading: 'もくようび に ひとり で ぎんこう へ いきました。', en: 'On Thursday I went to the bank alone.' } },
      { id: 'v-ja-n5-05-15', text: '金曜日', reading: 'きんようび', en: 'Friday', pos: 'noun', example: { text: '金曜日の午後、国へ帰ります。', reading: 'きんようび の ごご、 くに へ かえります。', en: "I'm going back to my country on Friday afternoon." } },
      { id: 'v-ja-n5-05-16', text: '土曜日', reading: 'どようび', en: 'Saturday', pos: 'noun', example: { text: '土曜日はかいしゃへ行きません。', reading: 'どようび は かいしゃ へ いきません。', en: "I don't go to the office on Saturdays." } },
      { id: 'v-ja-n5-05-17', text: '日曜日', reading: 'にちようび', en: 'Sunday', pos: 'noun', example: { text: '日曜日にどこへ行きましたか。', reading: 'にちようび に どこ へ いきました か。', en: 'Where did you go on Sunday?' } },
      { id: 'v-ja-n5-05-18', text: 'いつ', en: 'when', pos: 'adverb', example: { text: 'いつ東京へ行きますか。', reading: 'いつ とうきょう へ いきます か。', en: 'When are you going to Tokyo?' } },
      { id: 'v-ja-n5-05-19', text: 'ひとりで', en: 'alone; by oneself', pos: 'phrase', example: { text: 'ひとりで来ました。', reading: 'ひとり で きました。', en: 'I came alone.' } },
      { id: 'v-ja-n5-05-20', text: 'しゅうまつ', en: 'weekend', pos: 'noun', example: { text: 'しゅうまつ、どこへ行きますか。', reading: 'しゅうまつ、 どこ へ いきます か。', en: 'Where are you going this weekend?' } },
      { id: 'v-ja-n5-05-21', text: 'らいしゅう', en: 'next week', pos: 'noun', example: { text: 'らいしゅう、友だちが日本に来ます。', reading: 'らいしゅう、 ともだち が にほん に きます。', en: 'A friend is coming to Japan next week.' } },
      { id: 'v-ja-n5-05-22', text: '国', reading: 'くに', en: 'country; home country', pos: 'noun', example: { text: 'リーさんの国はどこですか。', reading: 'リー さん の くに は どこ です か。', en: 'What country are you from, Mr. Lee?' } },
    ],
    scenario: {
      title: 'Weekend plans',
      setting: "It's Friday afternoon at your office in Tokyo. A coworker stops by your desk to chat about the weekend.",
      aiRole: 'Yuki Nakagawa (なかがわさん), a friendly coworker',
      learnerGoal: "Say where you're going this weekend, on which day, how you'll get there, and who you're going with; then ask Yuki about her plans using いつ and だれと.",
      opener: 'おつかれさまです。あしたは土曜日ですね。どこへ行きますか。',
      openerReading: 'おつかれさま です。 あした は どようび です ね。 どこ へ いきます か。',
    },
  },
];
