import type { Unit } from '../types';

/** Japanese units 15–18 (JLPT N4, part 1). */
export const unitsN4a: Unit[] = [
  // ───────────────────────────── N4 ─────────────────────────────
  {
    id: 'ja-n4-01',
    cefr: 'A2',
    order: 15,
    title: '普通形: Plain form and casual speech',
    theme: 'Plain forms and casual conversation with friends',
    canDo: [
      'I can change verbs into the dictionary form and the ない-form.',
      'I can talk about the past in plain form with た and なかった.',
      'I can chat casually with a friend about my weekend.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-01-1',
        title: 'Dictionary form and ない-form',
        summary:
          'Japanese has a polite style (〜ます) and a plain style. The plain style is used with friends and family and inside longer sentences, so you need it for almost all grammar from here on. The dictionary form is the plain present: 食べます (たべます) → 食べる (たべる), 飲みます (のみます) → 飲む (のむ). For the ない-form (plain negative), group 2 verbs drop る and add ない (食べない), while group 1 verbs change the final -u sound to -a and add ない (飲む → 飲まない, 行く (いく) → 行かない); verbs ending in う use わ, so 会う (あう) becomes 会わない (あわない). The irregular verbs are する → しない and 来る (くる) → 来ない (こない). Pitfall: the negative of ある (to have, to exist) is just ない, never あらない.',
        examples: [
          { text: '今日、何する？', reading: 'きょう、 なに する？', en: 'What are you doing today?' },
          { text: '毎朝コーヒーを飲む。', reading: 'まいあさ コーヒー を のむ。', en: 'I drink coffee every morning.' },
          { text: '明日は学校に行かない。', reading: 'あした は がっこう に いかない。', en: "I'm not going to school tomorrow." },
          { text: '時間がない！', reading: 'じかん が ない！', en: "I don't have time!" },
          { text: '日曜日は何もしない。', reading: 'にちようび は なにも しない。', en: "I don't do anything on Sundays." },
        ],
        drills: [
          { text: '毎朝、駅まで歩___。', reading: 'まいあさ、 えき まで ある___。', en: 'I walk to the station every morning.', answer: 'く', distractors: ['かない', 'いた', 'いて'] },
          { text: '肉は食べ___。', reading: 'にく は たべ___。', en: "I don't eat meat.", answer: 'ない', distractors: ['る', 'らない', 'なかった'] },
          { text: '今日は田中さんに会___。', reading: 'きょう は たなか さん に あ___。', en: "I'm not meeting Tanaka today.", answer: 'わない', distractors: ['あない', 'いない', 'うない'] },
          { text: 'お金が___。', reading: 'おかね が ___。', en: "I don't have any money.", answer: 'ない', distractors: ['あらない', 'ありない', 'いない'] },
          { text: '田中さんは今日___。', reading: 'たなか さん は きょう ___。', en: "Tanaka isn't coming today.", answer: 'こない', distractors: ['くない', 'きない', 'くらない'] },
        ],
      },
      {
        id: 'g-ja-n4-01-2',
        title: 'Plain past (た / なかった) in casual conversation',
        summary:
          'The plain past is the casual version of 〜ました and 〜ませんでした. To make the た-form, take the て-form and change て to た, or で to だ: 食べて (たべて) → 食べた, 行って (いって) → 行った, 読んで (よんで) → 読んだ. For the negative past, change the final い of the ない-form to かった: 行かない → 行かなかった, しない → しなかった. Nouns and な-adjectives use だった (雨だった, あめ だった), and い-adjectives use かった (楽しかった, たのしかった). Between friends, people often drop を and は and ask questions with a rising voice instead of か: 映画、見た？ (えいが、 みた？). Pitfall: 行く (いく) is irregular, so its past is 行った, not 行いた.',
        examples: [
          { text: '土曜日、友だちとカラオケに行った。', reading: 'どようび、 ともだち と カラオケ に いった。', en: 'On Saturday I went to karaoke with friends.' },
          { text: '朝ごはん、食べなかった。', reading: 'あさごはん、 たべなかった。', en: "I didn't eat breakfast." },
          { text: '昨日は雨だった。', reading: 'きのう は あめ だった。', en: 'It was rainy yesterday.' },
          { text: 'パーティー、楽しかった？', reading: 'パーティー、 たのしかった？', en: 'Was the party fun?' },
          { text: 'あの映画、見た？', reading: 'あの えいが、 みた？', en: 'Have you seen that movie?' },
        ],
        drills: [
          { text: '昨日の夜、何し___？', reading: 'きのう の よる、 なに し___？', en: 'What did you do last night?', answer: 'た', distractors: ['て', 'ます', 'なかった'] },
          { text: '先週、新しいゲームを買___。', reading: 'せんしゅう、 あたらしい ゲーム を か___。', en: 'I bought a new game last week.', answer: 'った', distractors: ['いた', 'んだ', 'わなかった'] },
          { text: '土日はどこにも行か___。', reading: 'どにち は どこ に も いか___。', en: "I didn't go anywhere over the weekend.", answer: 'なかった', distractors: ['ない', 'なくて', 'った'] },
          { text: 'あの本、もう読___？', reading: 'あの ほん、 もう よ___？', en: 'Have you read that book yet?', answer: 'んだ', distractors: ['った', 'みた', 'いた'] },
          { text: '日曜日、友だちがうちに来___。', reading: 'にちようび、 ともだち が うち に き___。', en: 'A friend came over to my place on Sunday.', answer: 'た', distractors: ['て', 'ます', 'たい'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-01-01', text: 'ひさしぶり', en: 'long time no see', pos: 'phrase', example: { text: 'ひさしぶり！元気だった？', reading: 'ひさしぶり！ げんき だった？', en: 'Long time no see! How have you been?' } },
      { id: 'v-ja-n4-01-02', text: 'さいきん', en: 'recently; lately', pos: 'adverb', example: { text: 'さいきん、よくジムに行く。', reading: 'さいきん、 よく ジム に いく。', en: "Lately I've been going to the gym a lot." } },
      { id: 'v-ja-n4-01-03', text: 'じつは', en: 'actually; to tell the truth', pos: 'adverb', example: { text: 'じつは、土曜日に友だちとけんかした。', reading: 'じつは、 どようび に ともだち と けんか した。', en: 'Actually, I had a fight with a friend on Saturday.' } },
      { id: 'v-ja-n4-01-04', text: 'そうじする', en: 'to clean (a room, a house)', pos: 'verb', example: { text: '日曜日は家をそうじした。', reading: 'にちようび は いえ を そうじ した。', en: 'On Sunday I cleaned the house.' } },
      { id: 'v-ja-n4-01-05', text: 'せんたくする', en: 'to do the laundry', pos: 'verb', example: { text: '朝、せんたくをした。', reading: 'あさ、 せんたく を した。', en: 'I did the laundry in the morning.' } },
      { id: 'v-ja-n4-01-06', text: 'かたづける', en: 'to tidy up; to put away', pos: 'verb', example: { text: '昨日、本だなをかたづけた。', reading: 'きのう、 ほんだな を かたづけた。', en: 'Yesterday I tidied up my bookshelf.' } },
      { id: 'v-ja-n4-01-07', text: 'つかれる', en: 'to get tired', pos: 'verb', example: { text: '今日はすごくつかれた。', reading: 'きょう は すごく つかれた。', en: "I'm really tired today." } },
      { id: 'v-ja-n4-01-08', text: '楽しみ', reading: 'たのしみ', en: 'something to look forward to', pos: 'noun', example: { text: '土曜日のライブ、楽しみ！', reading: 'どようび の ライブ、 たのしみ！', en: "I can't wait for Saturday's concert!" } },
      { id: 'v-ja-n4-01-09', text: '集まる', reading: 'あつまる', en: 'to gather; to get together', pos: 'verb', example: { text: '先週、高校の友だちと集まった。', reading: 'せんしゅう、 こうこう の ともだち と あつまった。', en: 'Last week I got together with my high school friends.' } },
      { id: 'v-ja-n4-01-10', text: '試合', reading: 'しあい', en: 'match; game (sports)', pos: 'noun', example: { text: '昨日のサッカーの試合、見た？', reading: 'きのう の サッカー の しあい、 みた？', en: "Did you watch yesterday's soccer match?" } },
      { id: 'v-ja-n4-01-11', text: '気持ちいい', reading: 'きもちいい', en: 'feels good; pleasant', pos: 'adjective', example: { text: '朝のさんぽは気持ちいい。', reading: 'あさ の さんぽ は きもちいい。', en: 'A morning walk feels great.' } },
      { id: 'v-ja-n4-01-12', text: 'すごく', en: 'really; super (casual)', pos: 'adverb', example: { text: 'このラーメン、すごくおいしい。', reading: 'この ラーメン、 すごく おいしい。', en: 'This ramen is super good.' } },
      { id: 'v-ja-n4-01-13', text: 'うん', en: 'yeah; uh-huh (casual yes)', pos: 'interjection', example: { text: '「行く？」「うん、行く。」', reading: '「いく？」「うん、 いく。」', en: "—Are you going? —Yeah, I'm going." } },
      { id: 'v-ja-n4-01-14', text: 'ううん', en: 'nope; uh-uh (casual no)', pos: 'interjection', example: { text: '「昨日、学校に行った？」「ううん、行かなかった。」', reading: '「きのう、 がっこう に いった？」「ううん、 いかなかった。」', en: "—Did you go to school yesterday? —Nope, I didn't." } },
      { id: 'v-ja-n4-01-15', text: 'やっぱり', en: 'as I thought; sure enough; after all', pos: 'adverb', example: { text: 'やっぱり、雨がふった。', reading: 'やっぱり、 あめ が ふった。', en: 'Sure enough, it rained.' } },
      { id: 'v-ja-n4-01-16', text: 'ずっと', en: 'the whole time; all along', pos: 'adverb', example: { text: '日曜日はずっと家にいた。', reading: 'にちようび は ずっと いえ に いた。', en: 'I was at home the whole time on Sunday.' } },
      { id: 'v-ja-n4-01-17', text: '別に', reading: 'べつに', en: 'not really; not particularly', pos: 'adverb', example: { text: '「何かあった？」「別に。」', reading: '「なにか あった？」「べつに。」', en: '—Did something happen? —Not really.' } },
      { id: 'v-ja-n4-01-18', text: 'ねむい', en: 'sleepy', pos: 'adjective', example: { text: '今朝はすごくねむかった。', reading: 'けさ は すごく ねむかった。', en: 'I was really sleepy this morning.' } },
      { id: 'v-ja-n4-01-19', text: 'ごろごろする', en: 'to laze around', pos: 'verb', example: { text: '昨日は一日中、家でごろごろした。', reading: 'きのう は いちにちじゅう、 いえ で ごろごろ した。', en: 'Yesterday I lazed around at home all day.' } },
      { id: 'v-ja-n4-01-20', text: '帰り', reading: 'かえり', en: 'the way home; return', pos: 'noun', example: { text: '帰りにラーメンを食べた。', reading: 'かえり に ラーメン を たべた。', en: 'I had ramen on the way home.' } },
      { id: 'v-ja-n4-01-21', text: 'まあまあ', en: 'so-so; okay', pos: 'adverb', example: { text: '「テスト、どうだった？」「まあまあだった。」', reading: '「テスト、 どう だった？」「まあまあ だった。」', en: '—How was the test? —It was okay.' } },
    ],
    scenario: {
      title: 'Catching up after the weekend',
      setting: "It's Monday lunchtime in your university cafeteria in Tokyo. Your friend Yuta sits down next to you and wants to hear about your weekend.",
      aiRole: 'Yuta (ゆうた), a friendly classmate who loves soccer. He speaks only casual, plain-form Japanese.',
      learnerGoal:
        'Using plain forms only (no です/ます), tell Yuta two things you did and one thing you didn\'t do over the weekend, ask what he did, and react to his story with casual replies like うん, ほんと？ or いいね.',
      opener: 'ねえ、土日、何した？ぼくはサッカーの試合を見に行ったよ。',
      openerReading: 'ねえ、 どにち、 なに した？ ぼく は サッカー の しあい を みに いった よ。',
    },
  },
  {
    id: 'ja-n4-02',
    cefr: 'A2',
    order: 16,
    title: 'ルール: Permission and obligation',
    theme: 'Rules, permission, and obligation at work',
    canDo: [
      'I can ask for permission and say what is not allowed.',
      'I can say what someone has to do and does not have to do.',
      'I can understand the rules on my first day at a part-time job.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-02-1',
        title: '〜てもいい and 〜てはいけない: may and must not',
        summary:
          "To ask for or give permission, use the て-form + もいいです: 写真をとってもいいですか (しゃしん を とって も いい です か) 'May I take a photo?' Answer はい、いいですよ for yes; to refuse politely, people usually say すみません、ちょっと… instead of a direct no. To say something is not allowed, use the て-form + はいけません: ここでたばこをすってはいけません 'You must not smoke here.' 〜てはいけない sounds strong, so it is mostly used for rules and signs, or by parents and teachers; between friends you will hear 〜てもいい？ and だめ. Pitfall: the は in 〜てはいけない is the particle は, so it is pronounced wa.",
        examples: [
          { text: '中に入ってもいいですか。', reading: 'なか に はいって も いい です か。', en: 'May I come in?' },
          { text: 'きゅうけい中は、スマホを使ってもいいですよ。', reading: 'きゅうけいちゅう は、 スマホ を つかって も いい です よ。', en: 'You can use your phone during your break.' },
          { text: '店の中でたばこをすってはいけません。', reading: 'みせ の なか で たばこ を すって は いけません。', en: 'You must not smoke inside the store.' },
          { text: 'このペン、使ってもいい？', reading: 'この ペン、 つかって も いい？', en: 'Can I use this pen?' },
          { text: '図書館で電話してはいけません。', reading: 'としょかん で でんわ して は いけません。', en: 'You must not make phone calls in the library.' },
        ],
        drills: [
          { text: 'ここで写真をとっ___いいですか。', reading: 'ここ で しゃしん を とっ___ いい です か。', en: 'May I take pictures here?', answer: 'ても', distractors: ['ては', 'でも', 'たり'] },
          { text: '教室で物を食べ___いけません。', reading: 'きょうしつ で もの を たべ___ いけません。', en: 'You must not eat in the classroom.', answer: 'ては', distractors: ['ても', 'では', 'たり'] },
          { text: 'ここに車を止めては___。', reading: 'ここ に くるま を とめて は ___。', en: 'You must not park your car here.', answer: 'いけません', distractors: ['いいです', 'いけます', 'ありません'] },
          { text: '明日、休ん___もいいですか。', reading: 'あした、 やすん___ も いい です か。', en: 'May I take tomorrow off?', answer: 'で', distractors: ['て', 'だ', 'に'] },
          { text: '「まどを開けてもいいですか。」「はい、___よ。」', reading: '「まど を あけて も いい です か。」「はい、 ___ よ。」', en: '—May I open the window? —Sure, go ahead.', answer: 'いいです', distractors: ['いけません', 'だめです', 'いけます'] },
        ],
      },
      {
        id: 'g-ja-n4-02-2',
        title: '〜なければならない and 〜なくてもいい: must and don\'t have to',
        summary:
          "To say you must do something, take the ない-form, drop the final い, and add ければなりません (polite) or ければならない (plain): 行かない (いかない) → 行かなければなりません 'I have to go.' 〜なければいけません means the same and is just as common, and in casual speech both shrink to 〜なきゃ: もう帰らなきゃ (もう かえらなきゃ) 'I've got to go home.' To say you don't have to do something, change ない to なくてもいいです: 来なくてもいいです (こなくて も いい です) 'You don't have to come.' Pitfall: 'don't have to' is 〜なくてもいい, while 〜てはいけない means 'must not', so don't mix them up.",
        examples: [
          { text: '毎朝、8時までに店に来なければなりません。', reading: 'まいあさ、 はちじ までに みせ に こなければ なりません。', en: 'You have to come to the store by 8:00 every morning.' },
          { text: '店ではせいふくを着なければなりません。', reading: 'みせ で は せいふく を きなければ なりません。', en: 'You have to wear a uniform in the store.' },
          { text: '土曜日は来なくてもいいです。', reading: 'どようび は こなくて も いい です。', en: "You don't have to come in on Saturdays." },
          { text: 'もう帰らなきゃ。', reading: 'もう かえらなきゃ。', en: "I've got to go home now." },
          { text: '名前は書かなくてもいいですよ。', reading: 'なまえ は かかなくて も いい です よ。', en: "You don't need to write your name." },
        ],
        drills: [
          { text: '毎日、日本語を勉強___なければなりません。', reading: 'まいにち、 にほんご を べんきょう ___なければ なりません。', en: 'I have to study Japanese every day.', answer: 'し', distractors: ['す', 'さ', 'せ'] },
          { text: '明日は早く起き___もいいです。', reading: 'あした は はやく おき___ も いい です。', en: "You don't have to get up early tomorrow.", answer: 'なくて', distractors: ['なければ', 'て', 'ない'] },
          { text: 'レジでは、おきゃくさんにあいさつしなければ___。', reading: 'レジ で は、 おきゃくさん に あいさつ しなければ ___。', en: 'At the register, you have to greet customers.', answer: 'なりません', distractors: ['なります', 'ありません', 'いけます'] },
          { text: 'お金ははらわなくても___。', reading: 'おかね は はらわなくて も ___。', en: "You don't have to pay.", answer: 'いいです', distractors: ['いけません', 'なりません', 'ありません'] },
          { text: 'もう9時だ。早く帰ら___。', reading: 'もう くじ だ。 はやく かえら___。', en: "It's already nine. I've got to get home.", answer: 'なきゃ', distractors: ['なくても', 'ちゃ', 'ない'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-02-01', text: 'アルバイト', en: 'part-time job', pos: 'noun', example: { text: 'コンビニでアルバイトをしています。', reading: 'コンビニ で アルバイト を して います。', en: "I'm working part-time at a convenience store." } },
      { id: 'v-ja-n4-02-02', text: 'シフト', en: 'shift (at work)', pos: 'noun', example: { text: '来週のシフトを教えてください。', reading: 'らいしゅう の シフト を おしえて ください。', en: 'Please tell me my shifts for next week.' } },
      { id: 'v-ja-n4-02-03', text: 'おきゃくさん', en: 'customer; guest', pos: 'noun', example: { text: 'おきゃくさんに「いらっしゃいませ」と言います。', reading: 'おきゃくさん に 「いらっしゃいませ」 と いいます。', en: 'We say "irasshaimase" (welcome) to customers.' } },
      { id: 'v-ja-n4-02-04', text: 'レジ', en: 'cash register; checkout', pos: 'noun', example: { text: '今日はレジをおねがいします。', reading: 'きょう は レジ を おねがいします。', en: 'Please work the register today.' } },
      { id: 'v-ja-n4-02-05', text: 'せいふく', en: 'uniform', pos: 'noun', example: { text: 'せいふくはロッカーの中にあります。', reading: 'せいふく は ロッカー の なか に あります。', en: 'Your uniform is in the locker.' } },
      { id: 'v-ja-n4-02-06', text: 'ルール', en: 'rule', pos: 'noun', example: { text: '店のルールを教えてください。', reading: 'みせ の ルール を おしえて ください。', en: 'Please tell me the store rules.' } },
      { id: 'v-ja-n4-02-07', text: 'きゅうけい', en: 'break; rest', pos: 'noun', example: { text: 'きゅうけいは30分です。', reading: 'きゅうけい は さんじゅっぷん です。', en: 'The break is thirty minutes.' } },
      { id: 'v-ja-n4-02-08', text: 'すう', en: 'to smoke; to breathe in', pos: 'verb', example: { text: 'ここでたばこをすわないでください。', reading: 'ここ で たばこ を すわないで ください。', en: 'Please do not smoke here.' } },
      { id: 'v-ja-n4-02-09', text: 'ゴミ', en: 'trash; garbage', pos: 'noun', example: { text: 'ゴミは外に出してください。', reading: 'ゴミ は そと に だして ください。', en: 'Please take the trash outside.' } },
      { id: 'v-ja-n4-02-10', text: 'すてる', en: 'to throw away', pos: 'verb', example: { text: 'ここにゴミをすててはいけません。', reading: 'ここ に ゴミ を すてて は いけません。', en: 'You must not throw trash away here.' } },
      { id: 'v-ja-n4-02-11', text: '止める', reading: 'とめる', en: 'to park; to stop (something)', pos: 'verb', example: { text: '自転車はここに止めてください。', reading: 'じてんしゃ は ここ に とめて ください。', en: 'Please park your bike here.' } },
      { id: 'v-ja-n4-02-12', text: '運ぶ', reading: 'はこぶ', en: 'to carry', pos: 'verb', example: { text: 'このはこを運んでください。', reading: 'この はこ を はこんで ください。', en: 'Please carry this box.' } },
      { id: 'v-ja-n4-02-13', text: '用意する', reading: 'ようい する', en: 'to prepare; to get ready', pos: 'verb', example: { text: 'パーティーの食べ物を用意しました。', reading: 'パーティー の たべもの を ようい しました。', en: 'I prepared the food for the party.' } },
      { id: 'v-ja-n4-02-14', text: '説明する', reading: 'せつめい する', en: 'to explain', pos: 'verb', example: { text: 'すみません、もう一度説明してください。', reading: 'すみません、 もう いちど せつめい して ください。', en: 'Excuse me, please explain it once more.' } },
      { id: 'v-ja-n4-02-15', text: '気をつける', reading: 'き を つける', en: 'to be careful; to watch out', pos: 'phrase', example: { text: '車に気をつけてください。', reading: 'くるま に き を つけて ください。', en: 'Watch out for cars.' } },
      { id: 'v-ja-n4-02-16', text: 'あいさつする', en: 'to greet; to say hello', pos: 'verb', example: { text: 'おきゃくさんに元気にあいさつしましょう。', reading: 'おきゃくさん に げんき に あいさつ しましょう。', en: "Let's greet customers cheerfully." } },
      { id: 'v-ja-n4-02-17', text: 'かならず', en: 'always; without fail', pos: 'adverb', example: { text: 'かならず手を洗ってください。', reading: 'かならず て を あらって ください。', en: 'Be sure to wash your hands.' } },
      { id: 'v-ja-n4-02-18', text: 'きんし', en: 'prohibited; not allowed', pos: 'noun', example: { text: 'ここで写真をとるのはきんしです。', reading: 'ここ で しゃしん を とる の は きんし です。', en: 'Taking photos is prohibited here.' } },
      { id: 'v-ja-n4-02-19', text: 'ひつよう', en: 'necessary (na-adj.)', pos: 'adjective', example: { text: '明日はエプロンがひつようです。', reading: 'あした は エプロン が ひつよう です。', en: "You'll need an apron tomorrow." } },
      { id: 'v-ja-n4-02-20', text: 'ていねい', en: 'polite; careful (na-adj.)', pos: 'adjective', example: { text: 'ていねいなことばで話してください。', reading: 'ていねい な ことば で はなして ください。', en: 'Please speak in polite language.' } },
      { id: 'v-ja-n4-02-21', text: '特に', reading: 'とくに', en: 'especially', pos: 'adverb', example: { text: '朝は特にいそがしいです。', reading: 'あさ は とくに いそがしい です。', en: 'Mornings are especially busy.' } },
    ],
    scenario: {
      title: 'First day at the convenience store',
      setting: "It's your first shift at a convenience store near Shinjuku Station in Tokyo. Before you start, the store manager explains the rules in the back room.",
      aiRole: 'Mr. Yamamoto (山本さん), the store manager: kind, but strict about the rules. He speaks polite Japanese.',
      learnerGoal:
        'Listen to the rules, ask permission for at least two things (for example, using your phone on a break or drinking water at the register) with 〜てもいいですか, ask what you have to do with 〜なければなりませんか, and check one thing you don\'t have to do.',
      opener: 'おはようございます。店長の山本です。今日からよろしくおねがいします。じゃあ、まず店のルールを説明しますね。',
      openerReading:
        'おはようございます。 てんちょう の やまもと です。 きょう から よろしく おねがいします。 じゃあ、 まず みせ の ルール を せつめい します ね。',
    },
  },
  {
    id: 'ja-n4-03',
    cefr: 'A2',
    order: 17,
    title: '経験: Experiences and advice',
    theme: 'Life experiences, travel, and giving advice',
    canDo: [
      'I can talk about things I have done and have never done.',
      'I can give advice with 〜たほうがいい and 〜ないほうがいい.',
      'I can list a few things I did with 〜たり〜たりする.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-03-1',
        title: '〜たことがある: have you ever…?',
        summary:
          "To talk about experiences, use the plain past (た-form) + ことがある: 京都に行ったことがあります (きょうと に いった こと が あります) 'I have been to Kyoto.' For 'I have never…', use ことがない or ことがありません, and add 一度も (いちど も) for 'not even once'. Use 〜回 (かい) to say how many times: 二回 (にかい) 'twice'. In casual speech the が is often dropped: 食べたことある？ (たべた こと ある？) 'Have you ever eaten it?' Pitfall: ことがある is for experiences at some point in your life, not for a specific recent event; for 'I went to Kyoto last week', just say 先週京都に行きました (せんしゅう きょうと に いきました).",
        examples: [
          { text: '着物を着たことがありますか。', reading: 'きもの を きた こと が あります か。', en: 'Have you ever worn a kimono?' },
          { text: 'カラオケで日本の歌を歌ったことがあります。', reading: 'カラオケ で にほん の うた を うたった こと が あります。', en: "I've sung Japanese songs at karaoke." },
          { text: 'ゆきを一度も見たことがない。', reading: 'ゆき を いちど も みた こと が ない。', en: "I've never seen snow, not even once." },
          { text: '京都には3回行ったことがある。', reading: 'きょうと に は さんかい いった こと が ある。', en: "I've been to Kyoto three times." },
          { text: '「おんせんに入ったことある？」「ううん、まだない。」', reading: '「おんせん に はいった こと ある？」「ううん、 まだ ない。」', en: "—Have you ever been in a hot spring? —No, not yet." },
        ],
        drills: [
          { text: 'すしを食べ___ことがありますか。', reading: 'すし を たべ___ こと が あります か。', en: 'Have you ever eaten sushi?', answer: 'た', distractors: ['る', 'て', 'ない'] },
          { text: 'ゴルフをしたことが___。', reading: 'ゴルフ を した こと が ___。', en: "I've never played golf.", answer: 'ありません', distractors: ['あります', 'いません', 'しません'] },
          { text: 'すもうは一度___見たことがない。', reading: 'すもう は いちど ___ みた こと が ない。', en: "I've never watched sumo, not even once.", answer: 'も', distractors: ['は', 'が', 'に'] },
          { text: '北海道には一回行___ことがある。', reading: 'ほっかいどう に は いっかい い___ こと が ある。', en: "I've been to Hokkaido once.", answer: 'った', distractors: ['く', 'って', 'きた'] },
          { text: 'この映画、見たこと___？', reading: 'この えいが、 みた こと ___？', en: 'Have you ever seen this movie?', answer: 'ある', distractors: ['いる', 'する', 'なる'] },
        ],
      },
      {
        id: 'g-ja-n4-03-2',
        title: '〜たほうがいい and 〜たり〜たりする: advice and listing actions',
        summary:
          "To give advice, use the た-form + ほうがいい: 早くねたほうがいい (はやく ねた ほう が いい) 'You'd better go to bed early.' For negative advice, use the ない-form + ほうがいい: 行かないほうがいい (いかない ほう が いい) 'You'd better not go', not 行かなかったほうがいい. Advice can sound pushy, so with people above you it is often softened with と思います (と おもいます). 〜たり〜たりする lists a few example actions out of many ('do things like A and B'): add り to the た-form of each verb and finish with する in the right tense: 本を読んだり、映画を見たりしました (ほん を よんだり、 えいが を みたり しました). Pitfall: don't forget the final する; it carries the tense and politeness of the whole sentence.",
        examples: [
          { text: '早めによやくしたほうがいいよ。', reading: 'はやめに よやく した ほう が いい よ。', en: "You'd better book early." },
          { text: 'あまりおさけを飲まないほうがいいですよ。', reading: 'あまり おさけ を のまない ほう が いい です よ。', en: "You'd better not drink too much alcohol." },
          { text: '京都でおてらを見たり、着物を着たりした。', reading: 'きょうと で おてら を みたり、 きもの を きたり した。', en: 'In Kyoto I did things like visit temples and wear a kimono.' },
          { text: '休みの日は、そうじをしたり、買い物に行ったりします。', reading: 'やすみ の ひ は、 そうじ を したり、 かいもの に いったり します。', en: 'On my days off, I do things like clean and go shopping.' },
          { text: 'かぜをひいた？早くねたほうがいいよ。', reading: 'かぜ を ひいた？ はやく ねた ほう が いい よ。', en: 'Did you catch a cold? You should go to bed early.' },
        ],
        drills: [
          { text: 'ちょっと休ん___ほうがいいよ。', reading: 'ちょっと やすん___ ほう が いい よ。', en: 'You should rest a little.', answer: 'だ', distractors: ['で', 'じゃ', 'だり'] },
          { text: '夜は一人で出かけ___ほうがいいですよ。', reading: 'よる は ひとり で でかけ___ ほう が いい です よ。', en: "You'd better not go out alone at night.", answer: 'ない', distractors: ['なかった', 'た', 'て'] },
          { text: '日曜日は本を読んだり、テレビを見たり___。', reading: 'にちようび は ほん を よんだり、 テレビ を みたり ___。', en: 'On Sunday I did things like read and watch TV.', answer: 'した', distractors: ['する', 'だった', 'しない'] },
          { text: '夏休みは海でおよいだり、花火を見___しました。', reading: 'なつやすみ は うみ で およいだり、 はなび を み___ しました。', en: 'During summer vacation, I did things like swim in the sea and watch fireworks.', answer: 'たり', distractors: ['て', 'た', 'たら'] },
          { text: 'ホテルはよやくし___ほうがいいですか。', reading: 'ホテル は よやく し___ ほう が いい です か。', en: 'Should I book the hotel?', answer: 'た', distractors: ['て', 'たり', 'ない'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-03-01', text: 'けいけん', en: 'experience', pos: 'noun', example: { text: '一人で旅行したのは、いいけいけんだった。', reading: 'ひとり で りょこう した の は、 いい けいけん だった。', en: 'Traveling alone was a good experience.' } },
      { id: 'v-ja-n4-03-02', text: 'しんかんせん', en: 'bullet train; shinkansen', pos: 'noun', example: { text: 'しんかんせんに乗ったことがありますか。', reading: 'しんかんせん に のった こと が あります か。', en: 'Have you ever ridden the shinkansen?' } },
      { id: 'v-ja-n4-03-03', text: '計画', reading: 'けいかく', en: 'plan', pos: 'noun', example: { text: '旅行の計画はもうできた？', reading: 'りょこう の けいかく は もう できた？', en: 'Is your trip plan ready yet?' } },
      { id: 'v-ja-n4-03-04', text: '旅館', reading: 'りょかん', en: 'traditional Japanese inn', pos: 'noun', example: { text: '京都の旅館にとまった。', reading: 'きょうと の りょかん に とまった。', en: 'I stayed at a ryokan in Kyoto.' } },
      { id: 'v-ja-n4-03-05', text: 'とまる', en: 'to stay (overnight)', pos: 'verb', example: { text: '友だちの家にとまった。', reading: 'ともだち の いえ に とまった。', en: "I stayed over at a friend's house." } },
      { id: 'v-ja-n4-03-06', text: 'よやくする', en: 'to make a reservation; to book', pos: 'verb', example: { text: 'レストラン、よやくした？', reading: 'レストラン、 よやく した？', en: 'Did you book the restaurant?' } },
      { id: 'v-ja-n4-03-07', text: 'おんせん', en: 'hot spring', pos: 'noun', example: { text: '山の中のおんせんは、気持ちよかった。', reading: 'やま の なか の おんせん は、 きもちよかった。', en: 'The hot spring in the mountains felt wonderful.' } },
      { id: 'v-ja-n4-03-08', text: '着物', reading: 'きもの', en: 'kimono', pos: 'noun', example: { text: '着物を着て、写真をとった。', reading: 'きもの を きて、 しゃしん を とった。', en: 'I put on a kimono and took photos.' } },
      { id: 'v-ja-n4-03-09', text: 'おてら', en: 'Buddhist temple', pos: 'noun', example: { text: '京都には古いおてらがたくさんある。', reading: 'きょうと に は ふるい おてら が たくさん ある。', en: 'There are lots of old temples in Kyoto.' } },
      { id: 'v-ja-n4-03-10', text: 'じんじゃ', en: 'Shinto shrine', pos: 'noun', example: { text: 'お正月にじんじゃに行った。', reading: 'おしょうがつ に じんじゃ に いった。', en: "I went to a shrine at New Year's." } },
      { id: 'v-ja-n4-03-11', text: 'けしき', en: 'scenery; view', pos: 'noun', example: { text: '山の上からのけしきは、すごくきれいだった。', reading: 'やま の うえ から の けしき は、 すごく きれい だった。', en: 'The view from the top of the mountain was really beautiful.' } },
      { id: 'v-ja-n4-03-12', text: 'めずらしい', en: 'rare; unusual', pos: 'adjective', example: { text: 'ゆきは東京ではめずらしい。', reading: 'ゆき は とうきょう で は めずらしい。', en: 'Snow is rare in Tokyo.' } },
      { id: 'v-ja-n4-03-13', text: 'のぼる', en: 'to climb', pos: 'verb', example: { text: 'いつかふじさんにのぼりたい。', reading: 'いつか ふじさん に のぼりたい。', en: 'Someday I want to climb Mt. Fuji.' } },
      { id: 'v-ja-n4-03-14', text: 'しらべる', en: 'to look up; to check', pos: 'verb', example: { text: '行く前に、ネットでしらべた。', reading: 'いく まえ に、 ネット で しらべた。', en: 'I looked it up online before going.' } },
      { id: 'v-ja-n4-03-15', text: 'にもつ', en: 'luggage; bags', pos: 'noun', example: { text: 'にもつは少ないほうがいいよ。', reading: 'にもつ は すくない ほう が いい よ。', en: "It's better to pack light." } },
      { id: 'v-ja-n4-03-16', text: 'きせつ', en: 'season', pos: 'noun', example: { text: '日本ではどのきせつがいちばん好き？', reading: 'にほん で は どの きせつ が いちばん すき？', en: 'Which season do you like best in Japan?' } },
      { id: 'v-ja-n4-03-17', text: '一度', reading: 'いちど', en: 'once; one time', pos: 'noun', example: { text: '一度、ふじさんにのぼったことがある。', reading: 'いちど、 ふじさん に のぼった こと が ある。', en: "I've climbed Mt. Fuji once." } },
      { id: 'v-ja-n4-03-18', text: '回', reading: 'かい', en: 'times (counter for occurrences)', pos: 'counter', example: { text: 'この映画は2回見た。', reading: 'この えいが は にかい みた。', en: "I've watched this movie twice." } },
      { id: 'v-ja-n4-03-19', text: '楽しむ', reading: 'たのしむ', en: 'to enjoy', pos: 'verb', example: { text: '京都の旅行、楽しんでね！', reading: 'きょうと の りょこう、 たのしんで ね！', en: 'Enjoy your trip to Kyoto!' } },
      { id: 'v-ja-n4-03-20', text: 'まつり', en: 'festival', pos: 'noun', example: { text: '夏のまつりで、ゆかたを着たり、花火を見たりした。', reading: 'なつ の まつり で、 ゆかた を きたり、 はなび を みたり した。', en: 'At the summer festival, I did things like wear a yukata and watch fireworks.' } },
      { id: 'v-ja-n4-03-21', text: 'げんきん', en: 'cash', pos: 'noun', example: { text: '小さい店では、げんきんがひつようだよ。', reading: 'ちいさい みせ で は、 げんきん が ひつよう だ よ。', en: 'You need cash at small shops.' } },
    ],
    scenario: {
      title: 'Tips for a trip to Kyoto',
      setting: "You're at a café in Tokyo with your friend Kenta, who is going to Kyoto for the first time next month. You've been there before, so he asks you for tips.",
      aiRole: 'Kenta (けんた), a university friend who has never been to Kyoto. He speaks casually and asks lots of questions.',
      learnerGoal:
        "Say what you've done in Kyoto with 〜たことがある, describe your trip with 〜たり〜たりした, and give Kenta at least two pieces of advice with 〜たほうがいい and 〜ないほうがいい (for example, about booking, cash, or crowds).",
      opener: 'ねえ、来月、京都に旅行するんだ。京都に行ったことある？',
      openerReading: 'ねえ、 らいげつ、 きょうと に りょこう する ん だ。 きょうと に いった こと ある？',
    },
  },
  {
    id: 'ja-n4-04',
    cefr: 'A2',
    order: 18,
    title: '理由と説明: Reasons and describing people',
    theme: 'Giving reasons and excuses, and describing people',
    canDo: [
      'I can give reasons with から and ので.',
      "I can apologize for being late and explain why.",
      'I can describe people with noun-modifying clauses and say when things happened with 〜とき.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-04-1',
        title: 'から and ので: because, so',
        summary:
          "Both から and ので mean 'because' or 'so', and they come right after the reason: [reason] から/ので [result]. Unlike English 'because', the reason always comes first: 雨だから、行かない (あめ だ から、 いかない) 'It's raining, so I'm not going.' から is direct and very common in conversation; ので sounds softer and more objective, so it is better for excuses and polite requests: 電車がおくれたので、ちこくしました (でんしゃ が おくれた ので、 ちこく しました). After nouns and な-adjectives, use だから but なので: 学生 (がくせい) だから / 学生なので. Pitfall: 学生ので and しずかので are wrong; you need な before ので. To answer a どうして (why) question, you can give just the reason + から.",
        examples: [
          { text: 'バスが来なかったので、タクシーで来ました。', reading: 'バス が こなかった ので、 タクシー で きました。', en: "The bus didn't come, so I came by taxi." },
          { text: '明日はテストだから、今日は早くねる。', reading: 'あした は テスト だ から、 きょう は はやく ねる。', en: "I have a test tomorrow, so I'm going to bed early tonight." },
          { text: 'この町はしずかなので、好きです。', reading: 'この まち は しずか な ので、 すき です。', en: "I like this town because it's quiet." },
          { text: '「どうして食べないの？」「おなかがいっぱいだから。」', reading: '「どうして たべない の？」「おなか が いっぱい だ から。」', en: "—Why aren't you eating? —Because I'm full." },
          { text: 'すみません、道がこんでいたので、おくれました。', reading: 'すみません、 みち が こんで いた ので、 おくれました。', en: "Sorry, the roads were crowded, so I'm late." },
        ],
        drills: [
          { text: '雨だ___、今日は家にいる。', reading: 'あめ だ ___、 きょう は いえ に いる。', en: "It's raining, so I'm staying home today.", answer: 'から', distractors: ['ので', 'のに', 'けど'] },
          { text: '学生___ので、お金がありません。', reading: 'がくせい ___ ので、 おかね が ありません。', en: "I'm a student, so I don't have money.", answer: 'な', distractors: ['だ', 'の', 'で'] },
          { text: '電車がおくれた___、ちこくしました。', reading: 'でんしゃ が おくれた ___、 ちこく しました。', en: 'The train was delayed, so I was late.', answer: 'ので', distractors: ['のに', 'けど', 'まで'] },
          { text: '「どうしてちこくしたの？」「ねぼうした___。」', reading: '「どうして ちこく した の？」「ねぼう した ___。」', en: '—Why were you late? —Because I overslept.', answer: 'から', distractors: ['けど', 'のに', 'でも'] },
          { text: 'この店は安___から、よく来ます。', reading: 'この みせ は やす___ から、 よく きます。', en: 'This store is cheap, so I come here often.', answer: 'い', distractors: ['いだ', 'くて', 'く'] },
        ],
      },
      {
        id: 'g-ja-n4-04-2',
        title: 'Noun-modifying clauses (昨日買った本) and 〜とき',
        summary:
          "To describe a noun with a whole clause, put the clause in plain form right before the noun: 昨日買った本 (きのう かった ほん) 'the book I bought yesterday', めがねをかけている人 (めがね を かけて いる ひと) 'the person wearing glasses'. There is no separate word for 'who', 'which', or 'that'. Inside the clause, the subject takes が (or の), not は: 母が作ったケーキ (はは が つくった ケーキ) 'the cake my mother made'. 〜とき ('when') works the same way: plain form + とき, with な after な-adjectives and の after nouns: ひまなとき, 子どものとき (こども の とき). Pitfall: the tense before とき matters: 日本に行くとき (にほん に いく とき) means before or on the way to Japan, while 日本に行ったとき (にほん に いった とき) means after you got there.",
        examples: [
          { text: 'これは昨日買った本です。', reading: 'これ は きのう かった ほん です。', en: 'This is the book I bought yesterday.' },
          { text: 'あの赤いシャツを着ている人は、だれ？', reading: 'あの あかい シャツ を きて いる ひと は、 だれ？', en: "Who's that person wearing the red shirt?" },
          { text: '子どものとき、京都に住んでいました。', reading: 'こども の とき、 きょうと に すんで いました。', en: 'When I was a child, I lived in Kyoto.' },
          { text: '日本に来たとき、日本語がぜんぜん分からなかった。', reading: 'にほん に きた とき、 にほんご が ぜんぜん わからなかった。', en: "When I came to Japan, I didn't understand any Japanese." },
          { text: '日本に行くとき、新しいカメラを買いました。', reading: 'にほん に いく とき、 あたらしい カメラ を かいました。', en: 'I bought a new camera before going to Japan.' },
        ],
        drills: [
          { text: 'これは母が作___ケーキです。', reading: 'これ は はは が つく___ ケーキ です。', en: 'This is a cake my mother made.', answer: 'った', distractors: ['って', 'る', 'ったの'] },
          { text: '友だち___作った料理は、とてもおいしかった。', reading: 'ともだち ___ つくった りょうり は、 とても おいしかった。', en: 'The food my friend made was really delicious.', answer: 'が', distractors: ['は', 'を', 'に'] },
          { text: 'ひま___とき、よく本を読みます。', reading: 'ひま ___ とき、 よく ほん を よみます。', en: "When I'm free, I often read books.", answer: 'な', distractors: ['の', 'だ', 'に'] },
          { text: '子ども___とき、よく川であそびました。', reading: 'こども ___ とき、 よく かわ で あそびました。', en: 'When I was a child, I often played in the river.', answer: 'の', distractors: ['な', 'だ', 'が'] },
          { text: 'めがねをかけ___人が山田さんです。', reading: 'めがね を かけ___ ひと が やまだ さん です。', en: 'The person wearing glasses is Mr. Yamada.', answer: 'ている', distractors: ['て', 'ていて', 'ているの'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-04-01', text: 'ちこくする', en: 'to be late (for school, work)', pos: 'verb', example: { text: '今朝、会社にちこくした。', reading: 'けさ、 かいしゃ に ちこく した。', en: 'I was late for work this morning.' } },
      { id: 'v-ja-n4-04-02', text: 'おくれる', en: 'to be late; to be delayed', pos: 'verb', example: { text: 'ゆきで電車がおくれた。', reading: 'ゆき で でんしゃ が おくれた。', en: 'The train was delayed because of the snow.' } },
      { id: 'v-ja-n4-04-03', text: 'ねぼうする', en: 'to oversleep', pos: 'verb', example: { text: 'ねぼうしたので、朝ごはんを食べなかった。', reading: 'ねぼう した ので、 あさごはん を たべなかった。', en: "I overslept, so I didn't eat breakfast." } },
      { id: 'v-ja-n4-04-04', text: 'じこ', en: 'accident', pos: 'noun', example: { text: '道でじこがあったので、バスがおくれました。', reading: 'みち で じこ が あった ので、 バス が おくれました。', en: 'There was an accident on the road, so the bus was late.' } },
      { id: 'v-ja-n4-04-05', text: 'こむ', en: 'to be crowded', pos: 'verb', example: { text: '朝の電車はいつもこんでいる。', reading: 'あさ の でんしゃ は いつも こんで いる。', en: 'Morning trains are always crowded.' } },
      { id: 'v-ja-n4-04-06', text: '間に合う', reading: 'まにあう', en: 'to be in time; to make it', pos: 'verb', example: { text: '走ったから、電車に間に合った。', reading: 'はしった から、 でんしゃ に まにあった。', en: 'I ran, so I made the train.' } },
      { id: 'v-ja-n4-04-07', text: '急ぐ', reading: 'いそぐ', en: 'to hurry', pos: 'verb', example: { text: '急いで！映画が始まるよ。', reading: 'いそいで！ えいが が はじまる よ。', en: "Hurry! The movie's starting." } },
      { id: 'v-ja-n4-04-08', text: '急に', reading: 'きゅうに', en: 'suddenly', pos: 'adverb', example: { text: '急におなかがいたくなったので、休みました。', reading: 'きゅうに おなか が いたく なった ので、 やすみました。', en: 'I suddenly got a stomachache, so I took the day off.' } },
      { id: 'v-ja-n4-04-09', text: '用事', reading: 'ようじ', en: 'errand; something to take care of', pos: 'noun', example: { text: '今日は用事があるので、先に帰ります。', reading: 'きょう は ようじ が ある ので、 さき に かえります。', en: "I have something to take care of today, so I'll head home first." } },
      { id: 'v-ja-n4-04-10', text: '着く', reading: 'つく', en: 'to arrive', pos: 'verb', example: { text: 'さっき駅に着いた。', reading: 'さっき えき に ついた。', en: 'I just got to the station.' } },
      { id: 'v-ja-n4-04-11', text: 'りゆう', en: 'reason', pos: 'noun', example: { text: 'ちこくしたりゆうを教えてください。', reading: 'ちこく した りゆう を おしえて ください。', en: 'Please tell me why you were late.' } },
      { id: 'v-ja-n4-04-12', text: 'めがね', en: 'glasses', pos: 'noun', example: { text: '本を読むときだけ、めがねをかける。', reading: 'ほん を よむ とき だけ、 めがね を かける。', en: 'I only wear glasses when I read.' } },
      { id: 'v-ja-n4-04-13', text: 'かぶる', en: 'to wear (a hat)', pos: 'verb', example: { text: 'ぼうしをかぶっている女の人が、田中さんです。', reading: 'ぼうし を かぶって いる おんな の ひと が、 たなか さん です。', en: 'The woman wearing a hat is Ms. Tanaka.' } },
      { id: 'v-ja-n4-04-14', text: 'せが高い', reading: 'せ が たかい', en: 'tall (of a person)', pos: 'phrase', example: { text: '山田さんはせが高くて、かっこいい。', reading: 'やまだ さん は せ が たかくて、 かっこいい。', en: 'Yamada is tall and good-looking.' } },
      { id: 'v-ja-n4-04-15', text: '明るい', reading: 'あかるい', en: 'cheerful; bright', pos: 'adjective', example: { text: 'みかさんは明るくて、おもしろい人です。', reading: 'みか さん は あかるくて、 おもしろい ひと です。', en: 'Mika is a cheerful, fun person.' } },
      { id: 'v-ja-n4-04-16', text: 'やさしい', en: 'kind; gentle', pos: 'adjective', example: { text: 'みかさんのお母さんは、とてもやさしい人です。', reading: 'みか さん の おかあさん は、 とても やさしい ひと です。', en: "Mika's mother is a very kind person." } },
      { id: 'v-ja-n4-04-17', text: 'まじめ', en: 'serious; hardworking (na-adj.)', pos: 'adjective', example: { text: '弟はまじめな学生です。', reading: 'おとうと は まじめ な がくせい です。', en: 'My younger brother is a hardworking student.' } },
      { id: 'v-ja-n4-04-18', text: 'わかい', en: 'young', pos: 'adjective', example: { text: '父はわかいとき、よく山にのぼった。', reading: 'ちち は わかい とき、 よく やま に のぼった。', en: 'When my father was young, he often climbed mountains.' } },
      { id: 'v-ja-n4-04-19', text: '知り合い', reading: 'しりあい', en: 'acquaintance; someone you know', pos: 'noun', example: { text: 'パーティーで知り合いに会った。', reading: 'パーティー で しりあい に あった。', en: 'I ran into someone I know at the party.' } },
      { id: 'v-ja-n4-04-20', text: 'しょうかいする', en: 'to introduce (someone)', pos: 'verb', example: { text: '私の友だちをしょうかいします。', reading: 'わたし の ともだち を しょうかい します。', en: 'Let me introduce my friend.' } },
      { id: 'v-ja-n4-04-21', text: 'にる', en: 'to resemble; to look like (used as 〜ににている)', pos: 'verb', example: { text: 'みかさんはお母さんによくにている。', reading: 'みか さん は おかあさん に よく にて いる。', en: 'Mika looks a lot like her mother.' } },
      { id: 'v-ja-n4-04-22', text: '生まれる', reading: 'うまれる', en: 'to be born', pos: 'verb', example: { text: '私は北海道で生まれました。', reading: 'わたし は ほっかいどう で うまれました。', en: 'I was born in Hokkaido.' } },
    ],
    scenario: {
      title: 'Late to the party',
      setting: "You arrive almost an hour late to your friend Mika's house party in Tokyo. After you explain, she asks which of the guests you already know.",
      aiRole: 'Mika (みか), your friend who is hosting the party. She speaks casually and is curious about who you know.',
      learnerGoal:
        'Apologize and explain why you are late using ので or から, point out two guests you know by describing them with noun-modifying clauses (for example, めがねをかけている人), and say when or where you met each one, using 〜とき at least once.',
      opener: 'あ、やっと来た！どうしたの？みんな待ってたよ。',
      openerReading: 'あ、 やっと きた！ どうした の？ みんな まってた よ。',
    },
  },
];
