import type { Unit } from '../types';

/** Japanese units 15–18 (JLPT N4, part 2). */
export const unitsN4b: Unit[] = [
  // ───────────────────────────── N4 (A2) ─────────────────────────────
  {
    id: 'ja-n4-05',
    cefr: 'A2',
    order: 15,
    title: 'できること: Ability and plans',
    theme: 'Saying what you can do and talking about your plans',
    canDo: [
      "I can say what I can and can't do with the potential form.",
      'I can talk about skills such as languages, driving, and playing instruments.',
      'I can explain my plans and intentions with つもり and 〜(よ)うと思う.',
      'I can answer basic questions in a part-time job interview.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-05-1',
        title: 'Potential form and 〜ことができる',
        summary:
          "The potential form says what someone can do. Group 1 verbs change the final -u to -eru: 話す (はなす) → 話せる (はなせる), 書く (かく) → 書ける (かける). Group 2 verbs replace る with られる: 食べる (たべる) → 食べられる (たべられる); the irregulars are する → できる and 来る (くる) → 来られる (こられる). Potential verbs conjugate like group 2 verbs (話せます (はなせます), 話せない (はなせない)), and the thing you can do usually takes が instead of を: 日本語が話せます (にほんご が はなせます). Dictionary form + ことができる means the same and sounds a little more formal: およぐことができます. Pitfall: with する-verbs just swap する for できる — 運転できる (うんてん できる), never 運転するできる (うんてん する できる); and in casual speech you'll hear 見れる (みれる) for 見られる (みられる), but use the られる form in writing.",
        examples: [
          { text: '私は日本語が少し話せます。', reading: 'わたし は にほんご が すこし はなせます。', en: 'I can speak a little Japanese.' },
          { text: '朝早く起きられません。', reading: 'あさ はやく おきられません。', en: "I can't get up early in the morning." },
          { text: '来週のパーティーに来られますか。', reading: 'らいしゅう の パーティー に こられます か。', en: 'Can you come to the party next week?' },
          { text: '一人で着物を着ることができます。', reading: 'ひとり で きもの を きる こと が できます。', en: 'I can put on a kimono by myself.' },
          { text: 'この店ではカードが使えません。', reading: 'この みせ で は カード が つかえません。', en: "You can't use cards at this shop." },
        ],
        drills: [
          { text: '私は英語が___。', reading: 'わたし は えいご が ___。', en: 'I can speak English.', answer: '話せます', distractors: ['話します', '話せません', '話させます'] },
          { text: '生の魚が___か。', reading: 'なま の さかな が ___ か。', en: 'Can you eat raw fish?', answer: '食べられます', distractors: ['食べます', '食べました', '食べさせます'] },
          { text: '明日は___か。', reading: 'あした は ___ か。', en: 'Can you come tomorrow?', answer: '来られます', distractors: ['来ます', '来ました', '来させます'] },
          { text: '妹はピアノが___。', reading: 'いもうと は ピアノ が ___。', en: 'My little sister can play the piano.', answer: 'ひけます', distractors: ['ひきます', 'ひかれます', 'ひきません'] },
          { text: 'このカードで電車に乗る___ができます。', reading: 'この カード で でんしゃ に のる ___ が できます。', en: 'You can ride the train with this card.', answer: 'こと', distractors: ['もの', 'ところ', 'とき'] },
        ],
      },
      {
        id: 'g-ja-n4-05-2',
        title: '〜つもり and volitional 〜(よ)うと思う',
        summary:
          "Dictionary form + つもりです states a firm intention, 'I plan to'; for something you don't plan to do, use the ない-form: 行かないつもりです (いかない つもり です). For a plan you're considering or have just decided on, use the volitional form + と思います (と おもいます), 'I think I'll…'. To make the volitional, group 1 verbs change -u to -ou (行く (いく) → 行こう (いこう), 買う (かう) → 買おう (かおう)), group 2 verbs replace る with よう (食べる (たべる) → 食べよう (たべよう)), and the irregulars are する → しよう and 来る (くる) → 来よう (こよう). と思っています (と おもって います) shows a plan you've had for a while, and it's the form to use for someone else's intentions. Pitfall: don't put ましょう before と思う — say 行こうと思います (いこう と おもいます), not 行きましょうと思います (いきましょう と おもいます).",
        examples: [
          { text: '来年、日本へりゅうがくするつもりです。', reading: 'らいねん、 にほん へ りゅうがく する つもり です。', en: 'I plan to study abroad in Japan next year.' },
          { text: '今年の夏は国へ帰らないつもりです。', reading: 'ことし の なつ は くに へ かえらない つもり です。', en: "I don't plan to go back to my country this summer." },
          { text: '日曜日に新しいくつを買おうと思います。', reading: 'にちようび に あたらしい くつ を かおう と おもいます。', en: "I'm thinking of buying new shoes on Sunday." },
          { text: '毎日、漢字を五つおぼえようと思っています。', reading: 'まいにち、 かんじ を いつつ おぼえよう と おもって います。', en: "I'm planning to learn five kanji every day." },
          { text: '妹は大学で医学を勉強しようと思っています。', reading: 'いもうと は だいがく で いがく を べんきょう しよう と おもって います。', en: 'My little sister is planning to study medicine at university.' },
        ],
        drills: [
          { text: 'この夏、北海道へ行く___です。', reading: 'この なつ、 ほっかいどう へ いく ___ です。', en: 'I plan to go to Hokkaido this summer.', answer: 'つもり', distractors: ['こと', 'ため', 'もの'] },
          { text: '明日から毎朝___と思います。', reading: 'あした から まいあさ ___ と おもいます。', en: "I'm thinking of going running every morning, starting tomorrow.", answer: '走ろう', distractors: ['走ります', '走りましょう', '走らない'] },
          { text: 'たばこを___と思っています。', reading: 'たばこ を ___ と おもって います。', en: "I've been thinking of quitting smoking.", answer: 'やめよう', distractors: ['やめろう', 'やめます', 'やめた'] },
          { text: '今夜はおさけを___つもりです。', reading: 'こんや は おさけ を ___ つもり です。', en: "I don't plan to drink tonight.", answer: '飲まない', distractors: ['飲む', '飲みません', '飲もう'] },
          { text: '来年、車を___と思います。', reading: 'らいねん、 くるま を ___ と おもいます。', en: "I'm thinking of buying a car next year.", answer: '買おう', distractors: ['買よう', '買こう', '買いましょう'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-05-01', text: '運転する', reading: 'うんてん する', en: 'to drive', pos: 'verb', example: { text: '兄はトラックも運転できます。', reading: 'あに は トラック も うんてん できます。', en: 'My older brother can even drive a truck.' } },
      { id: 'v-ja-n4-05-02', text: 'およぐ', en: 'to swim', pos: 'verb', example: { text: '子どものとき、およげませんでした。', reading: 'こども の とき、 およげませんでした。', en: "I couldn't swim when I was a child." } },
      { id: 'v-ja-n4-05-03', text: 'ひく', en: 'to play (piano, guitar, etc.)', pos: 'verb', example: { text: '父はギターをひくのが好きです。', reading: 'ちち は ギター を ひく の が すき です。', en: 'My father likes playing the guitar.' } },
      { id: 'v-ja-n4-05-04', text: 'ピアノ', en: 'piano', pos: 'noun', example: { text: '小さいときからピアノを習っています。', reading: 'ちいさい とき から ピアノ を ならって います。', en: "I've been taking piano lessons since I was little." } },
      { id: 'v-ja-n4-05-05', text: '漢字', reading: 'かんじ', en: 'kanji (Chinese characters)', pos: 'noun', example: { text: 'この漢字が読めますか。', reading: 'この かんじ が よめます か。', en: 'Can you read this kanji?' } },
      { id: 'v-ja-n4-05-06', text: '外国語', reading: 'がいこくご', en: 'foreign language', pos: 'noun', example: { text: '外国語が話せる人をさがしています。', reading: 'がいこくご が はなせる ひと を さがして います。', en: "We're looking for someone who can speak a foreign language." } },
      { id: 'v-ja-n4-05-07', text: 'とくい', en: 'good at; strong point (na-adj.)', pos: 'adjective', example: { text: '私は料理がとくいです。', reading: 'わたし は りょうり が とくい です。', en: "I'm good at cooking." } },
      { id: 'v-ja-n4-05-08', text: 'にがて', en: 'weak at; not good with (na-adj.)', pos: 'adjective', example: { text: '早く起きるのがにがてです。', reading: 'はやく おきる の が にがて です。', en: "I'm not good at getting up early." } },
      { id: 'v-ja-n4-05-09', text: 'おぼえる', en: 'to memorize; to remember', pos: 'verb', example: { text: '一週間でメニューをおぼえられますか。', reading: 'いっしゅうかん で メニュー を おぼえられます か。', en: 'Can you memorize the menu in a week?' } },
      { id: 'v-ja-n4-05-10', text: 'なれる', en: 'to get used to', pos: 'verb', example: { text: '日本のせいかつにもうなれましたか。', reading: 'にほん の せいかつ に もう なれました か。', en: 'Have you gotten used to life in Japan yet?' } },
      { id: 'v-ja-n4-05-11', text: 'めんせつ', en: '(job) interview', pos: 'noun', example: { text: '明日、アルバイトのめんせつがあります。', reading: 'あした、 アルバイト の めんせつ が あります。', en: 'I have an interview for a part-time job tomorrow.' } },
      { id: 'v-ja-n4-05-12', text: '店長', reading: 'てんちょう', en: 'store manager', pos: 'noun', example: { text: '店長はとてもやさしい人です。', reading: 'てんちょう は とても やさしい ひと です。', en: 'The store manager is a very kind person.' } },
      { id: 'v-ja-n4-05-13', text: 'じきゅう', en: 'hourly wage', pos: 'noun', example: { text: 'この店のじきゅうは千二百円です。', reading: 'この みせ の じきゅう は せんにひゃくえん です。', en: 'The hourly wage at this shop is 1,200 yen.' } },
      { id: 'v-ja-n4-05-14', text: '土日', reading: 'どにち', en: 'Saturday and Sunday; the weekend', pos: 'noun', example: { text: '土日も働けますか。', reading: 'どにち も はたらけます か。', en: 'Can you work on weekends too?' } },
      { id: 'v-ja-n4-05-15', text: 'よてい', en: 'plan; schedule', pos: 'noun', example: { text: '夏休みのよていはもうきまりましたか。', reading: 'なつやすみ の よてい は もう きまりました か。', en: 'Are your summer vacation plans set yet?' } },
      { id: 'v-ja-n4-05-16', text: 'しょうらい', en: 'the future', pos: 'noun', example: { text: 'しょうらい、日本で働きたいです。', reading: 'しょうらい、 にほん で はたらきたい です。', en: 'In the future, I want to work in Japan.' } },
      { id: 'v-ja-n4-05-17', text: 'ゆめ', en: 'dream', pos: 'noun', example: { text: '私のゆめは先生になることです。', reading: 'わたし の ゆめ は せんせい に なる こと です。', en: 'My dream is to become a teacher.' } },
      { id: 'v-ja-n4-05-18', text: 'きめる', en: 'to decide', pos: 'verb', example: { text: '大学で何を勉強するか、まだきめていません。', reading: 'だいがく で なに を べんきょう する か、 まだ きめて いません。', en: "I haven't decided yet what to study at university." } },
      { id: 'v-ja-n4-05-19', text: 'つづける', en: 'to continue', pos: 'verb', example: { text: '日本語の勉強をつづけようと思います。', reading: 'にほんご の べんきょう を つづけよう と おもいます。', en: "I'm thinking of continuing my Japanese studies." } },
      { id: 'v-ja-n4-05-20', text: 'やめる', en: 'to quit; to stop (doing)', pos: 'verb', example: { text: '先月、たばこをやめました。', reading: 'せんげつ、 たばこ を やめました。', en: 'I quit smoking last month.' } },
      { id: 'v-ja-n4-05-21', text: 'りゅうがくする', en: 'to study abroad', pos: 'verb', example: { text: '大学生のとき、アメリカにりゅうがくしました。', reading: 'だいがくせい の とき、 アメリカ に りゅうがく しました。', en: 'I studied abroad in America when I was a university student.' } },
      { id: 'v-ja-n4-05-22', text: '一生けんめい', reading: 'いっしょうけんめい', en: "as hard as one can; with all one's effort", pos: 'adverb', example: { text: '一生けんめい働きます。', reading: 'いっしょうけんめい はたらきます。', en: "I'll work as hard as I can." } },
    ],
    scenario: {
      title: 'A part-time job interview',
      setting: "You're interviewing for a part-time job at a small café near Shibuya Station in Tokyo. The manager wants to know what you can do and what your plans are.",
      aiRole: 'Kimura-san, the friendly but busy manager of the café',
      learnerGoal:
        "Say which languages you can speak and what you can and can't do, tell the manager which days you can work, and explain how long you plan to stay in Japan and what you're thinking of doing in the future.",
      opener: 'はじめまして。店長の木村です。どうぞ、すわってください。日本語はどのくらい話せますか。',
      openerReading: 'はじめまして。 てんちょう の きむら です。 どうぞ、 すわって ください。 にほんご は どの くらい はなせます か。',
    },
  },
  {
    id: 'ja-n4-06',
    cefr: 'A2',
    order: 16,
    title: 'あげる・くれる・もらう: Giving and receiving',
    theme: 'Gifts, favors, and who does what for whom',
    canDo: [
      'I can say who gave what to whom, choosing between あげる, くれる, and もらう.',
      'I can talk about favors people did for me and favors I did for others.',
      'I can ask for small favors and thank people for presents.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-06-1',
        title: 'あげる・くれる・もらう with things',
        summary:
          "Japanese picks a giving verb by direction. あげる: someone gives something away from the speaker's side — I give to others, or one person gives to another (giver は receiver に thing を あげる). くれる: someone gives something to me or to someone on my side — my family, close friends, or you when I'm asking you (giver が receiver に thing を くれる). もらう: to receive, told from the receiver's side (receiver は giver に or から thing を もらう). The same event can be told with either くれる or もらう: 母がくれました (はは が くれました) = 母にもらいました (はは に もらいました), 'my mom gave it to me'. Pitfall: when the receiver is you, never use あげる — 友だちが私に本をあげました (ともだち が わたし に ほん を あげました) is wrong; it must be くれました.",
        examples: [
          { text: '私は友だちに本をあげました。', reading: 'わたし は ともだち に ほん を あげました。', en: 'I gave my friend a book.' },
          { text: '母が私にセーターをくれました。', reading: 'はは が わたし に セーター を くれました。', en: 'My mother gave me a sweater.' },
          { text: '私は兄から時計をもらいました。', reading: 'わたし は あに から とけい を もらいました。', en: 'I got a watch from my older brother.' },
          { text: '田中さんは妹にお花をくれました。', reading: 'たなか さん は いもうと に おはな を くれました。', en: 'Mr. Tanaka gave my little sister some flowers.' },
          { text: '山田さんはリーさんにチョコレートをあげました。', reading: 'やまだ さん は リー さん に チョコレート を あげました。', en: 'Ms. Yamada gave Mr. Lee some chocolate.' },
        ],
        drills: [
          { text: '私は弟にゲームを___。', reading: 'わたし は おとうと に ゲーム を ___。', en: 'I gave my little brother a video game.', answer: 'あげました', distractors: ['くれました', 'もらいました'] },
          { text: '友だちが私にケーキを___。', reading: 'ともだち が わたし に ケーキ を ___。', en: 'My friend gave me a cake.', answer: 'くれました', distractors: ['あげました', 'もらいました'] },
          { text: '私は先生からペンを___。', reading: 'わたし は せんせい から ペン を ___。', en: 'I received a pen from my teacher.', answer: 'もらいました', distractors: ['あげました', 'くれました'] },
          { text: '私はリンさん___手紙をもらいました。', reading: 'わたし は リン さん ___ てがみ を もらいました。', en: 'I got a letter from Lin.', answer: 'から', distractors: ['が', 'を', 'で'] },
          { text: 'だれがこの時計を___か。', reading: 'だれ が この とけい を ___ か。', en: 'Who gave you this watch?', answer: 'くれました', distractors: ['あげました', 'もらいました'] },
        ],
      },
      {
        id: 'g-ja-n4-06-2',
        title: '〜てあげる・〜てくれる・〜てもらう',
        summary:
          "Put あげる, くれる, or もらう after a verb's て-form to talk about favors; the directions are the same as with things. 〜てあげる means doing something for someone else. 〜てくれる means someone does something for me or my side, and it sounds grateful: 友だちが駅まで送ってくれました (ともだち が えき まで おくって くれました). 〜てもらう means I get someone to do something for me, and the person who does the favor takes に: 父になおしてもらいました (ちち に なおして もらいました). To ask for a favor, use 〜てくれませんか or the more polite 〜てもらえませんか. Pitfall: saying 〜てあげます straight to someone, especially an older person or your boss, can sound pushy, as if you're doing them a big favor — offer with 〜ましょうか instead: 持ちましょうか (もちましょう か).",
        examples: [
          { text: '私は妹に本を読んであげました。', reading: 'わたし は いもうと に ほん を よんで あげました。', en: 'I read a book to my little sister.' },
          { text: '友だちが駅まで送ってくれました。', reading: 'ともだち が えき まで おくって くれました。', en: 'My friend took me all the way to the station.' },
          { text: '父に自転車をなおしてもらいました。', reading: 'ちち に じてんしゃ を なおして もらいました。', en: 'I had my father fix my bicycle.' },
          { text: 'すみません、写真をとってもらえませんか。', reading: 'すみません、 しゃしん を とって もらえません か。', en: 'Excuse me, could you take a picture for us?' },
          { text: '田中さんに日本語の手紙を読んでもらいました。', reading: 'たなか さん に にほんご の てがみ を よんで もらいました。', en: 'I had Mr. Tanaka read a Japanese letter for me.' },
        ],
        drills: [
          { text: '母がおべんとうを作って___。', reading: 'はは が おべんとう を つくって ___。', en: 'My mom made me a boxed lunch.', answer: 'くれました', distractors: ['あげました', 'もらいました'] },
          { text: '私は友だちに日本語を教えて___。', reading: 'わたし は ともだち に にほんご を おしえて ___。', en: 'I taught my friend some Japanese (as a favor to them).', answer: 'あげました', distractors: ['くれました', 'もらいました'] },
          { text: '私は兄にしゅくだいを見て___。', reading: 'わたし は あに に しゅくだい を みて ___。', en: 'I had my older brother check my homework.', answer: 'もらいました', distractors: ['あげました', 'くれました'] },
          { text: '私は田中さん___車で送ってもらいました。', reading: 'わたし は たなか さん ___ くるま で おくって もらいました。', en: 'I got a ride from Mr. Tanaka.', answer: 'に', distractors: ['が', 'を', 'で'] },
          { text: 'となりの人がにもつを持って___。', reading: 'となり の ひと が にもつ を もって ___。', en: 'The person next to me carried my bag for me.', answer: 'くれました', distractors: ['あげました', 'もらいました'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-06-01', text: 'あげる', en: 'to give (to someone else)', pos: 'verb', example: { text: '父の日に父にネクタイをあげました。', reading: 'ちち の ひ に ちち に ネクタイ を あげました。', en: "I gave my dad a tie on Father's Day." } },
      { id: 'v-ja-n4-06-02', text: 'くれる', en: 'to give (to me or my family)', pos: 'verb', example: { text: 'おばあちゃんが手作りのクッキーをくれました。', reading: 'おばあちゃん が てづくり の クッキー を くれました。', en: 'My grandma gave me homemade cookies.' } },
      { id: 'v-ja-n4-06-03', text: 'もらう', en: 'to receive; to get', pos: 'verb', example: { text: 'クリスマスに何をもらいましたか。', reading: 'クリスマス に なに を もらいました か。', en: 'What did you get for Christmas?' } },
      { id: 'v-ja-n4-06-04', text: 'プレゼント', en: 'present; gift', pos: 'noun', example: { text: 'このプレゼント、開けてもいいですか。', reading: 'この プレゼント、 あけて も いい です か。', en: 'May I open this present?' } },
      { id: 'v-ja-n4-06-05', text: 'たんじょう日', reading: 'たんじょうび', en: 'birthday', pos: 'noun', example: { text: 'たんじょう日はいつですか。', reading: 'たんじょうび は いつ です か。', en: 'When is your birthday?' } },
      { id: 'v-ja-n4-06-06', text: 'おめでとう', en: 'congratulations', pos: 'phrase', example: { text: 'おたんじょう日おめでとう！', reading: 'おたんじょうび おめでとう！', en: 'Happy birthday!' } },
      { id: 'v-ja-n4-06-07', text: 'おいわい', en: 'celebration; congratulatory gift', pos: 'noun', example: { text: '入学のおいわいに、おじいちゃんが時計をくれました。', reading: 'にゅうがく の おいわい に、 おじいちゃん が とけい を くれました。', en: 'My grandpa gave me a watch to celebrate my starting school.' } },
      { id: 'v-ja-n4-06-08', text: 'おれい', en: 'thanks; a thank-you gift', pos: 'noun', example: { text: 'てつだってもらったおれいに、ケーキを買いました。', reading: 'てつだって もらった おれい に、 ケーキ を かいました。', en: 'I bought a cake to thank them for helping me.' } },
      { id: 'v-ja-n4-06-09', text: 'おかえし', en: 'a return gift', pos: 'noun', example: { text: 'ホワイトデーにチョコレートのおかえしをします。', reading: 'ホワイトデー に チョコレート の おかえし を します。', en: 'On White Day, I give return gifts for the chocolate I got.' } },
      { id: 'v-ja-n4-06-10', text: '送る', reading: 'おくる', en: 'to send; to take (someone) somewhere', pos: 'verb', example: { text: '母に花を送りました。', reading: 'はは に はな を おくりました。', en: 'I sent flowers to my mother.' } },
      { id: 'v-ja-n4-06-11', text: '貸す', reading: 'かす', en: 'to lend', pos: 'verb', example: { text: 'ペンを貸してくれませんか。', reading: 'ペン を かして くれません か。', en: 'Could you lend me a pen?' } },
      { id: 'v-ja-n4-06-12', text: '借りる', reading: 'かりる', en: 'to borrow', pos: 'verb', example: { text: '図書館で本を借りました。', reading: 'としょかん で ほん を かりました。', en: 'I borrowed a book from the library.' } },
      { id: 'v-ja-n4-06-13', text: 'かえす', en: 'to give back; to return (something)', pos: 'verb', example: { text: '借りた本を来週かえします。', reading: 'かりた ほん を らいしゅう かえします。', en: "I'll return the book I borrowed next week." } },
      { id: 'v-ja-n4-06-14', text: 'つつむ', en: 'to wrap', pos: 'verb', example: { text: 'プレゼント用につつんでもらえますか。', reading: 'プレゼントよう に つつんで もらえます か。', en: 'Could you gift-wrap it for me?' } },
      { id: 'v-ja-n4-06-15', text: 'えらぶ', en: 'to choose', pos: 'verb', example: { text: '母へのプレゼントをいっしょにえらんでくれませんか。', reading: 'はは へ の プレゼント を いっしょに えらんで くれません か。', en: 'Could you help me choose a present for my mom?' } },
      { id: 'v-ja-n4-06-16', text: 'てつだう', en: 'to help', pos: 'verb', example: { text: '友だちにひっこしをてつだってもらいました。', reading: 'ともだち に ひっこし を てつだって もらいました。', en: 'My friends helped me move.' } },
      { id: 'v-ja-n4-06-17', text: 'なおす', en: 'to fix; to repair', pos: 'verb', example: { text: '父がこわれたいすをなおしてくれました。', reading: 'ちち が こわれた いす を なおして くれました。', en: 'My father fixed the broken chair for me.' } },
      { id: 'v-ja-n4-06-18', text: 'よろこぶ', en: 'to be glad; to be delighted', pos: 'verb', example: { text: '母はプレゼントをとてもよろこんでくれました。', reading: 'はは は プレゼント を とても よろこんで くれました。', en: 'My mother was really happy with my present.' } },
      { id: 'v-ja-n4-06-19', text: '気に入る', reading: 'き に いる', en: 'to like; to be pleased with', pos: 'verb', example: { text: 'このかばん、とても気に入りました。', reading: 'この かばん、 とても き に いりました。', en: 'I really love this bag.' } },
      { id: 'v-ja-n4-06-20', text: '大切', reading: 'たいせつ', en: 'precious; important (na-adj.)', pos: 'adjective', example: { text: 'この時計は父にもらった大切なものです。', reading: 'この とけい は ちち に もらった たいせつ な もの です。', en: 'This watch is precious to me; I got it from my father.' } },
      { id: 'v-ja-n4-06-21', text: 'ハンカチ', en: 'handkerchief', pos: 'noun', example: { text: '先生にきれいなハンカチをもらいました。', reading: 'せんせい に きれい な ハンカチ を もらいました。', en: 'I got a pretty handkerchief from my teacher.' } },
      { id: 'v-ja-n4-06-22', text: 'ごちそうする', en: 'to treat (someone to food or drink)', pos: 'verb', example: { text: '今日は私がごちそうします。', reading: 'きょう は わたし が ごちそう します。', en: "Today it's my treat." } },
    ],
    scenario: {
      title: 'Birthday presents',
      setting: "It's the day after your birthday. At a café in Kichijoji, Tokyo, your friend Yui asks how your birthday went, and she wants advice on a present for her mother.",
      aiRole: 'Yui, a cheerful university student and your close friend',
      learnerGoal:
        'Tell Yui what presents you got and who gave them to you, describe something nice someone did for you on your birthday, and help her decide what to give her mother, using あげる, くれる, and もらう correctly.',
      opener: 'きのうはたんじょう日でしたね。おめでとう！どんなプレゼントをもらいましたか。',
      openerReading: 'きのう は たんじょうび でした ね。 おめでとう！ どんな プレゼント を もらいました か。',
    },
  },
  {
    id: 'ja-n4-07',
    cefr: 'A2',
    order: 17,
    title: 'もし: Conditionals',
    theme: 'If and when: conditions, natural results, and advice',
    canDo: [
      'I can say what will happen, or what I will do, if something happens.',
      'I can give and follow simple directions with 〜と.',
      'I can ask for advice with 〜ばいいですか and give it with 〜なら.',
      'I can describe simple symptoms at a pharmacy.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-07-1',
        title: '〜たら and 〜ば',
        summary:
          "〜たら is the all-purpose 'if / when' (often with もし, 'if by any chance', at the start): take the plain past and add ら — 行ったら (いったら), 安かったら (やすかったら), 雨だったら (あめ だったら). The second half can be anything, including a request, an invitation, or what you want to do: 駅に着いたら、電話してください (えき に ついたら、 でんわ して ください). 〜ば puts the focus on the condition, 'if, provided that': group 1 verbs change -u to -eba (行く (いく) → 行けば (いけば)), group 2 verbs change る to れば (食べる (たべる) → 食べれば (たべれば)), する → すれば, 来る (くる) → 来れば (くれば), い-adjectives change い to ければ (安い (やすい) → 安ければ (やすければ)), and negatives end in なければ. 〜ばいいですか asks for advice: どうすればいいですか, 'what should I do?' Pitfall: when the first half is an action and the second half is a request or invitation, use たら, not ば.",
        examples: [
          { text: 'もし雨がふったら、家にいます。', reading: 'もし あめ が ふったら、 いえ に います。', en: "If it rains, I'll stay home." },
          { text: '駅に着いたら、電話してください。', reading: 'えき に ついたら、 でんわ して ください。', en: 'When you get to the station, please call me.' },
          { text: '安ければ、買います。', reading: 'やすければ、 かいます。', en: "If it's cheap, I'll buy it." },
          { text: 'この薬を飲めば、すぐよくなりますよ。', reading: 'この くすり を のめば、 すぐ よく なります よ。', en: "If you take this medicine, you'll feel better soon." },
          { text: '何時に行けばいいですか。', reading: 'なんじ に いけば いい です か。', en: 'What time should I go?' },
        ],
        drills: [
          { text: '明日ひま___、映画を見ませんか。', reading: 'あした ひま ___、 えいが を みません か。', en: "If you're free tomorrow, why don't we see a movie?", answer: 'だったら', distractors: ['たら', 'かったら', 'ければ'] },
          { text: '家に___、メールをください。', reading: 'いえ に ___、 メール を ください。', en: 'When you get home, please send me an email.', answer: '帰ったら', distractors: ['帰れば', '帰ると', '帰るなら'] },
          { text: 'この薬を___、ねつが下がりますよ。', reading: 'この くすり を ___、 ねつ が さがります よ。', en: 'If you take this medicine, your fever will go down.', answer: '飲めば', distractors: ['飲むば', '飲みば', '飲んば'] },
          { text: 'もう少し___、買います。', reading: 'もう すこし ___、 かいます。', en: "If it's a little cheaper, I'll buy it.", answer: '安ければ', distractors: ['安いば', '安くば', '安かれば'] },
          { text: 'どこできっぷを___いいですか。', reading: 'どこ で きっぷ を ___ いい です か。', en: 'Where should I buy a ticket?', answer: '買えば', distractors: ['買うば', '買いば', '買えるば'] },
        ],
      },
      {
        id: 'g-ja-n4-07-2',
        title: '〜と (natural result) and 〜なら',
        summary:
          "Dictionary form + と means 'whenever / if X, then Y happens' for automatic results: nature, machines, habits, and directions — このボタンをおすと、水が出ます (この ボタン を おす と、 みず が でます). Because the result is automatic, the second half can't be a request, an invitation, or your own plan: 駅に着くと、電話してください (えき に つく と、 でんわ して ください) is wrong — use 着いたら (ついたら). なら means 'if that's the case': it picks up a topic, often something the other person just said, and gives advice or an opinion about it — かぜなら、この薬がいいですよ (かぜ なら、 この くすり が いい です よ). なら goes right after nouns and plain-form verbs and adjectives. Pitfall: with なら the second half can come first in time — 京都へ行くなら、この本を読んでください (きょうと へ いく なら、 この ほん を よんで ください) means 'read this before you go', which たら can't express.",
        examples: [
          { text: '春になると、さくらがさきます。', reading: 'はる に なる と、 さくら が さきます。', en: 'When spring comes, the cherry blossoms bloom.' },
          { text: 'このボタンをおすと、水が出ます。', reading: 'この ボタン を おす と、 みず が でます。', en: 'When you press this button, water comes out.' },
          { text: 'まっすぐ行くと、右に薬屋があります。', reading: 'まっすぐ いく と、 みぎ に くすりや が あります。', en: "Go straight and you'll see a pharmacy on the right." },
          { text: '頭がいたいなら、この薬がいいですよ。', reading: 'あたま が いたい なら、 この くすり が いい です よ。', en: 'If you have a headache, this medicine is good.' },
          { text: '日本へ行くなら、春がいいですよ。', reading: 'にほん へ いく なら、 はる が いい です よ。', en: "If you're going to Japan, spring is a good time." },
        ],
        drills: [
          { text: 'この道をまっすぐ行く___、駅があります。', reading: 'この みち を まっすぐ いく ___、 えき が あります。', en: "If you go straight down this street, you'll come to the station.", answer: 'と', distractors: ['なら', 'ば', 'から'] },
          { text: '二つ目のかどを左に___と、薬屋があります。', reading: 'ふたつめ の かど を ひだり に ___ と、 くすりや が あります。', en: "Turn left at the second corner and you'll find a pharmacy.", answer: 'まがる', distractors: ['まがった', 'まがって', 'まがろう'] },
          { text: 'かぜ___、この薬がいいですよ。', reading: 'かぜ ___、 この くすり が いい です よ。', en: "If it's a cold, this medicine works well.", answer: 'なら', distractors: ['と', 'ば', 'たら'] },
          { text: '京都へ行く___、しんかんせんがべんりです。', reading: 'きょうと へ いく ___、 しんかんせん が べんり です。', en: "If you're going to Kyoto, the shinkansen is convenient.", answer: 'なら', distractors: ['と', 'たら', 'ので'] },
          { text: 'おさけを飲む___、顔が赤くなります。', reading: 'おさけ を のむ ___、 かお が あかく なります。', en: 'Whenever I drink alcohol, my face turns red.', answer: 'と', distractors: ['なら', 'たら', 'のに'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-07-01', text: 'もし', en: 'if (by any chance)', pos: 'adverb', example: { text: 'もし時間があったら、いっしょに来てください。', reading: 'もし じかん が あったら、 いっしょに きて ください。', en: 'If you have time, please come with me.' } },
      { id: 'v-ja-n4-07-02', text: '薬', reading: 'くすり', en: 'medicine', pos: 'noun', example: { text: '一日三回、薬を飲んでください。', reading: 'いちにち さんかい、 くすり を のんで ください。', en: 'Please take the medicine three times a day.' } },
      { id: 'v-ja-n4-07-03', text: '薬屋', reading: 'くすりや', en: 'pharmacy; drugstore', pos: 'noun', example: { text: 'この近くに薬屋はありますか。', reading: 'この ちかく に くすりや は あります か。', en: 'Is there a pharmacy near here?' } },
      { id: 'v-ja-n4-07-04', text: 'かぜ', en: 'a cold (illness)', pos: 'noun', example: { text: 'かぜをひいたら、早くねてください。', reading: 'かぜ を ひいたら、 はやく ねて ください。', en: 'If you catch a cold, go to bed early.' } },
      { id: 'v-ja-n4-07-05', text: 'ねつ', en: 'fever', pos: 'noun', example: { text: '朝からねつがあります。', reading: 'あさ から ねつ が あります。', en: "I've had a fever since this morning." } },
      { id: 'v-ja-n4-07-06', text: 'せき', en: 'cough', pos: 'noun', example: { text: 'せきがひどいなら、病院へ行ったほうがいいですよ。', reading: 'せき が ひどい なら、 びょういん へ いった ほう が いい です よ。', en: 'If your cough is bad, you should go to the doctor.' } },
      { id: 'v-ja-n4-07-07', text: 'のど', en: 'throat', pos: 'noun', example: { text: 'のどがいたくて、声が出ません。', reading: 'のど が いたくて、 こえ が でません。', en: "My throat hurts and I've lost my voice." } },
      { id: 'v-ja-n4-07-08', text: '頭', reading: 'あたま', en: 'head', pos: 'noun', example: { text: '頭がいたいときは、この薬を飲みます。', reading: 'あたま が いたい とき は、 この くすり を のみます。', en: 'When I have a headache, I take this medicine.' } },
      { id: 'v-ja-n4-07-09', text: 'おなか', en: 'stomach; belly', pos: 'noun', example: { text: 'つめたいものを飲むと、おなかがいたくなります。', reading: 'つめたい もの を のむ と、 おなか が いたく なります。', en: 'Whenever I drink something cold, my stomach starts to hurt.' } },
      { id: 'v-ja-n4-07-10', text: 'いたい', en: 'painful; sore', pos: 'adjective', example: { text: '足がいたくて、歩けません。', reading: 'あし が いたくて、 あるけません。', en: "My leg hurts so much that I can't walk." } },
      { id: 'v-ja-n4-07-11', text: '気分', reading: 'きぶん', en: 'feeling; how one feels', pos: 'noun', example: { text: '気分が悪いなら、少し休んでください。', reading: 'きぶん が わるい なら、 すこし やすんで ください。', en: 'If you feel sick, please rest for a bit.' } },
      { id: 'v-ja-n4-07-12', text: '病気', reading: 'びょうき', en: 'illness; sickness', pos: 'noun', example: { text: '母が病気なので、今日は早く帰ります。', reading: 'はは が びょうき な ので、 きょう は はやく かえります。', en: "My mother is sick, so I'm going home early today." } },
      { id: 'v-ja-n4-07-13', text: 'なおる', en: 'to get better; to heal', pos: 'verb', example: { text: 'ゆっくり休めば、すぐなおりますよ。', reading: 'ゆっくり やすめば、 すぐ なおります よ。', en: "If you get plenty of rest, you'll get better soon." } },
      { id: 'v-ja-n4-07-14', text: '食後', reading: 'しょくご', en: 'after a meal', pos: 'noun', example: { text: 'この薬は食後に飲んでください。', reading: 'この くすり は しょくご に のんで ください。', en: 'Please take this medicine after meals.' } },
      { id: 'v-ja-n4-07-15', text: 'こまる', en: 'to be in trouble; to not know what to do', pos: 'verb', example: { text: 'こまったら、いつでも電話してください。', reading: 'こまったら、 いつでも でんわ して ください。', en: "If you're ever in trouble, call me anytime." } },
      { id: 'v-ja-n4-07-16', text: 'おす', en: 'to push; to press', pos: 'verb', example: { text: '赤いボタンをおすと、ドアが開きます。', reading: 'あかい ボタン を おす と、 ドア が あきます。', en: 'Press the red button and the door opens.' } },
      { id: 'v-ja-n4-07-17', text: 'まがる', en: 'to turn (a corner)', pos: 'verb', example: { text: 'あのかどを右にまがってください。', reading: 'あの かど を みぎ に まがって ください。', en: 'Please turn right at that corner.' } },
      { id: 'v-ja-n4-07-18', text: 'かど', en: 'corner', pos: 'noun', example: { text: 'かどに大きいコンビニがあります。', reading: 'かど に おおきい コンビニ が あります。', en: "There's a big convenience store on the corner." } },
      { id: 'v-ja-n4-07-19', text: 'しんごう', en: 'traffic light', pos: 'noun', example: { text: 'しんごうが赤のときは、わたってはいけません。', reading: 'しんごう が あか の とき は、 わたって は いけません。', en: "You mustn't cross when the light is red." } },
      { id: 'v-ja-n4-07-20', text: 'わたる', en: 'to cross (a street, a bridge)', pos: 'verb', example: { text: 'この道をわたると、右に病院があります。', reading: 'この みち を わたる と、 みぎ に びょういん が あります。', en: "Cross this street and you'll see a hospital on the right." } },
    ],
    scenario: {
      title: 'At the pharmacy',
      setting: "You've caught a cold on a trip to Tokyo. You walk into a pharmacy near Shinjuku Station for medicine and advice, and you also want to know how to get to a clinic in case it gets worse.",
      aiRole: 'Kobayashi-san, a kind, patient pharmacist',
      learnerGoal:
        'Describe your symptoms, ask which medicine is good and how to take it (〜ばいいですか), understand advice given with なら and たら, and ask for directions to the nearest clinic and follow them (〜と).',
      opener: 'いらっしゃいませ。今日はどうしましたか。どこかいたいですか。',
      openerReading: 'いらっしゃいませ。 きょう は どう しました か。 どこか いたい です か。',
    },
  },
  {
    id: 'ja-n4-08',
    cefr: 'A2',
    order: 18,
    title: 'そうだ・らしい: Guessing and hearsay',
    theme: 'Weather forecasts, appearances, guesses, and passing on what you heard',
    canDo: [
      'I can say how something looks with 〜そうだ.',
      'I can pass on information I heard with 〜そうだ and 〜らしい.',
      'I can show how sure I am with かもしれない, でしょう, and ようだ / みたい.',
      'I can chat about the weather forecast and office news.',
    ],
    grammar: [
      {
        id: 'g-ja-n4-08-1',
        title: '〜そうだ (looks like) vs 〜そうだ (I heard)',
        summary:
          "Appearance そうだ ('looks like', 'looks about to') is a guess from what you see. It attaches to the ます-stem of verbs (ふります → ふりそうです, 'it looks like it's going to rain'), to い-adjectives without い (おいしい → おいしそう), and to な-adjectives (元気 (げんき) → 元気そう (げんきそう)); いい becomes よさそう and ない becomes なさそう. Hearsay そうだ ('I heard that…') attaches to the full plain form — ふるそうです, おいしいそうです, 元気だそうです (げんき だ そう です) — and you can name the source with によると: 天気よほうによると (てんきよほう に よる と), 'according to the weather forecast'. Pitfall: the form in front of そう tells you which one it is — ふりそう means 'looks like rain', but ふるそう means 'I heard it will rain'. 〜らしい is close to hearsay そうだ and means 'apparently': 雨らしいです (あめ らしい です).",
        examples: [
          { text: '空が暗いですね。雨がふりそうです。', reading: 'そら が くらい です ね。 あめ が ふりそう です。', en: "The sky is dark. It looks like it's going to rain." },
          { text: '田中さんは今日、元気がなさそうです。', reading: 'たなか さん は きょう、 げんき が なさそう です。', en: 'Mr. Tanaka seems a bit down today.' },
          { text: '天気よほうによると、明日はゆきがふるそうです。', reading: 'てんきよほう に よる と、 あした は ゆき が ふる そう です。', en: "According to the weather forecast, it's going to snow tomorrow." },
          { text: '山田さんは来月けっこんするそうです。', reading: 'やまだ さん は らいげつ けっこん する そう です。', en: 'I heard Ms. Yamada is getting married next month.' },
          { text: 'あの店のラーメンはおいしいらしいですよ。', reading: 'あの みせ の ラーメン は おいしい らしい です よ。', en: 'Apparently the ramen at that shop is really good.' },
        ],
        drills: [
          { text: '今にも雨が___そうです。', reading: 'いまにも あめ が ___そう です。', en: 'It looks like it could start raining any minute.', answer: 'ふり', distractors: ['ふる', 'ふった', 'ふって'] },
          { text: 'この店のカレーは___ですね。', reading: 'この みせ の カレー は ___ です ね。', en: 'The curry at this shop looks delicious.', answer: 'おいしそう', distractors: ['おいしいそう', 'おいしくそう', 'おいしかったそう'] },
          { text: '明日は天気が___ですね。', reading: 'あした は てんき が ___ です ね。', en: "Tomorrow's weather looks like it'll be nice.", answer: 'よさそう', distractors: ['いいそう', 'いそう', 'よそう'] },
          { text: 'ニュースによると、来週台風が___そうです。', reading: 'ニュース に よる と、 らいしゅう たいふう が ___ そう です。', en: 'According to the news, a typhoon is coming next week.', answer: '来る', distractors: ['来ます', '来て', '来た'] },
          { text: '木村さんは料理が上手___そうです。', reading: 'きむら さん は りょうり が じょうず ___ そう です。', en: 'I heard Mr. Kimura is good at cooking.', answer: 'だ', distractors: ['な', 'の', 'で'] },
        ],
      },
      {
        id: 'g-ja-n4-08-2',
        title: '〜かもしれない, 〜でしょう, 〜ようだ / 〜みたい',
        summary:
          "〜かもしれない (polite: かもしれません) means 'might / maybe': you're about 50% sure or less. 〜でしょう means 'probably' and sounds more confident; weather forecasts use it all the time, and its casual form is だろう. Both follow plain forms, but nouns and な-adjectives take them directly, with no だ: 雨かもしれません (あめ かも しれません), ひまでしょう. 〜ようだ and 〜みたいだ mean 'it seems / it looks like', based on what you've seen or heard yourself; ようだ is more formal and みたい is everyday speech. Say noun + のようだ and な-adjective + なようだ, but みたい goes straight onto nouns and な-adjectives (かぜみたい). Pitfall: never put だ in front of かもしれない, でしょう, or みたい — 雨だかもしれない (あめ だ かも しれない) is wrong.",
        examples: [
          { text: '明日は雨がふるかもしれません。', reading: 'あした は あめ が ふる かも しれません。', en: 'It might rain tomorrow.' },
          { text: '午後からはれるでしょう。', reading: 'ごご から はれる でしょう。', en: 'It will probably clear up in the afternoon.' },
          { text: '電気がきえています。だれもいないようです。', reading: 'でんき が きえて います。 だれ も いない よう です。', en: "The lights are off. It seems nobody's there." },
          { text: '山田さんはかぜみたいです。', reading: 'やまだ さん は かぜ みたい です。', en: 'Ms. Yamada seems to have a cold.' },
          { text: '森さんは今日、休みのようです。', reading: 'もり さん は きょう、 やすみ の よう です。', en: 'It looks like Mr. Mori is off today.' },
        ],
        drills: [
          { text: '今夜はゆきがふる___。', reading: 'こんや は ゆき が ふる ___。', en: 'It will probably snow tonight.', answer: 'でしょう', distractors: ['かもしれません', 'そうです'] },
          { text: '明日はひま___。', reading: 'あした は ひま ___。', en: 'I might be free tomorrow.', answer: 'かもしれません', distractors: ['だかもしれません', 'なかもしれません', 'のかもしれません'] },
          { text: '音がしますね。となりのへやにだれかいる___です。', reading: 'おと が します ね。 となり の へや に だれか いる ___ です。', en: "There's a noise. Someone seems to be in the next room.", answer: 'よう', distractors: ['そう', 'こと', 'ため'] },
          { text: '外は雨___ようです。', reading: 'そと は あめ ___ よう です。', en: 'It seems to be raining outside.', answer: 'の', distractors: ['な', 'だ', 'で'] },
          { text: 'かばんがありませんね。ジョンさんはもう帰った___です。', reading: 'かばん が ありません ね。 ジョン さん は もう かえった ___ です。', en: 'His bag is gone. Looks like John has already gone home.', answer: 'みたい', distractors: ['そう', 'でしょう', 'の'] },
        ],
      },
    ],
    vocab: [
      { id: 'v-ja-n4-08-01', text: '天気よほう', reading: 'てんきよほう', en: 'weather forecast', pos: 'noun', example: { text: '天気よほうを見てから出かけます。', reading: 'てんきよほう を みて から でかけます。', en: 'I check the weather forecast before I go out.' } },
      { id: 'v-ja-n4-08-02', text: '台風', reading: 'たいふう', en: 'typhoon', pos: 'noun', example: { text: '台風で電車が止まりました。', reading: 'たいふう で でんしゃ が とまりました。', en: 'The trains stopped because of the typhoon.' } },
      { id: 'v-ja-n4-08-03', text: 'ゆき', en: 'snow', pos: 'noun', example: { text: '北海道はゆきが多いです。', reading: 'ほっかいどう は ゆき が おおい です。', en: 'Hokkaido gets a lot of snow.' } },
      { id: 'v-ja-n4-08-04', text: 'くもり', en: 'cloudy weather', pos: 'noun', example: { text: '今日は一日中くもりでした。', reading: 'きょう は いちにちじゅう くもり でした。', en: 'It was cloudy all day today.' } },
      { id: 'v-ja-n4-08-05', text: 'はれる', en: 'to clear up; to be sunny', pos: 'verb', example: { text: '日曜日にはれたら、海へ行きましょう。', reading: 'にちようび に はれたら、 うみ へ いきましょう。', en: "If it's sunny on Sunday, let's go to the beach." } },
      { id: 'v-ja-n4-08-07', text: 'やむ', en: 'to stop (of rain, snow, or wind)', pos: 'verb', example: { text: '雨がやんだら、出かけましょう。', reading: 'あめ が やんだら、 でかけましょう。', en: "Let's go out when the rain stops." } },
      { id: 'v-ja-n4-08-08', text: '風', reading: 'かぜ', en: 'wind', pos: 'noun', example: { text: '今日は風が強いですね。', reading: 'きょう は かぜ が つよい です ね。', en: "It's windy today, isn't it?" } },
      { id: 'v-ja-n4-08-09', text: 'きおん', en: '(air) temperature', pos: 'noun', example: { text: '明日はきおんが下がるでしょう。', reading: 'あした は きおん が さがる でしょう。', en: 'The temperature will probably drop tomorrow.' } },
      { id: 'v-ja-n4-08-10', text: 'うわさ', en: 'rumor; gossip', pos: 'noun', example: { text: 'あの二人のうわさを聞きましたか。', reading: 'あの ふたり の うわさ を ききました か。', en: 'Have you heard the rumor about those two?' } },
      { id: 'v-ja-n4-08-11', text: 'ニュース', en: 'news', pos: 'noun', example: { text: '毎朝、テレビでニュースを見ます。', reading: 'まいあさ、 テレビ で ニュース を みます。', en: 'I watch the news on TV every morning.' } },
      { id: 'v-ja-n4-08-12', text: 'ほんとう', en: 'truth; true', pos: 'noun', example: { text: 'その話、ほんとうですか。', reading: 'その はなし、 ほんとう です か。', en: 'Is that story true?' } },
      { id: 'v-ja-n4-08-13', text: 'たぶん', en: 'probably; maybe', pos: 'adverb', example: { text: 'たぶん明日は雨でしょう。', reading: 'たぶん あした は あめ でしょう。', en: "It'll probably rain tomorrow." } },
      { id: 'v-ja-n4-08-14', text: 'きっと', en: "surely; I'm sure", pos: 'adverb', example: { text: '木村さんならきっと来ますよ。', reading: 'きむら さん なら きっと きます よ。', en: "Mr. Kimura? I'm sure he'll come." } },
      { id: 'v-ja-n4-08-15', text: 'さっき', en: 'a little while ago', pos: 'adverb', example: { text: 'さっき森さんから電話がありました。', reading: 'さっき もり さん から でんわ が ありました。', en: 'Mr. Mori called a little while ago.' } },
      { id: 'v-ja-n4-08-16', text: 'けっこんする', en: 'to get married', pos: 'verb', example: { text: '姉は去年けっこんしました。', reading: 'あね は きょねん けっこん しました。', en: 'My older sister got married last year.' } },
      { id: 'v-ja-n4-08-17', text: 'かいぎ', en: 'meeting', pos: 'noun', example: { text: '午後三時からかいぎがあります。', reading: 'ごご さんじ から かいぎ が あります。', en: "There's a meeting at 3 p.m." } },
      { id: 'v-ja-n4-08-18', text: 'ぶちょう', en: 'department manager', pos: 'noun', example: { text: 'ぶちょうは今日、いそがしそうです。', reading: 'ぶちょう は きょう、 いそがしそう です。', en: 'The department manager looks busy today.' } },
      { id: 'v-ja-n4-08-19', text: '顔色', reading: 'かおいろ', en: 'complexion; how someone looks', pos: 'noun', example: { text: '顔色が悪いですね。だいじょうぶですか。', reading: 'かおいろ が わるい です ね。 だいじょうぶ です か。', en: 'You look pale. Are you OK?' } },
      { id: 'v-ja-n4-08-20', text: 'によると', en: 'according to', pos: 'phrase', example: { text: '森さんによると、駅の前に新しいカフェができるそうです。', reading: 'もり さん に よる と、 えき の まえ に あたらしい カフェ が できる そう です。', en: 'According to Mr. Mori, a new café is opening in front of the station.' } },
    ],
    scenario: {
      title: 'Office small talk',
      setting: "It's Friday morning at an office in Tokyo. While getting coffee, your coworker Mori-san chats with you about the weekend weather and some office rumors.",
      aiRole: 'Mori-san, a talkative coworker who always knows the latest gossip',
      learnerGoal:
        'Talk about the weather forecast with でしょう and かもしれない, pass on something you heard with 〜そうです or 〜らしい, comment on how people and things look with 〜そう or 〜みたい, and react to a rumor (ほんとうですか).',
      opener: 'おはようございます。外はくもっていますね。天気よほうによると、午後から雨だそうですよ。',
      openerReading: 'おはようございます。 そと は くもって います ね。 てんきよほう に よる と、 ごご から あめ だ そう です よ。',
    },
  },
];
